### ISSUE TITLE
Slate not watching header.liquid

### ISSUE THREAD

**Issue by masterShake** [Shopify/slate#1004]
npm start is triggering browser sync just fine and most of my files (templates, css, js) are being watched except section/header.liquid

Any idea how I can add this file to the watch list?

**Comment by YourWishes** [comment]
I'm noticing this for all sections after beta 16.

**Comment by Maurice-JB** [comment]
Same. Liquid files in sections\ folder not being watched. 
Due to changes from #1000?

**Comment by dan-gamble** [comment]
Does it work if you use the new convention of `section/header/template.liquid` and `section/header/schema.json`?

**Comment by dan-gamble** [comment]
Unfortunately, this is happening for everything inside sections including the new stuff.

I appreciate Slate has been put in low maintenance now but releasing a slightly broken release can hopefully be rectified before this low maintenance kicks into full effect @t-kelly @chrisberthe @wizardlyhel?

**Comment by wizardlyhel** [comment]
Thank you @dan-gamble for the PR

**Comment by dan-gamble** [comment]
Happy to help @wizardlyhel 😊

**Comment by harshal317** [comment]
Fixed in #1005
