### ISSUE TITLE
Help installing Slate

### ISSUE THREAD

**Issue by jj4111** [Shopify/slate#1007]
### Problem

I need some help installing Slate. This is on a windows server. I've been following the readme at https://github.com/SlateFoundation/slate. I've followed all the steps and when I get to the section to Run and Edit Slate the commands don't work. I type in start-all-local and I get the error that 'bash: start-all-local: command not found'. It's the exact same issue with the watch-site command. From what I've been lead to believe with the readme Slate should start working once I run the command start-all-local to start the habitat services. I know next to nothing about Slate, Habitat, and Docker so any help would be greatly appreciated.

### Replication steps

*How to replicate the problem. Screenshots or video?*

### More Information

*Any additional information which might be helpful.*

**Comment by jonathanmoore** [comment]
Looks like you're in the wrong Slate. :) This Slate is for Shopify theme development.  I have a feeling you'll want to post over at https://github.com/SlateFoundation/slate/issues
