### ISSUE TITLE
Difference between index.js and theme.js

### ISSUE THREAD

**Issue by josefarrugia** [Shopify/slate#1041]
Hi there,

I am creating a few components for my Shopify theme and I was wondering what's the difference between the `index.js` and `layout/theme.js` files. Where would I put the my `component/name.js`?

What's the best workflow?

**Comment by justinmetros** [comment]
`layout/theme.js` will get loaded on every page where that `layout/theme.liquid` is used. 

`templates/index.js` will just load scripts for the index page `templates/index.liquid`

You can put your components anywhere you want. I make a scripts/components folder and put stuff in there. Just use the right paths when importing.

**Comment by josefarrugia** [comment]
Thanks @justinmetros for clearing that up! Much appreciated!
