### ISSUE TITLE
Unclosed Statement in {{ content_for_header }} causing errors with start and watch commands

### ISSUE THREAD

**Issue by ericanafziger** [Shopify/slate#1065]
### Problem

When running `slate-tools start` or `slate-tools watch`, a large unformatted block of code appears at the top of the site above the rest of the page. In the console there is an error `Uncaught SyntaxError: missing ) after argument list`. 

### Replication steps

1. Run `slate-tools start` or `slate-tools watch`
2. Once files are uploaded you will see the error at the top of the screen
3. This does not appear to happen on `slate-tools deploy`

![image](https://user-images.githubusercontent.com/20483621/67244307-4e300480-f40e-11e9-9a23-4102ae40f9e8.png)

### More Information

From what I can tell this issue is coming from the `{{ content_for_header }}` code in the `theme.liquid` file. Everything in here is being injected from Shopify and does not appear to be editable.

**Comment by jaredkc** [comment]
I am having the same issue. Currently, I have `@shopify/slate-tools`: `1.0.0-beta.15`, going to update to beta.19 now add see if that helps.

**Comment by ericanafziger** [comment]
Updating to beta.19 looks like it resolved the issue on my end. Thanks @jaredkc.

**Comment by fbushell** [comment]
I was seeing this as well in `1.0.0-beta.15` and I found a temp solution [here](https://community.shopify.com/c/Technical-Q-A/Unknown-error-using-Slate-and-Browser-Sync/td-p/564376). 

Add this code in node_modules/@Shopify/slate-tools/tools/dev-server/index.js within the bsConfig function
```
snippetOptions: {
        rule: {
            match: /<head[^>]*>/i,
            fn: function(snippet, match) {
                return match + snippet;
            }
        }
    }
```
