### ISSUE TITLE
Slate Start: UnhandledPromiseRejectWarning

### ISSUE THREAD

**Issue by josefarrugia** [Shopify/slate#1076]
Currently getting several Promise errors when using `yarn start`. Any ideas as to why this is happening? I am currently on Beta 19.

`UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

**Comment by dan-gamble** [comment]
Duplicate of https://github.com/Shopify/slate/issues/1075

**Comment by josefarrugia** [comment]
@dan-gamble glad I am not the only one experiencing it. It has something to do with `axios` too.
