### ISSUE TITLE
yarn start  not working on Ubuntu 2020

### ISSUE THREAD

**Issue by ersanjay1995** [Shopify/slate#1103]
### This repo is no longer active. See README for details

yarn start
yarn run v1.22.5
$ slate-tools start

Error : 

(node:4529) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND v.shopify.com v.shopify.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:4529) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4529) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
DEPRECATION WARNING on line 6, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

**Comment by ironmarketing** [comment]
Repo is long dead, and barely worked when it was active anyway.

**Comment by gavsiu** [comment]
Still works for me. I do get Node Sass errors and that's why I'm browsing issues, but I am still actively editing my theme using Slate. I'm not gonna waste time redoing my theme trying to figure out what Shopify is up to now as long as Slate works.

Just an FYI for anyone thinking it's totally not working.
