### ISSUE TITLE
Feedback email address doesn't work

### ISSUE THREAD

**Issue by ch2ch3** [Shopify/slate#112]
### Problem

The feedback email (slate@shopify.com) in the sidebar [source](https://github.com/Shopify/slate/blob/master/docs/_includes/sidebar.html#L94) is broken / not open to the public. I sent some feedback in but got the following response:

>Hello [email],
>
>We're writing to let you know that the group you tried to contact (slate) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
>
> * You might have spelled or formatted the group name incorrectly.
> * The owner of the group may have removed this group.
> * You may need to join the group before receiving permission to post.
> * This group may not be open to posting.
>
>If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/shopify.com/bin/topic.py?topic=25838.
>
>Thanks,
>
>shopify.com admins

### Scope

*Is this an issue with Slate's theme scaffolding or its documentation?*

*If it is related to the `slate` commands, perhaps the [slate-cli repo](https://github.com/Shopify/slate-cli) or the [slate-tools repos](https://github.com/Shopify/slate-tools) are a more appropriate spot to log your issue.*

Documentation.

### Replication steps

*How to replicate the problem. Screenshots or video?*

![image](https://cloud.githubusercontent.com/assets/8350141/24765514/09214484-1af0-11e7-8547-9ae3071eaa96.png)

Click `Provide feedback` link. Send an email (that's not from the shopify.com domain).

### More Information

*Any additional information which might be helpful.*

**Comment by NathanPJF** [comment]
@ch2ch3 Oops! Google groups are confusing to us, sorry about that.  Thanks for letting us know 😄 

While I sort this out, I'm curious: What was the feedback?

**Comment by NathanPJF** [comment]
@ch2ch3 Should be good to go - feel free to send your feedback along via email or make an issue in one of the repos if you think that it makes sense there.

**Comment by ch2ch3** [comment]
Nice, that was quick! 😄 Thanks @NathanPJF.
