### ISSUE TITLE
Currency formatting without decimals

### ISSUE THREAD

**Issue by jonathanmoore** [Shopify/slate#113]
### Problem

Using slate.Currency's formatMoney method incorrectly returns cents and decimal places if you use the `amount_no_decimals` or `amount_no_decimals_with_comma_separator` format.

### Scope

This is an issue with Slate's JavaScript functionality in the theme scaffolding - [/src/scripts/slate/currency.js](https://github.com/Shopify/slate/blob/master/src/scripts/slate/currency.js)

### Replication steps

If the `amount_no_decimals` or `amount_no_decimals_with_comma_separator` case is used `formatWithDelimiters(cents, 0);` or `formatWithDelimiters(cents, 0, '.', ',');` is called.

In the `formatWithDelimiters` method, the `precision` variable is set to 2 as a default if the variable does not exist.
```js
precision = precision || 2;
```

However, since the `precision` argument in the `formatWithDelimiters` method could be 0, the line above is seeing `precision == false == 0` it is incorrectly setting the value to 2.

### More Information

The previous version of this file [carolineschnapp/currencies/master/jquery.currencies.js](https://github.com/carolineschnapp/currencies/blob/master/jquery.currencies.js#L543-L547) used a more explicit way to handle default values.

```js
function defaultOption(opt, def) {
  return (typeof opt == 'undefined' ? def : opt);
}

precision = defaultOption(precision, 2);
```

With this explicit approach, the value of `precision` could be correctly set to `0`.

**Comment by NathanPJF** [comment]
Thanks for the detailed issue, @jonathanmoore
