### ISSUE TITLE
Using IncludeMedia.scss as an include breaks Slate's Compiler.

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#117]
### Problem

There's something about using [Eduardo Bouças' Include Media.scss](https://github.com/eduardoboucas/include-media) that breaks the compiler.

If I create a new `*.scss` file and place it in either Global or Tools, I insert normal CSS to test:

`* {
color: red;
}`

And include the new file in `theme.scss` via `@import url('global/includemedia.scss');`, it works fine, as expected.

But when I paste in the IncludeMedia's SCSS code, Shopify shows the error: `Failed to compile SCSS file`

I've used this file in previous SCSS projects that weren't using Slate, so it can't be a problem with the document itself.

### Scope

Problem seems to occur with the theme scaffolding 

### Replication steps

1. Download [IncludeMedia.scss](https://github.com/eduardoboucas/include-media/blob/master/dist/_include-media.scss)
2. Create a new SCSS document in any of the styles folders (And @import) and set up `slate watch`
3. Paste in IncludeMedia and wait for the store to reload.

**Comment by NathanPJF** [comment]
@ConduciveMammal I pasted the partial you provided directly into the `theme.scss.liquid` of a theme via the online editor and it failed to compile, so this isn't a Slate specific issue.  

<details><summary>Screenshot here</summary>

![](http://take.ms/fKI6w)

</details>
&nbsp;

This is likely because IncludeMedia.scss is using a version of Sass that Shopify doesn't support.  Shopify's online compiler supports Sass v3.1; however, the partial you linked seems to have methods that aren't supported before v3.4.  [Screenshot example from Sassmeister using v3.3](http://take.ms/SSKTe)

Closing this issue as it's not an issue with Slate.

**Comment by ConduciveMammal** [comment]
Thanks for the response, Nathan. I hadn't even considered the Sass version.

Perhaps some more helpful error messages could be somehow added to avoid this situation. "Failed to compile SCSS" isn't the most helpful of errors.

**Comment by ConduciveMammal** [comment]
I do also wonder why a relatively brand new compiler wouldn't support the latest version of Sass.

**Comment by NathanPJF** [comment]
> I do also wonder why a relatively brand new compiler wouldn't support the latest version of Sass.

If this is referring to Shopify's compiler, then I want to point out that Shopify won't switch Sass versions on merchants to protect their interests.  If we bumped the Sass version one day, then we'd immediately break the CSS file on every store that is using methods that aren't compatible in this new version.  Like how the spec change the rules for `@extend` inside `@media` query going from 3.1 to 3.2 - [this blog has a good write up on that past release](http://chriseppstein.github.io/blog/2012/08/23/sass-3-2-is-released/).

**Comment by NathanPJF** [comment]
@ConduciveMammal 

I just merged a PR that gives more information about how Sass compilation is handled both by Slate and by Shopify. https://shopify.github.io/slate/theme-scaffold/#sass-helpers

> Slate does not compile Sass to CSS. Slate uploads `.scss` files to your theme's `/assets` directory and compilation is done by Shopify. Shopify is using a forked version of Sass v3.2 which does not support importing partial Sass files with the `@import` directive.

Perhaps you were referring to Slate itself when you talking about a "brand new compiler".  Regardless, hopefully this clears things up.

Also, I misspoke earlier when I said the version used was 3.1.
