### ISSUE TITLE
Why normalize.css v3?

### ISSUE THREAD

**Issue by yangkennyk** [Shopify/slate#121]
just curious as to why slate has normalize.css v3 when there is v6.

**Comment by NathanPJF** [comment]
Hi @yangkennyk v3 was the version were were using on our other themes for awhile.  This is a remanent of that workflow, but I'm going to mark this as an "enhancement" so we can revisit the version in the future.

**Comment by adrhumphreys** [comment]
Here's a [change log](https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md) of what has changed between versions. Due to the nature of slate coming with near nothing styled out of the box I would be in favour of using v6 of normalize.

**Comment by t-kelly** [comment]
Upgraded to v7 in Slate 0.11.0
