### ISSUE TITLE
Ship with .gitignore

### ISSUE THREAD

**Issue by peterberwind** [Shopify/slate#126]
### Problem

When creating a new theme or migrating an exsisting, there is no .gitignore so both `node_modules` and `dist` get commited to the git repo. Would be a nice to ship with this configured!

**Comment by NathanPJF** [comment]
Fixed in https://github.com/Shopify/slate-cli/pull/132 

Great suggestion, @peterberwind.  This will be available in the next Slate release. Going to update the docs now.
