### ISSUE TITLE
Log SCSS errors into console

### ISSUE THREAD

**Issue by peterberwind** [Shopify/slate#127]
Would be awesome if Slate would log SCSS errors like gulp-scss. Otherwise linting is the last line of defense before it makes it to the Shopify servers.

**Comment by idiazroncero** [comment]
Totally agree. Today i completely messed up a webpage because of a damn semicolon I inserted without noticing before push.

**Comment by clarose098** [comment]
Yeah - this would be huge. Just wasted a chunk of time because fancybox has `content: '×';
` and it causes the compile to fail. It makes debugging take a lot longer.

**Comment by PTcampbell** [comment]
+1 Absolutely!

**Comment by lizsterine** [comment]
+1 From me too!

**Comment by t-kelly** [comment]
Closing this since it is included with #258
