### ISSUE TITLE
Remember the minimization state for theme preview notification

### ISSUE THREAD

**Issue by RatulSaha** [Shopify/slate#141]
### Problem

When watching a slate theme (`slate watch`), in the localhost/external URL provided by browsersync, we consistently get a slide up notifying *You are currently previewing the theme: theme_name*. Even with each reload, the bottom bar pops up each time. Once minimized, this choice should be remembered locally as a user-defined choice.

### Scope

This is an issue with the theme scaffolding.

### Replication steps

- Deploy a theme successfully.
- Fire `slate watch`.
- The browersync link opens successfully with a bottom bar notifying that it's a theme preview.
- Click 'Minimize'.
- Make some changes to any file in the theme.
- The bottom bar pops back again.

**Comment by ConduciveMammal** [comment]
Minimise only hides it for that page load, in any scenario this would reappear after a page reload.

**Comment by t-kelly** [comment]
Hey @RatulSaha! Great observation. This is actually an issue with the Themes platform and how themes that are not 'live' are previewed. The same behaviour can be seen if you click the 'preview theme' button inside the admin themes section: 

![Alt text](https://monosnap.com/file/2kyKRzqspgRkF4bZUUnC8EZ71jJyBS.png)

I'm going to open up an issue in core to discuss this problem. I'll post any conclusions we come up with here.

**Comment by PTcampbell** [comment]
Plus one this enhancement! It's pretty annoying that it pops up every time you hit save. I understand why it happens but perhaps at the Shopify end you can detect whether it's being displayed via a local proxy?

**Comment by ConduciveMammal** [comment]
Bit of a hacky way but could it not just be hidden with CSS? At least for the time being until something better comes along?

**Comment by ConduciveMammal** [comment]
Just test this, you can indeed hide the bar with CSS, using:
`.shopify-preview-bar {
    display:none;
}`

In your main SASS/CSS file and just remember to remove it before deployment to production.

**Comment by PTcampbell** [comment]
Yeah, I had something like this in the end. Thanks!

**Comment by phillipdanielscott** [comment]
@ConduciveMammal you are a life saver lol this has been driving me crazy.

**Comment by t-kelly** [comment]
This issue didn't get merged into `shopify/slate-tools`. Now that `shopify/slate-tools` has been merged into this repo - I will redo this PR here.

**Comment by avishai** [comment]
As of 9/2018, the new admin bar can be hidden with this CSS:
`iframe#admin-bar-iframe { display:none; }`
