### ISSUE TITLE
Ajax functions for cart.js

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/slate#144]
### Problem

The Slate project does not have helper scripts for ajax carts.  We have an opportunity to simplify the methods described in our [Ajax API documentation](https://help.shopify.com/themes/development/getting-started/using-ajax-api) for themes.

Related issue: https://github.com/Shopify/slate/issues/132

### Scope

The helper script to add his to that would make most sense is `cart.js`.  From the conversation by @t-kelly in the related issue above;

> We are currently working on expanding cart.js so that it has more helpful functions like `cart.addItem()`, `cart.changeItem()`, etc. The functions included in this file should make creating an AJAX cart a lot easier, while not being opinionated on how the Liquid and CSS is written. Hoping to have a PR open in the near future.

The methods that we shipped in Narrative would be useful.

### More Information

Other helpers for Shopify: Cart JS 

The [core API of CartJS](https://cartjs.org/pages/guide#core-api) is worth taking a look at for additional inspiration.  

The [data API](https://cartjs.org/pages/guide#data-api) also included is very cool, but likely out of scope of what we'd like to ship as a helper script.  Reason: using certain methods makes assumptions about your page markup.  For example, data API's [adding items](https://cartjs.org/pages/guide#data-api-adding-items) adds based on a variant ID.  

```html
<button data-cart-add="12345678">Add a Widget</button>
```

This works great, assuming this is the only information you need.  But if you want to also handle line item properties in the future, you won't want to use this method.  

Side note: You could accomplish the same thing as the above example with:
 
```html
<a href="https://mystore.com/cart/add?id=12345678&quantity=1">Add a Widget</a>
```

**Comment by ConduciveMammal** [comment]
I understand your need to keep Slate as barebones as possible to avoid giving developers extra work removing things. But could it not be possible to release this kind of thing on an optional basis?

Kind of like Caroline Schnapp's repo for extra functions that the user can just include should they choose to use it?

**Comment by alexyakir** [comment]
Hey, I'm currently working on a new theme - really enjoying the slate boilerplate 👍 . Would be really helpful if cart.js had more methods as stated above.

Any idea when the new cart.js will be released? Thanks :)

**Comment by pveen2** [comment]
Hi is there any progress in the AJAX cart functions?

**Comment by t-kelly** [comment]
I'm currently focusing my efforts on the Slate v1.0. I'm really interested in expanding what we have for ajax-cart resources, but it's taking a back seat until we get Slate v1.0 in a good place.

**Comment by t-kelly** [comment]
Good news -- Cart.js has been moved to[ `Shopify/theme-scripts`](https://github.com/Shopify/theme-scripts/tree/master/packages/theme-cart) and iterated. Documentation and another iteration are in the works.

**Comment by pveen2** [comment]
@t-kelly is there an easy way to copy the ajax cart code of the narrative theme? And can we find the source files of the narrative somewhere? Thanks!

**Comment by arjunbanker** [comment]
+1 @pveen2, i am trying to help a client modify the narrative theme to support ajax add-to-cart from the collection view, and it is pretty difficult without the unminified narrative js source or client side cart api. i can call the ajax api to make the change on the server, but how do i update the cart drawer?
