### ISSUE TITLE
Preview Password Protected Site Locally

### ISSUE THREAD

**Issue by baberuth22** [Shopify/slate#145]
### Problem

I have a development store that is password protected.   Running slate start shows the password page at localhost:3000.   

### Scope

Normally, if I am logged into admin, I do not see the password page on a password protected site.

### Replication steps

Password protect a site, run slate start.

**Comment by rublev** [comment]
I have the same issue. No clue why. When I remove the password on my store, then I am able to run slate watch and develop locally. Otherwise it just redirects to my store's password page. @baberuth22 did you solve this somehow?

**Comment by orangemooncreative** [comment]
i am having the same issue. when i remove the password everything is fine but with it i am redirected to my store's password page.

**Comment by NathanPJF** [comment]
If you're using a custom domain (not the `*.myshopify.com` one) and experiencing this issue, there's another thread discussion it here: https://github.com/Shopify/slate/issues/182

If you are still using the `myshopify.com` domain, then you'll need to log into your storefront with the password only once at `localhost:3000/password`.
