### ISSUE TITLE
Documentation is not available .

### ISSUE THREAD

**Issue by engrshahabuddin** [Shopify/slate#147]
1. Documentation is not available  for this framework.
Where is Documentation for  this framework?

2. Are there any facility like Timber frame work to develop theme ? for - ajax-cart,Drawer etc.

**Comment by ConduciveMammal** [comment]
There's a [link](https://shopify.github.io/slate/) at the top of the repo's description that goes to Slate's documentation.

**Comment by NathanPJF** [comment]
> Documentation is not available for this framework.

You can find the link in the README.md: https://github.com/Shopify/slate#documentation

> Are there any facility like Timber frame work to develop theme ? for - ajax-cart,Drawer etc.

You can see the discussion about ajax and drawers here https://github.com/Shopify/slate/issues/132 and https://github.com/Shopify/slate/issues/144
