### ISSUE TITLE
Status: 422 Unprocessable Entity, Errors: Theme files may not be stored in subfolders

### ISSUE THREAD

**Issue by rawrsome** [Shopify/slate#148]
### Errors: Theme files may not be stored in subfolders
When using command slate deploy -e development 

slate will look at config/theme/dist/folder/file
but I don't have a parent folder above my theme name 'config'.

How can I make slate look in my /dist while deploying?

<img width="1440" alt="screen shot 2017-05-10 at 10 04 49 pm" src="https://cloud.githubusercontent.com/assets/11166888/25933852/161002f8-35cf-11e7-8645-f213adbd713c.png">

development:
  password: ---
  theme_id: "174469070"
  store: shop.myshopify.com
  ignore_files:

production:
  password: ---
  theme_id: "132337347"
  store: shop.myshopify.com
  timeout: 1m0s
  ignore_files:

**Comment by NathanPJF** [comment]
@rawrsome Are you still experiencing issues with this?  Mind sharing a screenshot of your project's folder structure? Or better yet: a link to a GitHub repo.

> When using command slate deploy -e development

Is this scoped to just running deploy with those flags?

> How can I make slate look in my /dist while deploying?

This is the default behaviour, so the issue you're getting is unexpected.

**Comment by rawrsome** [comment]
It looks like my PATH is incorrect. I re-installed everything and working like a charm!
