### ISSUE TITLE
Slate cannot compile Bootstrap 4

### ISSUE THREAD

**Issue by mblode** [Shopify/slate#149]
### Problem

I have tried to get Bootstrap 4 Alpha 6 SCSS to work with slate, however, when I try typing 'slate start' in the terminal, the files are successfully synced to the Shopify store. But in the inspect console, the file says 'can not get' and if you open the file in a new tab it says: 'Failed to compile SCSS file'. 

Does this have anything to do with the version of Sass Slate uses (A fork of 3.2)? 

### Sass Version 3.3
In Sass version 3.3 they introduced Sass script maps which seems to be one thing that breaks the compilation of Bootstrap: 
http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#selector_functions

**Comment by jonathanmoore** [comment]
This would be more of a general Shopify issue.  Currently, Shopify's CDN servers that compile the SCSS files support Sass 3.2.6.  So technically, Bootstrap 4's SCSS files that require at least 3.3 will not compile in any Shopify theme.

**Comment by NathanPJF** [comment]
Thanks @jonathanmoore 

@mblode I took a look at the repo for bootstrap-sass and see that Sass version 3.3.4 is required.  https://github.com/twbs/bootstrap-sass/blob/master/bootstrap-sass.gemspec#L14
You'll need to compile your Sass separately as Shopify's compiler won't be able to do this.

**Comment by mblode** [comment]
Yeah, I'm compiling bootstrap 4 with my own custom variables using Codekit and then just importing it. Is there any goal to update Sass from the 5-year-old version Shopify is currently using?

**Comment by NathanPJF** [comment]
> Is there any goal to update Sass from the 5-year-old version Shopify is currently using?

It's an issue we're aware of, but no timeline I can offer.

**Comment by mblode** [comment]
Is there any way to update the 'Failed to compile SCSS file' to reflect the actual error. I'm finding it near impossible to convert my site to being compiled by shopify

**Comment by tomaszbujnowicz** [comment]
Yes, it would be so nice and much easier to have Sass updated or at least have an option to choose which version to use so it doesn't break old themes. Ending up using compiled version of Bootstrap 4 Grid system (by CodeKit) and imported to the current theme.
