### ISSUE TITLE
Question: Sourcemap support

### ISSUE THREAD

**Issue by kettultim** [Shopify/slate#150]
Not so much an issue as a feature question. I'm relatively new to Gulp so having a bit of trouble finding the answer to this...

Is there a way to enable sourcemaps? Would be really useful for devtools/workspace workflow. 

Thanks!

**Comment by kettultim** [comment]
Nevermind... figured it out! I added sourcemaps support directly to the css build task within Slate tools. Perhaps not the best method as it alters master but here's what I did in case anyone else wants to add sourcemaps to their SASS compiling:

*Note: Use at own risk as it diverges from master*

`npm install --save-dev gulp-sourcemaps`

`#node_modules/@shopify/slate-tools/lib/tasks/build.css.js

line 12
`var sourcemaps = require('gulp-sourcemaps');`

line 20, replace
```
function processCss() {
  messages.logProcessFiles('build:css');

  return gulp.src(config.roots.css).pipe(plumber(utils.errorHandler)).pipe(cssimport()).pipe(extReplace('.css.liquid', '.css')).pipe(extReplace('.scss.liquid', '.scss')).pipe(gulp.dest(config.dist.assets));
}
```

with
```
function processCss() {
  messages.logProcessFiles('build:css');

  return gulp.src(config.roots.css).pipe(sourcemaps.init()).pipe(plumber(utils.errorHandler)).pipe(cssimport()).pipe(extReplace('.css.liquid', '.css')).pipe(extReplace('.scss.liquid', '.scss')).pipe(sourcemaps.write('.')).pipe(gulp.dest(config.dist.assets));
}
```

**Comment by NathanPJF** [comment]
@kettultim I've just made an issue in the slate-tools repo to discuss adding this to the build.

How's your experience been so far using source maps?  Any issues you can give us a heads-up on?

**Comment by kettultim** [comment]
@NathanPJF apologies on the delay.. everything's working well so far with the above solution. Best practice is as Tiffany mentions here: https://github.com/Shopify/slate-tools/issues/63#issuecomment-301747162

Compiling in the dev env with expanded sourcemaps/comments and switching them off for in the production env.
