### ISSUE TITLE
Migrate includes config.yml

### ISSUE THREAD

**Issue by baberuth22** [Shopify/slate#153]
### Problem

I just ran slate migrate on an existing theme and the config.yml file was not generated.

Did I miss something or am I supposed to create that file manually?

**Comment by chrisberthe** [comment]
Hi @baberuth22, unfortunately it's a manual process right now - you would have to create the file manually and add it to the root of your project.

However, there's currently a PR (https://github.com/Shopify/slate-cli/pull/125) that has yet to be merged that will take care of generating this file for you.

**Comment by kevinlg** [comment]
The link is broken
https://github.com/Shopify/slate/blob/master/config-sample.yml.

**Comment by t-kelly** [comment]
This file has moved to `https://github.com/Shopify/slate/blob/master/packages/slate-theme/config-sample.yml`

**Comment by puppycodes** [comment]
also broken... ^
