### ISSUE TITLE
Updating slate version and ignoring locales

### ISSUE THREAD

**Issue by ronnyew** [Shopify/slate#154]
Great package...

1. I have a theme I am developing and is deployed to live sites. How do I update slate (from version 0.9.1) to the latest version for this theme to take advantage of improvements?

2. I know I can ignore files during deployment using config.yml, but what is the best practice for ignoring locale files? If I simply ignore /locales/en.default.json from live sites, then they will not benefit from new terms that are added throughout the life of a project.

Appreciate your guidance.

Cheers.

**Comment by NathanPJF** [comment]
> How do I update slate (from version 0.9.1) to the latest version for this theme to take advantage of improvements?

Just to be sure: Are you referring to version 0.9.1 of the Slate theme (this repo) or a version of [Slate CLI](https://github.com/Shopify/slate-cli)?  

If you're wondering how to update your Slate project to use the latest changes from this repo, there is no automated way of doing this.  It would need to be a manual process of copying assets or updating Liquid drops.  You can see the release notes for the different changes that have been implemented.  Example here: [v0.10.1](https://github.com/Shopify/slate/releases).  Or the [entire changelog](https://github.com/Shopify/slate/blob/master/CHANGELOG.md) here.

If you're wanting to update the command line tool (Slate CLI).  You can update with the following command : `npm install -g @shopify/slate`

> If I simply ignore /locales/en.default.json from live sites, then they will not benefit from new terms that are added throughout the life of a project.

A locales file may be a good item to add to your ignore files if you feel that you or your client are going to be updating translations from the admin, `/admin/themes`.   By doing this, your local project is going to get out of sync with your Shopify hosted store.  

There's currently no tooling in place to pull down hosted theme files in Slate, like you can with Themekit.  This is something the Slate project team is discussing, but haven't come to a decision on how to implement.  You can find an active conversation about pulling down theme files in the Themekit repo here: https://github.com/Shopify/themekit/issues/330

**Comment by driespieters** [comment]
Hi Nathan,

If I try to update slate using the Slate CLI the version remains V0.10.0 

Is v0.10.1 not released yet?

Thanks!

**Comment by NathanPJF** [comment]
@driespieters I figured out what the hold up was - thanks for mentioning this.  You can get `0.10.1` release here: https://sdks.shopifycdn.com/slate/0.10.1/slate-theme.zip

This version will be reflected in running `slate theme` shortly.

**Comment by NathanPJF** [comment]
Related PR: https://github.com/Shopify/slate/issues/130

Issue is resolved now.
