### ISSUE TITLE
NPM deprecated packages

### ISSUE THREAD

**Issue by baberuth22** [Shopify/slate#160]
### Problem

I run slate migrate and I get the following warnings:

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3

**Comment by adamrasheed** [comment]
Same!

**Comment by t-kelly** [comment]
After looking into this, I have come to the conclusion that this is intended behaviour. These warnings are the result of our dependency's dependencies (aka gulp's dependencies) [being out of date](https://github.com/gulpjs/gulp/issues/1571). They are not errors.

I played with the idea of hiding npm warnings and only showing errors using the [`loglevel` flag](https://docs.npmjs.com/misc/config#loglevel), but I feel that there could potentially be useful information in npm warnings so I'm leaving it.
