### ISSUE TITLE
Notification on error

### ISSUE THREAD

**Issue by PTcampbell** [Shopify/slate#165]
Just a small suggestion – I normally add alert sounds or notifications to my tasks if there's an error – helps identify when something went wrong if the window is not in focus.

**Comment by NathanPJF** [comment]
Having some sort of system notification has been discussed internally, but we never made an issue.. thanks, @PTcampbell 😄 

I'm going to label this an `enhancement` as there should be a way to grab someone's attention if something went wrong.  I'm going to edit the title to be more generic about notifications.

**Comment by t-kelly** [comment]
This is not a priority for us in v0.x. Feel free to open a PR. Closing in the meantime.
