### ISSUE TITLE
JSLint Build Error on slate build or slate zip

### ISSUE THREAD

**Issue by adamrasheed** [Shopify/slate#167]
When you try to build slate with "slate build",  you get the following error:

```
/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/@shopify/theme-lint/index.js:12
module.exports.runAll = function(path, reporter = new Reporter()) {
                                                ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/lib/tasks/lint-locales.js:5:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireDir (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/require-dir/index.js:122:33)
    at Object.<anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/lib/gulpfile.js:38:23)
Adams-MacBook-Pro-2:flexrake-theme adamrasheed$ 
```

**Comment by txav92** [comment]
Having some issue but for all slate commands (start, watch, build, zip)

**Comment by novuswebbw** [comment]
Same here. I thought it was due to the deprecated modules, but I updated all I could, and still got this error.

**Comment by adamrasheed** [comment]
Update: Make sure both Node and NPM are updated to the latest stable version.

**Comment by novuswebbw** [comment]
I'm running v8.0.0 of Node.js and v5.0.1 of NPM. Is that correct?

**Comment by novuswebbw** [comment]
FWIW, I'm seeing these warnings when using slate theme [theme-name] command:

```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```
I ran the update on all these modules, but still the same error.
Is the slate theme package calling on the wrong versions of these tools?

**Comment by novuswebbw** [comment]
BTW, slate -v shows v0.10.0 instead of v0.10.1, which appears to be the latest release. This after using the slate theme command.

**Comment by l-fischer** [comment]
Having the same new Reporter, unexpected token, error with the start, zip, watch commands and just updated Node and NPM which didn't fix the error

**Comment by novuswebbw** [comment]
Thanks, I-fischer. I had uninstalled and re-installed Node using npm, but then tried using the Mac OSX package installer. That seemed to do the trick! Looks like we have liftoff!

**Comment by ry167** [comment]
Updating `node` to a newer version solved this for me

**Comment by NathanPJF** [comment]
I've just done a test run of `slate build` and `slate zip` using the v6.10.0 and npm v5.0.3 (`nvm use default` for those using nvm) and haven't encountered any issues.  If you're using those releases and still encountering issues, please let me know.

I know that folks have been having issues with node 8.0 - there's a couple issues in here.  We're currently only supporting the LTS version of node.  As @adamrasheed advices above, for now be sure to be using the latest stable ones.

> I'm running v8.0.0 of Node.js and v5.0.1 of NPM. Is that correct?

@novuswebbw You can see the LTS at nodejs.org.  Currently that's v.6.11.0.

> BTW, slate -v shows v0.10.0 instead of v0.10.1,

@novuswebbw The `slate` command is referring to the command line tool.  Latest release is `v.10.0` at this time: https://github.com/Shopify/slate-cli/releases

**Comment by t-kelly** [comment]
Are people still seeing this problem? I'm running Node v8.1.3 and npm 5.3.0 without any problems.
