### ISSUE TITLE
ES6 Support

### ISSUE THREAD

**Issue by baberuth22** [Shopify/slate#168]
### Problem

I'd like to use ES6

### Scope

What is the proper package.json config for using Babel to transpile ES6?   

### Replication steps

Use Slate

### More Information

I just watch the Shopify ES6 webinar and I couldn't believe there were no setup instructions.

**Comment by baberuth22** [comment]
Maybe slate already uses Babel?  Any update on this?

**Comment by baberuth22** [comment]
Would this package do it?  https://www.npmjs.com/package/babel-preset-shopify

And probably polyfill too.  https://babeljs.io/docs/usage/polyfill/

**Comment by panoply** [comment]
@baberuth22  see here: #181

**Comment by logancalldev** [comment]
Slate is already using Gulp, which also has some plugins available to transpile modern JS into ES5. Would it be possible to incorporate these without having to incorporate an entirely different build system (webpack)?

**Comment by t-kelly** [comment]
This has been started and shipped in the [1.x branch](https://github.com/Shopify/slate/tree/1.x).

**Comment by lux-capacitor** [comment]
@t-kelly First off thanks for all you do in this project, you're a rockstar!  I normally wouldn't ask here, but I can't find much info elsewhere -- Been excitedly waiting for imports and would LOVE the power this unleashes in the shopify dev space - any indications on when we might see 1.x release?

**Comment by t-kelly** [comment]
@lux-capacitor 1.x is in beta and has been merged into the master branch. See the[ releases page](https://github.com/Shopify/slate/releases).
