### ISSUE TITLE
Using special characters in directory name breaks zip tools

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#171]
### Problem

I created a theme inside a two-word directory with the theme name such as: "Theme name - XXX [Master]" using the command `slate theme "Theme name - XXX [Master]"` and from what I could tell, it created the theme as normal. But when I then ran `slate zip` it killed the build process after `[12:27:24] Finished 'zip' after` with no built theme and no dist folder. I changed the theme's folder name to simply "theme" and it worked perfectly.

Perhaps there's some undocumented restriction on folder names or perhaps a bug.

**Comment by NathanPJF** [comment]
@ConduciveMammal Could you please log this issue in the `slate-tools` repo?  From the issue template:

> If it is related to the `slate` commands, perhaps the [slate-cli repo](https://github.com/Shopify/slate-cli) or the [slate-tools repos](https://github.com/Shopify/slate-tools) are a more appropriate spot to log your issue.

**Comment by ConduciveMammal** [comment]
Sorry, Nathan. Yeah sure thing, I'll go post it now.
