### ISSUE TITLE
align_logo is not a setting in header.liquid

### ISSUE THREAD

**Issue by ry167** [Shopify/slate#172]
### Problem

[src/sections/header.liquid](https://github.com/Shopify/slate/blob/d7b02d579214ac4777eaf4f378e1e19d29ae2373/src/sections/header.liquid) contains the following code:
```
  {% if section.settings.align_logo == 'left' %}
    .site-header__logo-image {
      margin: 0;
    }
  {% endif %}
There is no matching section settings entry for this.
```

Should this be added as a setting or should this code be removed?

**Comment by NathanPJF** [comment]
@ry167 Good catch!  This code seems to be left over from Debut.  There shouldn't be any reference to a `section.settings.align_logo` in the Slate theme.

**Comment by NathanPJF** [comment]
Related:  `logo_max_width` should be using the new `range` input instead of `text`
