### ISSUE TITLE
Use the Neat grid

### ISSUE THREAD

**Issue by driespieters** [Shopify/slate#173]
**### Problem**

I'm unable to use the Neat grid (2.0). [https://github.com/thoughtbot/neat](https://github.com/thoughtbot/neat)

I've changed all Neat's import statements to use the correct markup: 
`@import url('new-folder/style.scss')`

It's get's passed through the Slate CLI build and the stylesheet get's uploaded to Shopify, but the site won't load the stylesheet. _(Note: I haven't used any neat mixins in the theme at this point)_

There are no logs and no developer mode, so I can't figure out what's going wrong.

**### Scope**
Issue with Slate's theme scaffolding 

**### Replication steps**
Install neat 2.0 and change it's import statements to comply with Slate

**Comment by jonathanmoore** [comment]
Ultimately Neat 2.0 isn't going to work with any Shopify theme since Shopify's servers only support Sass 3.2.6.  Since Slate doesn't handle any Sass compiling, there's no reason why it wouldn't work if Shopify decides to update to a more recent version of Sass.

**Comment by NathanPJF** [comment]
As mentioned in the public docs: "Slate does not compile Sass to CSS. Slate uploads .scss files to your theme's /assets directory and compilation is done by Shopify. Shopify is using a forked version of Sass v3.2 which does not support importing partial Sass files with the `@import` directive."
https://shopify.github.io/slate/theme-scaffold/#sass-helpers

> there's no reason why it wouldn't work if Shopify decides to update to a more recent version of Sass.

We'd have to figure out how to do this without breaking a whole bunch of stores using deprecated Sass directives first 😛

**Comment by wardpenney** [comment]
As a suggestion to @driespieters, Neat has a plugin to make a grid class set now https://github.com/whmii/neat-class-generator, so you could have a local process to generate your finished grid (with resulting compiled `CSS` file) then include that in your theme.

**Comment by driespieters** [comment]
Ok, thanks for all the info! I've decided to use a gulp build in combination with Themekit. (Using slate's theme files as a starting point.)

**Comment by curiouscrusher** [comment]
I realize this issue has been closed, but I just wanted to +1 the idea of using Neat & Updating SASS. 3.2.6 is 4 going on 5 years old, that's pretty stale IMO.

I was hoping to use Neat on a recent Slate based project, and was disappointed when I found I wouldn't be able to because of the old version of SASS in use.

As an aside, all versions of Neat were unusable in my testing, as the lowest required version of SASS I was able to locate was 3.3.X
