### ISSUE TITLE
Invalid CSS file if there is multiple media queries stacked together

### ISSUE THREAD

**Issue by sebastijandumancic** [Shopify/slate#176]
### Problem

When I use stacked media query such as: 

`@media (min-width: 500px) and (max-width: 900px) { ... } `

and while `slate watch` is watching and pushing the files, I get no apparent errors, but the whole CSS build fails and when you enter Theme customisation you get the error that after `(min-width: 500px) ` expected symbol was `{` and that `and` was provided, which was actually legitimate to have. 

### Scope

It looks like an issue with theme scaffolding.

### Replication steps

Insert CSS rule with two media queries linked by `and` instead of only one. CSS breaks, terminal gives no error, you feverishly try to `watch` `build` `whatever`, but to no avail, only to see the error in shopify's customisation tool.

### More Information

I'd like for someone to confirm this behaviour, but it doesn't look like error is local somehow. Thanks!

**Comment by t-kelly** [comment]
Hey @sebastijandumancic -- I gave this a run through and couldn't reproduce your problem. Everything seems to be working for me! [Video of my test](https://monosnap.com/file/ztSLpacuT6NAC2iWMSvorpZsTAgEfT)
