### ISSUE TITLE
Compile Sass before uploading

### ISSUE THREAD

**Issue by jackiboy** [Shopify/slate#177]
Hi Guys.
I am wondering is it possible to compile the sass before uploading it to the server?

My client does not need to do anything with the theme sections so I want to take advantage of the latest version of SASS and use my sass and postcss work flow like I normally do in other development environments.

Cheers,
Jack

**Comment by NathanPJF** [comment]
@jackiboy There's two things to this:
1. Currently the tooling in Slate will treat all CSS and SCSS files as if they are to be `*.liquid` files.  There an issue in the slate-tools repo where we are discussing addressing this: https://github.com/Shopify/slate-tools/issues/57
2. There's currently no way to inject your own compiling step.  Meaning, a way for you to add to or modify the asset build process.  This is a request we are aware of.  Modifying the build process has come up in other threads.

In the meantime, if you want to use your own preprocessors I recommend using Theme Kit to manage the Shopify deploys in lieu of Slate. https://shopify.github.io/themekit  You'll be able to integrate it's commands into your own custom build environment.

**Comment by jackiboy** [comment]
@NathanPJF Thanks for the heads up I will just use themekit for now :-)

**Comment by ckizer** [comment]
Themekit can be used with the slate theme?

**Comment by t-kelly** [comment]
@ckizer yes -- the contents of `dist/` directory can be uploaded to Shopify servers with Themekit. Just make sure you also include a `config.yml` in the `dist/` directory too.
