### ISSUE TITLE
How to use section js?

### ISSUE THREAD

**Issue by CodeGearThemes** [Shopify/slate#183]
We are using other framework like bootstrap and want to use section js function onUnload(), onSelect(), etc functions is it sufficient we include section.js and do necessary calls or is section.js dependent in other js files.

Lets say I can to make slider in homepage, so for theme editor we have to handle section:load etc 

Thanks in Advance!

**Comment by Codesesh** [comment]
I think there needs to be a nice clear tutorial written up on how to use section.js as I don't quite understand it fully yet either.

**Comment by CodeGearThemes** [comment]
Thank you for replying, figured our from Webinar from shopify.

**Comment by t-kelly** [comment]
@CodeGearThemes totally agree we could use some more documentation on all script files included in the `script/slate` folder. 

Will put this on our roadmap!

**Comment by CodeGearThemes** [comment]
Great Thank you! We will also try to contribute. Though we missed Shopify webinar, but recording was available in youtube which helps us a lot. Slate seems to have great flexibility we already have created section based theme with slate.

**Comment by joshbedo** [comment]
Any updates on this? I can't find any solid info on how to structure javascript for sections properly. I need access to section settings within my JS code.

**Comment by t-kelly** [comment]
Good news, sections.js has been moved to [Shopify/theme-scripts](https://github.com/Shopify/theme-scripts), and [updated with documentation](https://github.com/Shopify/theme-scripts/tree/master/packages/theme-sections)!

**Comment by YogiZoli** [comment]
I want to include script/slate but using -v0 which is not supported anymore. 
Where should I include it and how? {% include script/slate } ?
Thanks, great thread
