### ISSUE TITLE
Download changes made in Shopify UI

### ISSUE THREAD

**Issue by puppeteer701** [Shopify/slate#189]
How would someone download changes on HTML made in Shopify UI?

ThemeKit has 
```
theme download
```

**Comment by Jore** [comment]
For my continuous deployment setup I needed to download the settings_data.json file before pushing up template files with `slate`. I just installed and used `themekit` alongside `slate` as the config files are compatible.

**Comment by t-kelly** [comment]
@puppeteer701 As @Jore mentioned, the best way to download the theme from Shopify servers is to use `themekit` alongside `slate`. Slate wraps Themekit so they work well together.

I will leave this issue open so we can discuss if and how we could include `theme download` in Slate's commands.

**Comment by NathanPJF** [comment]
There's already a discussion on this in the slate-tools repo: https://github.com/Shopify/slate-tools/issues/40

**Comment by t-kelly** [comment]
Great - will close this a leave the discussion for the issue mentioned above.
