### ISSUE TITLE
zsh: command not found: slate

### ISSUE THREAD

**Issue by eheiser** [Shopify/slate#190]
### Problem

After installing node, npm and slate I keep getting zsh: command not found: slate in the terminal. 
How to remedy this? On Mac OS X Sierra.

**Comment by t-kelly** [comment]
Hey @eheiser, did you include the `-g` flag when you ran `npm install -g @shopify/slate`?

What is the output when you run `which npm`?

**Comment by eheiser** [comment]
which npm yields:
/usr/local/bin/npm

npm -v yields:
5.0.3

**Comment by t-kelly** [comment]
Running `npm install -g @shopify/slate` should create `slate` bin file inside the same directory as your `npm` bin command. Can you make sure you included the `-g` flag and also check your `/usr/local/bin/` directory for a `slate` bin?

**Comment by eheiser** [comment]
doing ls /usr/local/bin/ I don't see a slate directory - 
from the screenshot looks like it's being installed elsewhere

**Comment by t-kelly** [comment]
Yeah it looks like you've might multiple installs of node/npm. Ultimately, whatever path the slate command is being create in, needs to be included in the `PATH` of your `.zshrc` file.

Otherwise, if you're willing to restart and erase any installs of npm/node - [NVM](https://github.com/creationix/nvm) is a great Node version manager that lets you install and switch between versions really quickly. Worth exploring 😃

**Comment by eheiser** [comment]
I appreciate your help, but your answer is exactly why I hate all that npm/node/gem crap :)
(don't take this the wrong way, I really appreciate you taking the time.)

**Comment by t-kelly** [comment]
Going to close this as I'm pretty sure it's not a Slate bug but something with your Node setup. Feel free to continue to post and I'll do the best I can to help you get things up and running.

**Comment by sebbean** [comment]
just upgraded to slate 1.0 and upgraded my nvm version for it.

now my old theme's are broken with this this error

**Comment by sebbean** [comment]
<img width="661" alt="screen shot 2018-05-03 at 9 01 32 pm" src="https://user-images.githubusercontent.com/423997/39612536-3121c12a-4f15-11e8-8b67-8a38b0f2ded1.png">

**Comment by t-kelly** [comment]
@sebbean Slate v1 is a major version release where there are many breaking changes. I suggest you read through the new docs in the [Slate wiki](https://github.com/Shopify/slate/wiki) for how to get up and running :)

**Comment by sebbean** [comment]
@t-kelly yep i know all about the new one - excited to use it

i still have lots of themes running on the old one that i need to maintain.

I dont really know the flow to swapping between the two versions atm
