### ISSUE TITLE
Add CSS autoprefixer to build process

### ISSUE THREAD

**Issue by edeesims** [Shopify/slate#197]
I know that this is not something that you are looking into, but would be nice to know if there is a way for someone to add it into the build process

**Comment by t-kelly** [comment]
Hey @edeesims! We are currently investigating different ways of approaching our styles build process.  We had previously investigated auto-prefixing, but hit a roadblock when dealing with liquid inside our `.scss.liquid`. 

We recognize that not everyone deals with liquid inside their styles -- most often this is the case when you're developing a theme that is not going to be customized in the theme editor. 

As a first step, we could definitely get prefixing setup for `.scss` without liquid.

**Comment by jctchow** [comment]
Personally I run my own gulp tasks for compiling sass and I use:
``
.pipe(sass())
.pipe($.replace('"{{', '{{'))
.pipe($.replace('}}"', '}}'))
.pipe(autoprefixr())
``
and in my .scss I go:
``
#{'"{{ \'logo.png\' | asset_url }}"'}
``
to interpolate to not confuse the sass compiler with liquid tags

**Comment by t-kelly** [comment]
Closing this in preference to https://github.com/Shopify/slate/issues/268

**Comment by juanpasolano** [comment]
@jctchow Whats the dollar sign in your example?
