### ISSUE TITLE
why is slate previewing theme now?

### ISSUE THREAD

**Issue by yangkennyk** [Shopify/slate#208]
I built a site out with slate a couple months ago and whenever I ran slate it would simply load

 Local: https://localhost:3000/
    External: https://192.168.1.3:3000/
 --------------------------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.3:3001

but now it's loading it with "preview_theme_id" appended even on a fresh slate installation. 

 Local: https://localhost:3000/?preview_theme_id=
    External: https://192.168.1.3:3000/?preview_theme_id=
 --------------------------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.3:3001

it shows the "previewing theme" dialog box. how do I remove the preview? I've made sure I'm using the correct theme ID as well as the trying "live"

**Comment by chrisberthe** [comment]
Hi @yangkennyk - is everything still working on your side though and is it just `?preview_theme_id=` that's being appended to the URL?

This would make sense since in `slate-tools` we check for this: https://github.com/Shopify/slate-tools/blob/master/src/tasks/deploy-sync.js#L33-L35. Line 33 explains that we're always setting that parameter to break the theme preview cache. Perhaps there's another way around this for when someone sets the `theme_id` to "live".

@NathanPJF I believe you had updated this a while back?

**Comment by NathanPJF** [comment]
@yangkennyk you can see where this change came from on this issue: https://github.com/Shopify/slate-cli/issues/115

Once you click minimize on that preview bar it should stay minimized as @t-kelly introduced a new script for this in Slate Tools v0.3.3 https://github.com/Shopify/slate-tools/releases/tag/v0.3.3.  This may require you update your version of Slate Tools.

@chrisberthe 

> Perhaps there's another way around this for when someone sets the theme_id to "live".

No quick win that I know of.  I'm mimicing the behaviour seen at /admin/themes` to break the cache.

![](http://take.ms/alUO7)

**Comment by t-kelly** [comment]
> Once you click minimize on that preview bar it should stay minimized as @t-kelly introduced a new script for this in Slate Tools v0.3.3 https://github.com/Shopify/slate-tools/releases/tag/v0.3.3.

These changes were not merged and published in `v0.3.3`. They will be released in the upcoming version `v0.12.0`.

**Comment by t-kelly** [comment]
Closing as this behaviour is intended. If your `config.yml` has `theme_id: 'live'` then `?preview_theme_id=` does not appear. If an id is set for `theme_id` then it does appear.

https://github.com/Shopify/slate/pull/236 will take care of persisting the minimize of the preview bar.
