### ISSUE TITLE
Disable BrowserSync notification by default

### ISSUE THREAD

**Issue by kettultim** [Shopify/slate#210]
This is maybe more of a personal preference than a real issue but I think it's useful to disable the BrowserSync connected notification by passing the BS option 'notify:false':

`slate-tools/lib/tasks/deploy-sync.js line 47:`

```
browserSync.init({
++notify:false,
    proxy: {
      target: proxyTarget,
      middleware: function middleware(req, res, next) {
        var prefix = req.url.indexOf('?') > -1 ? '&' : '?';
        req.url += prefix + queryStringComponents.join('&');
        next();
      }
    }
```

It's particularly useful when developing in mobile and an ajax cart.

**Comment by t-kelly** [comment]
Going to close this in preference of #256. Like you said this might be a personal preference, but maybe it could enabled/disabled via the config file we're thinking of adding.
