### ISSUE TITLE
Using CSS injection instead of page reload in 'slate watch' task

### ISSUE THREAD

**Issue by kettultim** [Shopify/slate#211]
Quick question/feature request... is there any discussion about using injection instead of reloading in the `slate watch` task?

BrowserSync has functionality for it: https://www.browsersync.io/docs/api#api-stream but I'm a bit sketchy on how best to implement it into the existing Slate-tools workflow. I'll keep tinkering away and post back here when I have a solution if no one else claims one first.

**Comment by t-kelly** [comment]
Thanks for posting this @kettultim! We'll investigate this too. Keep us posted on your progress 😄

**Comment by linuxbastard** [comment]
+1 on this

**Comment by t-kelly** [comment]
We now us Webpack Hot Module Replacement to inject styles when developing.

This has been started and shipped in the [1.x branch](https://github.com/Shopify/slate/tree/1.x).
