### ISSUE TITLE
changing git branch doesn't update changed files automatically

### ISSUE THREAD

**Issue by samratrocks** [Shopify/slate#216]
### Problem

*Changing git branch in the directory slate is watching doesn't seem to trigger an update .*

### Replication steps

Initialize a git repo in the directory slate is watching. Make changes to multiple files and now change branches. Slate doesn't upload the reverted files to Shopify.

**Comment by t-kelly** [comment]
I have a gut feeling based on past experience with other watch tools that this may be a pretty big ask. Most of the time you need to restart a watch tool when switching branches due the large number of files that change at the same time.

Nevertheless, I will investigate this and see what's possible! Thanks for submitting it @samratrocks

**Comment by samratrocks** [comment]
@t-kelly Hey, the problem I'm facing is that frequently the files are out of sync between themes and branches. By restart do you mean do a theme upload after a branch change? 
If there is an easy solution (or a quick hack) I'm all for it since programming this feature would probably take a good amount of man hours.

Thanks!

**Comment by jonathanmoore** [comment]
@samratrocks I have not noticed that same issue with Slate. I'll frequently shift branches while working and `slate watch` will properly sync all the files changed between branches.  The only exception is if I switch between branches and the `config.yml` file has different config variables.

**Comment by t-kelly** [comment]
I don't think this a priority to fix for Slate v0.x. Closing.
