### ISSUE TITLE
[CLOSED] slate-cli section generator

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#222]
<a href="https://github.com/m-ux"><img src="https://avatars0.githubusercontent.com/u/4432259?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [m-ux](https://github.com/m-ux)**
_Friday Jun 24, 2016 at 22:17 GMT_
_Originally opened as https://github.com/Shopify/slate-cli/pull/6_

----

- generates a new section scaffold in the current theme's `src/sections/` directory
- fixed a bug with theme generation when no name was provided.

You can test this by pulling this branch into your `npm-link`ed slate-cli repo and running `slate new section <section-name>` from inside a slate theme directory.  

If you also pull the (section workflow branch)[https://github.com/Shopify/slate/pull/350] from the Slate repo, you can run this in conjunction with the `slate watch` task to see the fully functioning workflow.

@Shopify/themes-fed @macdonaldr93 

----

_**[m-ux](https://github.com/m-ux)** included the following code: https://github.com/Shopify/slate-cli/pull/6/commits_

**Comment by t-kelly** [comment]
<a href="https://github.com/m-ux"><img src="https://avatars0.githubusercontent.com/u/4432259?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [m-ux](https://github.com/m-ux)**
_Friday Jun 24, 2016 at 22:18 GMT_

----

could specifically use feedback / suggestions around the boilerplate content for section files.

Will add a followup PR next week to support all-in-one section.liquid files (i.e. opting out of folder approach).

**Comment by t-kelly** [comment]
<a href="https://github.com/cshold"><img src="https://avatars3.githubusercontent.com/u/1730309?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cshold](https://github.com/cshold)**
_Monday Jun 27, 2016 at 13:23 GMT_

----

Boilerplate ideas:

##### style.liquid

```
<style>
  /*
    Access section/block settings with liquid tags here to create an inline `<style>` tag for each instance of the section.
    Include the `section.id` or `block.id` in your selector to ensure the settings apply to the correct instance.
    E.g. `.element-{{ section.id }} { } `.

    If you don't need to access any section settings in CSS, you can delete this file.
  */
</style>
```

##### settings.json

```
{
  "settings": [],
  "presets": [{
    "name": "Section preset",
    "category": "Miscellaneous"
  }],
  "blocks" : {}
}
```

##### template.liquid

Safe to assume this can have a comment instead of any markup?

```
{% comment %}
  Define your section markup, using `section.settings.setting_name` to access specific settings.
  Sections do not have access to global liquid variables.
{% endcomment %}
```

##### script.js

```
/**
 * Section JS is concatenated together into a single file and loaded with a `defer` tag, meaning it will run after the page has finished parsing.
 * You cannot use liquid tags here. Instead, use data attributes on the elements themselves to access any required settings.
*/
```

**Comment by t-kelly** [comment]
<a href="https://github.com/macdonaldr93"><img src="https://avatars1.githubusercontent.com/u/5184848?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [macdonaldr93](https://github.com/macdonaldr93)**
_Tuesday Jun 28, 2016 at 15:51 GMT_

----

I'm assuming there won't be any docs up for the initial release of this so I'd be inclined to add more information coaching developers on best practices. Spinning off of what both Carson and Michael wrote:

**style.liquid**

``` html
<style>
  /**
   * Section settings are currently only accessible in CSS through inline <style> blocks. 
   * 
   * Use this file sparingly; only for setting color or font settings, etc. - the majority of
   * your section CSS should still live in your main theme.scss bundle.
   *
   * Access `section.blocks` settings with liquid tags here to create an inline `<style>` tag 
   * for each instance of the section. Include the `section.id` or `block.id` in your selector 
   * to ensure the settings apply to the correct instance.
   * E.g. `.element-{{ section.id }} { } `.
   *
   * If you don't need to access any section settings in CSS, you can delete this file.
  **/
</style>
```

Also, I'm just wondering if the files should be named differently to help with the association to the compiled code and the liquid drops for blocks.

**settings.json => schema.json**

The compiled code would be wrapping the contents from this file in the following liquid:

``` javascript
{% schema %}
  // some json stuff
{% endschema %}
```

**script.js => javascript.js**

The compiled code would be wrapping the contents from this file in the following liquid:

``` javascript
{% javascript %}
  // some javascript stuff
{% endjavascript %}
```

**Comment by t-kelly** [comment]
<a href="https://github.com/m-ux"><img src="https://avatars0.githubusercontent.com/u/4432259?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [m-ux](https://github.com/m-ux)**
_Tuesday Jun 28, 2016 at 16:56 GMT_

----

👍 thanks for the feedback guys, will update the PR and add some comments this afternoon as well.

**Comment by t-kelly** [comment]
<a href="https://github.com/cshold"><img src="https://avatars3.githubusercontent.com/u/1730309?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cshold](https://github.com/cshold)**
_Tuesday Jun 28, 2016 at 17:24 GMT_

----

> Section settings are currently only accessible in CSS through inline `<style>` blocks.

This makes it sound like they're going to be accessible elsewhere later. There are no plans for that, so I'd avoid hinting at it.

**Comment by t-kelly** [comment]
<a href="https://github.com/stevebosworth"><img src="https://avatars0.githubusercontent.com/u/1938373?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [stevebosworth](https://github.com/stevebosworth)**
_Monday Jul 04, 2016 at 23:00 GMT_

----

👍 

any 🎩 ing required?

**Comment by t-kelly** [comment]
<a href="https://github.com/m-ux"><img src="https://avatars0.githubusercontent.com/u/4432259?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [m-ux](https://github.com/m-ux)**
_Monday Jul 04, 2016 at 23:26 GMT_

----

@stevebosworth if you've got some time to do it, this & https://github.com/Shopify/slate/pull/350 need to be top-hatted together.

**Comment by ConduciveMammal** [comment]
Sorry to jump in on this guys but if there was ever a way to use section css outside of the inline `<style>` blocks, then that would be super great. Currently having inline `<style>` blocks all the way down your page throws up errors in the W3C validator. It's hard to promote "W3C Compliant Websites" whilst avoiding this error.

**Comment by t-kelly** [comment]
@ConduciveMammal want to create a new issue for what you just mentioned? This is old and the issue title doesn't really reflect this part of the discussion. 

Thanks!

**Comment by ConduciveMammal** [comment]
@t-kelly
Ahh of course, absolutely, I’ll do it, thanks!
