### ISSUE TITLE
slate download command

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#229]
<a href="https://github.com/NathanPJF"><img src="https://avatars2.githubusercontent.com/u/6284114?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NathanPJF](https://github.com/NathanPJF)**
_Saturday Jan 14, 2017 at 22:34 GMT_
_Originally opened as https://github.com/Shopify/slate-tools/issues/40_

----

Slate currently doesn’t have a equivalent of Theme Kit’s `theme download` command.  It may be helpful to have this pull down individual files, or the entire hosted site, into the `dist` folder so developers can use git to see what all has changed.

Scenario:  You have to make a hot fix on the live site, or the merchant you are working for made some of their own changes while you were away.  How do you find out what exactly changed and across which files?

Other scenario: I make a bunch of changes to my theme settings using the Online editor.  How should I have those reflected in my remote files?  Currently I would need to go to the `settings_data.json` files and copy its contents then paste those into my own `src/config` file (and `dist` if I want as well).

### Location of download

Suggesting the files be pulled into the `dist` folder because they are essentially compiled files.  This command would be there to help developers, particularly those using git, to see what changed and then work on their build files to match.

**Comment by t-kelly** [comment]
<a href="https://github.com/celsowhite"><img src="https://avatars0.githubusercontent.com/u/3518732?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [celsowhite](https://github.com/celsowhite)**
_Wednesday May 03, 2017 at 17:04 GMT_

----

This is the only thing preventing me from switching from [quickshot](https://quickshot.readme.io/docs/theme-download)! Would love to see this in place.

I typically develop sites for clients then only come in later for hot fixes or new feature requests. In between that time, many of my clients will upload new assets, make css changes or change content in template files. All of which I'd like to pull locally and potentially deploy to my development environment.

**Comment by t-kelly** [comment]
<a href="https://github.com/infernalsirius"><img src="https://avatars1.githubusercontent.com/u/11705?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [infernalsirius](https://github.com/infernalsirius)**
_Thursday May 04, 2017 at 09:53 GMT_

----

I was about to open an issue for this feature 😉  . Right now the watch feature does not look upstream for changes that may have been done in the web admin interface. If you try to download using the older themekit tool, it does not respect the folder hierarchy needed with the build system. 

If you are using an app that generates code and add it to your files, it can be quite a task to track every changes and transfer them to your local dev environment. For this use case, even _quickshot_ does not seems to be able to it since it is uploading the builded files.

Having the code downloaded to the dist folder would surely be a step forward, but if you track your project with a versioning system, you'll still have to find the code in the dist files, which is almost the same as copying and pasting it from the web editor.

Maybe that a kind of deploy hook in combination with a repo ( github, bitbucket, etc) could be the answer. The web editor would commit the changes to the repo and the sync would be done as usual, by pulling the latest changes from your remote repository... It sounds more complicated though than having a simple remote repository access to your Shopify store. Those are only ideas I throw in the wind here 😉 .

**Comment by t-kelly** [comment]
<a href="https://github.com/tkdave"><img src="https://avatars3.githubusercontent.com/u/219198?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tkdave](https://github.com/tkdave)**
_Wednesday Jul 05, 2017 at 21:16 GMT_

----

Themekit tool still works. Just tell it what directory to use.

`theme download -d src -e production`

**Comment by iamkeir** [comment]
+1 for this - I have just had a 3rd-party app install some stuff in my store and now I am having to manually extract what they have done into my local copy... a real faff!

**Comment by t-kelly** [comment]
Closing this in preference of #255
