### ISSUE TITLE
Add source maps to build

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#231]
<a href="https://github.com/NathanPJF"><img src="https://avatars2.githubusercontent.com/u/6284114?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NathanPJF](https://github.com/NathanPJF)**
_Sunday May 14, 2017 at 21:49 GMT_
_Originally opened as https://github.com/Shopify/slate-tools/issues/63_

----

### Problem

A question was posed in the Slate repo about adding source maps to the build by @kettultim https://github.com/Shopify/slate/issues/150

This has also been brought up internally as good development practice to help with debugging production code.  e.g. Narrative theme's minified JS shipped in production.

### Scope

Look into source map implementation for both JS and CSS.

### More Information

I remember that @tiffanytse recently asked us about source maps.  Tiffany: Any context you can share about how this came up?

In the linked issue, @kettultim said he got a working solution with https://www.npmjs.com/package/gulp-sourcemaps - worth looking into.

**Comment by t-kelly** [comment]
<a href="https://github.com/jonathanmoore"><img src="https://avatars0.githubusercontent.com/u/454095?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonathanmoore](https://github.com/jonathanmoore)**
_Monday May 15, 2017 at 18:55 GMT_

----

I was actually about to open a separate issue regarding minification during the build process.  With the premium theme support, we see very frequent requests to minify the JS files in an effort to boost PageSpeed.

Today I was going to try implementing a local variation of [build-js.js](https://github.com/Shopify/slate-tools/blob/master/src/tasks/build-js.js) that preserves the original JS file in case the merchant or developer needs to modify it, but also creates a new theme.js.min version that is loaded in theme.liquid.

Seeing how Narrative handles the JS files is what prompted the idea to make this happen with our next theme update.

**Comment by t-kelly** [comment]
<a href="https://github.com/tiffanytse"><img src="https://avatars0.githubusercontent.com/u/1638215?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tiffanytse](https://github.com/tiffanytse)**
_Tuesday May 16, 2017 at 10:56 GMT_

----

I had gotten a question on source maps via the blog - I wanted to clarify. From my understanding right now (maybe I'm wrong) the only way to get sort-of-source-maps is to compile the sass locally and have your compiler insert comments into your CSS - which could then be removed on production compile.

**Comment by t-kelly** [comment]
This has been started and shipped in the [1.x branch](https://github.com/Shopify/slate/tree/1.x).

**Comment by angelo-moreira** [comment]
This is not working for me, the styles get injected into the page and I cannot see which file they come from, any ideas what could be causing this?

**Comment by angelo-moreira** [comment]
I have noticed that the styles are injected in the `theme.js` file, could this be the issue?

**Comment by t-kelly** [comment]
@angelo-moreira I had to disable style source maps for now because of how they impact how styles are loaded. See https://github.com/Shopify/slate/blob/8984f7a620f665d11ed900cd086ddc51d6952635/packages/slate-tools/tools/webpack/config/dev.js#L41-L45 and https://github.com/webpack-contrib/style-loader/issues/293 for more.

**Comment by NeekSandhu** [comment]
You guys might wanna consider [`css-visor`](https://www.npmjs.com/package/css-visor)

I wrote this module due to ugly `style-loader` behaviour. `css-visor` leverages `HTMLWebpackPlugin` and injects stylesheets at compile time w/ HMR once loaded.

**Comment by t-kelly** [comment]
@NeekSandhu thanks! Will check it out.
