### ISSUE TITLE
Migrating theme and styles folder

### ISSUE THREAD

**Issue by orangemooncreative** [Shopify/slate#235]
I'm not sure if I don't understand how this is supposed to work or if it is truly an issue. I migrated an existing theme to slate. I am trying to add stylesheets to the styles folder in addition to the existing stylesheets. My file structure in the styles folder is as follows:

styles
    - modules
        - nav-menu.scss
    - theme.scss

I placed {{ 'theme.scss.css' | asset_url | stylesheet_tag }} in the head of my theme.liquid file below my existing styles.css.liquid file.

But for the life of me I can not get the theme.scss.css to load correctly on my site. It appears in the head of the live site but if I open the link in a new tab I get the error "failed to compile scss" instead of the actually css. If I remove the .css in the url the css is visible.

So if you migrate a theme can you still use the styles folder or does it only work for a new slate theme?

**Comment by t-kelly** [comment]
Hey @orangemooncreative -- it looks like you have an error somewhere in your `theme.scss` and that our SCSS compiler isn't giving you any helpful feedback as to where the error is.

My recommendation (until we fix this issue with SCSS error reporting) would be to remove pieces from your `theme.scss` file until you no longer get a "failed to compile scss" error and you actually see the compiled scss.

Related: https://github.com/Shopify/slate/issues/127

**Comment by orangemooncreative** [comment]
@t-kelly coolio. got it. thanks a bunch.

**Comment by t-kelly** [comment]
Looks like it should work. Are you sure the updated `.scss` file is being successfully uploaded to your store? It would be worth checking the `theme.scss.liquid` file on your store:

1. Go to `/admin/themes`
2. Click the *Actions* dropdown on the theme you're working on, and then select *Edit HTML/CSS*
3. Click on the `assets/` directory, and check if `theme.scss.liquid` has the contents of what you showed above

**Comment by orangemooncreative** [comment]
All sorted. Thanks a bunch. One more question...when you run a slate deploy is it normal for any image files added through theme customizations in the editor to be removed? Or is it a bug.

**Comment by NathanPJF** [comment]
> when you run a slate deploy is it normal for any image files added through theme customizations in the editor to be removed?

@orangemooncreative Are your images being removed from your `assets/` folder, or are image settings being reset in the online theme editor?

If it's an issue with the theme editor, that sounds like you may be uploading your local copy of `settings_data.json` which would not contain the changes you're making in the online editor.

https://github.com/Shopify/slate/blob/master/packages/slate-theme/config-sample.yml#L21

```
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings
```

**Comment by orangemooncreative** [comment]
@NathanPJF images were being reset in the online theme editor. thanks...I had the line uncommented but some kind of way the dash got deleted...so i am guessing you were right and the local copy was being uploaded. added the dash back and have my fingers crossed for the next time I deploy. Thanks!

**Comment by t-kelly** [comment]
Glad we could help @orangemooncreative. Thanks for posting an issue!
