### ISSUE TITLE
Slate Watch Error: Transfer Failed: File(s) failed to upload to store. See log notes above.

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#243]
### Problem

I've been in a situation where I've had to move my theme directory to and from BitBucket to pass work to colleagues and to work from home. After they've downloaded all of the files and attempted to start working, they use `slate watch` and it all starts fine, but as soon as they save a file, Slate CLI produces this error: `Transfer Failed: File(s) failed to upload to store. See log notes above.`. 
I looked in `deploy.log` but it seems it was empty. I figured it was a mismatch in differing Node/Slate versions. Now I'm on my home computer, downloaded from BitBucket, and I'm too now seeing this error whenever I try to push a new change to the store.

![image](https://user-images.githubusercontent.com/18140157/29590403-8d02e484-8791-11e7-980d-aeb6649cac30.png)

### More Information

Running `node -v` says my node version is v6.11.0
Running `npm -v` says my NPM version is 5.3.0
Running `slate -v` says my Slate version is 0.11.0

**Comment by carlosepp** [comment]
facing the same issue

**Comment by carlosepp** [comment]
fixed by wiping out `node_modules` and slate start again

**Comment by iamkeir** [comment]
Having same issue - colleague pulled down repo, ran `npm install`, ran `slate start`, everything begins running fine. However, when saving a file, we receive `Transfer Failed: File(s) failed to upload to store. See log notes above.` ...but no notes above.

`node -v` v8.8.1
`npm -v` v5.4.2
`slate -v` v0.13.0

Does `package-lock.json`, `deploy.log` or `theme.lock` have any impact on this? If so I can post the contents of them. Quite a critical issue as we are struggling to get setup for working together.

**Comment by ConduciveMammal** [comment]
I can’t remember how I got passed the issue, if I remember rightly, my colleague’s and I had different versions of some packages, try and update them all on both yours and their machines and see if that helps.

**Comment by iamkeir** [comment]
@ConduciveMammal thanks - will explore this (nice username btw).

Weirdly, we managed to get my colleague up and running by deleting `node_modules`, changing to Node v6 then running `npm install`. Problem is, now **_I_** am the one with the issue!

Will report back.

**Comment by iamkeir** [comment]
Right, it seems to be working now - not sure which thing did it but I did the following:

1. Delete `node_modules`, `package-lock.json`, `deploy.log` and `theme.lock` if you have them
2. Switch to Node `v6`
3. Run `npm install` (it must complete - if it hangs & fails on `node ./lib/cli.js install`, you'll need to go back to step 1)
4. Run `slate start`

I'm not really sure what is happening as there is little by way of error reporting.

**Comment by t-kelly** [comment]
Unable to replicate this due to lack of logging information, so I figure we may as well fix that first! #366
