### ISSUE TITLE
what is the package for using =require slate/a11y.js

### ISSUE THREAD

**Issue by yangkennyk** [Shopify/slate#244]
I'm just wondering what package is used for the importing of JS in the theme.js as I'd like to use it elsewhere but couldn't figure out what package makes it work

thanks!

**Comment by NathanPJF** [comment]
@yangkennyk In the public docs, there is a note about this https://shopify.github.io/slate/js-examples/

> In the theme.js file, you must import the Section specific JavaScript with the `// =require helper`, [more information here](https://www.npmjs.com/package/gulp-include), as it will contain your constructor.

**Comment by t-kelly** [comment]
@yangkennyk the package is `gulp-include`
