### ISSUE TITLE
Build and watch theme.scss.css?

### ISSUE THREAD

**Issue by salasmx** [Shopify/slate#245]
### Problem

Well this is kind of weird but build or watch seems to do nothing with styles.

Watch: Styles cannot be applied because gulp is watching for theme.scss.css and even if I remove .css it does the same, gulp is still watching for theme.scss and because there is no source maps browsers cannot translate/read scss.

Build does not compile theme.scss

It is me or anyone else has the same problem?

**Comment by t-kelly** [comment]
@salasmx SCSS watching works as follows:
1. The [`watch:css`](https://github.com/Shopify/slate/blob/master/packages/slate-tools/src/tasks/build-css.js#L47) watches [`theme.scss`](https://github.com/Shopify/slate/blob/master/packages/slate-theme/src/styles/theme.scss)
2. The [`watch:dist`](https://github.com/Shopify/slate/blob/master/packages/slate-tools/src/tasks/watchers.js#L105) task watches all files in `dist/` for changes.
3. Whenever [`theme.scss`](https://github.com/Shopify/slate/blob/master/packages/slate-theme/src/styles/theme.scss) is changed, `watch:css` triggers a rebuild and the new version output as `dist/assets/theme.scss.liquid`. `watch:dist` then triggers an upload of this new version to the servers.

Not sure what is wrong with your setup given the details you provided. Can you please elaborate?

**Comment by salasmx** [comment]
@t-kelly I've created a new slate theme and now everything works like a charm.

Thank you.

btw. it would be nice some scss error log on terminal/console.

**Comment by t-kelly** [comment]
https://github.com/Shopify/slate/issues/127 😉
