### ISSUE TITLE
Document theme development workflow with Slate

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#251]
If there is one thing we have discovered since launching Slate is the incredible number of different workflows developers have when developing themes. One of the objectives of Slate is to provide developers with a tested workflow. Part of Slates workflow can be inferred by the tools and features provided, but another part takes place outside of the development environment.

Lets document the workflow used by the Shopify Themes Team and open it up to the community. This will give developers new to Shopify a reliable reference, and experts tips on alternative approaches to their current workflow. Ideally this could also allow for feedback from the community, resulting in an even better workflow!

**Comment by t-kelly** [comment]
Related #333 

Make sure we touch on Git workflow. Adding a theme to Git. Cloning the Git repo to a new device.

**Comment by dan-gamble** [comment]
I'm in the process of trying to come up with a good workflow that works really well for team iteration. Would love to see some advice from your end on that.

**Comment by t-kelly** [comment]
Published https://www.shopify.ca/partners/blog/development-workflow

Will make a copy of it in the docs for future reference.
