### ISSUE TITLE
Full support for all Themekit commands

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#255]
Slate is tightly coupled with Themekit and extends Themekit's functionality to manage the entire theme development workflow. As an extension, Slate should inherently include all the features offered by Themekit. In its current state, Slate only provides indirect access to a couple ThemeKit commands, such as `theme upload` made available through `slate deploy`.

We should take full advantage of the features provided by Themekit, and extend them as we see fit with additional commands. For example, `slate upload` should call `theme upload dist/`, and `slate deploy` extends `slate upload` by calling `slate build && slate upload`.

The commands that should be made available include:
- bootstrap
- configure
- download
- open
- remove
- replace
- update
- upload

Related: 
* https://github.com/Shopify/slate/issues/229
* https://github.com/Shopify/slate/issues/369

**Comment by iamkeir** [comment]
What is the outcome - do we have 'download' now?

**Comment by iamkeir** [comment]
Yep, these are absolutely essential. Having to do it manually at the moment >:(

**Comment by iamkeir** [comment]
Turns out you can! https://github.com/Shopify/themekit/issues/483#issuecomment-339337452

So actually Theme Kit is fully available within Slate by the looks of it?

**Comment by t-kelly** [comment]
We are moving away from Themekit as we're realizing we don't need feature parity with it. More in #403
