### ISSUE TITLE
Add option for Prettier for automatic code formatting

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#257]
![image](https://api.monosnap.com/rpc/file/download?id=RdChpO469BLgz0k6qjSYxz1MW94t3q)

[Prettier](https://github.com/prettier/prettier) takes your code and reprints it from scratch. It removes all original styling and ensures that all outputted code conforms to a consistent style. Prettier is similar to linting, except instead of outputting errors and warnings, it outputs the corrected code.

Prettier is configurable but is extremely opinionated. If you just want to hack around or work on a prototype, it might get in the way. Prettier should be optional, with the ability to turn it on and off in the [Slate config file](https://github.com/Shopify/slate/issues/256).

**Comment by macs91** [comment]
Any update on this?

**Comment by t-kelly** [comment]
Being worked on for Slate v1.0! The VSCode plugin works well in the mean time if you want to take advantage of Prettier.

**Comment by macs91** [comment]
@t-kelly Thanks for the update. Will it be possible to format also liquid source with prettier?

**Comment by t-kelly** [comment]
Is it possible? Maybe? Probably? But it would require a custom Prettier extension. My gut feeling is that there are higher priorities to address for Slate v1.0, but it could be something explored in later releases.

**Comment by ConduciveMammal** [comment]
Out of interest, how would this function with liquid JS? `addToCart: {{settings.cartBtn}},` for example?

My experience with SCSS beautify when it contains liquid isn’t at all pleasant.

**Comment by t-kelly** [comment]
I would not expect it to work with `.js.liquid` syntax.
