### ISSUE TITLE
Manage .scss, .css, .scss.liquid, and .css.liquid files independently

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#258]
Slate currently treats all stylesheets equally. By doing this we miss out on a lot of great features available to files that don't need to be built on our servers (aka non-liquid files).

Some of these features include:
- Local compilation and error logging of `.scss` files (https://github.com/Shopify/slate/issues/127)
- Notification on SCSS error (https://github.com/Shopify/slate/issues/165)
- Reduced chance of server-side compilation timeout (https://github.com/Shopify/slate/issues/230, https://github.com/Shopify/slate/issues/133)
- Autoprefixing (https://github.com/Shopify/slate/issues/197)

Some of the features might be possible to do locally with `.scss.liquid`, but require custom plugins. This will take time. In the meantime, let's make these features available to styles that don't need to be customized by the Theme editor, aka `.scss`.

**Comment by driespieters** [comment]
@t-kelly Will this make it easier to add the Neat grid to Slate, since the compilation is done locally? (Local compilation using a more recent Sass version I presume)

**Comment by t-kelly** [comment]
@driespieters yes it should 😄

**Comment by vfonic** [comment]
@t-kelly I just hit the issue where I'm trying to migrate a WordPress website over to Shopify. The WP website uses SCSS and I'm having extremely hard time to port it to Shopify and make it work...Especially since I can't see any error messages...

Is there any possibility to see the error message somewhere? In the logs or compile it aside or...?

Much appreciated! Thanks!

**Comment by vfonic** [comment]
How stable is 1.x? When will it be released? I'm a little bit hesitant to use a branch that wasn't officially released. Thanks!

**Comment by vfonic** [comment]
To me it looks like 1.x already supports everything that 0.x has, now it's just missing couple of stuff that will be an addition on top of v0.x. I think in that case, following the semver, you could release 1.0.0 and, when you add those extra stuff, release 1.1.0
