### ISSUE TITLE
Promote the use of custom.js for theme customizations

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#265]
One of the biggest problems we have with updating an existing implementation of a theme is that the theme's source code often is modified. Once these edits have been made, it makes it pretty hard to apply updates - especially to a large number of stores. The edits can be made directly to the theme's JS files, or they live as inline scripts scattered throughout the DOM (not good).

`custom.js` is a file where you can perform theme modification without the need to edit Theme source code or inline JS inside liquid files. When combined with the new version of `section.js`, you can customize and extend any existing JS in the theme without the need to touch source code.

`custom.js` itself is very simple, just a empty JS file with maybe some comments. The power of it lies in documentation and examples.

**Comment by ConduciveMammal** [comment]
I must admit, I'm guilty of editing `theme`, `cart`, etc. I hadn't even thought about the upgradeability of doing so.

If we're not supposed to edit these files, would it not be wise to have them served as a Shopify global asset instead of baked right into the theme files?

**Comment by t-kelly** [comment]
The idea of not editing them is fairly recent and we're still investigating if it is indeed the right approach. Not moving forward with an official solution until we're sure its the right one.

**Comment by t-kelly** [comment]
Moved to https://github.com/Shopify/theme-scripts/issues/1
