### ISSUE TITLE
Bundle splitting and dynamic imports

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#266]
One of Webpack's most powerful features is code splitting. By using ES6 `imports`, Webpack builds a dependency tree of all assets and splits those assets as you want. These bundles can be requested on page load or dynamically after the page has loaded. The goal is to only request and execute code that is shared between pages or only needed by the current page.

Bundle splitting would allow us to have page and section specific JS bundles. Each template could have an associated JS bundle. Each section can have it's own bundle and be requested dynamically only if the section is present on the page.

Decreasing the amount of JS we download, parse, compile, and execute decreases first render, page load, and time to interactivity. Big perf win!

cc @Shopify/performance

**Comment by quinn** [comment]
@t-kelly Why not just use webpack and get all of this for free? Do you need help transitioning away from grunt?

**Comment by t-kelly** [comment]
@quinn see https://github.com/Shopify/slate/tree/v1.0.0-pre-alpha

**Comment by t-kelly** [comment]
Implemented in https://github.com/Shopify/slate/pull/450
