### ISSUE TITLE
Add vendor auto prefixing to .scss files

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#268]
Currently we use SCSS mixins to make working with vendor prefixes a little easier. Prefixing [has been attempted before](https://github.com/Shopify/slate/commit/a3be3e553ca8dc8e1036a736ad14f349a6c0bf06), but the hurdle that we couldn't get over was Liquid inside our SCSS files.

As mentioned in https://github.com/Shopify/slate/issues/258, there are lots of cases where developers only need `.scss` and not `.scss.liquid`. At the very least these files can receive the benefits of auto prefixing.

The most popular solution right now to this is https://github.com/postcss/autoprefixer

**Comment by rafaelderolez** [comment]
Any news on this? @t-kelly Using `@include prefix(position, sticky, webkit spec);` for example compiles:
```-webkit-position: sticky;
position: sticky;```

where (in this case) it should compile:
```position: -webkit-sticky;
    position: sticky;```

**Comment by t-kelly** [comment]
@rafaelderolez This is working in Slate v1. Will be making the alpha officially public in a week or two.

**Comment by t-kelly** [comment]
This has been started and shipped in the [1.x branch](https://github.com/Shopify/slate/tree/1.x).

**Comment by mtclmn** [comment]
Hi @t-kelly –
Is postcss/autoprefixer enabled in webpack by default? 
Or do I need to explicitly add it and turn it on?
And if so, how exactly would I do that? :) 
Thanks!

**Comment by t-kelly** [comment]
@mtclmn [Its on by default](https://github.com/Shopify/slate/blob/master/packages/slate-tools/tools/webpack/config/prod.js#L56-L63) with the `slate-tools build` script
