### ISSUE TITLE
Use the regular product template instead of a section

### ISSUE THREAD

**Issue by driespieters** [Shopify/slate#269]
Currently product.liquid is a section. However, I don't see the added value of using a section here. Wouldn't it be cleaner just to use it as a product.liquid file in the templates folder?

* The social share doesn't have to be a setting.
* It's probably used as an example, but is that Slate's objective?

**Comment by ConduciveMammal** [comment]
The Product template as a section has lots of added value, the same way any sections do.

Blocks can be used for various things such as item description tabs, product FAQs, sales banners etc.

Not only that but additional code put inside of `{% javascript %}`, `{% schema %}, & `{%stylesheet %}` is much more organised and manageable.

Imagine a theme that has hundreds of theme settings, now imagine trying to find the settings for the product within the thousands of lines of code within the `settings_schema.json` file. Plus that file has a max filesize of 1MB (I think that's the right number), so by keeping product in a section file, you keep that file size down.

**Comment by driespieters** [comment]
Agreed that using a section for the product template could be awesome. But should it come out of the box?

Most Slate projects will be used as a starting point for custom themes that won't provide a lot of settings.

My point being: keep it simple & clean.

**Comment by t-kelly** [comment]
@driespieters One of the biggest struggles with how we've approached Slate so far has been drawing the line on what to include and what not to include. Ultimately, no matter what we choose it will only serve a particular audience. For example, if we include more examples it could help beginners but get in the way for experts who will want to delete them. 

We're hoping to make these types of decisions easier with https://github.com/Shopify/slate/issues/262
