### ISSUE TITLE
Warnings when installing a new theme

### ISSUE THREAD

**Issue by ronnyew** [Shopify/slate#270]
### Problem

When installing a new theme, or migrating an existing one, I receive these warnings.

Is that normal? What action should I take?

Thank you.

- npm WARN deprecated express@2.5.11: express 2.x series is deprecated
- npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
- npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
- npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
- npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
- npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
- npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

### Replication steps

Just run slate theme or slate migrate

### More Information

*Any additional information which might be helpful.*

**Comment by t-kelly** [comment]
This is normal. More info here https://github.com/Shopify/slate/issues/160#issuecomment-323426417
