### ISSUE TITLE
method called on undefined variable for featured image for variant image on product page

### ISSUE THREAD

**Issue by mrahlstrom** [Shopify/slate#273]
### Problem

Variable undefined error in product.js.  Product.prototype.updateProductImage function.

"Cannot read property 'attr' of undefined 

this.**$featured_image**.attr('src', sizedImgUrl);

should be: this.**$featuredImage**.attr('src', sizedImgUrl); 

snake case should be camel case

### Replication steps

Select a product variant that has a variant image on a product page.

### More Information

this.$featuredImage defined at approximately line 53 
this.$featured_image used at approximately line 132

**Comment by saudslm** [comment]
@t-kelly there's another instance where $featuredImage has a type and is being used as $featured_image on line # 125 in product.js

**Comment by t-kelly** [comment]
This was fixed with [v0.12.3](https://github.com/Shopify/slate/releases/tag/v0.12.3). @sebpettersson [beat you both to it](https://github.com/Shopify/slate/pull/264#issuecomment-327454512) 😉

**Comment by saudslm** [comment]
@t-kelly you da man! 👍
