### ISSUE TITLE
Product featured image not showing in search results (search.liquid)

### ISSUE THREAD

**Issue by taylorbryant** [Shopify/slate#274]
### Problem

Product featured image not showing in search results (search.liquid).

### Replication steps

* Add a product with an image to your store
* Search using the product title as the search term

### More Information

* I was able to get the featured image to show by changing `{% if item.image != blank %}` to `{% if item.featured_image != blank %}`.

**Comment by t-kelly** [comment]
Good catch @taylorbryant. This is a mistake from a recent [result of a recent PR](https://github.com/Shopify/slate/pull/239/files#diff-133a54c52a7b2a8b71f702ad93ad3c83R35).

What we should be doing is checking for both [.image](https://help.shopify.com/themes/liquid/objects/article#article-image) and [.featured_image](https://help.shopify.com/themes/liquid/objects/product#product-featured_image). This covers images for article and products object results. Opening a PR soon!
