### ISSUE TITLE
JS Error: _ is not defined when trying to work with Section JS

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#277]
### Problem

After following @NathanPJF's Slate webinar, I'm trying to hook into the section functions `onBlockSelect()`, but I keep running into a console error saying `_ is not defined`.

This error is coming from `_.assignIn`.

I'm not sure what I'm doing wrong but it's just not having it, I looked through the JS code for the Slate Webinar demo theme and `_.assignIn` is used throughout that too.

### Replication steps

My Code inside of `faq-section.js` is:
```
theme.FAQ = {};

theme.FAQ = (function () {
  function FAQSection(container) {
    var $container = this.$container = $(container);
    var sectionId = $container.attr('data-section-id');
    var FAQ = this.FAQ = '#FAQ-' + sectionId;
    theme.FAQs[FAQ] = new theme.FAQ(FAQ);
  }
  return FAQSection;
})

theme.FAQSection.prototype = _.assignIn({}, FAQSection.prototype, {
  onBlockSelect: function (evt) {
    console.log('Block Selected');
  }
});
```

And inside of `theme.js`, I've registered the section as:
`sections.register('frequent-questions', theme.FAQSection);`

**Comment by t-kelly** [comment]
Hey @ConduciveMammal -- the examples you are probably seeing include [Lodash](https://lodash.com/) on the page. Lodash defaults to using the `_` global variable. 

Best thing to do is to add Lodash to your `/scripts/vendor` folder and it will get included in the `vendor.js` bundle.

**Comment by ConduciveMammal** [comment]
Hey @t-kelly, thanks a lot for the Lodash information, I'll be sure to check it out.

If Lodash wasn't to be used, to you know of any other examples that can be used as a starting point?

I feel the docs are definitely lacking in this area, will these be improved upon? The problem is since Slate is still relatively unheard of, here is the only place to seek information despite it not being it's purpose.

**Comment by ConduciveMammal** [comment]
@NathanPJF Similar to the above, I'm now getting a new error after including Lodash.

The error I'm now getting is: `Cannot read property 'prototype' of undefined`.

My full code is:

```
theme.slideshows = {};

theme.SlideshowSection = (function() {
  function SlideshowSection(container) {
    var $container = this.$container = $(container);
    var sectionId = $container.attr('data-section-id');
    var slideshow = this.slideshow = '#Slideshow-' + sectionId;

    $('.slideshow__slide', slideshow).each(function() {
      var $el = $(this);
      console.log(HELP);
        });

    theme.slideshows[slideshow] = new theme.SlideshowSection(slideshow);
  }


  console.log('Slideshow Function');


theme.SlideshowSection.prototype = _.assignIn({}, theme.SlideshowSection.prototype, {
  onUnload: function() {
    delete theme.slideshows[this.slideshow];
    console.log('Section Unload');
  },

  onSelect: function(evt) {
    console.log('Block Selected');
    var $slideshow = $(this.slideshow);

    var $slide = $('.slideshow__slide--' + evt.detail.blockId + ':not(.slick-cloned)');
    var slideIndex = $slide.data('slick-index');

    return theme.SlideshowSection.prototype;
  }

  // onBlockDeselect: function() {
  //   console.log('Block DeSelected');
  // }
});
})();
```

**Comment by t-kelly** [comment]
> If Lodash wasn't to be used, to you know of any other examples that can be used as a starting point?

jQuery `$.entend()` function similarly.

> The error I'm now getting is: Cannot read property 'prototype' of undefined.

Your brackets are messed up. Move the last line of code just above `theme.SlideshowSection.prototype = `
