### ISSUE TITLE
getting author photo URL

### ISSUE THREAD

**Issue by yangkennyk** [Shopify/slate#282]
It looks like the author photo url follows this pattern

//cdn.shopify.com/s/files/1/1871/6581/users/author-photo.jpg

but I can't seem to find a way to get the /users/ path.

is it possible to pull the blog post author photo into the theme automatically?

**Comment by t-kelly** [comment]
Hey @yangkennyk -- looks like you're onto something here. Searching through the Shopify forums only shows some [hacky ways of getting this image](https://ecommerce.shopify.com/c/ecommerce-design/t/add-user-image-for-blog-author-391906). I feel like you should be able to reference it directly inside the [`article.user`](https://help.shopify.com/themes/liquid/objects/article#article-user-account_owner) object -- maybe as `article.user.image`?

I'm going to escalate this to Shopify core and see what we can do. Will keep you posted!

**Comment by t-kelly** [comment]
We have deployed a new attribute in core -- `article.user.image`. You can use it with the `img_url` to get a CDN url to the author's profile image. Note that it only gives a URL for an image uploaded to Shopify servers, it does not provide a URL to the Gravatar fallback used by admin for the account image. [Docs](https://help.shopify.com/themes/liquid/objects/article#article-user-account_owner) will be updated soon!
