### ISSUE TITLE
Trouble with deploying

### ISSUE THREAD

**Issue by taulant** [Shopify/slate#286]
### Problem
Having trouble deploying the theme to the live Shopify site. Whenever I try to `slate start` I get this output:
```
[19:32:58] Using gulpfile ~/Projects/coffee-booster-shopify/node_modules/@shopify/slate-tools/lib/gulpfile.js
[19:32:58] Starting 'default'...
[19:32:58] Starting 'deploy'...
[19:32:58] Starting 'validate:id'...
[19:32:58] Invalid theme id for undefined: undefined `theme_id` must be an integer or "live".
```
- I am currently have put the `theme_id` in the `config.yml` file as an integer.
- I have also trite to put `"live"` in the theme_id but with the same result

### Replication steps
1. Successfully `slate migrate` an existing theme
2. Setup `config.yml` with` store:`, `theme_id:`, and `password:`
3. Rum `slate start` 

### More Information

- I am currently building on top of the Kingdom Theme
https://themes.shopify.com/themes/kingdom/styles/king

**Comment by t-kelly** [comment]
Make sure you write your theme ID as a integer? Without quotes? Like:
```
theme_id: 1234567
``

Does that work for you?

**Comment by taulant** [comment]
It worked! Thanks so much!

I was missing the `development:` as a top-level item.

FYI I had the `theme_id:` as an integer number at the beginning with no quotes.

**Comment by t-kelly** [comment]
Hmmm, [config-sample.yml](https://github.com/Shopify/slate/blob/master/packages/slate-theme/config-sample.yml) is included when you create a new theme with `slate theme`, and it should be include with `slate migrate` with [this code](https://github.com/Shopify/slate/blob/master/packages/slate-cli/src/commands/migrate.js#L101)... Are you sure there was no `config-sample.yml` created in your project?
