### ISSUE TITLE
Slate terminal should warn of update before any previous commands are carried out.

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#291]
### Problem

When creating a new theme, or deploying/watching a current theme, Slate will warn of a pending update to Slate tools only after it's completed the task I set. 

Would it not be better to have Slate warn the user before any command is carried out that an update is pending?

I just created a new theme, and after it had finished setting up the theme, it told me about the available update, so now I've deleted the theme it's just built in case the Slate update includes updates to the theme files.

![image](https://user-images.githubusercontent.com/18140157/30741408-8f4bb5f0-9f8c-11e7-93a9-fdb09dfa19ea.png)

**Comment by t-kelly** [comment]
What you're seeing is a warning that there is a new version of [`slate-cli`](https://github.com/Shopify/slate/tree/master/packages/slate-cli). All versions of `slate-cli` reference the latest version of [slate-theme](https://github.com/Shopify/slate/tree/master/packages/slate-theme) via the `https://sdks.shopifycdn.com/slate/latest/slate-src.zip` URL. In other works, you're always guaranteed to get the latest version of `slate-theme` regardless of what version of `slate-cli` you're running.
