### ISSUE TITLE
Put the store name at the front of the SEO title on index 

### ISSUE THREAD

**Issue by driespieters** [Shopify/slate#292]
### Problem
All tough different for each brand's SEO strategy, I would consider it good practice to put the store name at the front of the SEO title on the **homepage**.

### More Information

Suggested change:
`  {% capture seo_title %}
    {% if template == 'index' %}
      {{ shop.name }} &ndash; {{ page_title }}
    {% else %}
      {{ page_title }}
      {% if current_tags %}
        {%- assign meta_tags = current_tags | join: ', ' %} &ndash; {{ 'general.meta.tags' | t: tags: meta_tags -}}
      {% endif %}
      {% if current_page != 1 %}
        &ndash; {{ 'general.meta.page' | t: page: current_page }}
      {% endif %}
      {% unless page_title contains shop.name %}
        &ndash; {{ shop.name }}
      {% endunless %}
    {% endif %}
  {% endcapture %}
  <title>{{ seo_title }}</title>`

**Comment by NathanPJF** [comment]
For the homepage, `{{ page_title }}` will use the string merchants enter from online store preferences in the admin at `/admin/online_store/preferences`.

![](http://take.ms/1AVRO)

> All though different for each brand's SEO strategy

Yep - different folks/experts have different suggestions.  If someone wants to have their store name first on the homepage, then the admin is the place to control that.  The `unless` statement at the end will address duplication.

**Comment by NathanPJF** [comment]
Going to close as this is behaving as intended.
