### ISSUE TITLE
Not all processes are terminated when you stop using Ctrl^c the slate watch

### ISSUE THREAD

**Issue by idanb11** [Shopify/slate#296]
### Problem

I use slate ver 0.12.1 on windows.
After `slate watch` is running in my project folder, when I stop the slate watch using Ctrl^c - one process of slate is not terminated and keep on watching the project folder for changes.

This is the 3 processes that are present when you start `slate watch`:

- `"C:\Program Files\nodejs\node.exe" C:/Users/---/AppData/Roaming/npm/node_modules/@shopify/slate/lib/index.js watch`
- `node   "C:\Users\---\Work\picwheel-myshopify-com-pop\node_modules\.bin\\..\gulp\bin\gulp.js" "watch" "--gulpfile" "C:\Users\---\work\picwheel-myshopify-com-pop\node_modules\@shopify\slate-tools\lib\gulpfile.js" "--cwd" "C:\Users\---\work\picwheel-myshopify-com-pop" "--environment" "development"`
- `C:\Windows\system32\cmd.exe /d /s /c ""C:\Users\---\work\picwheel-myshopify-com-pop\node_modules\.bin\gulp" "watch" "--gulpfile" "C:\Users\---\work\picwheel-myshopify-com-pop\node_modules\@shopify\slate-tools\lib\gulpfile.js" "--cwd" "C:\Users\---\work\picwheel-myshopify-com-pop" "--environment" "development""`

After pressing Ctrl^c to stop slate watch the following process is not terminated:
`node   "C:\Users\---\Work\picwheel-myshopify-com-pop\node_modules\.bin\\..\gulp\bin\gulp.js" "watch" "--gulpfile" "C:\Users\---\work\picwheel-myshopify-com-pop\node_modules\@shopify\slate-tools\lib\gulpfile.js" "--cwd" "C:\Users\---\work\picwheel-myshopify-com-pop" "--environment" "development"`

Running `slate watch` again will result the following error:
```
\slate-tools\lib\tasks\build-config.js:64
    throw new Error(messages.configChange());
    ^

Error: Changes to ThemeKit Config Detected: You may need to quit <slate watch> and run a full <slate deploy> as a result.
    at FSWatcher.<anonymous> (C:\Users\Idanb11\work\picwheel-myshopify-com-pop\node_modules\@shopify\slate-tools\lib\tasks\build-config.js:64:11)
    at emitThree (events.js:116:13)
    at FSWatcher.emit (events.js:194:7)
    at FSWatcher.<anonymous> (C:\Users\Idanb11\work\picwheel-myshopify-com-pop\node_modules\chokidar\index.js:192:38)
    at FSWatcher._emit (C:\Users\Idanb11\work\picwheel-myshopify-com-pop\node_modules\chokidar\index.js:233:5)
    at FSWatcher.<anonymous> (C:\Users\Idanb11\work\picwheel-myshopify-com-pop\node_modules\chokidar\lib\nodefs-handler.js:263:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Replication steps
1. use windows machine and install git from git-scm.com
2. open the git bash
3. install node.js ver 6
4. install slate globally
5. cd to your shopify project folder (the project was already migrated to slate using `slate migrate`)
6. run `slate watch` and watch for the new processes created by slate
7. stop `slate watch` with Ctrl^c
8. check that all processes from step no. 6 are terminated
9. 1 process is not terminated...

**Comment by t-kelly** [comment]
Thanks for the well detailed bug report @idanb11. We'll look into this and get back to you. Keep us posted if you find anything else.

**Comment by t-kelly** [comment]
@idanb11 I'm having a hard time reproducing this. Going to close as it seems to be system/setup specific and maybe not a problem with Slate.
