### ISSUE TITLE
Unable to use 'slate watch' access URLs within c9. How do I change the watch server code?

### ISSUE THREAD

**Issue by mime0n** [Shopify/slate#297]
### Problem

I'm trying to access the access URLs that are shown after running `slate watch` . For me these URLs are 

```
Access URLs:
 -----------------------------------------------------------------
       Local: https://localhost:3000/?preview_theme_id=200440203
    External: https://172.17.0.21:3000/?preview_theme_id=200440203
 -----------------------------------------------------------------
          UI: http://localhost:3001
 UI External: http://172.17.0.21:3001
 -----------------------------------------------------------------
```

Because I am using the c9 (cloud9) IDE I need to change the server addresses (from this c9 thread https://community.c9.io/t/why-cant-i-load-my-app-with-http-in-the-embedded-preview/2555/6) 

> use `process.env.PORT` instead of `1337`, and `process.env.IP` instead of `127.0.0.1`

So where could I find the server code that is run behind the scenes when I run `slate watch` in order to edit the variables?

**Comment by t-kelly** [comment]
You'll need to fork this repo and edit the [options we pass to Browsersync](https://github.com/Shopify/slate/blob/master/packages/slate-tools/src/tasks/deploy-sync.js#L47). Look at the [Browsersync docs](https://www.browsersync.io/docs) to find out what you can pass.

**Comment by mime0n** [comment]
Right on. I see that there are quite a few options in the `browserSync.init()` method and above that as well but, honestly, I'm lost. I really wouldn't know where to pop in port number **8081** (which is what c9.io uses for livereloading). I came across UI https://browsersync.io/docs/options#option-ui. I suppose I'm looking for a section of the code like this where I can just swap out the port numbers. Any more ideas?
