### ISSUE TITLE
use full color svg icons

### ISSUE THREAD

**Issue by orangemooncreative** [Shopify/slate#298]
I don't see it anywhere in the documentation but how do you include full color svgs in the icons folder? 

If I add "icon--full-color" as a class to the svg itself, the class does not carry over. If I add "icon--full-color" after everything is compiled using chrome developer tools the svg icon is displayed correctly.

http://cloud.orangemooncreative.com/1m3d211e032x/Screen%20Recording%202017-09-26%20at%2011.08%20AM.gif

**Comment by orangemooncreative** [comment]
it was some rogue code on my end that caused the issue. i'm good.

**Comment by t-kelly** [comment]
Great to hear you got it fixed. Thanks @orangemooncreative.

**Comment by jorgebambu** [comment]
I know this is closed but... what was the solution? What was that "rogue code" you are referring to? This is unhelpful for people with the same problem. Please share your solution.
