### ISSUE TITLE
Why are all the requires commented out? How do I use the dependencies correctly?

### ISSUE THREAD

**Issue by adamrasheed** [Shopify/slate#301]
### Problem

Every fresh install of slate comes with a folder of scripts that have some lines like this commented out:
```
/*================ Slate ================*/
//  =require slate/a11y.js
//  =require slate/cart.js
//  =require slate/utils.js
//  =require slate/rte.js
//  =require slate/sections.js
//  =require slate/currency.js
//  =require slate/images.js
//  =require slate/variants.js
// =require main.js
/*================ Sections ================*/
//  =require sections/product.js

/*================ Templates ================*/
//  =require templates/customers-addresses.js
```
How do I use these? uncommenting them just gives out errors in the logs. Would love some info on this.

**Comment by NathanPJF** [comment]
That is the syntax required to use `gulp-include`.  They are already in their "usable" form 😃 

There's a note of this in the public help docs, https://shopify.github.io/slate/js-examples/

> In the theme.js file, you must import the Section specific JavaScript with the `// =require helper`, [more information here](https://www.npmjs.com/package/gulp-include), as it will contain your constructor.

Duplicate issue of https://github.com/Shopify/slate/issues/244
