### ISSUE TITLE
Error: Cannot find module '../lib/completion'

### ISSUE THREAD

**Issue by kevmon** [Shopify/slate#304]
Hi, when I try to run slate build or deploy, I get the following error:

module.js:471
    throw err;
    ^

Error: Cannot find module '../lib/completion'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/computeruser/Sync/Work/Sites/New Site/node_modules/.bin/gulp:13:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I don't know enough to explain how to replicate the issue, sorry.  But I've tried re-installing node and nam and have been searching for similar errors for days.

**Comment by t-kelly** [comment]
Hey @kevmon -- we'll need more info to start triaging this bug. Node version, NPM version, Operating System, Slate version.

Thanks.

**Comment by kevmon** [comment]
Thanks t-kelly, I was on a deadline so I re-installed everything and it works fine now.  If it happens again, I'll send the needed into!

**Comment by matteoboscolo** [comment]
I'm having the same issue, my situation is:
-I've been working on a project and I had to reformat my system
-If I run slate theme themename and then run the deploy, watch etc everything works just fine on the new project, but if I run deploy,watch etc on my old project I'm getting the same error as kevmon

node v8.9.1
npm v5.5.1
macos yosemite
slate v0.13.0

**Comment by kevmon** [comment]
Hi Guys, 

I hope this helps as it's made this issue much easier for me.  I've installed Node Version Manager (NVM) which makes it much easier to install/uninstall node/npm globally or per-project (via an nvm file in your project directory).  I forget which versions they were, but things seem to break because of npm being incompatible with Slate.  

Since then, I haven't had to do a reformat, just change nom's version until it works.  I'm using npm v5.4.2 which installs with node v8.6.0 and I haven't had any problems.

Cheers,
Kevin
