### ISSUE TITLE
The latest release is not synced with npm

### ISSUE THREAD

**Issue by hisyam** [Shopify/slate#306]
I looked at the [slate npm package](https://www.npmjs.com/package/@shopify/slate) and it's still at version 0.12.1 while the latest release is at 0.12.4. Creating a new theme using `slate theme <my-theme-name>` installs the 0.12.1 version. Is there a way to install the latest version?

**Comment by t-kelly** [comment]
👋 Hey @hisyam -- You are correct that the current version of the Slate repo is `0.12.4`. However, the Slate NPM packages are only bumped when there is a change to them. There wouldn't be much point in releasing a `0.12.4` that is identical to `0.12.1`.

In this case, all of the changes done in `0.12.2`, `0.12.3`, and `0.12.4` were done to [`packages/slate-theme`](https://github.com/Shopify/slate/tree/master/packages/slate-theme). The next time there is a change to [`packages/slate-cli`](https://github.com/Shopify/slate/tree/master/packages/slate-cli) or [`packages/slate-tools`](https://github.com/Shopify/slate/tree/master/packages/slate-tools) then they will be bumped to the latest version, e.g `0.12.5`.
