### ISSUE TITLE
Dev/Prod settings_data.json discrepancies

### ISSUE THREAD

**Issue by targetcreature** [Shopify/slate#308]
### Problem

Hi, sorry if this is the wrong forum for this.

I'm scratching my head over the `settings_data.json` files in my development and production themes. Currently, I have a dev version of my live theme to test before deploying. However, settings changes (like new collections) are only made to the live theme. So when I `slate watch` I only see the settings from the dev theme's `settings_data.json` which is never updated.

The only solution I can think of is to duplicate all of the settings changes in my live theme to my dev theme. That would take too much time to do manually, though.

Is there a way to `watch` my dev theme, but with the `settings_data.json` of my live one?

Or maybe I'm missing something simple in all of this.

Any help appreciated :)

### Replication steps

1. Create new collection in production theme (through admin panel)
2. `slate watch` to view your development theme. The collection is not there.

**Comment by t-kelly** [comment]
Hey @targetcreature -- please see https://github.com/Shopify/slate/issues/174
