### ISSUE TITLE
Using layout none breaks BrowserSync

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#311]
### Problem

So I was working on a new template for an email landing page and used `{% layout none %}`, and it seems this breaks BrowserSync's live reloading.
Looking in the template's source code, it leaves out the BrowserSync script at the base of the template:
```

<script id="__bs_script__">//<![CDATA[
--
  | document.write("<script async src='/browser-sync/browser-sync-client.js?v=2.18.2'><\/script>".replace("HOST", location.hostname));
  | //]]></script>
```

Which seems completely logical but makes things a little tricky.

### Replication steps

Create a new template and lead it with `{% layout none %}`
Add in some code and run `slate start`

**Comment by t-kelly** [comment]
@ConduciveMammal you are the ultimate stress tester of this tool. Always something new that we haven't tried. Thanks! 😃 

Will look into this. Let us know of anything you find out, too.

**Comment by ConduciveMammal** [comment]
Aha I do seem to have a knack for it 😄. Maybe when Shopify branches further into the UK, I can myself a job with you guys ha!

**Comment by t-kelly** [comment]
Had a chance to finally look into this. Browsersync would break if you don't have a `</body>` tag. I feel like it's a reasonable expectation to have a `<body></body>` tag, I'm going to leave it how it is.
