### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by timdonaldson** [Shopify/slate#317]
### Problem

Creating a new theme using the command (slate theme test) results in the following error:

/usr/local/Cellar/nvm/0.29.0/v0.10.40/lib/node_modules/@shopify/slate/node_modules/figures/index.js:2
const escapeStringRegexp = require('escape-string-regexp');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/Cellar/nvm/0.29.0/v0.10.40/lib/node_modules/@shopify/slate/lib/index.js:10:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

### Replication steps

NPM install data...

install : node-v4.4.2
mkdir : /usr/local/n/versions/node/4.4.2
fetch : https://nodejs.org/dist/v4.4.2/node-v4.4.2-darwin-x64.tar.gz
installed : v0.10.40

node -v results in: v0.10.40

**Comment by t-kelly** [comment]
You're using an unsupported version of Node (that doesn't have `const` variable declarations). Please upgrade to a version of 6 or greater.

**Comment by timdonaldson** [comment]
Ah yes of course, I've just updated to v6.11.0 (following these instructions: https://www.abeautifulsite.net/how-to-upgrade-or-downgrade-nodejs-using-npm)

sudo npm cache clean -f
sudo npm install -g n
sudo n 6.11.0

which resulted in:
     install : node-v6.11.0
       mkdir : /usr/local/n/versions/node/6.11.0
       fetch : https://nodejs.org/dist/v6.11.0/node-v6.11.0-darwin-x64.tar.gz
######################################################################## 100.0%
   installed : v0.10.40

But I still get the same error:
/usr/local/Cellar/nvm/0.29.0/v0.10.40/lib/node_modules/@shopify/slate/node_modules/figures/index.js:2
const escapeStringRegexp = require('escape-string-regexp');
^^^^^
SyntaxError: Use of const in strict mode.

**Comment by t-kelly** [comment]
> /usr/local/Cellar/nvm/0.29.0/v0.10.40/

I think you're still running v0.10.40?
