### ISSUE TITLE
Currency converter reverts to default using Slate

### ISSUE THREAD

**Issue by emmadolan** [Shopify/slate#322]
### Problem

Following the below tutorial to add a currency converter and it does not work with Slate or sectioned themes. Shopify say they will update the documentation but a fix is needed.

https://help.shopify.com/themes/customization/currencies/show-multiple-currencies

When the code is added, the converter converts the prices into the selected currency but thereafter if a page is loaded or refreshed, the price reverts back to the shop currency.

**Comment by NathanPJF** [comment]
Sorry to hear you're having trouble, @emmadolan 

I'm going to label this one as `question` and we'll see if there's something going on in Slate that is stripping the HTML wrappers declared in the currency formatting.

---

Note to contributors:

Verify that any HTML elements added by merchants are kept.

<details><summary>Screenshot from docs.</summary>

![](http://take.ms/sdxp6)

</details>
&nbsp;

**Comment by t-kelly** [comment]
@emmadolan I'm fairly confident this is not a bug with Slate. 

The tutorial you provided is one solution of many for dealing with currencies, something we can never fully predict when developing Slate. Being a public repo with a growing number of users, we also need to make sure we stay focused on addressing issues about Slate and not theme development in general.

I would recommend getting in touch with a [Shopify Expert](https://experts.shopify.com) if you're having trouble debugging your solution.

**Comment by sebbean** [comment]
@t-kelly the show-multiple-currencies workflow is completely broken with the new version of slate

I think updating it or removing it is best to avoid confusion.

Been banging my head against the wall for most the day trying to get that tutorial up and running.

this seems related
https://github.com/Shopify/slate/issues/409

it's come down to the code snipped having $ vs jQuery conflicts.

I've had this before with webpack but none of the normal tricks (trying to set `window.jQuery = $`) seem to work. Still getting jQuery undefined errors.
