### ISSUE TITLE
"Forgot Password?" form not showing up when link is clicked

### ISSUE THREAD

**Issue by tigerstripemedia** [Shopify/slate#324]
### Problem

Hi All, I'm having an issue on the slate login page. The link "Forgot Password?" is meant to toggle a class in the two form elements on the page however when clicked it does nothing other than change add the hash #recover to the URL. When the hash is added it is meant to hide the login form and display the recover password form. I haven't changed anything in the customers-login.js file all I have done is added some CSS to the login page. I can't work out why it isn't running the javascript.

I have un-hidden the recover password form and tested it and it works fine just seems to be a problem with getting the form to display when you click the link.

the URL is: www.themirfieldemporium.myshopify.com

password is: ceutto

Thanks for any help

### Replication steps

*How to replicate the problem. Screenshots or video?*

![screen shot 2017-10-17 at 13 26 39](https://user-images.githubusercontent.com/29272782/31664831-dbdc009e-b33e-11e7-81c4-507ff32a96ee.png)

![screen shot 2017-10-17 at 13 27 12](https://user-images.githubusercontent.com/29272782/31664853-eb3ad272-b33e-11e7-87fb-a4bebf7f3785.png)

**Comment by NathanPJF** [comment]
@tigerstripemedia I'm not able to reproduce on my dev site.  I logged into your store and tried the "Forgot password" link and the toggling appears to be working fine.  The `#recover` hash isn't added until I actually submit the recovery form - which is intended.

Are you still experiencing issues? If so, would you be able to give a recording with replication steps of the issue?

**Comment by tigerstripemedia** [comment]
Hi Nathan, sorry I have only just seen this. I managed to fix it actually. Seemed to be an issue with another js file. I moved it into it's own folder and it worked! Thanks for looking into it! Cheers, Hayden
