### ISSUE TITLE
How can I watch without deploying?

### ISSUE THREAD

**Issue by edhenderson** [Shopify/slate#325]
### Problem

I want to watch files locally, deploy them locally and see changes using BrowserSync. Basically `slate watch` but without the deploy.

I want to deploy when I am ready.

### Replication steps

Run `slate watch`, it deploys, how do I make it not deploy.

### More Information

Nope.

**Comment by NathanPJF** [comment]
This isn't possible with the tool.  There's no "true local" development with Slate, but a link to a specified environment in your `config.yml` file.

> I want to deploy when I am ready.

It's recommended to specify a separate environment in your `config.yml` for development, staging, production, etc.  An example can be seen in [sample-config.yml](https://github.com/Shopify/slate/blob/master/packages/slate-theme/config-sample.yml)
