### ISSUE TITLE
Updating slate from 0.9.1.

### ISSUE THREAD

**Issue by mightymess** [Shopify/slate#326]
### Worry

I started using slate when it came out (super cool tool btw). I've put off updating slate but my project has reach a milestone now and I think I need to do it before I get way behind. 

I saw the milestones for the releases but I'm unsure of what will actually get updated. Will only the slate files and tool be updated or will my theme will also get some updates? The later is the one that worries me.

### More Information

I've tripled checked the slate doc, googled it, etc... I'm not a npm guy (check the slate doc there too) but can't find an answer. I'm probably missing something...

**Comment by mightymess** [comment]
### Update

I found closed issues 😅 that mention the same worry (sorry). I'm still not 100% sure as I can't find it in written in the doc. 

### Questions

1. I can safely update the CLI using `npm install -g @shopify/slate` and that won't do anything to my theme. but what about slate-tools? My package.json mention version 0.2.7 `"@shopify/slate-tools": "0.2.7"` can this also be updated with this command or that's also a manual thing? If manual, does that mean it could break a theme? 

2. Updating a theme started with an older version of slate cannot be updated to the latest release automatically, which makes total sense. _This has to be manual_. Would be great to know which files can be updated _safely_ if left untouched in the first place, like the following folders:
- node_module > *
- node_module > shopify > *
- node_module > shopify > slate-tools
- src > scripts > slate

3. Is updating manually just a matter of trial and error?

**Comment by t-kelly** [comment]
Hey @mightymess -- best thing to do is to run `npm install @shopify/slate-tools@latest --save-dev` in your terminal from the project folder. That will update you to the latest version. We have not released any breaking changes so you can still upgrade without worry.

`npm install -g @shopify/slate@latest` will get you the latest version of the command line tool. It will not affect your theme in any way.
