### ISSUE TITLE
data-product-single-thumbnail doesn't do anything

### ISSUE THREAD

**Issue by driespieters** [Shopify/slate#327]
**data-product-featured-image** changes the featured image when a variant is selected. However **data-product-single-thumbnail** doesn't seem to do anything. 

Possible uses when the data-product-single-thumbnail get's clicked could be:
- Change the featured image
- Change the selected variant

Or am I missing something?

**Comment by montalvomiguelo** [comment]
Just placeholder selectors, you can use your own

**Comment by NathanPJF** [comment]
The `product.js` file is meant to show how one might use the `slate` methods in production; so as @montalvomiguelo points out, devs are encouraged to write JS that works for their project.

With that said, it looks like there was an original intention to use `data-product-single-thumbnail` as I see there's an unused `selectors.productThumbs` variable in `product.js`.  So it would be good to expand the example to use product thumbnails as you described @driespieters 

Going to label as a learning issue we can address.

**Comment by montalvomiguelo** [comment]
I have created this Shopify Theme with Slate http://bit.ly/2gEddRx
Source Files https://github.com/montalvomiguelo/theme-with-slate

@driespieters Here is an example how you could use `[data-product-single-thumbnail]`

https://github.com/montalvomiguelo/theme-with-slate/blob/master/src/scripts/sections/product.js

**Comment by t-kelly** [comment]
Moved to https://github.com/Shopify/starter-theme/issues/6
