### ISSUE TITLE
Clarify the difference between Slate and Theme Kit

### ISSUE THREAD

**Issue by ADTC** [Shopify/slate#328]
What's the difference between Slate and Theme Kit? A bit of info in the Readme will be helpful.

**Comment by montalvomiguelo** [comment]
[Theme Kit](https://shopify.github.io/themekit/) is a command line interface that allows you to manage and edit theme files directly on your computer... then your files can be manually or automatically uploaded, downloaded, and synced with your Shopify Store.

Slate uses [Theme Kit](https://shopify.github.io/themekit/) (and other tools) behind the scenes  to give you a professional workflow to create Shopify Themes.

**Comment by NathanPJF** [comment]
Theme Kit manages sending files up and down to Shopify's servers, as @montalvomiguelo describes.  It's a one-to-one match; however, meaning that your local file structure must match the Shopify hosted directory exactly for it to work.

Slate uses Theme Kit for deployment, but has a number of other functions hidden behind  `gulp` tasks that lets users use a `src` directory that splits out files and folders more.

I'll label this issue as documentation; I agree it's worth clarifying in our public docs.

**Comment by ADTC** [comment]
Thanks for the replies and action. I'll quote @tanema's reply from Shopify/themekit#480 as well:

> Slate is a bunch of tooling built on top of Themekit. Themekit is more just a client with the themes API, letting you use whichever tools you need on top. Slate has an opinionated set of tools that Shopify uses to develop its own themes. I will update the Docs accordingly.

**Comment by t-kelly** [comment]
Added in the wiki! https://github.com/Shopify/slate/wiki/About
