### ISSUE TITLE
slate theme test is resulting in a ECONNREFUSED

### ISSUE THREAD

**Issue by ashrayvenkat** [Shopify/slate#329]
### Problem

`# slate theme test

  This may take some time...

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 151.101.10.110:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)`

### Replication steps

# slate theme test

### More Information

my network is behind a proxy, but node is configured to that. but i feel this could be the issue, i can be wrong.

**Comment by t-kelly** [comment]
Hi @ashrayvenkat -- we'll need more information in order to verify that this is actually a bug with Slate and to replicate it. Please try this on a non proxied and connection and let us know if you still have problems.

**Comment by ashrayvenkat** [comment]
it works fine without the proxy.

**Comment by ashrayvenkat** [comment]
make you firewall allow this ip 151.101.10.110:443.(slate internally uses it i'm guessing)
