### ISSUE TITLE
Missing currency formats from currency.js

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/slate#330]
### Problem

Slate's `currency.js` is missing a couple currency format options.

https://github.com/Shopify/slate/blob/master/packages/slate-theme/src/scripts/slate/currency.js

Missing formats:
* `amount_with_comma_separator`
* `amount_with_apostrophe_separator`

### More Information

* Doc on currency formats: https://help.shopify.com/manual/payments/currency-formatting

**Comment by montalvomiguelo** [comment]
There is an issue with format `amount_no_decimals_with_comma_separator` as well:

```js
slate.Currency.formatMoney('113465', '${{amount_no_decimals_with_comma_separator}}'); // "$1,135"
```

It should be using a dot `$1.135`

![2017-10-26 01 55 26](https://user-images.githubusercontent.com/5134470/32038734-e968462e-b9f0-11e7-9d5b-5de5eab7a86f.gif)

**Comment by t-kelly** [comment]
@NathanPJF can you reopen this in https://github.com/Shopify/theme-scripts?
