### ISSUE TITLE
Slate Start also overwrites Checkout settings

### ISSUE THREAD

**Issue by whoiskjl** [Shopify/slate#331]
### Problem

Slate Start - also overwrites Checkout settings

### Replication steps

Settings > Checkout > Style > Customize Checkout > Set Banner with some image

$ slate start 

if you go back to Customize Checkout, all the previous settings are empty
 
### More Information

There is no info in settings_schema.json I can preset before I run Slate Start

**Comment by t-kelly** [comment]
All editor settings values are tracked using the `settings_data.json` file. If you upload the version of `settings_data.json` included with Slate, it will essentially erase any previous settings you selected.

I tried to clarify this with https://github.com/Shopify/slate/pull/201
