### ISSUE TITLE
Error: ENOENT: no such file or directory ... @shopify/slate-tools/lib/commands

### ISSUE THREAD

**Issue by iamkeir** [Shopify/slate#333]
### Problem

Unable to get existing Slate theme up and running.

### Replication steps

1. Download existing Slate theme from Git repo
2. Navigate to theme directory (e.g. `cd project-name/theme-name/`)
3. Run `npm install -g @shopify/slate`
4. Run `slate start` (or any `slate` command, inc. `slate -v`)
5. Receive error:

```
fs.js:906
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^
Error: ENOENT: no such file or directory, scandir '/Users/******/Sites/project-folder/theme-name/node_modules/@shopify/slate-tools/lib/commands'
    at fs.readdirSync (fs.js:906:18)
    at Object.<anonymous> (/Users/******/.nvm/versions/node/v8.8.1/lib/node_modules/@shopify/slate/lib/index.js:93:23)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

### More Information

Any `slate ...` command causes the above error.

However, if I navigate to home folder `~/`, I can run the following:
- `node -v` = v8.8.1
- `npm -v` = 5.4.2
- `slate -v` = 0.13.0

**Comment by iamkeir** [comment]
If I instead run `npm install` in theme folder, then `slate` commands work - but that is not a step required in the documentation?

**Comment by t-kelly** [comment]
So everything is working? Looks like you were missing some dependencies which were installed with `npm install`.

If you are downloading a repo from Git, you always need to run `npm install` to install dependencies specified in the `package.json` file. This is common practice across every project/repo that uses Git and NPM -- I don't believe it needs to be reiterated in Slate docs.

**Comment by iamkeir** [comment]
That is true and fair enough - I realise the confusion here is that I would usually _always_ run `npm install` for standard Git/NPM projects but as `slate theme` at initial project setup seems to include this step internally, my subsequent (incorrect) assumption is that Slate would continue to handle this within its own commands.

As it turns out, `slate theme` creates those new dependencies in `package.json` that will subsequently require `npm install` when working in an existing theme.

I will add it to my local project README and hopefully this GH issue can serve as useful if anyone else gets caught out by this gotcha, in the absence of a nod in the docs.

FWIW I would almost prefer if `slate theme` _didn't_ handle `npm install` and that was an explicitly  required pre-step. Just IMO, but pretty minor - thanks for reply.

**Comment by t-kelly** [comment]
Good points @iamkeir! We are in the process of planning out the next version of Slate and its docs, I'll make a followup issue to this to make sure we consider it when building them.

**Comment by juanpasolano** [comment]
Actually `npm i` is not working for me.
Not even removing node_modules and installing again. 

node v6.10.0
npm 5.5.1

**Comment by mattkersner** [comment]
Running npm install in the theme folder did not solve this issue for me either. Please help. 
[#528](https://github.com/Shopify/slate/issues/528)

**Comment by michael-lynch** [comment]
I'm having the same problem.

Node
`v8.8.1`

Slate
`v0.13.0`

- `npm install -g @shopify/slate`
- `slate theme my-new-theme`
- `cd my-new-theme`
- `npm install`

None of the `slate` commands work in the `my-new-theme` directory even after running `npm install`. I get the `Error: ENOENT: no such file or directory` pointing to `node_modules/@shopify/slate-tools/lib/commands`.

**Comment by mattkersner** [comment]
@michael-lynch take a look at the package.json file in your my-new-theme folder. Change the @shopify/slate-tools: 1.0.0-beta1 to @shopify/slate-tools: 0.13.0. Then run npm install. All the commands should work moving forward.

**Comment by michael-lynch** [comment]
@mattkersner Yep, that did it. Thanks for the tip.
