### ISSUE TITLE
Can't seem to replace SVG social icons 

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#335]
### Problem

So I tried to replace the SVG code for the  Facebook social icon in the Icons directory with [this one](https://www.flaticon.com/free-icon/facebook_23730#term=facebook&page=1&position=44) and it just disappeared entirely. Looking at the source, I noticed what was loading, wasn't the SVG code I'd put in. I thought it had stuck in a caching issue or something, so I reverted to the original and changed the widths and heights, the change showed, I then removed the "icon" class and this change didn't show.

Do these icons go through some kind of JS cleaning or something?

**Comment by dirad** [comment]
They go through the build task and are saved as a liquid file in the snippets folder so make sure to name your file icon-facebook.svg or icon-facebook-somename.svg 

Also you should change the SVG viewbox property to fit your sizes, while width and height properties should be removed.

**Comment by NathanPJF** [comment]
Thanks for replying on this @dirad :)

Closing now
