### ISSUE TITLE
Suggestion: Global styles

### ISSUE THREAD

**Issue by driespieters** [Shopify/slate#337]
Everyone has a different workflow, but I do think the global styles could provide a little more resets and some minor restructuring.

A great example: [Bitters](https://github.com/thoughtbot/bitters/tree/master/core )

**Proposed changes:**
- Add a typography.scss
- Remove slate-reset.scss and add that code to the related stylesheets.
- Add variables for animation, line-heights, focus states...

**Comment by t-kelly** [comment]
Moved to https://github.com/Shopify/starter-theme/issues/5
