### ISSUE TITLE
Integrate Slate into a DeployBot workflow

### ISSUE THREAD

**Issue by AlchemyUnited** [Shopify/slate#339]
I (was hoping to) have the /dist (folder) setup as a Git submodule. The idea was to work on the /src, then build (to /dist). Everything but the /dist (submodule) would be it's own safe keeping repo (on GitHub). The /dist submodule was going to go to DeployBot (and from there to Shopify). 

Unfortunately, a slate build (or deploy -m) wipes out the the contents of /dist folder. That is, any of the git files within /dist are lost. That is, ya can't make it a submodule. 

Mind you, I could skip the "wrapper" repo (going to GitHub) but that just feels sloppy. It - pre-build - is it's own beast and should be treated as such. 

I can, for now, stomach the lack of a true local dev environment. And Slate makes a lot of sense. But it seems (to me) there wasn't too much thought given to a traditional (?) dev workflow (i.e., src, dev, etc.) 

Help. Please.

**Comment by AlchemyUnited** [comment]
After some mucking around I ended up modifying build-utils.js. Obviously, not a great idea but there seems to be little choice. 

gulp.task('clean', function () {
  return del(['upload', 'dist/assets', 'dist/config', 'dist/layout', 'dist/locales', 'dist/sections', 'dist/snippets', 'dist/templates' ]);
});

I hope someone else can point me in a better direction. However, currently, no other Slate + Theme Kit + Git + DeployBot workflow makes sense.  What am I missing?

**Comment by NathanPJF** [comment]
> But it seems (to me) there wasn't too much thought given to a traditional (?) dev workflow (i.e., src, dev, etc.)

That's a bit harsh to say about the developers of this project and my colleagues, @AlchemyUnited.  This project has a [code of conduct](https://github.com/Shopify/slate/blob/master/CODE_OF_CONDUCT.md), so going forward please have your feedback focused on the desired outcomes and not the people maintaining the project.

---

> However, currently, no other Slate + Theme Kit + Git + DeployBot workflow makes sense. 

From what you've described, you're working with two different deployment systems: DeployBot and Theme Kit.  Slate is built with only Theme Kit in mind and working with multiple environments (such as development vs production) is managed through the `config.yml`.  In working with Git, when we have a totally separate build for development, we do that in a separate branch or even repo with it's own environments not pointed at the production site.

Having a distribution version of the theme maintained as it's own repo isn't part of what we'd consider a traditional development of a theme.  However, I'll leave this issue open since it sounds like it would be an improvement to help you integrate with deployment processes that aren't Theme Kit.

**Comment by AlchemyUnited** [comment]
@NathanPJF - You say "harsh" I say honest :)  

Sometimes (read: often) it's the freshest pair of eyes that see things the clearest.  Please keep in mind, just prior to opening this issue I spent the better part of a 8 to 12 hours (over 2 or 3 days) trying to get this sorted out. To me it was pretty obvious. I was wrong? Perhaps my expectations of Shopify are too high? Well, then I'll apologize. No problem. 

Let's say I use Slate to be a theme dev. That is, to build theme for sale (and not just modify as I'm doing now). Those would "compile" into the dist folder and what's in that folder is what I would sell, correct?  

As it is, that just doesn't make sense. I would expect to be able to "deploy" my product from the dist folder. As it is, that's not possible, is it? 

> @NathanPJF  said "Slate is built with only Theme Kit"

Yes. But that's pretty much exactly my point :) 

It makes max sense to build with Slate (as that's what it's for), VC with git (as is a dev best practice), and at allow for the ability to deploy with Beanstalk or similar (which might not be a best practice per se but it's a pretty standard practice). 

Note: What we like best about Beanstalk (and similar) is it leave a digital paper trail. I can also webhook messages into Slack such that everyone in Slack (read: the client and his/her non-tech team) can see the dev activity. This is another reason why ThemeKit isn't a good fit (for us).  

> @NathanPJF  said "Having a distribution version of the theme maintained as it's own repo isn't part of what we'd consider a traditional development of a theme. "

(Sincerely) sorry, I don't see how Slate allows me to ship my product (i.e., theme) when the dist folder can't be it's own repo.  I mean, the "raw" Slate (i.e., pre build) copy *should* be a repo, yes? And that  isn't what ships as the theme product, yes? So then what?  What do you do then? Copy & paste the dist folder out? And then somehow ship that? Oh :(

I don't want to sound like a jerk but that just doesn't make any sense to me. Even if I'm not using Theme Kit (which I'm kinda not now), Slate's mindset is conflicted (?). I should use to to build themes, but not VC them? And not ship them? 

---

I did find a short term solution, see above. But sooner or later than fix is going to blow up on me as I mucked with the Slate "core". Unless you can think of a good reason - and please share that so I can learn - for not adopting that change, then a standard practice of being able to make dist a git submodule makes max sense. I hope you agree. 

Thanks again.

**Comment by AlchemyUnited** [comment]
@t-kelly " Integrate Slate into a DeployBot workflow "

That's not really what I'm suggesting. Ultimately, the dist folder should not be over-written in whole, period. Just stick to the specific child folders. 

Point being, the fix isn't DeployBot or Beanstalk specific per se. It's mostly about being able to treat the raw Slate folder as it's own repo (as it should be), and then dist as it's own repo (as it should be). 

It's great that Slate handles processor stuff. But then dist being the finished product should be able to be treated as such. 

I hope I'm making sense.

**Comment by t-kelly** [comment]
@AlchemyUnited it sounds like you have a particular workflow that works well for you and your team. I appreciate the detail in which you have been able to describe it in the thread above -- it provides us with valuable insight into the variety of workflows we can consider to make Slate as configurable as possible.

Please be aware that the workflow you want Slate to be compatible with is not what we intended Slate to be used with. However, we are currently [exploring what we see as the ideal, community-approved workflow for Slate V1](https://github.com/Shopify/slate/issues/251) and working on creating detailed documentation describing this workflow. 

For the time-being, my advice for you is to create your build-tool that works well for you and your team. Slate and its dependencies are fully open-sourced so there is nothing stopping you from taking what you like and leaving what you don't.

Thank you for your feedback!

**Comment by pensandpencils** [comment]
@AlchemyUnited - I was, strangely enough, looking for a similar solution of using Slate with Deploybot for updating themes recently. Mainly as I was tired of the sometimes inconsistent outcomes from 'slate deploy' or that I couldn't simultaneously watch both my production and development themes etc etc and that for some sites I was having to replicate and publish the live theme from the development one in Shopify admin (I know there are better ways of doing this, but slate deploy stung me once too often - and yes, settings_data.json was set to ignore...deploy didn't seem to notice).

I've started running my themes in what initially seems a convoluted way but is, in practice, currently working nicely. 

I run my development theme in Slate, as usual, testing in the usual manner and running through Github for VC. But, for my live theme once ready to deploy I run a simple gulp task to duplicate my 'dist' folder wholesale to a directory outside of my slate environment. 

`var gulp = require('gulp');
gulp.task('copy', function () {
    return gulp.src(['dist/**/*'], {
        base: 'dist'
    }).pipe(gulp.dest('../DEPLOY_DIRECTORY_HERE'));
});`

This is run through Github as its own repo and I have that synced up to Deploybot and then to the live Shopify theme. Although this seems convoluted, in practice once set up all I have to do to deploy from development to live is:

`gulp copy`

Then push the deployment repo to Github and Deploybot takes care of the rest, only uploading files that have changed, and no .git files are touched.

Not ideal, but so far it's making my life a lot easier.

**Comment by AlchemyUnited** [comment]
@t-kelly  - Sorry, but I have to push back a bit. The workflow is not "particular", nor is it unique. It's actually standard / best practice.  I would love to claim otherwise, but we didn't invent sub-modules :) Nor did we invent Beanstalk / DeployBot. They are all just tools in a typical dev tool box, yes?

The change I've made and am suggesting would not change your current workflow. But it would allow for "my" workflow as well.  And per @pensandpencils , I'm not alone. 

p.s. In case you didn't already know, Beanstalk actually has deploy to Shopify baked in. Unfortunately, Slate in it's current form can't be used with Beanstalk. I updated my local copy of Slate but don't think that's ideal. In fact, I know it isn't. 

Please give this some further consideration.

**Comment by lemonadecreative** [comment]
++ @AlchemyUnited.

I have to agree here. This is a flow I would love to see as this is standard practice for my team as well.
