### ISSUE TITLE
Unable to use slate node 8.8.1

### ISSUE THREAD

**Issue by juanpasolano** [Shopify/slate#342]
### Problem

Slate command line not working on node 8.9.1 npm 5.4.2

### Replication steps

1. Install slate globally `npm install -g @shopify/slate`
2. run `slate`

### More Information

Returns
```
$ slate
/Users/juanpablosolano/.nvm/versions/node/v8.8.1/bin/slate: line 1: use strict: command not found
/Users/juanpablosolano/.nvm/versions/node/v8.8.1/bin/slate: line 3: syntax error near unexpected token `('
/Users/juanpablosolano/.nvm/versions/node/v8.8.1/bin/slate: line 3: `var _fs = require('fs');'
```

**Comment by juanpasolano** [comment]
Runing `npm install -g @shopify/slate` a second time has fixed the issue

**Comment by t-kelly** [comment]
When did you do this yesterday? You may have coincidently `npm install`'d when I mistakingly had `@shopify/slate` pointing to the wrong version of the repo 😅
