### ISSUE TITLE
[development]: 0 / 0 [|] 0 % when file is ignored and not uploaded

### ISSUE THREAD

**Issue by iamkeir** [Shopify/slate#344]
### Problem

When specifying files to ignore in `config.yml` using `ignore_files`, files are either _not_ ignored or cause Slate to 'hang'.

### Replication steps

Add to `config.yml` and run `slate watch` or `slate start`:
```
ignore_files:
  - src/locales/en.default.json
```
_en.default.json is still uploaded (therefore not being ignored)_

Alternatively, using any of the following causes Slate to hang on `[development]: 0 / 0 [|]   0 %`
```
ignore_files:
  - locales/en.default.json
  - dist/locales/en.default.json
  - en.default.json
```
### More Information

Ignoring files is absolutely essential to a non-destructive workflow.

**Comment by t-kelly** [comment]
`ignore_files:` is relative to the `src/` folder, so you'd want a `locales/en.default.json`. 

Any other details? I've never experienced the tool hanging when ignoring files.

**Comment by iamkeir** [comment]
@t-kelly thanks for the reply - here it is in action: http://jmp.sh/V5XPjZU

This is a development shop that is also the live published theme, and config has:
```
ignore_files:
    # Prevent overwrite of theme settings & locale data online (comment out to allow overwrite)
    - config/settings_data.json
    - locales/*
```

**Comment by jonathanmoore** [comment]
I can confirm that I've seen the same issue. The `[development]: 0 / 0 [|] 0 %` log will appear if I edit and save an ignored file.  However, I've never had it hang up everything else.  If I edit and save another non-ignored file it uploads and syncs as it should.

**Comment by iamkeir** [comment]
@t-kelly Finally got round to looking at this again, sorry for delay.

I can confirm that the ignored file is _not_ being updated. 

Unfortunately, unlike @jonathanmoore, Slate hangs permanently after that, even when updating non-ignored files: http://jmp.sh/9Luj69G

To be fair, I use ignores as a safety - I don't tend to edit files I know I am ignoring. If I accidentally do, I usually just restart Slate. Would be nice for it to deal with it more elegantly though :)

**Comment by thisislawatts** [comment]
Just following up on this issue to confirm that I am also seeing the hanging behaviour.

__Steps taken__

1. Update `config.yml` to ignore `config/settings_data.json`
2. Start up `slate watch`
3. Edit a file which isn't ignored to test watcher/upload. eg. `product.liquid`
4. Make a change to an ignored file
5. Make a change to another unignored file. This file will never be uploaded, as the process is hanging.

![shopifymoreinfo](https://user-images.githubusercontent.com/472589/34601281-287054bc-f1f3-11e7-9ace-bcc8aa1d3407.gif)

Restarting fixes the issue, but agree with @iamkeir here that this could be handled more elegantly. Each restart generates a new tab and aren't there already too many of those in our life? 😉

**Comment by t-kelly** [comment]
Closing this as it is not a critical bug and our priority is now Slate v1.
