### ISSUE TITLE
Slick Slider - product.js

### ISSUE THREAD

**Issue by driespieters** [Shopify/slate#345]
Hi, 

I'm using a Slick Slider for a product images carousel. I'm trying to figure out how to slide to the current variant, when it's selected.

Here's what I got so far:

```
updateProductImage: function(evt) {

  var slideIndex = XXXXXXXXXXX.data("index");

  $('.product-images__slider').slick('slickGoTo', slideIndex);

},
```
Basically, I just can't figure out what to place at the XXXXXXXXXXX. 

Could someone show me in the right direction? Would be very much appreciated! Thanks!

_Feel free to close this issue, as it's more a support request._

**Comment by t-kelly** [comment]
The Slate repo is intended to facilitate communication between Shopify and the developer community on issues related to Slate, not general theme development. Please refrain from creating issues that are not associated with Slate.

There are plenty of other places available to developers to ask these kinds of questions, such as [Shopify Experts](https://experts.shopify.com/), the [Shopify Ecommerce Forum](https://ecommerce.shopify.com/forums), or even [the library you're having problems with](https://github.com/kenwheeler/slick).
