### ISSUE TITLE
Slate migrate back

### ISSUE THREAD

**Issue by swnikita** [Shopify/slate#346]
Hello,

This is my first step on Shopify, and I have questions regarding version control system.
But the first question is - is it possible to run (any) command to convert slate format theme into default one? To be able to commit changes using GIT.

And the second question - I tried to find something about how Shopify themes work with GIT, but saw only other external services (where you should pay money for 1+ repo). Not a solution at all. Question - is it possible to work with slate and commit changes to GIT?

Possibly, two questions are very similar, but I hope you understand my issue.

Please, help me with these questions!
Thanks,
Nikita

**Comment by NathanPJF** [comment]
@swnikita I have some questions about your post

> is it possible to run (any) command to convert slate format theme into default one?

What would a default theme be?

> To be able to commit changes using GIT.

When are you expecting to commit changes to a git repository? You might find this thread relevant: https://github.com/Shopify/slate/issues/225

> Question - is it possible to work with slate and commit changes to GIT?

From the thread I linked above, you'll see that this is not something we plan on adding to Slate.  However, after reading this thread and you still feel it's important to have Slate commit for you as opposed to developers running their own commands, please let me know.
