### ISSUE TITLE
Is tailwind compatible with slate?

### ISSUE THREAD

**Issue by orangemooncreative** [Shopify/slate#349]
I wasn't sure where else to ask this question. It's not really an issue since I haven't tried it yet but I was wondering if there is any reason that tailwind would not work with slate.

https://tailwindcss.com/docs/installation

**Comment by t-kelly** [comment]
I'm not familiar with Tailwind CSS but it looks like an alternative to SCSS or other styling languages? Looks like you'd need to modify/add a [gulp task to manage compiling the styles](https://tailwindcss.com/docs/installation/#gulp). 

Thanks for sharing this. Will explore the project when I have a chance.
