### ISSUE TITLE
Hide sold out options

### ISSUE THREAD

**Issue by artshostak** [Shopify/slate#356]
### Problem

What would be the best way to go about having the sold out variant options removed or disabled in the dropdown? There are many outdated guides out there, and most of them don't tackle the complexity of having multiple combinations of variants.

### Replication steps

Would love to provide the user with some sort of indication that the option combination (ie. Ivory in Size 2) is not available here:
<img width="1634" alt="screenshot 2017-11-27 14 50 57" src="https://user-images.githubusercontent.com/6820356/33293766-c4bda2c8-d382-11e7-9be8-94017afc4029.png">

Ideally, the only selection that should be available is Ivory in size 3, which Slate actually selects by default out of the box — but can one go a step further and simply hide them as available options?
<img width="701" alt="screenshot 2017-11-27 14 55 14" src="https://user-images.githubusercontent.com/6820356/33293939-5e6763b4-d383-11e7-874e-1cf88ab77fda.png">

Any help at all would be greatly appreciated.
Thanks!

**Comment by ruairiphackett** [comment]
Hi @artshostak 

This repo is specifically for issues to do with the Slate framework and Slate tools. Please post to the Shopify Design forums with questions like the above 🙂 

https://ecommerce.shopify.com/c/ecommerce-design
