### ISSUE TITLE
Problem installing slate on MacOs Sierra

### ISSUE THREAD

**Issue by mazzinger** [Shopify/slate#357]
### Problem

*Succinct outline of the problem or request.*
I cannot install Slate on my machine. Tried various node/npm packages, cache clean, etc. Nothing seems to work.
### Replication steps

I am getting errors when running the command: npm install -g @shopify/slate
These are the errors:
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "@shopify/slate"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@shopify/slate"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

My versions of node: v6.11.5
My version of npm: 3.10.10
MacOs Sierra 10.12.6

I have done a npm cache clean, but I also get the following errors after cache clean:
npm ERR! unpack Could not read data for @shopify/commander@2.9.2
npm ERR! unpack Could not read data for @shopify/slate@0.13.0
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "@shopify/slate"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@shopify/commander"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

At this point, I don't know what else to do here. Your help would be greatly appreciated!
*By the way, I don't believe this is an npm issue because I can install other packages without problems.

**Comment by t-kelly** [comment]
It bizarre that you're getting `Invalid name: "@shopify/slate"`... I'm not sure what to suggest.

Could you try installing another npm with an `@` at the start? Like `npm install --save-dev @babel/core @babel/cli`?

**Comment by mazzinger** [comment]
Tried your suggestion.
npm install --save-dev @babel/core : 
npm ERR! unpack Could not read data for @babel/code-frame@7.0.0-beta.32
npm ERR! unpack Could not read data for @babel/types@7.0.0-beta.32
npm ERR! unpack Could not read data for @babel/helper-get-function-arity@7.0.0-beta.32
npm ERR! unpack Could not read data for @babel/template@7.0.0-beta.32
npm ERR! unpack Could not read data for @babel/helper-function-name@7.0.0-beta.32
npm ERR! unpack Could not read data for @babel/traverse@7.0.0-beta.32
npm ERR! unpack Could not read data for @babel/generator@7.0.0-beta.32
npm ERR! unpack Could not read data for @babel/helpers@7.0.0-beta.32
npm ERR! unpack Could not read data for @babel/core@7.0.0-beta.32
npm WARN enoent ENOENT: no such file or directory, open '/Users/mazzinger/package.json'
...
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "@babel/core"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10

What is it about @ packages that cannot be installed?

**Comment by mazzinger** [comment]
Ok, thanks to your question, I was able to find something online about this issue. It does seem to be an npm 3.10 issue. I installed npm4.0.2 as recommended by other people, and that seems to have fixed the issue.
Thanks!

**Comment by t-kelly** [comment]
Cool! Happy I was able to help. 🍸
