### ISSUE TITLE
Article comment submission does not check for failure

### ISSUE THREAD

**Issue by mmargel** [Shopify/slate#358]
### Problem

When posting an invalid comment to an article (for example, one with an empty name or body), both the success and error messages are shown. Additionally, the comment counter is incremented, even though no comment was actually posted.

[![alt](https://screenshot.click/30-50-g9zfu-9tio2.jpg)](https://screenshot.click/30-50-g9zfu-9tio2.jpg)

### Replication steps

1. Go to a store using Slate's default article.liquid template (or at least, one that has not been updated with error handling).
2. Post an invalid comment.
3. Observe both the success and error messages, as seen above.

### More Information

This seems to occur because the template only checks if the `comment` object exists in order to show the success message, but does not check if the form submission returned an error. Checking whether the form submission returned an error should remedy the issue.

This was recently discovered by a merchant: https://shopify.zendesk.com/agent/tickets/7461501

**Comment by t-kelly** [comment]
Moved to https://github.com/Shopify/starter-theme/issues/4
