### ISSUE TITLE
Slate migrate won't create .gitignore

### ISSUE THREAD

**Issue by willowcheng** [Shopify/slate#359]
### Problem
When performing command of `slate migrate`, it won't create `.gitignore` automatically.

### Replication steps
Download a theme, and `slate migrate`.

### More Information
I can't find how to create `.gitignore` for Slate in documentation, so the only way for me is to create a fake theme and grab `.gitignore` which is annoyed.

**Comment by NathanPJF** [comment]
@willowcheng Thanks for logging the issue.  We're focused on the next release of Slate, so it will be a little while until this gets addressed, or addressed in that next release. 

You're welcome to open a PR to address this if you feel comfortable 😄

**Comment by t-kelly** [comment]
This is not a problem in [Slate v1.x](https://github.com/Shopify/slate/tree/1.x). Don't see it a priority to fix in `0.x`. Closing.
