### ISSUE TITLE
Add new/edit existing gulp tasks

### ISSUE THREAD

**Issue by chrisrowe** [Shopify/slate#362]
In relation to #349 (Tailwind isn't an alternative to SCSS but just a postcss plugin)
Is there any documentation on how to configure slate for adding/modifying the provided gulp tasks

**Comment by rlambertsen** [comment]
I 100th that please. Dealing with issue where I assume `gulp-svgmin` is parsing the svg and removing important things, like `hrefs` . Trying to find solution but I can't be mad at `gulp-svgmin` as I presume I change that in a setting if I had control over the gulpfile....

**Comment by t-kelly** [comment]
This is not a priority for us as we are focused on shipping [Slate v1.x](https://github.com/Shopify/slate/tree/1.x).

There is a discussion about how to extend/customize Slate v1 build pipeline here https://github.com/Shopify/slate/issues/394
