### ISSUE TITLE
Using dynamic sections on other templates

### ISSUE THREAD

**Issue by jordanmoon** [Shopify/slate#363]
### Is there anyway to use the dynamic sections functionality from the homepage on other page templates? Or are there plans to add this functionality?

It seems slightly odd that this awesome functionality is only available on the homepage. 

If not, are there any ways of making sections unique so schema content is not duplicated throughout multiple pages?

Apologies if this has been answered previously or not relevant here, I couldn't seem to find any information amongst the issues.

**Comment by t-kelly** [comment]
You can currently only use dynamic sections on the homepage. You could use global settings if you don't want them repeated for every section?

**Comment by jordanmoon** [comment]
Hey @t-kelly, thanks for clarifying the dynamic sections. 

I don't think I explained the unique sections well enough. At the moment I can't see a way of using a section with editable content multiple times on the site.

For instance, if I create a section called banner like so:

```
{% schema %}
  {
    "name": "Banner",
    "settings": [
      {
        "type": "image_picker",
        "id": "image",
        "label": "Banner Image"
      }
    ],
    "presets": [{
      "name": "Banner",
      "category": "Global"
    }]
  }
```

If I use this section on a collection template for instance, select and image for the banner using the image picker, everything works fine.

It's only when I then try to use this banner on a different template, the uploaded image is already in the section. If I change the image on this different template, the collection template will change too. 

The only way I can see getting round this is creating the same section for different templates. But this seems like a very unneccessary duplication of code.

**Comment by 1aurabrown** [comment]
+1

**Comment by NathanPJF** [comment]
> The only way I can see getting round this is creating the same section for different templates. 

@jordanmoon That would be the way to do it. As @t-kelly said, dynamic sections are only available on the homepage.  That's the limitation of the current editor; which is outside the scope of this project.

**Comment by khoipro** [comment]
That's a bad case when we have the same module and want to reuse them on the homepage and About pages.

**Comment by lucasvocos** [comment]
+1

**Comment by t-kelly** [comment]
Locking this thread because as @NathanPJF said:

> dynamic sections are only available on the homepage. That's the limitation of the current editor; which is outside the scope of this project.

Shopify is aware of this limitation and any change to improve it would take place on the Shopify platform, not Slate.
