### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by dmitrywebtalent** [Shopify/slate#369]
Hello Slate Developers!

I used this slate and I'm very happy with this! It's a great tool for Shopify.

But I have a suggestion. It would be good if I can download files using command from the shopify theme. Here is why. Let's assume there are two developers working on the same shopify theme.
And one developer is working using slate. And other developer is working on the shopify theme code editor. If the second developer made changes to one of the theme file and later the first developer make changes to the same file. In this case, the first developer will overwrite the second developer's changes. 

So it would be great if I can download files before start work. It'll not overwrite anything. 

Thanks and Regards,

**Comment by NathanPJF** [comment]
Hello, @dmitrywebtalent 
Happy to hear you're like the project.

We have had similar requests for a `download` command in the past.  We have an open issue for it already here: Full support for all Themekit commands #255

I'm going to close this issue in favour of that one, but I'll add it to the list of "related issues".

In the meantime, you can use ThemeKit's `download` command to do what you are describing.  Hope that helps 😃 

https://shopify.github.io/themekit/commands/#download

Related issue in the ThemeKit repo: Theme download into specific directory #483
