### ISSUE TITLE
Why do all JavaScript files upload during "watch" when only one is changed?

### ISSUE THREAD

**Issue by kevmon** [Shopify/slate#371]
When I run `slate watch` and modify only one of the three js files in /scripts, at least two files need to upload and most of the time it's four files.

In this example, I only made a change to theme.js:

```
[14:54:29] change in src/scripts - change theme.js
[14:54:29] running task - build:js
[14:54:29] change in src/scripts - change theme.js
[14:54:29] running task - build:js
[14:54:29] change in assets - change giftcard.js
[14:54:29] Initiating deploy to development
[14:54:29] change in assets - change theme.js
[14:54:29] Initiating deploy to development
[14:54:29] change in assets - change giftcard.js
[14:54:29] Initiating deploy to development
[14:54:29] change in assets - change theme.js
[14:54:29] Initiating deploy to development
[14:54:30] running task [child process] - theme upload
[development]: 4 / 4 [====================================================================] 100 %
```

Why is this?  I never really noticed on a fast connection, but after taking a work-cation to a country with developing infrastructure, each save could take up to a minute.

Thanks!

**Comment by NathanPJF** [comment]
Thanks for the question @kevmon 

In the `processThemeJs` function that's part of the build, you can see that we are grouping all JS files that aren't third-party vendor files under the same watch task. https://github.com/Shopify/slate/blob/master/packages/slate-tools/src/tasks/build-js.js#L11-L42

So a change in any file that isn't in the vendor folder triggers `processThemeJs`.  Reason being: If I'm remembering correctly, this was a decision taken waaay back when there was more Liquid in JS files.  We didn't know of the dependency between files, so we'd rebuild everything.  

However, it's worthwhile for us to take a new look at this and save the unnecessary builds.

**Comment by NathanPJF** [comment]
Related: you can see the same behaviour in modifying CSS files.  If I have both a `theme.scss` and another "top level" `main.scss`, a change in any file will rebuild both stylesheets.

<details><summary>Screenshot of behvaiour</summary>

![](http://take.ms/KE18x)

</details>
&nbsp;

**Comment by NathanPJF** [comment]
Quick update: Taking this off the 0.14.0 milestone as this process is being revisited in the next release.

**Comment by kevmon** [comment]
Thanks!  That makes sense.  A little off topic, but my buddy and I have been putting together our own gulp workflow that works on top of slate and I'd like to start a thread where others and I can share our setups for feedback and ideas.  Is a thread in this GitHub repository the appropriate place to do that?  (I'm a bit new to using GitHub)

**Comment by NathanPJF** [comment]
@kevmon It would be best if you started a separate GitHub repo for your project :) 

It's common that people will "fork" a public GitHub project to change it as they see fit.  For example this project has been forked a number of times, which you can see here: 

![](http://take.ms/hWaRg)

**Comment by kevmon** [comment]
Thanks!
