### ISSUE TITLE
Import node_modules package issue

### ISSUE THREAD

**Issue by schellenbergk** [Shopify/slate#374]
I'm having issue importing npm package script but not css

if I try:

`@import url('../../node_modules/package/style.css');`

it works perfectly fine and combiles styles correctly however in vendor.js I've tried:

```
require 'package/script.js'
//and
require '../../node_modules/package/script.js'
//and
// =require package/script.js'
//and!!!
// =require ../../node_modules/package/script.js'
```
but that does not seem to work as for the first 2 I get:

```
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: string (../../node_modules/package/script.js) (line: 29, col: 8, pos: 91993)
```
and for the rest it compiles but without my package, uggggh!!!  Is this a bug or am I doing something wrong?

**Comment by t-kelly** [comment]
Slate currently uses `gulp-include` to concat JS files. After [reviewing the docs](https://www.npmjs.com/package/gulp-include), it looks like you'll need to add `__dirname + 'node_modules'` as the `includePath` option in Slate's [`build-js.js`](https://github.com/Shopify/slate/blob/master/packages/slate-tools/src/tasks/build-js.js)

**Comment by schellenbergk** [comment]
Thanks @t-kelly ,

That worked... I just edited:

`node_modules/@shopify/slate-tools/lib/tasks/build-js.js`

and updated `processVendorJs` and added:
```
 {
    includePaths:[
      config.themeRoot + "/src/scripts",
      config.themeRoot + "/node_modules"
    ]
  }
```
to gulp-include.  Here's the full function:
```
function processVendorJs() {
  messages.logProcessFiles('build:vendor-js');
  return gulp.src(config.roots.vendorJs).pipe(plumber(utils.errorHandler)).pipe(include({
    includePaths:[
      config.themeRoot + "/src/scripts",
      config.themeRoot + "/node_modules"
    ]
  })).pipe(uglify({
    mangle: true,
    compress: true,
    preserveComments: 'license'
  })).pipe(gulp.dest(config.dist.assets));
}
```
