### ISSUE TITLE
Customers/orders.liquid template incomplete re: Refunds

### ISSUE THREAD

**Issue by rickydazla** [Shopify/slate#375]
### Problem

The [customers/order.liquid template](https://github.com/Shopify/slate/blob/master/packages/slate-theme/src/templates/customers/order.liquid) does not contain complete information regarding the Order — there is nothing in the Liquid that pertains to Refunds (or Transactions of any kind for that matter.)

**Comment by t-kelly** [comment]
Moved to https://github.com/Shopify/starter-theme/issues/2
