### ISSUE TITLE
Understand the interaction between theme JavaScript and the theme editor

### ISSUE THREAD

**Issue by muhammad-musa** [Shopify/slate#379]
When a section is re-rendered or added to the page then JavaScript can't load. How can I solve it?

**Comment by t-kelly** [comment]
You'll need to use the [`shopify:section:load` event](https://help.shopify.com/themes/development/sections#understand-the-interaction-between-theme-javascript-and-the-theme-editor) emitted in the editor to trigger any JS you wish to execute.
