### ISSUE TITLE
Installing Node Modules does not appear in node_modules

### ISSUE THREAD

**Issue by patrickbjohnson** [Shopify/slate#381]
## Problem

When trying to run `npm i --save <PACKAGE NAME>` the package never downloads to Slate's `node_modules` directory. 

### Replication steps

1. Open terminal and the install Flickity package: `npm i --save flickity`
2. Upon successful installation (no errors in terminal), review the `node_modules` directory at the root of the Slate project. 
3. the `flickity` direcotry does not display. 

### More Information

For me, this has happened with two separate packages: Flickity and CartJS. This has happened within the same project but across two separate computers. More than happy to try and duplicate on a fresh theme install if that would better service this issue. 

Currently using `"@shopify/slate-tools": "0.13.0"` version of Slate

**Comment by patrickbjohnson** [comment]
Seems like it may be related to the `node_modules` being ignored and not code editors (in this case VSCode) not updating the directory unless you reboot the IDE.

**Comment by t-kelly** [comment]
I've also seen this behaviour in VSCode. When in doubt, open the directory in Finder 😄
