### ISSUE TITLE
Breaking settings_data.json removes all content and resets theme settings

### ISSUE THREAD

**Issue by jordanmoon** [Shopify/slate#384]
### Problem

When developing a theme, it's possible to reset all theme settings by breaking settings_data.json

### More Information

I appreciate there is a comment in the config.yml to address this specific issue. But this seems to be a bit of a harsh workaround, especially being default for the production environment.

Are there any future plans to improve this stop settings_data.json completing removing all the content?

**Comment by NathanPJF** [comment]
> reset all theme settings by breaking settings_data.json

What do you mean by "breaking" @jordanmoon? Like if you mistype a comma in the JSON object?  Mind providing some reproduction steps?

>  especially being default for the production environment.

What do you mean by this?  The tool will default to a `development` environment, and this has no `theme_id` in the generated `config.yml` file.

**Comment by jordanmoon** [comment]
Hey @NathanPJF thanks for the reply. 

> Mind providing some reproduction steps?

Sure! So if I have a fairly basic `settings_data.json` like so:

```
{
  "current": "Default",
  "presets": {
    "Default": {
      "sections": {
        "collection-list": {
          "type": "collection-list",
          "blocks": {
            "collection-list-0": {
              "type": "collection"
            },
            "collection-list-1": {
              "type": "collection"
            },
            "collection-list-2": {
              "type": "collection"
            }
          },
          "block_order": [
            "collection-list-0",
            "collection-list-1",
            "collection-list-2"
          ]
        },
        "featured-collection": {
          "type": "featured-collection",
          "settings": {
            "collection": "frontpage"
          }
        },
        "slideshow": {
          "type": "slideshow"
        }
      },
      "content_for_index": [
        "slideshow",
        "featured-collection"
      ]
    }
  }
}
```

I start a `slate watch` which succeeds. I continue developing my theme, adding content to my dev store etc. 

If I then add a new section to the `settings_data.json` and provide any invalid JSON. The watcher dies and clears all content I've uploaded in the dev store. I get this for the dev store, as it is specifically stated in the `config.yml`. Although, it's pretty inconvenient if you aren't running a JSON linter to have all your content eradicated.

> What do you mean by this? The tool will default to a development environment, and this has no theme_id in the generated config.yml file.

As above, I understand it is specifically stated in the `config.yml`, but if you `slate deploy -e production` to your live site, you could potentially delete all of your content. It seems if it's broken, the watch or deploy should break without deleting all content?

**Comment by NathanPJF** [comment]
Thanks for the reproduction steps.  I'm not able to reproduce on my end though.  When I try to upload a broken JSON object in `settings_data.json`, I'm given back the following message and my hosted file is left untouched.

```bash
17:25:20 [development]Asset Perform Update to config/settings_data.json at host test.myshopify.com
        Status: 422 Unprocessable Entity
        Errors: Invalid JSON: unexpected token

[17:25:20] Transfer Failed: 17:25:20 [development]Asset Perform Update to config/settings_data.json at host test.myshopify.com
        Status: 422 Unprocessable Entity
        Errors: Invalid JSON: unexpected token
```

> The watcher dies and clears all content I've uploaded in the dev store.

Nothing is being cleared on my end. Are you saying your `settings_data.json` file gets turned into a blank file?  If so, would you been able to provide a screen recording of this?

**Comment by jordanmoon** [comment]
Thanks for the reply. I think I've confused things a little!

I get the same error message as you do on the command line, my `settings_data.json` stays the exact same. It's my shops content that is cleared. If I have basic text section with the following schema:

```
{% schema %}
  {
    "name": "About",
    "settings": [
      {
        "type": "text",
        "id": "title",
        "label": "Title",
      },
      {
        "type": "textarea",
        "id": "description",
        "label": "Description"
      }
    ],
    "presets": [{
      "name": "About",
      "category": "Global"
    }]
  }
{% endschema %}
```

This would be the content that get's cleared:

![screen shot 2018-02-06 at 09 24 04](https://user-images.githubusercontent.com/19351135/35851323-9b6adab0-0b1f-11e8-9cc8-d8c32afad3af.png)

But this would be for all sections with content from the `schema`, including the dynamic sections on the home page. So essentially, most of the content is cleared out.

If you can't recreate that or i've confused things even further. I can provide a screen recording! 😄

**Comment by jonathanmoore** [comment]
@jordanmoon Do you have your `config.yml` file set up to ignore the `settings_data.json` file?  If not what your experiencing would be expected behavior if you make a valid JSON change to `config/settings_data.json` locally and it gets uploaded to the Shopify servers.

The `settings_data.json` file is used by Shopify to store every change made (General settings, home page sections, etc) in the Customize Theme menu.  So if your local copy of `settings_data.json` is uploaded to Shopify this will wipe out anything that was done in Shopify's menus.

When I'm working on a theme, I'll first do a fresh upload to Shopify and then add `settings_data.json` to the `ignore_files` list.  Virtually all of my environments use this option.
```
development:
  password: 00000000000000000000
  theme_id: "live"
  store: shopname-dev.myshopify.com
  ignore_files:
    - settings_data.json
```

As long as I'm ignoring `settings_data.json` both valid and invalid JSON changes will be prevented to upload.  If I don't ignore `settings_data.json` then an invalid JSON change is properly blocked.
```
[16:04:18] Transfer Failed: 16:04:18 [development]Asset Perform Update to config/settings_data.json 
        Status: 422 Unprocessable Entity
        Errors: Invalid JSON: unexpected token
``` 
*However*, as soon as I fix and save the broken JSON in `settings_data.json` the file does upload and 100% of the customizations are wiped out as expected.

**Comment by NathanPJF** [comment]
Thanks for jumping in @jonathanmoore :)  I agree that this now all sounds like intended behaviour.

@jordanmoon Just to add one more point on workflow: we typically use the online theme editor to populate `settings_data.json` for us.

**Comment by jordanmoon** [comment]
Thanks for the clarification @jonathanmoore :D I understand this is intended behaviour and can see why in relation to the way Shopify handles it. I'll go with @NathanPJF's way of doing it from now on!

> When I'm working on a theme, I'll first do a fresh upload to Shopify and then add settings_data.json to the ignore_files list. Virtually all of my environments use this option.

Would it be possible to update the comment in `config.yml` for further clarification that all data will be removed? Or maybe leave the production environments `settings_data.json` uncommented. It does seem a bit dangerous to allow a user to deploy to production and replace everything in the theme by missing out a commented line.

>Just to add one more point on workflow: we typically use the online theme editor to populate settings_data.json for us.

Maybe this could be added to the Slate instructions as a tip? As a dev who's never used Slate before, this setting isn't very obvious until it becomes a problem.

I appreciate this is all pretty minor stuff, just want to make sure nobody else is losing their entire themes settings! 😄

**Comment by t-kelly** [comment]
@jordanmoon opened an issue with a proposed solution #404
