### ISSUE TITLE
What is the proper workflow for a small team?

### ISSUE THREAD

**Issue by SockFuzz** [Shopify/slate#385]
We are a small team of just a couple people and decided to use slate for this project along with git. Currently we are all pushing and working off of the development branch, making daily commits, and pulling down latest changes before working each day. 

Using 'slate start' deploys your local source to the server, and if anyone else has a different feature then it will overwrite their code. We are all using watchers with live reloading as part of our development flow. We are stepping on each others toes while doing so.

It would make sense to create separate development stores per person, and in the future this will likely be the route we take, but Shopify has no clone store option which means we have to manually create all of our store content into our private development stores.

Does anyone else have a better workflow than to individually create and migrate store data into personal development stores? # #

**Comment by eltonjuan** [comment]
@SockFuzz:  This is the exact issue I've been trying to address in the issue that I opened:  https://github.com/Shopify/slate/issues/373 . 

I also don't see how creating a development store per person is a reasonable solution.

**Comment by SockFuzz** [comment]
@eltonjuan Thank you for replying to this and advising me you already have an issue opened. I scanned through the issues and saw the title of your issue but did not read the content. I am going to close this issue and refer to yours.

I agree that creating separate stores is not the most elegant solution, but until a better solution appears this was the best I could scrap up for now.

**Comment by SockFuzz** [comment]
Duplicate of #373, closing issue.
