### ISSUE TITLE
Every link in a custom theme (based on Slate) opening in a new tab

### ISSUE THREAD

**Issue by louiseswift** [Shopify/slate#391]
Hi, I'm posting this issue [as suggested](https://twitter.com/ShopifySupport/status/961655357524373506) by @ShopifyDevs on Twitter.

### Problem

We're working on our first Shopify custom theme (built on top of the Slate framework, using the Slate toolset - version 0.13.0) and at some point in our dev process all of the links in the site have started to open in new tabs.

(These links do not have `target="_blank"` set on them.)

We've done a fair bit of searching and not found any mention of anything similar. Apologies if our newness to the Shopify theme dev stack means that we're missing something.

### Replication steps

We're not sure of the best way to share replication steps for Shopify development issues as the "constantly deploy local changes directly to the production server" process is a new/unusual one for us.

The store name is 'byfarleigh' and our custom theme is named 'Farleigh-Staging', if troubleshooters at Shopify are able to take a look directly.

I've included a demo video below to confirm that we don't have `target="_blank"` set on these links.

![issue_demonstration](https://user-images.githubusercontent.com/7622586/36029990-5e3cb408-0d9d-11e8-9a43-dd578418a585.gif)

Let me know if there's something else I should do to help with replication.

Thanks for looking into this.

**Comment by NathanPJF** [comment]
@louiseswift just to set expectations: This project typically does not provide troubleshooting on individual projects/stores.  

With that said, I suspect the behaviour you're seeing has to do with a 3rd party library attaching it's own event handlers.  I recommend going through the different loaded resources and individually [blocking resource requests](https://developers.google.com/web/updates/2017/04/devtools-release-notes#block-requests) until you've found the responsible script.

**Comment by louiseswift** [comment]
Thanks for the response - it did turn out to be a library we're using. New libs + new development process at the same time = asking for trouble!
