### ISSUE TITLE
Align "System Requirements" and "Getting started"

### ISSUE THREAD

**Issue by uli-weltersbach** [Shopify/slate#395]
### Problem

The `yarn [...]` and `npx [...]` commands used in the [Getting started section](https://github.com/Shopify/slate/tree/1.x#getting-started) require packages which aren't mentioned in the [System Requirements section](https://github.com/Shopify/slate/tree/1.x#system-requirements).

### Replication steps

![image](https://user-images.githubusercontent.com/1416006/36227487-7fcaa1ec-11d1-11e8-801e-e5832745d138.png)

**Comment by t-kelly** [comment]
@uli-weltersbach Yarn is not a system requirement, it's an optional package manager to NPM. I don't think it needs to be specified.

[`npx`](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) is included with NPM 5.2.0 or greater. I will update the docs to be more accurate about the NPM version.

**Comment by uli-weltersbach** [comment]
Alright - I disagree with your decision, although I'm aware that `yarn` has become the replacement for NPM in a lot of consulting firms.

**Comment by t-kelly** [comment]
@uli-weltersbach care to elaborate? Just trying to understand your frame of mind.

What's wrong with `npx`?

**Comment by uli-weltersbach** [comment]
Sorry, I overlooked your explanation of `npx` being part of NPM 5.2. All is well and I will shut up.
