### ISSUE TITLE
Add installation instructions to README.md

### ISSUE THREAD

**Issue by uli-weltersbach** [Shopify/slate#396]
### Problem

I'm a novice and don't know how to install Slate. The current `README.md` offers no help in that regard.

### Replication steps

See the [README.md](https://github.com/Shopify/slate/blob/1.x/README.md).

**Comment by t-kelly** [comment]
Hey @uli-weltersbach -- Curious. What about the current `Getting Started` section of the README.md is not helping you get things running?

**Comment by uli-weltersbach** [comment]
Nope. When I run `yarn [...]` my machine tells me it's "an unknown command". 
I know how to install `yarn`, but not everyone in our company does.

Is the "Getting Started" section aimed at Shopify employees or at the general public? Maybe me and my colleagues are not the intended audience.

This is what I see in the "Getting started" section - maybe you're looking at a different branch:

![image](https://user-images.githubusercontent.com/1416006/36502776-3e5e8794-174b-11e8-83d7-79cdec90c6a5.png)

**Comment by uli-weltersbach** [comment]
To make it more clear: I'm looking for something like `npm i @shopify/slate --save-dev` or whatever does the trick.
E.g. the current version of slate has the following instructions available via https://www.npmjs.com/package/@shopify/slate:
`npm install -g @shopify/slate`
