### ISSUE TITLE
[slate-env] Default .env missing comments / descriptions

### ISSUE THREAD

**Issue by jonathanmoore** [Shopify/slate#398]
### Problem

Running State 1.x alpha, the `.env` file is a bit bare missing comments that would help on-boarding.  For example, it wasn't clear until I opened [slate-env.config.js](https://github.com/Shopify/slate/blob/1.x/packages/slate-env/slate-env.config.js) that the `SLATE_IGNORE_FILES` should be separated by a `:`

> 'The environment variable used to reference a list of files, separated by ":", to ignore'

The README.md shows that the default should be...

```
# The API password generated from a Private App
SLATE_PASSWORD=

# The ID of the theme you wish to upload files too.
SLATE_THEME_ID=

# The myshopify.com URL to your Shopify store.
SLATE_STORE=

# A list of file patterns to ignore, with each list item seperated by ':'
SLATE_IGNORE_FILES=
```

**Comment by jonathanmoore** [comment]
Would it be possible to use the descriptions from `slate-env.config.js` as the comment?

**Comment by t-kelly** [comment]
Maybe what I'll do is insert the `.description` value of each variable as a comment when generating the file? Shouldn't be too hard! 

Thanks for this issue! Exactly the kind of feedback I'm hoping to receive by having this open to the public 😄
