### ISSUE TITLE
Change `src/assets/vendors` to `src/assets/static`

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#411]
### Problem
Currently, `src/assets/vendors` is the only folder that has its contents copied directly to the `dist/assets` folder, e.g. `src/assets/vendors/modernizr.js` gets copied to `dist/assets/modernizr.js`.

All other files and folders in the `src/assets/` folder need to be referenced from an entry point, e.g. `theme.js`.

The current name `vendors` implies, at least to myself, that it is for vendor JS (e.g. jQuery, or Modernizr), where in fact it is for any file you want always copied into your `dist/assets` folder.

I propose that we rename the `vendor` folder to `static` to make this a little more clear.

**Comment by jlyon** [comment]
+1
