### ISSUE TITLE
Getting a MIME error when compiling scss

### ISSUE THREAD

**Issue by graftstudio** [Shopify/slate#412]
### Problem

*Succinct outline of the problem or request.*

Im getting a weird error in console saying:
'Refused to apply style from 'https://cdn.shopify.com/s/files/1/3101/9164/t/9/assets/theme.scss.css?18124487024720594321' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.'

There isnt any issue with the scss, it has been checked over. but for some reason the whole theme is broken. 

The only thing i can think of was that i installed an updated version of slate. maybe some node modules are not compatible??

here is a screenshot:
https://www.evernote.com/l/AFzRfDeycPdFHplOj45dTpOBUQjnHVyuzXsB/image.png

any help appreciated!

**Comment by t-kelly** [comment]
What version of Slate did you upgrade too?

**Comment by iz103** [comment]
Hi guys, I am having the same problem which only happened today, without any changes on my side.

My Slate version is 0.13.0
I am on Node 6

My logs look fine

**Comment by graftstudio** [comment]
Hi 

It was actually a SCSS error. The problem for me was that there was no indication where the error was originating from, but opening the .scss file through the source code and seeing an error message was the information I got to finally realise what it was.

If you do the same - and see an error message that will tell you the scss isnt compiling due to an error.

Shopify - perhaps it would be useful to have a sort of debugger set up in console? something to help us figure out the source of errors?

thanks!

**Comment by whosdustin** [comment]
Hi,

I've come across this exact error and found it was related to my usage of CSS variables. 
Are you using Bootstrap 4, or including CSS variables? For example:

```
:root {
  --primary: #ff0;
}
```

This might be another case of - Shopify's online compiler supports Sass v3.1 [mentioned here](https://github.com/Shopify/slate/issues/117#issuecomment-293553100). 

Unfortunately, there is no mention of CSS variables in Sass's changelog until [v3.4.22](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#3_4_22) and even then needed to be interpolated `#{}`. I've tried every mixin, function, interpolation possible to trick the compiler. It all boils down to any text beginning with `:` or `--` that will turn the `theme.scss.css` into a MIME type of (text/plain).

If this is related to your situation, the only way is to put the variables in a css file that doesn't require compilation. Which obviously defeats the purpose of using CSS variables with Shopify variables in liquid.

I hope this helps. Even if a little. :smiley:

**Comment by graftstudio** [comment]
Hi Dustin

Not using bootstrap no

It was the usage of variables like you discussed

Looks like the compiler is in need of an update… same with node, node is currently V8 whereas slate uses V6…

**Comment by t-kelly** [comment]
@graftstudio @whosdustin would recommend looking at [Slate 1.x branch](https://github.com/Shopify/slate/tree/1.x). We're now compiling SCSS locally (so you can use the latest version of SCSS) and taking advantage of CSS Variables for Liquid variables.

**Comment by RadDog25** [comment]
In my case the culprit was a bullet entity (•) which caused issues even while being commented.

**Comment by jonathanmoore** [comment]
@RadDog25 Make sure you have `@charset 'UTF-8';` at the very top of the SCSS file, and then you should be able to add bullets • and emoji 🙌
