### ISSUE TITLE
Slate deploy using cached theme.js

### ISSUE THREAD

**Issue by paul-muckypuddle** [Shopify/slate#415]
### Problem

Using slate watch, I can make changes to JS files and see them reflected in real time. Running slate deploy after a period of slate 'watching', the JS file deployed is stale. and doesn't contain the updates In this instance I was editing product.js

### Replication steps

1. Run slate watch
2. Edit product.js
3. Stop slate watch
4. Run slate deploy
5. theme.js file contains stale product.js before edits

### More Information

Running slate 0.13.0
Tried deleting dist folder with no success

**Comment by t-kelly** [comment]
@paul-muckypuddle Can you make sure you're viewing the theme with the same ID as the one you're deploying too? This functionality is pretty core to Slate.. I'm pretty sure it works 😅

**Comment by paul-muckypuddle** [comment]
Hahahah I’d would of thought so too, but the concatenated theme.js file in /dist has some prior changes but not all and the env is the same

----

**Comment by paul-muckypuddle** [comment]
I'm out of the office just now but perhaps my brain was just fried - I'll do the same thing tomorrow and see what's what 😄

**Comment by paul-muckypuddle** [comment]
OK so coming in fresh - I was working on a previously built theme which I needed to update with some new features. As the client had installed some apps I needed to pull down their changes and combine them with my local copy before starting. As Slate 0.x doesn't have this feature, I downloaded a zip of the theme and copied the files over, overrwriting my versions where appropriate.

Of course, Shopify stores JS / CSS files in `assets` server-side, which was part of the zip (client side they're in `src/scripts` and `src/styles`). And in that folder was the previous `theme.js`, amongst other things. Not sure what the internals are, but running `slate build` copied(?) the downloaded JS files, including `theme.js`, from `src/assets`, instead of the newly compiled ones, into `dist/assets`.

Deleting the offending JS files from `src/assets` did the trick.

I assume JS assets are inherently not to be placed in `src/assets`, but is there any way to make Slate ignore them? I've seen GH issues from users wanting to combine app changes made server-side with their own code client-side, and the zip option is always discussed, but nothing mentioned about what may reside in `<zip>/assets` that you definitely don't want in `src/assets`.

**Comment by t-kelly** [comment]
@paul-muckypuddle Syncing changes definitely a tricky problem theme developers are having right now, and one [we plan on tackling in a future release of Slate v1.x](https://github.com/Shopify/slate/issues/403).

The only ignore function we have is to ignore files being uploaded to Shopify servers via `config.yml`. We don't have any configuration for ignoring files being copied from `src/assets` to `dist/assets`.
