### ISSUE TITLE
No CSS on Newly Created Project

### ISSUE THREAD

**Issue by jesster2k10** [Shopify/slate#419]
### Problem

Created a new theme using both slate v0.13 and the latest 1.x alpha. When I preview the theme, there is no css loaded and the page is barebone html

### Replication steps

![screen shot 2018-02-28 at 23 41 11](https://user-images.githubusercontent.com/6454286/36819343-0be32fd6-1ce1-11e8-83cf-b3436f60b3f6.png)

### More Information

`- Node: 9.6.1
  - NPM: 5.6.0
  - Yarn: 1.3.2
`

**Comment by t-kelly** [comment]
Hey @jesster2k10, you are actually seeing some styles! See the ['Intentionally Blank'](https://shopify.github.io/slate/theme/#intentionally-blank) section in the docs for more info.

**Comment by jesster2k10** [comment]
I noticed that earlier on. Thanks!
