### ISSUE TITLE
Admin Bar: Hide bar action not working on localhost

### ISSUE THREAD

**Issue by seandogg** [Shopify/slate#420]
### More Information

<img width="104" alt="screen shot 2018-03-01 at 10 20 32 am" src="https://user-images.githubusercontent.com/7729784/36861994-6bd38932-1d3a-11e8-881e-905f2f0874d2.png">

**Comment by t-kelly** [comment]
Hmmm I think a team updated the Preview Admin Bar... probably broke something in Slate. Will 🔬

**Comment by erbanach** [comment]
I also have this issue locally - Slate version 0.13.0.

**Comment by puppycodes** [comment]
+1

**Comment by ConduciveMammal** [comment]
As handy as the preview bar is, it’s a massive pain in the neck. It’s be so much better if there was a small tab at the bottom with the theme name and an arrow to click to expand it. Perhaps put this to the Shopify team?

**Comment by hcmlopes** [comment]
I can confirm that the preview bar functionality broke when the preview bar was updated some time ago. I think about 2 months now

**Comment by LeRoyJulian** [comment]
Any fix coming?

**Comment by dirad** [comment]
The admin bar is now totally different and so none of the buttons work...

**Comment by ccdunder** [comment]
Workaround: Add to theme.scss.liquid: `iframe[src="//localhost:3000/preview_bar"] { display:none; }`

**Comment by ConduciveMammal** [comment]
@ccdunder Oh that's a **lot** better than my solution! I'm always forgetting to remove it in production.

**Comment by macrozone** [comment]
Any update from the shopify-team on that? the preview bar is _completly_ broken at this state. It overlaps the content, looks ugly and the buttons do not work.

**Comment by huguestennier** [comment]
Fixed in #953

**Comment by ConduciveMammal** [comment]
@huguestennier although this is a **very** welcome fix. Was it not possible to fix the core issue, rather than just hiding it? Shopify has a rather awkward cookie/cache issue where theme previews will randomly disable and instead show the live theme.

When working with a theme that's nearly identical to the live theme, without the preview bar it'd be a nightmare to realise I'm suddenly seeing the live theme and wondering why changes aren't being applied.

**Comment by seandogg** [comment]
> Workaround: Add to theme.scss.liquid: `iframe[src="//localhost:3000/preview_bar"] { display:none; }`
> 
> (inspired by [this](https://github.com/Shopify/slate/issues/141#issuecomment-304475032) comment)

Using `iframe#preview-bar-iframe { display:none; }` is working for me on a themekit project, in case anyone needs a quick fix.
