### ISSUE TITLE
Improve documentation on Slate's CSS Variable solution

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#423]
### Problem

There is some confusion around how CSS variables are being integrated into the Slate v1.x workflow. 

Currently we have this blurb in the [*Local SASS compilation with vendor prefixing and Liquid*](https://github.com/Shopify/slate/tree/1.x#local-sass-compilation-with-vendor-prefixing-and-liquid) section:

---
Slate introduces a new way of handling styles made possible through CSS Custom Properties. CSS Custom Properties are the perfect mechanism to link styles to Theme Editor Liquid settings. They allow you you to write valid CSS and SCSS that doesn’t break build tools like PostCSS vendor prefixing, and are supported in all modern browsers.

When local SASS compilation is combined with Slate's Local Development Assets Server, style changes are instantly injected into the page, without waiting for Shopify servers, resulting in a lightning fast development experience.

To support legacy browsers, Slate includes a transpiler that replaces CSS Variables with matching Liquid Variables as a last step in the production build script.

---

and a little bit more in the [`@shopify/slate-cssvar-loader`](https://github.com/Shopify/slate/tree/1.x/packages/slate-cssvar-loader) package README

### More Information

This is a big change from anything we've done before. Let's make sure we explain it thoroughly.

Related: https://github.com/Shopify/slate/issues/421

**Comment by jesster2k10** [comment]
I think improving the way javascript works with the html/liquid would be good. I'm still finding it hard trying to add some js functionality to my header section without using `<script>` tags in the section itself.

**Comment by t-kelly** [comment]
@jesster2k10 lets keep the scope of this issue to what is described in the title and description. Please make another issue for subjects outside of this scope.
