### ISSUE TITLE
'slate-tools' command not found

### ISSUE THREAD

**Issue by jesster2k10** [Shopify/slate#425]
### Problem

Running `yarn start` on a newly created (or existing) Slate v.1.x project produces an error saying `slate-tools command not found`.

I've attempted to reinstall slate globally alongside `@shopify/slate-tools` but none resolve the issue.

### Replication steps

Create a new project using slate v1.x using the command

`yarn create slate-theme my-new-theme`

and run

`yarn start` or `npm start`

### More Information

iMac, Late 2013

- Node v8.9.4
- NPM v5.6.0
- Yarn v1.3.2

MacBook Pro, Mid 2014

It works in the same project when running on another computer (MacBook Pro) with the same info.

**Comment by jesster2k10** [comment]
Just to note running `slate -v` produces this:

```bash
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/jesseonolememen/Documents/Shopify/theme/node_modules/@shopify/slate-tools/lib/commands'
    at fs.readdirSync (fs.js:904:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@shopify/slate/lib/index.js:93:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by pveen2** [comment]
Same problem

**Comment by NathanPJF** [comment]
Thanks for answering @elisechant 😄 

@jesster2k10 @pveen2 As Elise said, the version of `@shopify/slate-tools` your project should be referencing is the local one.  Running `yarn install` is part of the initial process when running `yarn create slate-theme my-new-theme`.  Below I have the output when I run the command, you can see near the end where it runs `yarn install`.

```
$ yarn create slate-theme from-scratch
yarn create v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "create-slate-theme@1.0.0-alpha.24" with binaries:
      - create-slate-theme
[#########################################################################################################################################] 137/137
Creating a new Slate theme in: /Users/nathanferguson/code/from-scratch.
Cloning theme from a git repo: git@github.com:shopify/starter-theme.git
Installing theme dependencies...
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
```

Though if your project failed to install the required `node_modules` after this build, please let us know.  

![](http://take.ms/e4A2k)

A quick workaround should be running `yarn install` from within your project as @elisechant said.

**Comment by NathanPJF** [comment]
@jesster2k10 I meant to follow-up on this line earlier

> I've attempted to reinstall slate globally alongside `@shopify/slate-tools` but none resolve the issue.

Could you try by globally uninstalling with `npm uninstall @shopify/slate -g` (and same for `@shopify-slate-tools`) and try again?  There's a chance there's a conflict.

And thank you for providing details in the original post :)

**Comment by t-kelly** [comment]
Closing since @elisechant nailed the answer ❤️

**Comment by mattkersner** [comment]
I am getting this same issue and I have tried everything. I even tried setting up a new slate theme from scratch using slate theme my-theme, same error. Same with using slate migrate on an existing theme. I can't run any slate commands. What I also find odd is it seems to be looking in the wrong place. It's looking in my-theme/node_modules/@shopify/slate-tools/lib/commands but I see those files in my-theme/node_modules/@shopify/slate-tools/cli/commands. Not sure what to do or how to troubleshoot.

**Comment by sebbean** [comment]
sup @mattkersner from 5 hours ago

I'm having same issue
just tested out 1.0 on a new theme and now my old themes are broken

https://github.com/Shopify/slate/issues/190

**Comment by mattkersner** [comment]
I do not believe we're having the same issue, as I am running slate 0.13

Here is a full detailed report of my issues: [#528 ](https://github.com/Shopify/slate/issues/528)

**Comment by austinhutchison** [comment]
The documents both https://www.npmjs.com/package/@shopify/slate and https://www.shopify.com/partners/blog/getting-started-with-slate-in-4-simple-steps include the instruction to run this command 
`npm install -g @shopify/slate`
and if you run that command and then run
`slate -v`
you'll get the `no such file or directory,` looking for `slate-tools/lib/commands`

**Comment by mattkersner** [comment]
@bernier That did it! Great find! Thank you

**Comment by pvidali** [comment]
For whatever reason, could not install until changed "@shopify/slate-tools": "1.0.0-beta.1" with "@shopify/slate-tools": "0.13.0", but that install failed; once changed _back_ to "@shopify/slate-tools": "1.0.0-beta.1" could install properly without conflict.

**Comment by simonmosse** [comment]
@bernier Good spot, that did the business.

**Comment by santoshkpragiti** [comment]
Thanks @bernier it really works.
