### ISSUE TITLE
"Go ahead with replace" prompt fails in CI tools

### ISSUE THREAD

**Issue by jlyon** [Shopify/slate#427]
### Problem

I am trying to build and deploy our theme with [Deploybot].  After looking through the `slate-tools` code, I was able to avoid the "Enter your email address" prompt by setting `export NODE_ENV=test`, however my build fails on the prompt, "Environment is default. Go ahead with "replace" ? [y/N]".

### Replication steps
Run:
```
export NODE_ENV=test
npm run deploy
```

Result:
Deployment halts on prompt, "Environment is default. Go ahead with "replace" ? [y/N]"

Requested change:
Deployment skips prompt step because `NODE_ENV=test`, or we add an additional `--force-yes` flag or envvar that can be set to force yes on all prompts. 

### More Information
n/a

**Comment by t-kelly** [comment]
Definitely did not think about CI when implementing this. Will take a look, thanks!

**Comment by jlyon** [comment]
Awesome, thanks!

**Comment by Jore** [comment]
We came across the same issue, I ended up using themekit to deploy the theme as a quick fix. I suggest all inquirer prompt messages have a flag to bypass for instances like this.

**Comment by t-kelly** [comment]
@Jore Yes! Good idea. One flag to rule them all 😄
