### ISSUE TITLE
Yarn start without upload

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/slate#429]
### Problem
Is there a way to have yarn start work without it uploading all the files first? At the moment if Developer A worked on the site on Monday, developer B comes along to work on it Tuesday. If developer A doesn't push all of the changes in to git and Developer B just runs yarn start it will erase everything on the dev store.

### Replication steps
- yarn start
- Asks if i want to upload, say no, shuts off.

### More Information
Currently with theme kit the normal process when moving to a project it's normal to run `theme download -e env` then `theme watch -e env`. Something that would emulate this at the very least would be nice.

**Comment by elisechant** [comment]
I don't think this is practical because of the liquid templates needing a server to compile. And shouldn't you _be_ pushing to git, is this scenario realistic?

**Comment by NathanPJF** [comment]
@dan-gamble I think there's a couple pieces to this:
* Sounds like you're suggesting a warning prompt that `yarn start` will overwrite everything? A check for overwriting your **live** theme is in place with a Y/N question.  Though it sounds like you'd want to asking this for all cases of `yarn start`.
* You mention you use the `download` command from ThemeKit. This has been talked about before and comes with some challenges.  This is a relevant thread: https://github.com/Shopify/slate/issues/403
* You also mentioned the `watch` command. Would you see a benefit in having a stand alone `watch` command?

> We do push to git but you can't push things to git like `settings_data.json`, etc.

Why is that @dan-gamble? If you're concerned about that file specifically, you can add it to the ignore files in the `.env` file.

**Comment by dan-gamble** [comment]
Hi @NathanPJF,

My fundamental issue at the moment is having `yarn start` perform the equivalent of a `theme upload` before it goes in to the equivalent `theme watch`.

I'll detail my current workflow when switching to a project:

```base
cd ~/path/to/project
git pull
theme download -e env
git add .
git commit -m 'Theme download'
theme watch -e env
# Start development
```

This ensures that the files i have locally are up to date with the files on the server. (As a side note i think it makes sense to probably gitignore pushing `settings_data.json` as a rule)

Currently with Slate i'd do:

```bash
cd ~/path/to/project
git pull
yarn start
# Start development
```

Now if for some reason the last dev to work on the site hadn't pushed to git (unfortunately this does happen) or a client has edited a template themselves, as they were told to add a snippet to `x.liquid`, then when i run `yarn start` i would've now overwritten all of these changes as it would have uploaded my current local files.

I was just curious to see if we could get a `yarn start` that doesn't upload all of my local files overwriting things that are currently on the store. Making it act a bit like `theme watch` in the it will only bundle / upload on a local file change.

**Comment by auntluke** [comment]
I believe that Shopify / slate team has a broken workflow for anyone working on teams. This has been called out several times, with the team failing to address the issue in every thread. It makes no sense to push local changes up to the Shopify store with every local change. 

https://github.com/Shopify/slate/issues/385
https://github.com/Shopify/slate/issues/373

I'd be happy to contribute to creating a better solution, but as it stands this tool is a giant pain-in-the-ass for teams larger than 1.

**Comment by dan-gamble** [comment]
Yea, this issue does look the same as #385 and #373 to be fair. 

Could be worth closing this one in favour of opening #373 back up as i think that has more details than this.

**Comment by t-kelly** [comment]
@dan-gamble Have you had a chance to look at https://github.com/Shopify/slate/issues/383? I feel like this, in addition to https://github.com/Shopify/slate/issues/403, might eliminate the pains you're having right now with accidentally.

> but as it stands this tool is a giant pain-in-the-ass for teams larger than 1

@auntluke I can totally understand [that a detailed workflow has now been documented](https://github.com/Shopify/slate/issues/251), but we've been successfully developing themes internally with team sizes ranging from 2-5 developers with these tools. Yes, [we know there are areas that can be improved](https://github.com/Shopify/slate/issues/373#issuecomment-359798775), but themes like Debut, Venture, Boundless, and Narrative are proof we have something that works.  

Saying this, I understand that the Shopify Themes team only develops for the Theme store, and doesn't need to deal with edits performed after theme installation in the code editor. Thats why we love hearing from you guys about your pains and gripes 😄 

Do you feel like https://github.com/Shopify/slate/issues/403 and https://github.com/Shopify/slate/issues/383 would would solve this issue?

**Comment by t-kelly** [comment]
Also @dan-gamble there is an undocumented `--skipFirstDeploy` flag you can pass use with `yarn start`, if that helps in the meantime?

**Comment by dan-gamble** [comment]
I'll test the flag out when i get home tonight, also #383 looks like a solution that possible work to me.

Also, please don't mistake this issue as a "Please fix your shit" kind of post, i really like what you guys have done with Slate, it's a massive step in the right direction in terms of having a modern day workflow and i appreciate all the work you guys have put in to it!

**Comment by t-kelly** [comment]
Cool - so I'll close this in preference to #403 and #383. If there is another proposed solution, please make a new issue to discuss it.
