### ISSUE TITLE
[DOCS] More detail to variant.js documentation (examples, callback data)

### ISSUE THREAD

**Issue by iamkeir** [Shopify/slate#432]
### Problem

Documentation is quite limited on the usage of `variants.js`

### Replication steps

1. Visit https://shopify.github.io/slate/js-examples/#variantjs 

### More Information

Took me several hours to pick my way through and learn how to use `variants.js` - some more detail to the documentation could save others the same task.

For example, 

**Options:**
- `$container` = the wrapping jQuery element containing selectors
- `enableHistoryState` = whether to support back button (I think?)
- `singleOptionSelector` = ID/class/data-attr for option selector/s
- `originalSelectorId` = ID/class/data-attr for variant selector
- `product` = product JSON (parsed)

**Usage:**
```
var variants = new slate.Variants({
  $container: $wrapper,
  enableHistoryState: false,
  singleOptionSelector: '[data-single-option-selector]',
  originalSelectorId: '[data-product-select]',
  product: yourProductJson
});

$wrapper.on('variantChange', function() { console.log('variantChange!'); });
$wrapper.on('variantImageChange', function() { console.log('variantImageChange!'); });
$wrapper.on('variantPriceChange', function() { console.log('variantPriceChange!'); });
```

**Gotchas**
- You must use `data-index="option{{ option.position }}"` on each option selector

Would also be useful to know **if the events return any data about the product option selection**, e.g. current selection is out-of-stock or unavailable. (`variantChange`, `variantImageChange` and `variantPriceChange`)

Thanks :)

Ref #93

**Comment by iamkeir** [comment]
Follow-up, `variantChange` returns an event object which contains `variant` and contains useful data about the currently selected variant, for example `variant.available = true/false`.

Another gotcha - if a variant combination doesn't exist, `variant` returns `null`.

**Comment by rossb** [comment]
I agree the documentation on `variant.js` and more generally the built-in Slate JavaScript functions is quite limited. It would be really useful for developers if they were more explicitly documented, even if just by inline JSDoc statements, as it would encourage developers to use and build on what comes with Slate rather than writing unnecessary parallel code.

**Comment by t-kelly** [comment]
We're currently exploring alternative solutions to `variant.js` which will eventually be published in the https://github.com/Shopify/theme-scripts repo. As a result, we have no plans on documenting `variant.js`

**Comment by karimmtarek** [comment]
Hey @t-kelly any updates on the `alternative solutions`?
