### ISSUE TITLE
Yarn create Error for 1.x version

### ISSUE THREAD

**Issue by nnennajohn** [Shopify/slate#433]
I am running into some permissions error when running "Yarn Create"

Please see screenshot

> Install shopify/slate
> run yarn create slate-theme slate-theme-name

![screen shot 2018-03-11 at 11 35 18 pm](https://user-images.githubusercontent.com/1761197/37268834-2bb0d8a2-2585-11e8-8031-8a2e8e489988.png)

**Comment by t-kelly** [comment]
Looks like an authentication problem with GitHub - please see https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey

**Comment by nnennajohn** [comment]
I don't know that it is. I've not come across this problem on any other repo, and I use a lot. Also the link you included suggested using http instead and I ran into the same problem.

**Comment by t-kelly** [comment]
I'm unable to reproduce this. Given the information I see, there is an authentication problem between your computer and Github/Starter Theme repo.

**Comment by nnennajohn** [comment]
You are right @t-kelly . Sorry. Was able to get this fixed by following your suggestion to look into my Git auth.  Got it resolved. Thank you!
