### ISSUE TITLE
Help moving scripts.js in head.

### ISSUE THREAD

**Issue by darkrubyist** [Shopify/slate#435]
Hi, 

How can I move the scripts.js in `head` instead of `body` and use defer instead when compiling?
```
<head>
  <script type="text/javascript" src="https://localhost:8080/scripts.js" defer></script>
</head>
```

Thank you!

**Comment by t-kelly** [comment]
@darkrubyist thanks for reminding me of this! Was in the back of my head by forgot to write it down. The Shopify Themes Team is also a fan of that approach. Will create an issue and get this implemented ASAP.
