### ISSUE TITLE
`slate deploy` ignores `--env` when used together with `--manual`

### ISSUE THREAD

**Issue by jbruni** [Shopify/slate#441]
### Problem

- I have number of environments in my `config.yml`.
- If I run `slate deploy --env myenv1`, it correctly uses "myenv1" as environment.
- If I run `slate deploy --env myenv1 --manual`, it incorrectly uses "development" as environment.

### Replication steps

It is easier to replicate if your `config.yml` has several environments, but none called "development". Just run `slate deploy --env whatever --manual` and you will see that `--env` is ignored... it will try to use "development" and it will fail.

### More Information

I expected it to open the store admin as configured in the specified environment at `config.yml`.

I have tried variations (the shortcuts `-e`, `-m`, in different order), result is always the same.

Then, I have done some basic debugging (some `console.log` lines at `slate-tools/lib/tasks/deploy-utils.js`) and was able to verify that `--env` is being ignored when `--manual` is used.

**Comment by t-kelly** [comment]
Closing this as it is not a critical bug and our priority is now Slate v1.

To get around this, you can use the `slate zip` command and open the admin manually.
