### ISSUE TITLE
adding linked options and shipping calculator code to Slate fails

### ISSUE THREAD

**Issue by dirad** [Shopify/slate#442]
### Problem

*Javascript errors when trying to add shipping calculator or linked options code*

### Replication steps

Following the tutorials in https://help.shopify.com/themes/customization/cart/add-shipping-calculator
and https://help.shopify.com/themes/customization/products/variants/link-product-options-in-menus

Shipping-calculator
 **vendors.js** 
required vendor/shipping-cart.js from https://gist.githubusercontent.com/sadiesaurus/23f14eb5c3e2f0f8ae2828a1f6e2f4c8/raw/5de3c11c46265d7a45f93e2a7e5b3f3094feee05/shipping-calculator 

**cart.liquid**
```
<script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.10/handlebars.min.js"></script>
<script src="/services/javascripts/countries.js"></script>
Shopify.Cart.ShippingCalculator.show( { .... 
```

**while viewing cart page**
Shipping calculator shows up and countries show up in the dropdown, but submit button does not work
I get the following error:
```
Uncaught TypeError: Countries.updateProvinceLabel is not a function
    at _init (vendor.js?17070549174101670235:43)
``` 

Linked Options
Using the code from https://gist.github.com/1083007 , and including it in either product.liquid or theme.liquid , the following error shows up:
```
Uncaught TypeError: Shopify.uniq is not a function
    at Object.Shopify.linkOptionSelectors (ede?variant=423003413443:732
```

### More Information

Others have encountered this:
- https://ecommerce.shopify.com/c/ecommerce-design/t/adding-shipping-calculator-to-slate-497586#comment-503326
- https://help.shopify.com/themes/customization/products/variants/link-product-options-in-menus

**Comment by t-kelly** [comment]
This is a theme development problem. Please keep issues on the Slate repo specific to Slate bugs and feature requests.

**Comment by dirad** [comment]
@t-kelly thanks. Maybe a suggestion on where to go with this, being as all this code comes from Shopify ..

**Comment by t-kelly** [comment]
The top of the tutorial you linked to has a that + a disclaimer 😉:
```
This is an advanced tutorial and is not supported by Shopify. Knowledge of web design languages such as HTML, CSS, Javascript and Liquid is required. We suggest hiring a Shopify Expert if you are not comfortable proceeding with the following tutorial.
```

**Comment by dirad** [comment]
@t-kelly  yes, not so very helpful, thank you.
