### ISSUE TITLE
Node error while checking Slate version

### ISSUE THREAD

**Issue by et1421** [Shopify/slate#443]
### Problem

After installing version 1.0.0-alpha.15, I get an error while typing _slate_ in the command line (before installing a new theme) : 
`/usr/local/bin/slate: line 1: use strict: command not found`

Node version : v8.10.0

### More Information

I don't no much about bash, but it seem that by adding `#!/usr/bin/env node` to the file _index.js_ inside _/usr/local/bin/slate_, the error goes away as stated  [here :](https://stackoverflow.com/questions/34353512/node-npm-package-throw-use-strict-command-not-found-after-publish-and-install-g)

**Comment by t-kelly** [comment]
@et1421 Slate v1 does not include a `slate` command. Please read the [Getting Started Guide](https://github.com/Shopify/slate/tree/1.x#getting-started). Ask any other questions you have here and maybe open a PR to change anything thats not clear to you? Thanks!

**Comment by et1421** [comment]
@t-kelly Thanks, your absolutely right, I mixed up the 2 starters. I'm not sure if I should continue asking here : 
When doing _yarn start_ does the project should start in local mode ? The build start successfully, but I think it opens a new window linked to the production url : _shop-name.myshopify.com_ and the CSS changes are not reflected. Is it suppose to open a localhost:8080 url ? Thanks

**Comment by t-kelly** [comment]
@et1421 In [Step 3 of the Getting Started](https://github.com/Shopify/slate/tree/1.x#3-start-developing):

This will boot up a local express server and serve most of your assets from `https://localhost:8080`.

> ⓘ Because we are running localhost on `https` you will need to visit this URL at least once and tell your browser to trust it, otherwise local assets will be blocked. Alternatively, you could [create a trusted SSL certificate for localhost](#how-to-create-a-trusted-local-ssl-certificate).

In other words, you view your store from our servers but all files (other than Liquid) are served from `https://localhost:8080`.

**Comment by et1421** [comment]
Thanks for the clarification. I suggest you update the documentation. At the moment, it is a bit ambiguous for the beginners in Shopify.

**Comment by t-kelly** [comment]
@et1421 Care to open a PR with proposed edits? Could always use some help 😄
