### ISSUE TITLE
yarn create slate-theme command should work without an SSH key to Github

### ISSUE THREAD

**Issue by et1421** [Shopify/slate#444]
### Problem
In version 1.0.0-alpha.15,

_yarn create slate-theme my-new-theme_ command does not work if you don't have an SSH key linked to GitHub on your computer.

Many of my colleagues don't even have a GitHub account. I think they should be able to create a theme anyhow.

### Error from the command line

```
There was an error while cloning the git repo:

Error: Command failed: git clone git@github.com:shopify/starter-theme.git /Applications/MAMP/htdocs/slate-1.0/<folder-name> --single-branch
Cloning into '/Applications/MAMP/htdocs/slate-1.0/<folder-name>'...
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by t-kelly** [comment]
Agreed! I will add `https` cloning.
