### ISSUE TITLE
Slate and multiple variant images

### ISSUE THREAD

**Issue by justinma** [Shopify/slate#451]
### Problem

Hello,

I'm just trying to get this to work:
https://gist.github.com/carolineschnapp/d3c1af82b915e9cae82929e6486f22fe

Later, I will want swatches as well but this will do for now. 

Is it because I don't have option_selection.js in slate that this won't fire correctly? 
Only the featured image for each variant will change, but not the images that have matching 'alt' tags.

**Comment by NathanPJF** [comment]
Hi, @justinma 

We don't provide help on individual projects, so I'll be closing the issue.  We are keeping issues in this repo scoped to the Slate tool.

Best of luck!

**Comment by justinma** [comment]
Woops. That makes sense. Sorry!
