### ISSUE TITLE
@shopify/slate-tools@1.0.0-alpha.25 file path change breaks slate-tools start

### ISSUE THREAD

**Issue by aschmoe** [Shopify/slate#457]
### Problem

`: fs.readFileSync(path.join(__dirname, '../ssl/server.pem'));` fails since file paths have changed

`Error: ENOENT: no such file or directory, open '{fullpath}/node_modules/@shopify/slate-tools/cli/ssl/server.pem'`

### Replication steps

run `slate-tools start` in theme with latest

### More Information

should now be `'../../ssl/server.pem`

**Comment by t-kelly** [comment]
Ah -- I have a [trusted local SSL certificate](https://github.com/Shopify/slate/tree/1.x#how-to-create-a-trusted-local-ssl-certificate) and didn't hit this condition. Thanks for reporting!
