### ISSUE TITLE
Since alpha.25 user webpack is no longer merged

### ISSUE THREAD

**Issue by aschmoe** [Shopify/slate#459]
### Problem

Looks like `slate-tools/slate-tools.config.js` will always return default `dev` and `prod`. 

In `slate-config/index.js` the call to `getSlateConfig()` does return values, but unfortunately somehow gets lost in `_generateConfig` and by the time `item.id === 'extends'` is going through, `overrides` is undefined.

### Replication steps

Have theme with `slate.config.js` that should break webpack

```
module.exports = {
  extends: {
    dev: { 
      entry: { dont: 'exist' }, 
      output: {
        filename: 'differentfile.js',
      } 
    },
    prod: { 
      entry: { dont: 'exist' },
      output: {
        filename: 'differentfile1.js',
      } 
    },
  },
};
```

### More Information

Definitely works as of alpha.24

Thanks,
Alex

**Comment by t-kelly** [comment]
@aschmoe configs are now namespaced under their respective package, so in your case it would be:
```
module.exports = {
  slateTools: {
    extends: {
      dev: { 
        entry: { dont: 'exist' }, 
        output: {
          filename: 'differentfile.js',
        } 
      },
      prod: { 
        entry: { dont: 'exist' },
        output: {
          filename: 'differentfile1.js',
        } 
      },
    },
  },
};
```
