### ISSUE TITLE
Installation via npm fails for 1.x branch

### ISSUE THREAD

**Issue by Eleeleth** [Shopify/slate#469]
### Problem

Trying to install the 1.x branch or the latest 1.x tag fails due to a missing `version` property in the `package.json` file. 

### Replication steps

First, to make sure it's not a versioning issue on my end, the output of `npm -v` and `node -v` are as follows:

```
$ node -v
v8.11.1
$ npm -v
v5.8.0
```

Since ideally I'd like to try installing the lastest 1.x version, I attempted the install via the following command:

`npm i -g https://github.com/Shopify/slate/archive/1.x.tar.gz`

which produces the following:

`npm ERR! Can't install https://github.com/Shopify/slate/archive/1.x.tar.gz: Missing package version`

The same issue is present on the latest 1.x tag I can see, which is v1.0.0-alpha.26.

**Comment by t-kelly** [comment]
This is not how you install Slate, nor how to start a new Slate project. Please read the [Getting Started ](https://github.com/Shopify/slate/tree/1.x#getting-started) section of the 1.x README.
