### ISSUE TITLE
Alpha tag on npm is out of date.

### ISSUE THREAD

**Issue by Eleeleth** [Shopify/slate#470]
### Problem

Installing the alpha tag on npm installs a several months old version of the 1.x branch, instead of the expected latest tag based on that branch.

### Replication steps

Running `npm install -g @shopify/slate@alpha` will install `1.0.0-alpha.1` instead of the expected `1.0.0-alpha.26`, based on the tags on the repo.

**Comment by t-kelly** [comment]
The [`@shopify/slate` ](https://www.npmjs.com/package/@shopify/slate) package is not part of Slate v1.0. We have moved away from a global CLI, please make sure you have read the 1.x docs, in particular the [Getting Started section](https://github.com/Shopify/slate/tree/1.x#getting-started).

The alpha version published to `@shopify/slate` were made by mistake. I have removed the tags and deprecated the mistake versions. Sorry for the confusion! Thanks for letting me know 😄

**Comment by Eleeleth** [comment]
I see, sorry for the confusion! 👍
