### ISSUE TITLE
Use system's environment variables in .env file

### ISSUE THREAD

**Issue by jmcmullen** [Shopify/slate#475]
### Problem

I am wanting to use CircleCI to deploy my Slate 1.x theme to multiple regions. I don't want to store my .env file in my repo, is there a way I can pass through environment variables from the local system instead?

**Comment by t-kelly** [comment]
@jmcmullen totally! The key:values declared in the `.env` file are simply declaring environment variables. I'm not sure what CI you're using, but it's a fairly common feature in most of them to set environment variables.

**Comment by jmcmullen** [comment]
Oh awesome, that makes a lot more sense. Thanks!
