### ISSUE TITLE
Variant change event seems out-of-sync with variant dropdown change event

### ISSUE THREAD

**Issue by iamkeir** [Shopify/slate#481]
### Problem

Not sure the source of this issue but when, attaching behaviour to the `variantChange` event, it seems to fire at a different time to when the variant dropdown updates, so that the selected variant is often returned as the one _prior_ to the change.

### Replication steps

I've uploaded a fresh install of Slate to a playground URL and added a `console.log` to the `product.js` `updateAddToCartState` function to demonstrate:

Theme preview: https://iamkeir-playground.myshopify.com/?preview_theme_id=11438751808
Product page: https://iamkeir-playground.myshopify.com/products/product-13

I am logging the following to console:
`console.log(variant.title, $('[data-product-select]').find(':selected').text());`

In console, you will see that the `variant.title` and selected value differ - one is the new variant, the other is the former variant.

Video: http://jmp.sh/WVYEb31

This issue is also present when using your own instance of `new slate.Variants`.

### More Information

I am not sure if this is a Slate issue or just order-of-JS execution. I encountered this issue when trying to attach separate behaviours to the change of options - I needed to know which option had been changed (color or size) but the `variant` object does not seem to include data that would indicate this. Instead, I checked for which option had been changed and the new value within the `variantChange` event, only to find it was reporting differing selected variants as above.

I know you are revisiting `variants.js` in the new version of Slate, but wanted to flag this and see your take on it.

**Comment by NathanPJF** [comment]
Hey @iamkeir, thanks for providing a detailed write-up 😄 

> I am not sure if this is a Slate issue or just order-of-JS execution.

It's essentially the "order-of-JS execution".  You're listening for the `variantChange` event - when that fires, updating the master select (`select[id="name"]`) is one function of a handful.

https://github.com/Shopify/slate/blob/77a52ee5f0cb41fd97a946b112a3ecd11d668fba/packages/slate-theme/src/scripts/slate/variants.js#L110

So essentially, in the `console.log` you wrote, you are looking at `$('[data-product-select]')` before it can be updated.

Firing `variantChange` before the master select is updated it intended behaviour (for this version of variant JS). We want to signal that someone changed the product options and know if their choices resulted in an actual new variant.  If it didn't, we pass that information along. If it did, we update the master select with the appropriate variant.

>  I needed to know which option had been changed (color or size) but the variant object does not seem to include data

It does 😃  You can write some JS to check the values of `variant`.  This requires a valid variant being chosen, however.

!()[http://take.ms/XMoos]

**Comment by NathanPJF** [comment]
> I needed to know which option had been changed (color or size) but the variant object does not seem to include data

Though it may be useful to have what the person **tried** to choose to come back in the `variantChange` response.  

I'll add a label to mark this idea.

**Comment by iamkeir** [comment]
Hey @NathanPJF thanks for your detailed response :)

> Firing variantChange before the master select is updated it intended behaviour (for this version of variant JS). We want to signal that someone changed the product options and know if their choices resulted in an actual new variant. If it didn't, we pass that information along. If it did, we update the master select with the appropriate variant.

That makes a lot of sense - I understand the rationale, thanks.

> It does 😃 You can write some JS to check the values of variant. This requires a valid variant being chosen, however.

Sorry, what I meant was I need to know if it was a size or color _option_ that had been changed, rather than the outcome value of that option. 

I guess I could compare option1/option2/option3 to previous selected value, and then try and map it retrospectively to find out which has changed but feels like sledgehammer to crack a nut.

More useful would be if the element that fired `variantChange` was captured in `variant` data, perhaps? That way I could attach a `data-attr` to the 'trigger', and identify that within `variantChange`.

> Though it may be useful to have what the person tried to choose to come back in the variantChange response.

Yep, I'd agree with that :)

Thanks again.
