### ISSUE TITLE
Edit page challenge

### ISSUE THREAD

**Issue by InfinityWebMe** [Shopify/slate#485]
Hello,

I use slate to create a custom theme but i don't found, how i can edit the challenge page when i submit a contact form ( with google recaptcha ) ? 

Thanks a lot =)

**Comment by ConduciveMammal** [comment]
You can't that's a Shopify embedded page that isn't hosted on the store. The best you can do is inspect the elements on that page and try and override their CSS.

**Comment by t-kelly** [comment]
@ConduciveMammal, correct! Thanks for helping respond to issues!

**Comment by t-kelly** [comment]
Also, this is a theme development question. Please keep Slate issues for Slate feature requests and bug reports only.
