### ISSUE TITLE
Can't install slate 1.x

### ISSUE THREAD

**Issue by vfonic** [Shopify/slate#486]
### Problem

I'm trying to install slate 1.x using this command: `https://github.com/Shopify/slate/archive/190e6ba430c657283ee4d83d1793db36a819f430.tar.gz` (the hash is the currently last 1.x branch commit hash)

The error I'm getting (with both npm and yarn) is invalid package version. I checked `package.json` and don't see the package version. How can I install the package v1.x globally otherwise?

**Comment by lux-capacitor** [comment]
For any google searchers that landed here, I've outlined the basic flow of the new slate-tools library below to better help new users understand the new process. (slate-tools = new namespace)

The getting started guide link is broken above, but the starter theme link is what you want really ( re : https://github.com/Shopify/starter-theme )

**STEPS :** 
1. No longer globally installed, clone that project linked above and run :
`npm i`

2. To start the project, you'll notice in the package.json that the npm start script is mapped to :
`slate-tools start`

3. It'll ask about giving up your email to feed their analytics and then start right up. Didn't see a way to opt out..

PS : There isn't a `slate-tools --help` functionality to list all functions, but you can reverse engineer it from the library itself by digging into its code. The primary functions are also wired up in the scripts block of the package.json file too. 

Hope that helps!
