### ISSUE TITLE
Error: Can't resolve 'concat-style-loader'

### ISSUE THREAD

**Issue by jonathanmoore** [Shopify/slate#490]
### Problem

Running any of the build commands using the current version of starter-theme results in an error while trying to process `styles/theme.scss.liquid` using the new `concat-style-loader` package.

`Module not found: Error: Can't resolve 'concat-style-loader'`

![image](https://user-images.githubusercontent.com/454095/38900065-f5d93238-424e-11e8-908d-bc103a6ea1a3.png)

### More Information

Commenting out the *.scss.liquid import from `assets/theme.js` does allow the theme to build, however it seems like PR #488 is missing the inclusion of the new `concat-style-loader` in the package files.

**Comment by jonathanmoore** [comment]
For now manually adding `concat-style-loader` does the trick for testing.

```
$ yarn add concat-style-loader
```

**Comment by t-kelly** [comment]
Thanks @jonathanmoore!
