### ISSUE TITLE
ReferenceError: path is not defined when running yarn start

### ISSUE THREAD

**Issue by josephchan91** [Shopify/slate#492]
### Problem

/node_modules/@shopify/slate-tools/tools/dev-server/ssl/index.js:6
    : readFileSync(path.join(__dirname, './server.pem'));
ReferenceError: path is not defined

### Replication steps

1. Follow setup instructions
2. Run 'yarn start'
3. Command fails

**Comment by phlfvry** [comment]
I got the same issue, did you install with `yarn create slate-theme` or `create-slate-theme` .. the latter seems to trigger this issue.

Once you get past this though you're going to encounter a WebPack issue. this release is a mess.

**Comment by josephchan91** [comment]
Yup, now I'm getting the webpack module build failures.

**Comment by t-kelly** [comment]
Thanks for the bug report @josephchan91!
