### ISSUE TITLE
Browsersync breaks on custom domain with password enabled

### ISSUE THREAD

**Issue by macdonaldr93** [Shopify/slate#5]
When running `slate start` or `slate watch` on a Shopify store that has a custom domain with force redirect and password protection enabled, the browser will be redirect out of the localhost proxy and therefore breaking Browsersync.
## Reproduce
- Navigate to Shopify store with custom domain enabled
- Make sure all traffic is being forced to the custom domain
- Password protect the store
- Run `slate start` or `slate watch` to the given store
- You should be redirected out of the localhost proxy and to the custom domain /password

Video: https://screenshot.click/23-59-xrh6y-33nuk.mp4

**Comment by baberuth22** [comment]
Can you be more specific?  

> Closed with _fd URL param

What does _fd?   Is it documented?

I am trying to view a site in development that is password protected.   How do I view it with slate start at localhost:3000?   All I see is the password protected page even though I am logged into the admin.

**Comment by martylouis** [comment]
@baberuth22 Are you using a custom domain? I had a similar issue because it was trying to redirect to my original 'myshopify' domain. Once I updated the store domain it worked, even with password protection.

```yml
# config.yml

development:
    password: .....
    theme_id: "...."
    store: shop.mydomain.com # was demoshop.myshopify.com

```

**Comment by macdonaldr93** [comment]
@baberuth22 `_fd` was implemented internally on slate tools. It fixed a slightly different issue than what you're saying. 

Would you be able to create a separate and describe your problem? Hopefully we can help you debug from there.
