### ISSUE TITLE
Commented @import statements in .scss.liquid files are still being registered and can cause Webpack build to crash

### ISSUE THREAD

**Issue by phlfvry** [Shopify/slate#502]
### Problem

Webpack fails to build `theme.scss.liquid` and `theme.js`

`ERROR in ./assets/styles/theme.scss.liquid
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'length' of undefined`

`ERROR in ./assets/styles/theme.scss.liquid
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'length' of undefined`

### Replication steps

Simply running `yarn build` will cause this to happen.

### More Information

The last call in the stack trace is `getImportStatements` from `concat-style-loader/concat.js:54:45` in both instances.

Also, when first running the build, this is output into the console:
`clean-webpack-plugin: /path/to/dist has been removed.`
`(node:35452) DeprecationWarning: Tapable.plugin is deprecated. Use new API on ``.hooks`` instead`
`(node:35452) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)`
.
.
.
`(node:35452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)`
`(node:35452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
`Node#moveTo was deprecated. Use Container#append.`
`Version: webpack 4.6.0`

**UPDATE: Commenting out `import '../../styles/theme.scss.liquid';` in theme.js allows Webpack to build.**

**Comment by t-kelly** [comment]
Hey @phlfvry! You nailed it on the cause:

> Commenting out import '../../styles/theme.scss.liquid'; in theme.js allows Webpack to build.

I have since[ removed this comment from Starter Theme](https://github.com/Shopify/starter-theme/commit/c5afdf5f2832a436e47387e505a897f0143c8fa5). In the mean time this will let things run normally.

I'm going to keep this issue to track the progress on fixing the bug of reading commented `@import` statements. I have some logic in `concat-style-loader` to avoid this but clearly its not working as intended!

**Comment by t-kelly** [comment]
Fixed! Will ship these changes in the next release.
