### ISSUE TITLE
Can’t install slate 1.x Alpha – “No Such File or Directory” Error

### ISSUE THREAD

**Issue by nathanaelphilip** [Shopify/slate#505]
### Problem
I can’t get the `yarn create slate-theme slate` command to work

### Replication steps
`yarn create slate-theme slate`

### More Information
node: 9.9.0
npm: 5.8.0

I am use `asdf` as my package manager. Here’s the full error:

```
success Installed "create-slate-theme@1.0.0-alpha.28" with binaries:
      - create-slate-theme
/bin/sh: /Users/nathanaelmoody/.asdf/installs/nodejs/9.9.0/.npm/bin/create-slate-theme: No such file or directory
error Command failed.
Exit code: 127
Command: /Users/nathanaelmoody/.asdf/installs/nodejs/9.9.0/.npm/bin/create-slate-theme
Arguments: slate
Directory: /Volumes/Studio/Tools/shopify-test
Output:
```

Thanks!

**Comment by t-kelly** [comment]
Hey @nathanaelphilip -- can't say I've tested Slate with asdf. I can't reproduce this on my end when using NVM.

**Comment by nathanaelphilip** [comment]
@t-kelly thanks for your response – do I need to do anything else before running `yarn create` ? or does that pull down everything I need?

**Comment by t-kelly** [comment]
You shouldn't need to do anything - [here a description of the command](https://yarnpkg.com/lang/en/docs/cli/create/)

**Comment by nathanaelphilip** [comment]
I can install with `npx` but still having trouble with `yarn` – feel free to close if you don’t want to worry about it!
