### ISSUE TITLE
node_modules directory replicated in every theme

### ISSUE THREAD

**Issue by LukeStratton** [Shopify/slate#507]
Unless I'm misunderstanding the Slate application, it seems incredibly wasteful/untidy to replicate the `node_modules` folder in every new slate theme created.

My main issue with this is that it generates some 10,000 odd files, which wreaks havoc with cloud sync services like Dropbox and OneDrive and causes the sync utilities to either crash or take hours to perform a sync.

It would be a useful feature if the location of the `node_modules` folder could be redirected and shared amongst the projects, or at least the ability to move this folder to another location on the local machine on a per-theme basis.

Forgive me if I'm misunderstanding this, or this isn't the right place to discuss such issues. Any suggestions to get around this issue would be appreciated.

**Comment by NathanPJF** [comment]
@LukeStratton Each project having its own `node_modules` is intended. 

I understand what you mean about it being "wasteful" to sync those files to Dropbox.  That's taken care of for projects that are using git for version control, we mark that folder in the `.gitignore` file: https://github.com/Shopify/slate/blob/41b3269ff7164e9193aeb758a10554527dbb318f/packages/slate-theme/.gitignore-sample#L8-L14

What you're describing about Dropbox and `node_modules` is an issue with using Dropbox.  I recommend you ignore the folder using selective sync. I found an article about another developer facing the same issue you're describing: https://www.justinsilver.com/technology/osx/ignore-node_modules-dropbox/
