### ISSUE TITLE
How to add to promptSettings:false to slate.config.js

### ISSUE THREAD

**Issue by clarkewd** [Shopify/slate#508]
### Problem

Unable to disable the prompt to skip uploading `settings_data.json`

### Replication steps

Run `yarn start`

### More Information

Message says:

>    It looks like you are about to upload the settings_data.json file.
>    This can reset any theme setting customizations you have done in the
>    Theme Editor. To always ignore uploading settings_data.json, add the
>    following to your .env file:
> 

      SLATE_IGNORE_FILES=/config/settings_data.json

   Or to disable this prompt, add the following to your slate.config.js file:

      'slateTools': { promptSettings: false }

The default `slate.config.js` looks like this:

    /* eslint-disable no-undef */

    const path = require('path');

    const alias = {
      jquery: path.resolve('./node_modules/jquery'),
      'lodash-es': path.resolve('./node_modules/lodash-es'),
    };

    module.exports = {
      extends: {
        dev: {resolve: {alias}},
        prod: {resolve: {alias}},
      },
    };

Where / how do I add `promptSettings: false` so that it takes effect? I've tried inside the `module.exports` and also inside the `extends` / `dev` blocks without success. Can you provide an example?

**Comment by chrisberthe** [comment]
Hi @clarkewd, this will eventually be documented as it's not the most obvious thing right now, but you should be able to open up your `slate.config.js` and add the following:

```js
module.exports = {
  slateTools: {
    promptSettings: false,
  },
};
```

It seems you may have tried that but it works on my side. Perhaps it's the addition of the quotes surrounding the property? Please try and let us know.

**Comment by niedfelj** [comment]
I opened this issue with the default slate starter-theme repo also, as they don't nest under slateTools and that is required if you are using the new webpack/slate-tools 1.x

https://github.com/Shopify/starter-theme/issues/48
