### ISSUE TITLE
Slate watch command Invalid theme id

### ISSUE THREAD

**Issue by itzm3** [Shopify/slate#514]
### Problem

[22:23:33] Starting 'watch'...
[22:23:33] Starting 'validate:id'...
[22:23:33] Finished 'watch' after 7.92 ms
[22:23:33] Invalid theme id for development: undefined `theme_id` must be an int
eger or "live".

### Replication steps

slate watch

### More Information

config.yml

development:
  password:[password]
  theme_id:[12345]
  store:[storename].myshopify.com
  #ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings

**Comment by chrisberthe** [comment]
Hi @itzm3, can you provide a few more details?

I assume this doesn't work when running `slate start` as well. The error output is telling you what's wrong. If you're actually using the format you posted, you'll want to remove the brackets from the `password`, `theme_id` and `store` values, e.g.:

```
password:somelonghash
theme_id: 1234567
store: myshop.myshopify.com
```
