### ISSUE TITLE
Yarn Start command does not boot up local server

### ISSUE THREAD

**Issue by hanihsdd** [Shopify/slate#518]
### Problem

`yarn start` does not boot up a local Express server

### Replication steps

I have just started using Slate v1.0 and followed the getting started guide. 

I have input the correct details of my development store in the .env file.

When I run `yarn start`, the development store (*.myshopify.com) opens in my browser. However, the localhost server is not opened.

I attempt to view `localhost:8080` but am greeted with a blank browser page titled 'Error' with the following message:

> Cannot GET /

A screenshot has been attached below. 

![localhost8080_error](https://user-images.githubusercontent.com/11101576/39483962-099b1994-4d6c-11e8-90af-b29198145e90.png)

When I make changes to files they are successfully compiled. However, I have to reload the development store to see the changes.

### More Information

From what I understand, this could be a routing issue. However, I'm very unfamiliar with this so any help on how to get this sorted would be greatly appreciated.

Thanks for all the great work on the Slate project btw!

**Comment by t-kelly** [comment]
Hey @hanihsdd -- what you're actually seeing IS the local dev server, as sad as it may look from this view 😅. It's not meant to be accessed directly through the browser as it's sole purpose is to serve up assets and not as an actual local web server.

When you run `yarn start`, a browser window should open to your `myshopify.com` URL, and if you check in the page source, you should see that assets should be fetched from `localhost`.

We're working on docs to make this clearer, but for now make sure you check out [The Getting Started](https://github.com/Shopify/slate/wiki/Getting-Started) guide to make sure you didn't miss anything.

Also,  I'm going to create a followup issue to this to address the screenshot you posted above. I think we can return something a little more helpful to users then `Cannot GET /` 😅
