### ISSUE TITLE
product.js not being injected?

### ISSUE THREAD

**Issue by kpow** [Shopify/slate#523]
### Problem
product.js not being injected?
Product Variants Updates not working.

When you scaffold slate for a new theme using the create-theme command using the starter-theme.  the code from product.js is not executing.  So this means you cannot select a variant to add to cart and the price update isn't not showing

### Replication steps
1. yarn create slate-theme my-new-theme
2. Create private app get api password
3. Duplicate theme and get ID
4. build .env
5. yarn deploy
6. Populate store with shopify developer tools.
7. visit page and try to invoke a variant.

The variant dropdown is present.

https://ellwooodz.myshopify.com/products/adaptive-awesome-soft-pizza?variant=7842794995763

### More Information

I'm kind of a shopify noob. and if I'm just missing something (to get section level .js to work), if you could point me in the right direction that would rock.

**Comment by t-kelly** [comment]
@kpow your timing is impeccable. It's going to be fixed in https://github.com/Shopify/starter-theme/pull/54

Once that is merged, try creating a new project and everything should work.
