### ISSUE TITLE
Theme scaffold - Dynamic sections link is broken

### ISSUE THREAD

**Issue by sudipk3** [Shopify/slate#525]
### Problem
Dynamic sections "sections development documentation" link is broken

### Replication steps
In [Theme scaffold](http://shopify.github.io/slate/theme-scaffold/) page, the **Dynamic sections**

> sections development documentation

link is broken.

**Comment by hcmlopes** [comment]
not sure if it helps but this is the correct url:

`https://help.shopify.com/themes/development/sections`

**Comment by t-kelly** [comment]
Fixed in https://github.com/Shopify/slate/commit/4084063e1c7b1062ec44ac9b80d3c947a1bf8f50
