### ISSUE TITLE
Uncaught TypeError: slate.Sections is not a constructor

### ISSUE THREAD

**Issue by ClearMarble** [Shopify/slate#526]
I'm seeing this error in the Console on every page load coming from theme.js: `Uncaught TypeError: slate.Sections is not a constructor`

I've also just tried using some slate functions like the preloader (i.e. `slate.Image.preload(imgList);`), and I get: `Uncaught TypeError: Cannot read property 'preload' of undefined`

Looks like slate itself is not initializing for me for whatever reason. Any suggestion as to how I might troubleshoot this? Sorry if it's obvious, I'm new to slate.

**Comment by t-kelly** [comment]
Hey @ClearMarble -- going to need more info to help you. Please read the issue template when creating a new issue for details of what you should include.

**Comment by t-kelly** [comment]
Woops! My bad - I thought our issue template had requirements for Node version, operating system, etc. 

Can you please tell us a bit about the system your running on, as well as the version of Slate you are using?

**Comment by t-kelly** [comment]
Also, if you're new to Slate, I would recommend using the newest version, Slate v1. Check out the [Getting Started Docs](https://github.com/Shopify/slate/wiki/Getting-Started).

**Comment by ClearMarble** [comment]
Apologies for not including the necessary info. I'm on Windows 10, Node 8.10.0,  NPM 5.6.0, Slate 0.13.0.

I've used the Getting Started guide and other documentation on https://shopify.github.io/slate/...not totally brand new to Slate as I'd at least set this up before that documentation referred people to the Wiki for the latest version.

Everything has been working pretty well, I've mostly just been running `slate start` after getting the base theme setup and going from there. I've just been noticing this in the console and as I'm starting to get into some more heavy JS implementation now I thought I should troubleshoot it if possible.

I use NVM so can easily switch Node versions if you think that'd help, but I've not getting any errors on the command line or anything.

**Comment by t-kelly** [comment]
As you mentioned, it sounds like the scripts you're trying to reference are not being initialized before referencing the variables they assign. Check your theme for script loading order. Pay attention to any `defer` and `async` tags as these would affect the order in which your scripts are executed.

Going to close this since it doesn't sound like a problem with Slate, rather a theme development problem about script execution order.
