### ISSUE TITLE
yarn deploy not updating CSS to Shopify server

### ISSUE THREAD

**Issue by et1421** [Shopify/slate#530]
### Problem

CSS deployed to the server does not correspond to local SCSS.

### Replication steps

I have tried to deploy multiple times, empty the cache from the browser, and the local change is still absent from the server.

### More Information

In local I have this code : 
`.header {
  background: $white;
  padding-top: 20px;
  position: relative;
  width: 100%;
  z-index: 2;
}`

But if I inspect the layout.theme.css file, I have : 
`.header {
    background: #fff;
    padding-top: 20px;
    position: relative;
    width: 100%;
    z-index: 1
}`

The z-index is wrong.
Therefore, my project manager cannot see my bug fix.

**Comment by et1421** [comment]
After some check, I'd say the _build_ task is the problem. If I look at the _layout.theme.css_ file inside the local _dist_ folder, the z-index is also wrong. And if I run the _yarn start_ task, I can see the correct CSS in the browser.

**Comment by et1421** [comment]
I realized while testing that this is CSSNano who changes the z-index value.

Maybe z-index optimisation of [CSSNano](http://cssnano.co/optimisations/zindex/) should be at false by default ?

**Comment by t-kelly** [comment]
Interesting @et1421. I was totally unaware of this optimization. Could you create a new issue with specific details of the CSSNano z-index problem and close this one?
