### ISSUE TITLE
Local CSS not deploying to Shopify

### ISSUE THREAD

**Issue by Derplicity** [Shopify/slate#533]
### Problem

The CSS from the local environment is not deploying to Shopify upon `yarn start` and `yarn watch`.
(`yarn deploy` works perfectly and `yarn zip` and directly uploading it to Shopify works as well, so I would assume it is an issue with `slate-tools start`)

### Replication steps

- npm i @shopify/slate-tools
- yarn create slate-theme my-new-theme
- Set up .env file
- cd /my-new-theme
- Yarn Start or Watch (tried both)
- Add classes to `theme.liquid`
- Customize classes in `layout.scss` which is imported into `theme.scss`
- Save
- Reload .myshopify.com

(attempted fix)
- Ctrl C
- Yarn Start or Watch
(and)
- Reinstall slate tools
- Recreate slate-theme

### More Information

My local environment
<img width="881" alt="screen shot 2018-05-04 at 8 38 47 pm" src="https://user-images.githubusercontent.com/24903093/39659019-9f71723e-4fdc-11e8-9e60-db27593248d8.png">
<img width="365" alt="screen shot 2018-05-04 at 8 39 27 pm" src="https://user-images.githubusercontent.com/24903093/39659032-b690c0f0-4fdc-11e8-9b98-4692a2e64f5b.png">

Shopify environment
<img width="1056" alt="screen shot 2018-05-04 at 8 37 36 pm" src="https://user-images.githubusercontent.com/24903093/39659041-ef326fda-4fdc-11e8-8a94-3d0daa630dab.png">
<img width="272" alt="screen shot 2018-05-04 at 8 38 23 pm" src="https://user-images.githubusercontent.com/24903093/39659043-f33eba66-4fdc-11e8-94b6-393384bcf6df.png">

The HTML is updated, however the CSS is not. And it doesn't seem that the `theme.scss` file is even deployed, as the only SCSS file that is deployed is `theme.scss.liquid`.
<img width="621" alt="screen shot 2018-05-04 at 8 52 54 pm" src="https://user-images.githubusercontent.com/24903093/39659062-4d4a829c-4fdd-11e8-8358-8d0a2a11cf5c.png">

**Comment by t-kelly** [comment]
Hey @Derplicity -- styles are included and applied to the page via the main JS file, which is served from localhost, in the development build pipelines (watch and start):

![image](https://user-images.githubusercontent.com/4837696/39677155-50756bae-5144-11e8-9ccd-09951953cac3.png)

This is to take advantage of [Hot Module Reloading](https://webpack.js.org/concepts/hot-module-replacement/). You should not expect to see any new CSS files uploaded for these commands, and these commands will not erase the existing files. 

Does that make sense?

**Comment by Derplicity** [comment]
Seeing that made me think that perhaps it was the https:localhost, so I created an SSL for localhost and everything is working now! Gotta love it... Thanks @t-kelly

**Comment by t-kelly** [comment]
@Derplicity great! Did you follow the guide to create an SSL from the wiki? Everything worked?

Alternatively, you can visit https://localhost:8080 and manual tell your browser to trust it. But the SSL certificate is a much more permanent solution.
