### ISSUE TITLE
slate.config.js is silently ignored when there are errors

### ISSUE THREAD

**Issue by milesw** [Shopify/slate#539]
### Problem

Errors in slate.config.js are not reported anywhere. When there is a typo or syntax error, Slate carries on and the config from that file is ignored, leaving you with the defaults.

### Replication steps

Add this to the top of slate.config.js and `yarn run watch`:

```javascript 
/* eslint-disable no-undef */

import 'nothing';
```

**Comment by t-kelly** [comment]
Yes! Great issue. Thanks @milesw. This is exactly the stuff I'm hoping to flush out in Beta.

**Comment by t-kelly** [comment]
Fixed in https://github.com/Shopify/slate/pull/750
