### ISSUE TITLE
Add PostCSS to slate.config.js

### ISSUE THREAD

**Issue by RustyDev** [Shopify/slate#540]
Is there any documentation for adding a PostCSS plugin in the build process? I'd like to use [Tailwind CSS](https://tailwindcss.com/docs/installation#using-tailwind-with-postcss).

**Comment by t-kelly** [comment]
I am using PostCSS in the webpack build. I can make it configurable via `slate.config.js`. I'm going to change the title of this and use this issue to keep track of the progress.

**Comment by anjolovic** [comment]
@t-kelly Any progress on the use of PostCSS plugins? I'd love to be able to start using TailwindCSS soon.

**Comment by mrobit** [comment]
Sorry to be a bother - any update on this? @t-kelly you'd mentioned that your'e using PostCSS in the webpack build - can you explain a little more on how that works? I saw your [comment about slate.config.js and webpack configs here](https://github.com/Shopify/slate/issues/394#issuecomment-374303889)  so I wasn't sure if that's where I should start or not.

**Comment by seandogg** [comment]
+1 -- looking to add some CSS Grid support in IE11 and add some PostCSS plugins to the build.

**Comment by dan-gamble** [comment]
I don't think that it quite fits with this issue but i've implemented PostCSS using slate.config.js here: https://github.com/Shopify/slate/issues/670

It does basically replace Sass with PostCSS so it's not really using PostCSS in addition to Sass but i thought it may be helpful.

**Comment by dan-gamble** [comment]
I'm sure there's more to it than what i've done here but i've started a PR that could get a decent initial version of this going: https://github.com/Shopify/slate/pull/683

**Comment by pveen2** [comment]
@mrobit Did you already manage to get the tailwind x Slate working, i want to start with this combination but only if it isn't a big hassle?
