### ISSUE TITLE
Slate does not update the product.

### ISSUE THREAD

**Issue by maxwell-movchan** [Shopify/slate#543]
### Problem

Slate does not update the product price when changing the variant. This problem occurs if the prices in euros

**Comment by dejanstrancar** [comment]
@maxwell-movchan what class does your variant selector have? 
Is it no-js maybe?

If is not, is there any error in console log on variation change?

**Comment by maxwell-movchan** [comment]
@dejanstrancar There are no errors in the console. I just downloaded a clean slate theme and here is the same error. If the price in euros, if the price changes, the price is updated but only the euro's paw is shown

**Comment by maxwell-movchan** [comment]
@dejanstrancar 
<img width="382" alt="2018-05-10 14 29 29" src="https://user-images.githubusercontent.com/28295561/39867653-97c60442-545e-11e8-8b49-41b821ec9d13.png">

**Comment by maxwell-movchan** [comment]
The problem is solved. I took a function with the Timber framework and replaced old function on new function.

function formatMoney(cents, format) {
    var value = '',
        placeholderRegex = /\{\{\s*(\w+)\s*\}\}/,
        formatString = (format || this.money_format);

    if (typeof cents == 'string') {
      cents = cents.replace('.','');
    }

    function defaultOption(opt, def) {
      return (typeof opt == 'undefined' ? def : opt);
    }

    function formatWithDelimiters(number, precision, thousands, decimal) {
      precision = defaultOption(precision, 2);
      thousands = defaultOption(thousands, ',');
      decimal   = defaultOption(decimal, '.');

      if (isNaN(number) || number == null) {
        return 0;
      }

      number = (number/100.0).toFixed(precision);

      var parts   = number.split('.'),
          dollars = parts[0].replace(/(\d)(?=(\d\d\d)+(?!\d))/g, '$1' + thousands),
          cents   = parts[1] ? (decimal + parts[1]) : '';

      return dollars + cents;
    }

    switch(formatString.match(placeholderRegex)[1]) {
      case 'amount':
        value = formatWithDelimiters(cents, 2);
        break;
      case 'amount_no_decimals':
        value = formatWithDelimiters(cents, 0);
        break;
      case 'amount_with_comma_separator':
        value = formatWithDelimiters(cents, 2, '.', ',');
        break;
      case 'amount_no_decimals_with_comma_separator':
        value = formatWithDelimiters(cents, 0, '.', ',');
        break;
    }

    return formatString.replace(placeholderRegex, value);
  }

**Comment by dejanstrancar** [comment]
Confirming a bug if you change currency formatting from {{amount}} to {{amount_with_comma_separator}} .. i believe currency it self does not make a difference, but devider is problematic. #
