### ISSUE TITLE
Proposal Codesplit JS Code

### ISSUE THREAD

**Issue by shelldandy** [Shopify/slate#545]
https://www.mpz.im/posts/shopify-webpack-codesplit/

I think it's worth adding this to the webpack config, also I'd appreciate your overall thoughts on the idea and maybe find better ways of doing it.

**Comment by qw-in** [comment]
Looks like slate generates a `script-tags.liquid` snippet that does some javascript codesplitting by generating (this)[https://github.com/Shopify/slate/blob/master/packages/slate-tools/tools/webpack/script-tags.html] snippet. Seems to work based on which template is active

```
<!-- snippets/script-tags.liquid - included in `<head>`-->
{% if template.name == 'foo' %}{{ 'foo.js' | asset_url | script_tag }}{% endif %}
...
```

If you want more details [here](https://github.com/Shopify/slate/blob/34af626b76cdbfa65d2fb57e6f86ff73155b4f86/packages/slate-tools/tools/webpack/config/prod.js#L132) is where it is being generated by `HtmlWebpackPlugin`.

I couldn't find this behaviour in the docs though, and it does not appear to work for styles yet. Would be nice to get some clarification

**Comment by t-kelly** [comment]
@shelldandy and @qw-in mentioned, we have this feature (actually the [newer solution found in Webpack v4](https://webpack.js.org/plugins/split-chunks-plugin/)) shipped in Slate 😬  

@qw-in we're working on the docs -- stay tuned over the next couple weeks and you should see something :)

**Comment by shelldandy** [comment]
@t-kelly that sounds really cool would you care to explain a bit how it works in regards with shopify cdn cache busting thing? Is that solved with your custom loader solution?

**Comment by t-kelly** [comment]
It is handled with the included solution. We just use the `asset_url` filter. Here is the contents of a auto-generated `script-tags.liquid` snippet:

```

{%- if layout == 'theme' -%}
<!--[if (gt IE 9)|!(IE)]><!--><script type="text/javascript" src="{{ 'vendors@layout.theme.js' | asset_url }}" defer="defer"></script><!--<![endif]-->
<!--[if lte IE 9]><script type="text/javascript" src="{{ 'vendors@layout.theme.js' | asset_url }}"></script><![endif]-->
{%- endif -%} {%- if layout == 'theme' -%}
<!--[if (gt IE 9)|!(IE)]><!--><script type="text/javascript" src="{{ 'layout.theme.js' | asset_url }}" defer="defer"></script><!--<![endif]-->
<!--[if lte IE 9]><script type="text/javascript" src="{{ 'layout.theme.js' | asset_url }}"></script><![endif]-->
{%- endif -%} {%- if template.name == 'gift_card' -%}
<!--[if (gt IE 9)|!(IE)]><!--><script type="text/javascript" src="{{ 'template.gift_card.js' | asset_url }}" defer="defer"></script><!--<![endif]-->
<!--[if lte IE 9]><script type="text/javascript" src="{{ 'template.gift_card.js' | asset_url }}"></script><![endif]-->
{%- endif -%} {%- if template.name == 'product' -%}
<!--[if (gt IE 9)|!(IE)]><!--><script type="text/javascript" src="{{ 'template.product.js' | asset_url }}" defer="defer"></script><!--<![endif]-->
<!--[if lte IE 9]><script type="text/javascript" src="{{ 'template.product.js' | asset_url }}"></script><![endif]-->
{%- endif -%} {%- if template.name == 'addresses' -%}
<!--[if (gt IE 9)|!(IE)]><!--><script type="text/javascript" src="{{ 'template.addresses.js' | asset_url }}" defer="defer"></script><!--<![endif]-->
<!--[if lte IE 9]><script type="text/javascript" src="{{ 'template.addresses.js' | asset_url }}"></script><![endif]-->
{%- endif -%} {%- if template.name == 'login' -%}
<!--[if (gt IE 9)|!(IE)]><!--><script type="text/javascript" src="{{ 'template.login.js' | asset_url }}" defer="defer"></script><!--<![endif]-->
<!--[if lte IE 9]><script type="text/javascript" src="{{ 'template.login.js' | asset_url }}"></script><![endif]-->
{%- endif -%}
```
