### ISSUE TITLE
Slate tools start command silently hangs on incorrect password

### ISSUE THREAD

**Issue by dangreaves** [Shopify/slate#551]
### Problem

When an incorrect API password is entered into `.env`, `slate-tools start` will output "Compiled successfully" followed by an infinite hang. Running `slate-tools deploy` reveals the true error (password is incorrect).

### Replication steps

1. Add `SLATE_PASSWORD=foobar` to `.env`
2. Run `slate-tools start` or `yarn start`
3. See compilation successful message followed by silent hang

### More Information

`slate-tools deploy` outputs the correct error message.

**Comment by t-kelly** [comment]
Wonderful bug report. Thanks @dangreaves!

**Comment by t-kelly** [comment]
This was fixed with https://github.com/Shopify/slate/pull/643
