### ISSUE TITLE
User cannot opt-out of Slate Analytics

### ISSUE THREAD

**Issue by madma** [Shopify/slate#552]
### Problem

User is not offered the option of opting out of Slate Analytics, nor does analytics "opt-out" seem to be a feature that has been built-in yet hidden at this time, after inspecting relevant source code: slate/packages/slate-analytics/index.js (last commit affecting this file: https://github.com/Shopify/slate/commit/e8b5b1d590a2052daa891ed22fbf2606cf7be011).

This is misleading, as the documentation suggests that a user is able to opt-out of analytics: https://github.com/Shopify/slate/wiki/Slate-Analytics (last commit: 7ebceb3).

### Replication steps

1. Run `yarn create slate-theme my-new-theme`
2. User is prompted for email to provide consent for analytics.
3. There is no option for user to use Slate without consenting to analytics.
4. On Mac: `cmd + c` to interrupt the theme scaffold script.
5. An empty theme folder is generated.

**Comment by t-kelly** [comment]
@madma This was a choice the team made for pre-releases of Slate v1. We intend to make analytics optional when we release the final version of Slate 1.0.0.
