### ISSUE TITLE
Increment port if Slate is already running

### ISSUE THREAD

**Issue by huguestennier** [Shopify/slate#553]
### Problem

Right now, you can't run two Slate project at the same time because you will run into an port already in use error : `Error: listen EADDRINUSE :::8080`

### Replication steps

- Have two Slate project
- Run `yarn watch` in one project
- Try to run `yarn watch` in the second project

### Recommandation

Slate should just increment the default `:8080` port to `:8081` so we can run multiple Slate instance at the same time.

**Comment by t-kelly** [comment]
This is now happening thanks to #712
