### ISSUE TITLE
yarn start --env=production

### ISSUE THREAD

**Issue by Bek81** [Shopify/slate#556]
I have created and correctly config- urated the ".env.staging" and ".env.production" files. When I execute the "yarn start --env = production" command, it looks for the default ".env" file....

Can you help me? please.

**Comment by t-kelly** [comment]
Hey @Bek81 -- can you try `yarn start --env=production`, without the spaces around the `=`?

**Comment by Bek81** [comment]
Hi @t-kelly ,
sorry, it was just a copy&past error. I tried it without the spaces.

**Comment by t-kelly** [comment]
And did it work?

**Comment by Bek81** [comment]
No, it does not work.

**Comment by chrisberthe** [comment]
@Bek81 can you copy and paste the output (or screenshot) whatever command it is you're trying to run?

**Comment by Skoulix** [comment]
This works on Macs but not on Windows.

On Windows,  when I execute the `yarn start --env=development` or `yarn start --env=production` command, it always looks for the default ".env" file.

Does this happens to anyone else?
Thanks.

**Comment by t-kelly** [comment]
@Skoulix thanks for clarifying! Will tackle this when we start testing on Windows.

**Comment by Bek81** [comment]
Hi, @Skoulix it does not work on my Mac either.
@t-kelly the same commands that Skoulix indicates.

Thanks

**Comment by t-kelly** [comment]
@Bek81 we're going to need some more info because we can't reproduce this on our end...

**Comment by sasankmukkamala** [comment]
The same thing happens to me on Mac.` yarn start --env=development` or `yarn start --env=production`, always looks for the default ".env" file.

Changing the command like this worked for me: `npm start -- --env=development` or `yarn start -- --env=development`

**Comment by t-kelly** [comment]
Removing the Window flag. Will investigate!

**Comment by t-kelly** [comment]
This will be fixed when https://github.com/Shopify/slate/pull/812 is merged and released
