### ISSUE TITLE
Not automatically uploading Images

### ISSUE THREAD

**Issue by magpiedigital** [Shopify/slate#557]
### Problem

When I add an image to the assets/images/ folder, and reference it in liquid, I get an error:

```
ERROR in ./sections/header.liquid
Module not found: Error: Can't resolve './image1.png' in '/Users/hamishjohnson/Documents/Magpie Digital/Web Development/shopify themes/my-new-theme/src/sections'
 @ ./sections/header.liquid
 @ . sync ^\.\/sections.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
```

My expectations (based off how theme kit works) is that the images automatically get uploaded to Shopify, but checking the theme files shows me that they don't exist.

### Replication steps

Drag image into /assets/images/

`<img src="{{ 'image1.png' | asset_url }}">`

### More Information

*Any additional information which might be helpful.*

**Comment by magpiedigital** [comment]
Right well I figured that you're supposed to reference like so:
`<img src="{{ '../assets/images/image1.png' | asset_url }}">`
Is there some documentation I'm missing? I wouldn't have figured that out if it wasn't for the **How do you handle dynamic name images?** issue

**Comment by t-kelly** [comment]
> Is there some documentation I'm missing?

Yes. We're working on expanding the docs now actually 😅 I will make sure to include a page on referencing assets in Liquid!
