### ISSUE TITLE
Document how to reference assets in Liquid files

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#559]
### Problem

It's not totally clear how to include an images in your Liquid files and have them included in the build. Let's clarify how this works in our docs!

Related: https://github.com/Shopify/slate/issues/557

**Comment by timtorres** [comment]
Did you end up documenting this? There's currently no way I'm able to compile anything when using the [documented way](https://help.shopify.com/themes/liquid/filters/url-filters#asset_img_url) of referencing custom assets.

**Comment by t-kelly** [comment]
Assets have been simplified in #850 and the change is now available in [v1.0.0-beta.12](https://github.com/Shopify/slate/releases/tag/v1.0.0-beta.12)

Docs that have also been updated:

- https://github.com/Shopify/slate/wiki/Slate-themes
- https://github.com/Shopify/slate/wiki/Template-and-layout-bundles
- https://github.com/Shopify/slate/wiki/Local-development
