### ISSUE TITLE
BEM in SCSS erroring

### ISSUE THREAD

**Issue by itsece** [Shopify/slate#560]
Hi there, I'm trying to use BEM syntax within my SCSS files. However, I receive this error in the console. Any ideas?

Example: 

`.navigation {
  width: 100%;
  height: 3.125rem;
  background: $dark-primary;
  &__list {
   margin: 0;
 }
}
`

`Refused to apply style from 'https://cdn.shopify.com/s/files/1/0003/1516/2652/t/1/assets/layout.theme.styleLiquid.scss.css?8489435675598013539' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

**Comment by jonathan5572** [comment]
@itsece I'm not 100%, but I'm pretty sure what's happening here is that the periods in your file name is what's causing this issue. My understanding is that you can't use periods in names - the site thinks your file is "layout.theme". Try changing your file name to "layout-theme-styleLiquid" and only use .scss not .scss.css as Shopify will compile your scss on the server.

**Comment by jonathanmoore** [comment]
@jonathan5572 The period in the file name is 100% ok. 👌`layout.theme.styleLiquid.scss.css` is the new file naming structure Slate 1.0 generates.

@itsece Sass introduced BEM-selector support in Sass version 3.3. Unfortunately [Shopify uses a forked version of Sass 3.2](https://shopify.github.io/slate/theme-scaffold/#sass-helpers) for rendering scss files on their servers. As a result the file you're uploading is failing to compile by Shopify.

Slate 1.0 helps to fix this issue by [compiling SCSS locally](https://github.com/Shopify/slate/wiki/Styles-with-Liquid#liquid-with-css-custom-properties) before it's sent to Shopify's servers.
