### ISSUE TITLE
Document that a theme deployed with yarn start is only intended for development

### ISSUE THREAD

**Issue by RustyDev** [Shopify/slate#563]
### Problem

Using `yarn start` works as expected however if I end that process, the site's css doesn't load. It requires a deploy in order to get it to load again.

Is this the intended behavior? If so, the docs should be updated so developers know to always deploy after ending a session. Seems like this could be really bad if you're connected to your live production site.

### Replication steps

1. `yarn start`
2. quit process (ctrl + c)
3. refresh site to find that css is not loading
4. `yarn deploy` in order to get css loading again

**Comment by t-kelly** [comment]
Related: https://github.com/Shopify/slate/issues/383

**Comment by RustyDev** [comment]
Thanks, @t-kelly. Looking forward to reading about the Shopify Theme Team's workflow. I also really like the proposal in #383.

It's been a struggle trying to find the right workflow with two environments so I've just been using one. Should we be using two separate stores? How do you keep them in sync if only products, orders, and customers can be exported via csv? Manually copying settings_data, pages and apps?

**Comment by t-kelly** [comment]
Instead of using two stores, you can use multiple themes (i.e. multiple theme IDs) within the same store. 

Personally I usually have a Theme ID which I use everyday for development. When I want to share progress or open a PR and have a link to preview the changes, I got to the admin and duplicate my development theme, and use that duplicate as my 'snapshot'. 

Like I said, we'll be going into more detail in the article but I hope that helps? 😅

**Comment by RustyDev** [comment]
Follow up: I tried out setting up a separate `.env.development` that's pointing to a duplicated theme and it's working great. It wasn't clear that you can use a different theme and then the local files are only updating that preview.

Agreed, updated documentation will help :)

**Comment by RustyDev** [comment]
Thank you 🙏

**Comment by phlfvry** [comment]
I figured this out the hard way. @t-kelly I think it would really help others if this was made very clear in the documentation! Would have saved me some time and frustration :)

**Comment by ConduciveMammal** [comment]
@t-kelly if you wanted to do a webinar to demonstrate these workflows, I certainly wouldn’t complain 😉

**Comment by t-kelly** [comment]
@ConduciveMammal if there were three more of me I wouldn't hesitate for a second to do a webinar 😬 all in good time!

**Comment by ConduciveMammal** [comment]
@t-kelly Aha, you'll have to have a word with your bosses, see if they can afford the budget for three more 😉

**Comment by huguestennier** [comment]
👋 We reworked the [commands documentation](https://github.com/Shopify/slate/wiki/6.-Commands) and added a warning on development versus production. Closing this for now.
