### ISSUE TITLE
Theme.js not Loading in Development

### ISSUE THREAD

**Issue by itsece** [Shopify/slate#564]
Following the documentation I have imported JS into theme.js file, compiled and seen it has correctly been compiled to the layout.theme.js file in `/dist`. However on the server I get the error `GET https://localhost:8080/layout.theme.js 0 ()`

**Comment by t-kelly** [comment]
Hey @itsece -- did you see the Note in [step 4 of the Getting Started guide](https://github.com/Shopify/slate/wiki/4.-Start-developing)?

>**Note**: Because we are running the server on `https://`, you will need to visit this URL at least once and tell your browser to "trust it". Otherwise, local assets will be blocked and your theme will appear broken.
>
>Alternatively, you could [create a trusted SSL certificate](https://github.com/Shopify/slate/wiki/How-to-create-a-trusted-local-SSL-certificate) for `localhost`.

**Comment by chrisberthe** [comment]
Hi @itsece, let us know if this solved your issue :')

**Comment by itsece** [comment]
@chrisberthe Yep. 

Thanks @t-kelly.
