### ISSUE TITLE
No page exists for Theme Linting in the Wiki

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#574]
### Problem
I noticed in the Wiki docs for V1 that the link for Theme Linting doesn't exist so it just asks me to create a new page.

[Screenshot](https://prnt.sc/jjodga)

**Comment by chrisberthe** [comment]
Thanks for letting us know @ConduciveMammal - keep in mind the Wiki is still very much a work in progress and we will be updating this over the coming weeks.

**Comment by chrisberthe** [comment]
I went ahead and created a new page and just for the time being added "coming soon"; will be updating this in the next few days.

**Comment by ConduciveMammal** [comment]
Ahh apologies for that, I presumed the link being there meant it was ready for use.

Thanks for updating the page 👍
