### ISSUE TITLE
Importing CSS file from CDN causes theme.js to not run

### ISSUE THREAD

**Issue by RustyDev** [Shopify/slate#578]
### Problem

When trying to link an external stylesheet, theme.js fails to run. I'm importing other CSS files this way without an issue.

### Replication steps

1. Run `slate-tools start --env=development `
2. Add `<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
` to `theme.liquid` in the head.
3. Code inside theme.js fails to run.
4. Remove the `<link>` and `theme.js` runs normally

**Comment by t-kelly** [comment]
For what it's worth, its more performant to copy this stylesheet into your project then to request it from another CDN. The extra DNS lookup required for this external call could be avoided.

Nevertheless this sounds peculiar.

**Comment by RustyDev** [comment]
Yes, I tried multiple ways and still had the same issue. For the sake of submitting the issue, I thought this was the easiest to replicate.

I tried all of these:

- placing the file in `vendors` and using `asset_url`
- importing the .css file into theme.scss via `@import` 
- copying the contents of the file into a .scss file and importing into theme.scss

**Comment by RustyDev** [comment]
Odd, I tried again today and it works. I'll reopen this if it happens again.
