### ISSUE TITLE
How to import SCSS from node_modules?

### ISSUE THREAD

**Issue by awesomenkj** [Shopify/slate#582]
### Problem
I'm using new slate (v1.beta)
I cannot import bootstrap scss from node_modules.
But I can see Slate import normalize.css in theme.scss like this 
```
@import '~/normalize.css/normalize'
```
So I also tried like this 
```
@import '~/bootstrap/bootstrap'
```
But it was failed.
I also tried to import scss from node_modules like this 
```
@import '../../../node_modules/bootstrap/bootstrap'
```
Is there any special way to configure this even though that is not bootstrap ?

**Comment by t-kelly** [comment]
It looks like you missed a slash, did you try:
```
@import '~/bootstrap/bootstrap'
```

**Comment by w-lemon** [comment]
hi @t-kelly . thanks for your quick response. 
But I didn't miss slash in my code. 

it is just typo in above question . will edit it 

but if I write like @import '~/....' , it will import from node_modules ?
right ?
thx

**Comment by chrisberthe** [comment]
The first slash isn't required. The correct syntax is: `@import '~nameOfPackage';`. For instance, try following these steps:

1. Run `yarn add bootstrap@4.1.1`.
2. In `theme.scss`, add `@import '~bootstrap/scss/bootstrap';` (which follows the folder structure for that version of the Bootstrap module).

Please do this and report back with any updates.

**Comment by w-lemon** [comment]
It works well. 
Thanks
