### ISSUE TITLE
Yarn Start fails with exit code 1

### ISSUE THREAD

**Issue by rpasillas** [Shopify/slate#584]
### Problem

Running Yarn Start ends with error _Command failed with exit code 1_. 

### The Goal
Make customizations to an Envato purchased theme. Wasn't sure the best approach so I mostly used the custom starter themes part of the documentation.

### Replication steps

1. Cloned the Slate repo.
2. `yarn create slate-theme my-theme-edit my-theme-edit/`
3. `yarn create slate-theme my-other-theme`
4. Copy the contents of `my-other-theme` inside of `my-theme-edit` 
5. Replace the contents of `src` with a download of our Shopify theme.
6. Update .env file with `SLATE_STORE`, `SLATE_PASSWORD` & `SLATE_THEME`
7. Run `yarn`
8. Run `yarn start`

**Comment by lloydstubber** [comment]
What's the entire output of the error?

**Comment by chrisberthe** [comment]
Please post the entire output of the error. And I'm not sure if it's a typo while you wrote up the issue, but it should be `SLATE_THEME_ID`.

**Comment by ConduciveMammal** [comment]
This is also occurring for me. I'm using Windows 10.

I had the `yarn start` running but when the store's frontend wasn't reloading itself, I restarted the script. Now it's producing:

```
$ yarn start --env=development
yarn run v1.3.2
$ slate-tools start --env=development
(node:12000) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at DevServer.start (C:\Users\facko\Desktop\KubixShopifyThemes\graffia\node_modules\@shopify\slate-tools\tools\dev-server\index.js:32:17)
    at Object.<anonymous> (C:\Users\facko\Desktop\KubixShopifyThemes\graffia\node_modules\@shopify\slate-tools\cli\commands\start.js:151:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ConduciveMammal** [comment]
Ahh possibly of interest.

After quitting the Yarn script, I went to my task manager and found three Node.js processes still occurring, I killed them and then the build script worked fine again.

I'm guessing stopping the script isn't killing all of the services properly.

**Comment by chrisberthe** [comment]
@ConduciveMammal that's a separate issue - it doesn't look like you're fully killing the server. The `Error: listen EADDRINUSE :::8080` message means the server port is already being run. There is currently an issue open #553 to increment the port if Slate is already running.

How do you kill the server on Windows 10, <kbd>Ctrl</kbd> + <kbd>C</kbd>?

**Comment by ConduciveMammal** [comment]
That's right, yeah. `Ctrl` + `C` to kill the Slate build. But the issue is it's not killing the server. The only time the server is in use for me is via Slate so I don't think it's a matter of incrementing the port in this case as that just avoids the main issue.
