### ISSUE TITLE
Auto css prefixing 

### ISSUE THREAD

**Issue by eighthday** [Shopify/slate#593]
Is it now possible to setup auto vendor css prefixing? There is an issue that says it has been added to the v 1.0, but I can't find any documentation on how to use it.

**Comment by jonathanmoore** [comment]
Both the production and development environments use PostCSS with the [autoprefixer plugin](https://github.com/postcss/autoprefixer) to handle all of the prefixing.  
https://github.com/Shopify/slate/blob/d67f445ea4dda555cce836f58d78f23ec3b55b84/packages/slate-tools/tools/webpack/config/prod.js#L61

I believe that the targeted browsers for prefixing relies on the Babel settings which comes from [babel-presets-shopify](https://github.com/Shopify/babel-preset-shopify/blob/master/browsers.js)
```
module.exports = [
  'last 3 chrome versions',
  'last 3 firefox versions',
  'last 2 versions',
  'safari >= 8',
  'ios >= 8',
  'ie >= 11',
  'explorermobile >= 11',
  'android >= 4.4',
];
```

**Comment by chrisberthe** [comment]
Hi @eighthday, as @jonathanmoore already said this is already included as part of Slate's Webpack build (both development and production).

Are you encountering any issues around this, i.e. not seeing the vendor CSS prefixes after compiling?

**Comment by brantward** [comment]
Quick question - How do we overwrite the autoprefixer settings in slate.config.js? I'd like to target a few older browsers.

**Comment by simonsmith** [comment]
You should be able to use browserslist - https://github.com/browserslist/browserslist

**Comment by brantward** [comment]
Just to add to this - i need autoprefixer to cater for ios 8. eg ```display: -webkit-box;```.
It looks like 8 should be covered, but my generated styles have all -webkit- prefixes stripped.

**Comment by brantward** [comment]
even after manually updating ``` babel-presets-shopify``` I'm still not seeing -webkit- prefixers. Could cssnano be the cause here?

**Comment by brantward** [comment]
ooohhhkay sweet.
Browserslist works from package.json, and doesnt require any updates to slate.config:
```
"browserslist": [
    "last 4 versions"
  ]
```
ty @simonsmith

**Comment by deuce-studio** [comment]
Hi Guys, currently trying to use auto prefixing & im not getting any results. Just doesnt seem to be processing it.  is there something i need to add in? any documentation i could be pointed at?

Cheers
