### ISSUE TITLE
No instructions between downloading Node/Yarn and next step

### ISSUE THREAD

**Issue by Farscaper** [Shopify/slate#597]
### Problem

Granted, I'm a noob but when I get to step 2, Create a new Slate project, it just shows an unidentified panel that includes the word Shopify. 

I've installed Node and Yarn.

When I put the offered code into Node I just get an error. I think it needs to be a bit clearer as to what a person is expected to do and where. 

Edit: I initially used the Node icon app window instead of just the Node command prompt which worked a bit better until it gave an error about copying over the git.  I ended up doing that manually.

Still, you should consider paying a noob to write out instructions at a Grade 7 level, as with all Shopify help functions.  I could be available.

### Replication steps

*How to replicate the problem. Screenshots or video?*

https://d.pr/i/sBbjEQ

### More Information

*Any additional information which might be helpful.*

**Comment by t-kelly** [comment]
Hey @Farscaper, welcome to Slate 👋. We're doing our best to be as thorough as possible with Slate's getting started guide, but we also don't want to overlap docs made specifically for Node, NPM, and/or Yarn. I would recommend familiarizing yourself with those tools as they are critical to Slate and a ton of other modern JS developing libraries.

Can you please provide some more information on the error you received?

**Comment by maxcr** [comment]
I can't really help you if you're on windows and the documentation is severely lacking but it should be as simple as this.

```
npm i -g @shopify/slate@latest
mkdir ~/www
cd ~/www
slate t myNewDankTheme
slate s
```
profit???

**Comment by Farscaper** [comment]
Sorry, I can't recall the error now. I was working on something else and killed my system after installing Docker. Unrelated but a warning to others averse to a BSOD.
