### ISSUE TITLE
How to import jquery plugins like Headroom or Owl Carousel?

### ISSUE THREAD

**Issue by w-lemon** [Shopify/slate#605]
### Problem

*Uncaught TypeError: Cannot read property 'fn' of undefined*

### what I have done
```
import $ from 'jquery';
import 'owl.carousel';
```

**Comment by ninjaaa** [comment]
Going by what you've posted, I would assume that your error is because you haven't defined the path from where Owl Carousel is imported from.  In other words Owl Carousel hasn't been imported.

For example, this is what I do to import Headroom.js into my theme.js and initiate it...

```
import $ from 'jquery';
import Headroom from 'headroom.js/dist/headroom';

const hd = new Headroom(header, {});
hd.init();
```

In your case I would say you would need to amend it to something like this...

`import owlCarousel from 'path-to-owl-carousel';`

... then you can use `owlCarousel` where ever you need in that particular file.

**Comment by w-lemon** [comment]
hi @ninjaaa 

Your way to import Headroom is not for jQuery plugin. 
In this way, this will import pure JS headroom plugin. 

And also owlCarousel always trigger this issue. 
```
Uncaught TypeError: Cannot read property 'fn' of undefined

```

**Comment by huguestennier** [comment]
Related issue https://github.com/Shopify/slate/issues/605

**Comment by w-lemon** [comment]
I found  what's the problem
the problem is window.jQuery is undefined .
when import owl.carousel , jquery cannot be used within owl.carouse itself. 

I tried this. 
import $ from 'jquery';
window.jQuery = $;

But it cause another issue 
I can see the result of console.log(window.jQuery) without import 'owl.carousel'.
but if I add "import 'owl.carousel';" , then window.jQuery comes undefined. 

Why this happen?
this issue is caused when use other jQuery plugin as well. 

I think this issue is related with Slate.

**Comment by w-lemon** [comment]
Is there any way to register jQuery globally like $?

**Comment by jonathanmoore** [comment]
Yes, there is a way to register jQuery globals for specific modules using [webpack granular shimming](https://webpack.js.org/guides/shimming/#granular-shimming).
> The webpack compiler can understand modules written as ES2015 modules, CommonJS or AMD. However, some third party libraries may expect global dependencies (e.g. $ for jQuery). The libraries might also create globals which need to be exported. These "broken modules" are one instance where shimming comes into play.

Here is an example where the [imports-loader](https://webpack.js.org/loaders/imports-loader/) is used to add a global $ and jQuery variable requiring jquery to the top of the `owl.carousel` module.

1. Add webpack imports loader plugin: `yarn add imports-loader`
2. Update `slate.config.js` to set jQuery and $ for the `shopify-cartjs` module for both dev and prod

```js
// slate.config.js

/* eslint-disable no-undef */

const path = require('path');

const alias = {
  jquery: path.resolve('./node_modules/jquery'),
  'lodash-es': path.resolve('./node_modules/lodash-es'),
};

module.exports = {
  slateCssVarLoader: {
    cssVarLoaderLiquidPath: ['src/snippets/css-variables.liquid'],
  },
  slateTools: {
    extends: {
      dev: {
        resolve: {alias},
        module: {
          rules: [
            {
              test: require.resolve('owl.carousel'),
              use: 'imports-loader?$=jquery,jQuery=jquery',
            },
          ],
        },
      },
      dev: {
        resolve: {alias},
        module: {
          rules: [
            {
              test: require.resolve('owl.carousel'),
              use: 'imports-loader?$=jquery,jQuery=jquery',
            },
          ],
        },
      },
    },
  },
};
```

You could also look into a more modern carousel option that does not have jQuery requirements and works well with webpack https://flickity.metafizzy.co/

**Comment by w-lemon** [comment]
window.jQuery is still undefined. 

How to fix this issue?

**Comment by w-lemon** [comment]
Always keeps this issue. 

**Uncaught ReferenceError: jQuery is not defined**

**Comment by joshbedo** [comment]
The above with imports-loader doesnt fix the problem, still can't get owl carousel to load after jquery is loaded. This seems overly complicated.

**Comment by w-lemon** [comment]
The issue is caused because slate loads vendor.js in defer mode after build. 

you can check that in ./dist/scripts-tag.liquid

I think it is needed to edit this in slate

**Comment by chrisberthe** [comment]
@w-lemon can you try what @jonathanmoore suggested? I'm going to close this issue for the time being but please report back with any further issues.
