### ISSUE TITLE
import  video file from asset directory 

### ISSUE THREAD

**Issue by w-lemon** [Shopify/slate#606]
How to import *.mp4 file from assets directory ?

**Comment by huguestennier** [comment]
I highly recommend using either Youtube or Vimeo to host your video file, but if it's not possible : 

You can put your .mp4 file inside `src/assets/static` folder and you will need to run `yarn deploy` to deploy it to our servers.

Your code will look something like this : 

```HTML
<video controls>
  <source src="{{ "myvideo.mp4" | asset_url }}" type="video/mp4">
</video>
```

Note the double quote `"` around `myvideo.mp4`. This will tell Webpack to skip over this asset and not try to transform it.

**Comment by w-lemon** [comment]
hi @t-kelly  and @huguestennier 

it is still causing issue. 
The issue is timestamp number in the url. 
for example

https://cdn.shopify......./.....mp4?3242422342342... 

Is there any way to remove this number in the asset url?
