### ISSUE TITLE
SVG assets in CSS

### ISSUE THREAD

**Issue by jonathanmoore** [Shopify/slate#610]
### Problem

Any SVG image added to `src/assets/svg` is moved into `dist/snippets` for usage as a snippet include, for example `{% include 'icon-search' %}`.  However, I'm unsure how an SVG can be used as an asset (`/dist/asset`) usable in CSS or an [image tag](https://github.com/Shopify/slate/issues/542#issuecomment-392547635).

### Replication steps

1. Added icon-arrow-down.svg image to `src/assets/svg`
2. Initially expected a reference in CSS to work
```css
select {
  background-image: url('{{ "icon-arrow-down.svg" | asset_url }}');
}
```

### More Information

Dropping the SVG into `/src/assets/static` it is never uploaded to Shopify before running or while running `yarn start`.  It takes `yarn deploy` for the asset to be uploaded to Shopify.

Dropping the SVG  into `/src/assets/images` the file is never uploaded to Shopify with `yarn start` or `yarn deploy`.

Related:
https://github.com/Shopify/slate/issues/542

**Comment by t-kelly** [comment]
Assets have been simplified in #850 and the change is now available in [v1.0.0-beta.12](https://github.com/Shopify/slate/releases/tag/v1.0.0-beta.12)

Docs that have also been updated:

- https://github.com/Shopify/slate/wiki/Slate-themes
- https://github.com/Shopify/slate/wiki/Template-and-layout-bundles
- https://github.com/Shopify/slate/wiki/Local-development
