### ISSUE TITLE
cannot import script file from asset directory.

### ISSUE THREAD

**Issue by rabpeter** [Shopify/slate#612]
### Problem

*Cannot import custom js file from asset directory*

<script src="{{ '../assets/scripts/vendor/app.js' }} | asset_url"></script>
  This is causing MIME type issue due to timestampe numbers 
  (https://cdn.shopify..... js?234234234242)

also tried to import from static directory 
<script src="{{ 'app.js' }} | asset_url"></script>
This caused 404 error.

And tried to add double quote in the url like  this
<script src="{{ "../assets/scripts/vendor/app.js" }} | asset_url"></script>

**Comment by maxcr** [comment]
Did you declare it in `theme.js` first?

```
src/assets/scripts

This folder constains all your JS modules. A theme.js must be present, as it will act as the entry point for your JS application.
```

**Comment by t-kelly** [comment]
Duplicate of https://github.com/Shopify/slate/issues/409
