### ISSUE TITLE
Cssnano @keyframes collision

### ISSUE THREAD

**Issue by dictions** [Shopify/slate#614]
### Problem

Cssnano minifies `@keyframes` names. By adding multiple SASS entrypoints, `@keyframes` names collide.

### Replication steps

1. Create multiple SASS files. Each SASS file has a `@keyframes` call.
2. Run `slate-tools build` to create a production, minified build
3. Keyframe calls now have the same minified name in the two output CSS files.

### More Information

Related cssnano issue [here](https://github.com/ben-eb/cssnano/issues/361). This can be fixed with a cssnano optimization option.

**Comment by jonathanmoore** [comment]
You can fix this by customizing the cssnano config in `slate.config.js`

```js
// slate.config.js

const path = require('path');

const alias = {
  jquery: path.resolve('./node_modules/jquery'),
  'lodash-es': path.resolve('./node_modules/lodash-es'),
};

module.exports = {
  slateCssVarLoader: {
    cssVarLoaderLiquidPath: ['src/snippets/css-variables.liquid'],
  },
  slateTools: {
    cssnanoSettings: {
      zindex: false,
      reduceIdents: false,
    },
    extends: {
      dev: {resolve: {alias}},
      prod: {resolve: {alias}},
    },
  },
};
```

**Comment by dictions** [comment]
@jonathanmoore this may solve other issues I'm having, is there a general place I can look for any `slate.config.js` options? The wiki seems bare so far.

**Comment by chrisberthe** [comment]
Unfortunately, not yet - the wiki is still very much a work in progress but these configuration options will be something we tackle soon.

**Comment by dictions** [comment]
Thanks!

**Comment by dictions** [comment]
It looks like that solution had no effect on the output when I deploy to production (where cssnano is used). Thoughts?

**Comment by chrisberthe** [comment]
@dictions you'll need to ensure you update your `node_modules` - running `yarn upgrade` should update your dependencies (or simply deleting the folder and running `yarn install`).

I tried this on my side and it works fine. Please report back once you do this.
