### ISSUE TITLE
The folder structure for assets is rejected

### ISSUE THREAD

**Issue by jonkwheeler** [Shopify/slate#618]
### Problem

The folder structure for assets, [shown here](https://github.com/Shopify/slate/wiki/Template-and-layout-bundles#project-file-structure), is rejected by the slate CLI.

```
[11:21:24] Transfer Failed: 11:21:23 [development]Asset Perform Update to assets/scripts/templates/index.js at host xxxxxxxxxxx.myshopify.com
	Status: 422 Unprocessable Entity
	Errors: Theme files may not be stored in subfolders
11:21:24 [development]Asset Perform Update to assets/scripts/layout/theme.js at host xxxxxxxxxxx.myshopify.com
	Status: 422 Unprocessable Entity
	Errors: Theme files may not be stored in subfolders
```

**Comment by t-kelly** [comment]
Hey @jonkwheeler -- are you using `yarn deploy`? Looks like you're trying to upload raw Slate project files, not the compiled in dist/

**Comment by jonkwheeler** [comment]
@t-kelly it actually came from doing a `slate migrate` on an existing (but dated) shopify theme. I noticed the new folder structure needs `assets/scripts` to compile, but I got an error every time. This doesn't happen on a fresh slate install, but migrating my theme to a fresh install has been a bit tricky.

**Comment by t-kelly** [comment]
@jonkwheeler I think you're mixing up Slate v0 and Slate v1. Please give the docs for Slate v1 a read through -- there is no migrate command in Slate v1.
