### ISSUE TITLE
Slate hanging on "yarn start" or "npm start"

### ISSUE THREAD

**Issue by rniller** [Shopify/slate#620]
### Problem

As followed, I attempted to create a new project, run it, and deploy to Shopify. However, Slate hangs on the compile and file sync when I either run "npm start" or "yarn start".

### Replication steps

Here are the steps that I took to produce this problem.

1. `npx create-slate-theme my-new-theme`
2. CD-ed into the created project
3. Configured admin settings and modified the .env configuration
4. ran `npm start` and `yarn start` (Both separately and at different instances, of course)

The result is the project compiling fairly fast, however, the project doesn't sync to Shopify. Also, when attempting to access `https://localhost:8080` I'm prompted with `Cannot GET /` on the page.

Has anyone ran into this issue or have any possible solutions? I'm running on macOS 10.13.14 and have the latest Xcode Tools.

**Comment by bstjepanovic1** [comment]
How did you solve this? It happens to me as well.
