### ISSUE TITLE
Importing images via file-loader breaks in production

### ISSUE THREAD

**Issue by dictions** [Shopify/slate#627]
### Problem

Importing images via Slate's file-loader breaks when building for production.

### Replication steps

Import image in JS (I'm using preact and aliases here).

```
import muteIcon from 'images/icon-radio-mute.svg';
<img src={muteIcon} />
```

Localhost correctly serves the file via Webpack Dev Server. Building for production simply returns the name of the image file.

<img width="1440" alt="screenshot 2018-06-07 16 49 14" src="https://user-images.githubusercontent.com/4307278/41125678-2933abf8-6a73-11e8-8eed-b78bb340ddc6.png">

<img width="1440" alt="screenshot 2018-06-07 16 49 27" src="https://user-images.githubusercontent.com/4307278/41125679-2c053838-6a73-11e8-9a05-5e80b9214d18.png">

**Comment by t-kelly** [comment]
This falls out of the scope of Slate, we can't guarentee that it plays friendly with 3rd party frameworks.

**Comment by dictions** [comment]
@t-kelly I'm confused why this would fall under a 3rd party issue. Isn't this an issue with Slate's configuration for `img-loader` and `file-loader` [here](https://github.com/Shopify/slate/blob/master/packages/slate-tools/tools/webpack/config/core.js#L104)?

Just as in development there is an absolute path for image assets, I would expect the same in production. I'm not sure why this is out of scope of the Slate. That seems like default behavior.

**Comment by t-kelly** [comment]
We are not prioritizing integration with Preact. You can open a PR if you find a fix!
