### ISSUE TITLE
Slate tools issue

### ISSUE THREAD

**Issue by itsece** [Shopify/slate#630]
> "On build, Slate moves all SVGs contained within this folder to the snippets/ folder and renames them to .liquid files. To use an SVG in your theme, include it like any other snippet"

When using slate build none of my icons within the SVGs compile into the snippet folder, however on slate start they do. When slate zip is used and uploaded to production the preview produces these errors:

`Liquid error: Could not find asset snippets/style-tags.liquid Liquid error: Could not find asset snippets/script-tags.liquid Liquid error (line 16): Could not find asset snippets/icon-brand-logo.liquid`

Assuming that is because the snippets folder isn't compiling. Is this because of my particular version of slate-tools (0.13.0) or some process from the documentation I am missing?

Any help would be appreciated!

**Comment by huguestennier** [comment]
You're looking at the documentation for Slate v1 and are running v0.13. 

Take a look at the documentation for how we handled SVGs in 0.x here : https://shopify.github.io/slate/css-examples/#svg-icons

Feel free to open an issue if something is not working.
