### ISSUE TITLE
Unexpected character '@' in @font-face. Need additional loaders.

### ISSUE THREAD

**Issue by xavianaxw** [Shopify/slate#631]
Considering an external build tool like Blendid where we have our own `app.js` and `app.css` which we want to use in Shopify's Slate.

### Problem

I'm trying to import my `app.js` and `app.css` into my `scripts/layout/theme.js` where I updated my code to include both files I want to import. Here's my code

```
@import '../../build/javascripts/app.js'
@import '../../build/stylesheets/app.css'
```

Shopify picks up this changes but it throws an error on the following line.

```
@font-face{font-family:apercu;font-style:normal;font-weight:400;src:url(../fonts/apercu-regular.eot);src:url(../fonts/apercu-regular.eot?#iefix) format("embedded-opentype"),url(../fonts/apercu-regular.woff) format("woff"),url(../fonts/apercu-regular.woff2) format("woff2"),url(../fonts/apercu-regular.ttf) format("truetype")}
```

Pardon the minified look.

```
ERROR in ./assets/build/stylesheets/app.css
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
```

Here's the error that is getting thrown.

### Replication steps

1. Set up shopify store + theme etc
2. Create a file in `assets/build/stylesheets` and call it `app.css`
3. Add the following into it

```
@font-face{font-family:apercu;font-style:normal;font-weight:400;src:url(../fonts/apercu-regular.eot);src:url(../fonts/apercu-regular.eot?#iefix) format("embedded-opentype"),url(../fonts/apercu-regular.woff) format("woff"),url(../fonts/apercu-regular.woff2) format("woff2"),url(../fonts/apercu-regular.ttf) format("truetype")}
```

4. Add the following to your `scripts/layouts/theme.js`

```
@import '../../build/stylesheets/app.css'
```

### Question

I'm guessing the issue I'm facing requires additional webpack loaders but I'm not sure how to configure it on Shopify's `slate.config.js` so any help would be much appreciated!

**Comment by t-kelly** [comment]
@xavianaxw why are you including an `@` symbol before your imports in `theme.js`? That's not valid JS syntax.

**Comment by xavianaxw** [comment]
Oh yikes. Probably the issue then!
