### ISSUE TITLE
Shopify SCSS compilation: issue with str-replace function.

### ISSUE THREAD

**Issue by andreas-sotnik** [Shopify/slate#633]
*I'm not sure if this is the correct repository to open issue in, so If I'm wrong, please suggest a better place.*

### Problem

Basically,

```
@charset "UTF-8";

@function str-replace($string, $search, $replace: '') {
  $index: str-index($string, $search);
  @if $index {
    @return str-slice($string, 1, $index - 1) + $replace + str-replace(str-slice($string, $index + str-length($search)), $search, $replace);
  }
  @return $string;
}

.test {
  color: str-replace("#ccc", "#ccc", "#aaa");
}
```

When I compile it locally (or using https://www.sassmeister.com/) it works okay, and I see `.test { color: "#aaa"; }` as a result. But when it's compiled by Shopify platform, I see the error. 

Are there specific limitations to the SCSS compilation on Shopify?

**Comment by chrisjreber** [comment]
Yes, limitations are that Shopify uses SASS version 3.2.
https://www.shopify.com/partners/blog/a-beginners-guide-to-building-shopify-themes-with-sass-part-1-getting-started-with-sass

**Comment by andreas-sotnik** [comment]
@chrisjreber, Oh.. I see. Thanks!

**Comment by t-kelly** [comment]
@andreas-sotnik Slate v1 introduces [local SCSS compilation](https://github.com/Shopify/slate/wiki/Styles-with-Liquid#liquid-with-css-custom-properties) which might help you get over this. Take a look!

**Comment by andreas-sotnik** [comment]
@t-kelly Thanks for the suggestion! Currently, I'm using slate v0 but after current tasks are done, I will check v1 as well.
The only doubt I have is that with v1 SCSS is precompiled, and I'm not sure how to pass liquid variables from theme settings there...
