### ISSUE TITLE
Slate V0 causes theme Preview Bar to have undefined height 

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#637]
### Problem

When serving a store via Slate V0, the theme preview bar that shows at the bottom of the screen has an extended border with `height: undefinedpx`.

Also: the Share Preview and Hide Bar buttons don't work when being served via Slate.

### Replication steps
![download](https://user-images.githubusercontent.com/18140157/41429272-8dacebe4-7004-11e8-84bc-8a4a8adcb282.png)

**Comment by t-kelly** [comment]
Related https://github.com/Shopify/slate/issues/420

**Comment by huguestennier** [comment]
Fixed in #953
