### ISSUE TITLE
custom cart.js not injected

### ISSUE THREAD

**Issue by davidpenuelab** [Shopify/slate#644]
### Problem

Hi,
i created a new cart.js file as product.js but is not being injected. How can i create a new cart.js that would work only for the template /cart?

**Comment by t-kelly** [comment]
Is the file in `src/assets/templates/cart`? Don't see why it shouldn't be working..

**Comment by davidpenuelab** [comment]
Hi T!
no, its not showing as it is when I am in product, the product.js

In this image you can see how it looks my filesystem and my code inside the cart.js:
https://imgur.com/pqBAc5j

In this one, you can see what i get in the dev tools when i am in /cart:
https://imgur.com/pMCg9li

and in this one what i get when i see a product:
https://imgur.com/vwglG5g

I am not sure if i have to do something more than adding the file to the current folder.

**Comment by t-kelly** [comment]
Oh it's because you're trying to see it in development build. The development doesn't bundle assets separately because it's not needed while you're developing and would slow down the build (slower time to see your changes).

You need to run `yarn deploy` if you want to test bundles.

**Comment by davidpenuelab** [comment]
But @t-kelly, if I want to work with specif js for a specific section (cart in this case), how can I do it then? Where can I add my code, inside the template file(cart.liquid), in index.js, or in a custom file I could add to the static folder?

Thanks!

**Comment by davidpenuelab** [comment]
I just want to follow this up.

I'd be happy to provide more information or steps I have done to try and fix this issue. I am using beta.5 version of the code.

My question is: how should I work with js or .css that is specific to a page, can I create separate files as the [documentation says](https://github.com/Shopify/slate/wiki/Template-and-layout-bundles)? I am trying to figure out how to add specific code to cart/product/home from the template system and not asking in the index if it's cart >> load cart.js 
 
Any response is greatly appreciated.

Thanks

**Comment by davidpenuelab** [comment]
I will close this issue since @t-kelly's reply solved the issue:
– when creating a specific js for a template file (eg: cart.js for cart page), you need to run: 

`yarn deploy`

in order to create the file. Once created, you can work on it normally when running 

`yarn start` or `yarn watch`

Thanks @t-kelly !
