### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Dazdd** [Shopify/slate#646]
### Problem

After I follow the guidelines all the way through (https://github.com/Shopify/slate/wiki/4.-Start-developing) and using 'npm start' to launch my server, I cannot view my site via localhost:8080, I get the error 'Cannot GET /'.

I can view the site on the actual url {{myshop}}.shopify.com, and the changes I make locally are updated because Im still running npm start, I would prefer to be able to develop on localhost:800 if anybody can help fix this issue

**Comment by t-kelly** [comment]
Hey Dazdd -- looks like everything is working as it's supposed too. Please see https://github.com/Shopify/slate/wiki/Local-development for more details.

**Comment by simonmclean** [comment]
I'm also getting this problem. Nothing the above wiki solves the issue. I have a secure localhost.

**Comment by t-kelly** [comment]
@simonmclean -- as the docs mention:

> Local Development Asset Server only serves assets, not .liquid files. There is currently no easy way to compile Liquid files off of Shopify servers. We are aware of how this impacts development and doing our best to find a solution.

When you run `yarn start`, it opens your browser to your `myshopify.com` page. That is the page you're meant to develop from. If you check in dev tools, you will see that assets like JS are being served from `localhost`.

**Comment by YogiZoli** [comment]
@t-kelly explains more on this here https://github.com/Shopify/slate/issues/518
thanks for Slate and for the explanation
