### ISSUE TITLE
Not all JS files are importing in theme.js file

### ISSUE THREAD

**Issue by jayres** [Shopify/slate#651]
### Problem

I am unable to get all of my js files that are being imported to run the code in the onLoad() {} of the section register (code below should be helpful...). Issue is for Slate v.1. 

My problem is two-fold: 

1. If I get rid of one of my js files being imported then the other works or if I import one before the other it works (and vice versa), 

2. I am unable to debug what the problem may be since no error messages are sent to indicate the failure of the onLoad function. There are no linting or spelling issues in my code.

### Replication steps

Code is simplified to show example but this exact code example fails in my environment. Both my minicart section file and footer section file have the data-section-type identifier like `<footer class="footer" data-section-type="footer">` and `<div class="minicart" data-section-type="minicart">`.

scripts/sections/minicart.js
```
import sections from '@shopify/theme-sections';

sections.register('minicart', {
  onLoad() {
    console.log('test minicart');
 },
});
```
scripts/sections/footer.js
```
import sections from '@shopify/theme-sections';

sections.register('footer', {
  onLoad() {
    console.log('test footer');
 },
});
```
scripts/layout/theme.js
```
import sections from '@shopify/theme-sections';

import '../sections/minicart';
import '../sections/footer';

$(document).ready(() => {
  sections.load('*');  // this doesn't fix the issue
  // sections.load(['minicart', 'footer',]); // neither does this...

 //... there is more Slate exclusive code here but nothing below here is different from the initial setup
});
```

In the above example the minicart console log will run but not the footer one. If I switch the order of import around then the footer one will but not the minicart. I know it doesn't seem like there's much code here but even with putting the code down to this tiny amount the code doesn't run.

### More Information

If this is a bug then I'd appreciate a fix obviously but even if it is not a bug I would love some error messages in the compiling stage.

**Comment by jayres** [comment]
I just want to follow this up. 

I'd be happy to provide more information or steps I have done to try and fix this issue. I noticed that the beta tag was added to Slate v.1, but the project I have been building on is near launching and I would rather hand off with well formed code instead of.... get ready for it.... inlining the js for the minicart.

Any response is greatly appreciated.

**Comment by t-kelly** [comment]
Hey @jayres -- what version of `theme-sections` are you using?

**Comment by jayres** [comment]
Hi @t-kelly, 

I'm using `"@shopify/theme-sections": "^1.0.0-alpha.4",`

Here is the rest of the package.json just in case you might see something there.

```
{
  "name": "starter-theme",
  "version": "1.0.0-alpha.1",
  "private": true,
  "author": "Shopify Inc.",
  "description": "An opinionated, Slate compatible, starting point for developing Shopify themes.",
  "keywords": [
    "shopify",
    "theme"
  ],
  "bugs": "https://github.com/Shopify/starter-theme/issues",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/Shopify/starter-theme.git"
  },
  "devDependencies": {
    "@shopify/slate-tools": ">=1.0.0-beta.1",
    "babel-preset-shopify": "^16.2.0",
    "eslint-plugin-shopify": "^19.0.0",
    "stylelint-config-prettier": "^3.0.4",
    "stylelint-config-shopify": "^5.0.0"
  },
  "dependencies": {
    "@shopify/theme-a11y": "^1.0.0-alpha.3",
    "@shopify/theme-cart": "^1.0.0-alpha.3",
    "@shopify/theme-currency": "^1.0.0-alpha.3",
    "@shopify/theme-images": "^1.0.0-alpha.3",
    "@shopify/theme-rte": "^1.0.0-alpha.3",
    "@shopify/theme-sections": "^1.0.0-alpha.4",
    "@shopify/theme-variants": "^1.0.0-alpha.5",
    "gsap": "^2.0.1",
    "imports-loader": "^0.8.0",
    "jquery": "^3.2.1",
    "lazysizes": "^4.0.2",
    "lodash-es": "^4.17.4",
    "lodash.throttle": "^4.1.1",
    "normalize.css": "^7.0.0",
    "object-fit-polyfill": "^0.1.0",
    "object-fit-videos": "^1.0.4",
    "scrollmagic": "^2.0.5",
    "sticky-kit": "^1.1.3"
  },
  "scripts": {
    "start": "slate-tools start",
    "watch": "slate-tools start --skipFirstDeploy",
    "build": "slate-tools build",
    "deploy": "slate-tools build && slate-tools deploy",
    "zip": "slate-tools build && slate-tools zip",
    "lint": "slate-tools lint",
    "format": "slate-tools format"
  }
}
```

**Comment by t-kelly** [comment]
Can you please upgrade to the latest version `beta.7` and tell me if the problem still exists? This should have been fixed with https://github.com/Shopify/theme-scripts/commit/4d05f19de0f47212a9c5059424c8ee4ca779474c#diff-5b072069d215d7eba3eba5f71bd19816R257

**Comment by t-kelly** [comment]
@jayres I released a new version of [`theme-sections`](https://github.com/Shopify/theme-scripts/tree/master/packages/theme-sections) -- worth giving it a shot. If there are any other problems with it please open an issue in its repo and not Slate.
