### ISSUE TITLE
ENOTFOUND error on yarn start

### ISSUE THREAD

**Issue by marioloncarek** [Shopify/slate#652]
### Problem

Hello, i cant start developing again, i fixed 8080 port problem but now i cant start because of ENOTFOUND error when trying to run yarn start. I found the [#629]https://github.com/Shopify/slate/issues/629) issue which was wrong .env configuration about store and the theme but i checked multiple times and everything is ok with api password and theme ID.
Please help and thanks in advance

```
✔  Compiled successfully in 12.352s!
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND redlemonclub.myshopify.com/ redlemonclub.myshopify.com/:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:395:9)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Replication steps

`yarn start`

**Comment by tea2sugars** [comment]
I'm having the same problem this morning. I was developing all day yesterday but started up this morning and I am getting the following...

Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
layout.theme.js:1

Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
template.index.js:1

**Comment by tea2sugars** [comment]
Solved the above by revisiting the localhost:8080 url again and forcing chrome to trust it again.

**Comment by t-kelly** [comment]
Not sure what I can do to help. Unable to reproduce this.

**Comment by jarvisjohnson** [comment]
my issue was in my `.env` I had a trailing slash after the `SLATE_STORE` like
```
SLATE_STORE=my-store.myshopify.com/
```
should just be
```
SLATE_STORE=my-store.myshopify.com
```

**Comment by t-kelly** [comment]
@jarvisjohnson good catch!
