### ISSUE TITLE
npm start doesn't auto-reload when changes are made 

### ISSUE THREAD

**Issue by GuillermoCasanova** [Shopify/slate#656]
### Problem

Not sure if this is something that has yet to roll out with v1, but in v0 when changes were made the page localhost:8080 is on would automatically reload. However, now with v1 after doing a npm start the page doesn't reload to show changes made. 

### Replication steps

cd to project directory
npm start  (opens in browser window) 
make a change on html or css 
Change is made (confirmed by refreshing manually) but fails to auto-refresh (preview stays the same) 

### More Information

I've just recently moved to using v1 today for a new project. Running npm 5.6.0 and node 10.0.0 with the latest Slate version installed with npx.

**Comment by t-kelly** [comment]
Hey @GuillermoCasanova -- we're unable to reproduce this bug. Are you sure you read through the Wiki and followed the Getting Started guide?
