### ISSUE TITLE
Yarn deploy fails 422 "theme_packaged_with" is not a valid attribute

### ISSUE THREAD

**Issue by MitchEff** [Shopify/slate#657]
### Problem
'yarn start' and 'yarn build' are working perfectly fine. All of a sudden, using 'yarn deploy' fails, saying "theme_packaged_with" is not a valid attribute. 

I can see in 'dist/config/settings_schema.json', it's adding this just sort of randomly in the middle of the file: 

""theme_packaged_with":"@shopify/slate-tools@1.0.0-beta.1"

Screenshot [here](https://imgur.com/a/EN6d2Mw). 

### Replication steps
Use 'yarn deploy', then go check your dist/config/settings_schema.json. It _might_ be there? Just appeared today for us.

**Comment by Skoulix** [comment]
Same thing happens to me. Deploy command fails.

**Comment by t-kelly** [comment]
@MitchEff was this working before? This attribute should be whitelisted on Shopify servers...

**Comment by MitchEff** [comment]
Yeah, it was working okay a couple days prior. 

Oddly enough, with beta 5 it fails and then doesn't deploy, but on beta 1 it fails but still deploys everything except settings schema, which I'm just copying manually for now.

**Comment by t-kelly** [comment]
Looking into it! 🕵️

**Comment by Skoulix** [comment]
I don't have the warning any more so this is indeed whitelisted by Shopify servers. Honestly I had the warning for a couple of days, everything seems fine now. 

Thank you.

**Comment by t-kelly** [comment]
I can confirm that this issue occurs when the object with `name: "theme_info"` is not the first object in the `settings_schema.json` array.
