### ISSUE TITLE
Deployed theme trying to load JS files from localhost (and therefore breaking)

### ISSUE THREAD

**Issue by robertcoopercode** [Shopify/slate#659]
### Problem

After running `yarn deploy` (with no terminal errors) and then trying to preview my theme, all of the styles are missing and thus the theme is broken. The browser console shows `GET` errors related to trying to fetch `https://localhost:8080/layout.theme.js` and `https://localhost:8080/template.gift_card.js`.

### Replication steps

- `yarn deploy`
- Visit Shopify store URL to preview theme

### More Information

- Version 1.0x
- Latest slate-tools beta (as of this post)

Maybe Webpack isn't injecting the proper URL? Maybe it has something to do with the [script tags](https://help.shopify.com/api/reference/online_store/scripttag#create). Honestly have no clue, just shooting in the dark.

**Comment by robertcoopercode** [comment]
I had `yarn start` running in parallel with `yarn deploy` and this is what caused the issue. I re-ran `yarn deploy` with no development server running and it created the build folder correctly.

**Comment by t-kelly** [comment]
@robertcoopercode please see https://github.com/Shopify/slate/wiki/4.-Start-developing, in particular the note below the first image.

**Comment by robertcoopercode** [comment]
Thanks for the response @t-kelly. I don't think the issue was related to the browser && SSL certificates, but rather the build script injecting the incorrect asset URL into the compiled code.

This only happens if `yarn start` is being run at the same time as you run `yarn deploy`.
