### ISSUE TITLE
Styles not displaying after deploy

### ISSUE THREAD

**Issue by robertcoopercode** [Shopify/slate#660]
### Problem

I've deployed my theme using `yarn deploy`, but the styles are not being display on the page. All the styles show up during local development with `yarn start`, but they do not appear after deploy (while previewing the theme).

### Replication steps

- `yarn deploy`
- View Shopify store preview

### More Information

- Slate v1.0x

I do not get any browser console errors. Looking inside of the html `<head>` I can see the `<link>` element with an `href` attribute to the `layout.theme.css` file stored on the Shopify CDN. I've even visited the link to the CSS file and all the CSS declarations I wrote in my Sass files are found in the CSS file.

For some reason the stylesheet is just not applying styles to the html 🤔

For what it's worth here is the `<link>` element I'm talking about:

```html
<link rel="prefetch" href="//cdn.shopify.com/s/files/1/2486/4986/t/2/assets/layout.theme.css?4955788339739835475" as="style">
```

**Comment by dan-gamble** [comment]
[I think this was recently updated in the start template](https://github.com/Shopify/starter-theme/commit/dcb67e99aa04f9ee68c226e0dd71375ad6a2c2bf)

**Comment by robertcoopercode** [comment]
Ah, it looks like it has been updated! Thanks for pointing that out.

**Comment by lmartins** [comment]
omg I was pulling my hair out because of this. Thanks so much for the update!

**Comment by fhodzic** [comment]
@lmartins Me too! Pretty major change passing the variable in, you would think the main theme stylesheet would have been included by default...

**Comment by chillburn** [comment]
The Skeleton theme https://github.com/Shopify/skeleton-theme and Starter theme https://github.com/Shopify/starter-theme both mention the following. 

> Starter Theme and Slate v1 are currently in beta! You should expect potentially breaking changes between updates and more bugs than a finalized release. Slate v1.0 has not yet been tested on Windows.

I would be checking the commits in those themes until slate is out of beta.
