### ISSUE TITLE
Deploying without changing theme settings? 

### ISSUE THREAD

**Issue by eighthday** [Shopify/slate#665]
Deploying the theme removes the theme settings, it is possible to deploy but skip the settings upload like you can with yarn start? When it's time to do browser / device testing it is a real pain to have to add back in the settings after every little change.

**Comment by t-kelly** [comment]
We handle this, in detail, with a prompt on `yarn start` and `yarn deploy`

```
   It looks like you are about to upload the settings_data.json file.
   This can reset any theme setting customizations you have done in the
   Theme Editor. To always ignore uploading settings_data.json, add the
   following to your .env file:

      SLATE_IGNORE_FILES=/config/settings_data.json

   Or to disable this prompt, add the following to your slate.config.js file:

      slateTools: { promptSettings: false }

?  Skip uploading settings_data.json? (y/N)
```

**Comment by t-kelly** [comment]
Oh you're using Slate v0? You need to [add settings_data.json to your config.yml](https://github.com/Shopify/slate/issues/384#issuecomment-363609475)
