### ISSUE TITLE
Slate doesn't deploy SCSS and JS files

### ISSUE THREAD

**Issue by rizqinizamil** [Shopify/slate#668]
### Problem

Slate doesn't deploy SCSS and JS files
Additional problem: browser doesn't reload automatically after compiling.

### Replication steps

1. using `npm install`
2. Here the screenshot
https://cldup.com/WRCxX4-bKw.png
https://cldup.com/VPV5XbiOuu.png
3. Repository: https://github.com/rizqinizamil/first-slate-theme

**Comment by dan-gamble** [comment]
[You need to create a local SSL certificate](https://github.com/Shopify/slate/wiki/How-to-create-a-trusted-local-SSL-certificate)

Also i'm pretty sure you don't need to add that import to the `theme.scss.liquid`. Mine currently looks like below and works fine.

```scss
/**
 * Insert your styles with Liquid below.
 *
 * Import additional stylesheets into this sheet using CSS imports:
 * @import url('./global/form.scss');
 */
```

**Comment by t-kelly** [comment]
@dan-gamble answer should be correct! Let us know if you continue to have any problems @rizqinizamil

**Comment by dan-gamble** [comment]
I don't have an answer for you RE: the issue but i'd open a new ticket otherwise it'll get buried here with no one likely to see it.
