### ISSUE TITLE
SCSS not compiling successfully on watch

### ISSUE THREAD

**Issue by simonmclean** [Shopify/slate#673]
### Problem

When running `yarn watch`, changes to `src/assets/styles/scss/*` are detected, and the command line informs me that compilation was successful. However the compiled `theme.css.liquid` file does not reflect my changes. Only when I run `yarn deploy` does this actually work.

And of course, these changes are not reflected on the site itself.

Editing template files seems to work as expected. It's just SCSS.  

### Replication steps

- Run `yarn watch`
- Edit `src/assets/styles/components/responsive-images.scss`
- Once the the command success message is shown, check the output in `dist/assets/layout.theme.css.liquid`

### More Information

- MacOS High Sierra
- Slate 1.0.0-beta.5

**Comment by t-kelly** [comment]
@simonmclean styles are only outputted to the file system when you run `yarn deploy`. With `yarn watch` they are included in the dev JS bundle and injected into the page to enable features like Hot Module Reloading.

The behaviour you are describing is intended. If you want to update your `theme.css.liquid` file without deploying, you can run `yarn build`
