### ISSUE TITLE
Yarn deploy doesn't seem to work

### ISSUE THREAD

**Issue by magnuspaaske** [Shopify/slate#675]
I'm developing a site and would like to have a live theme, a staging theme and a dev theme. That way I can preview changes with my client on the staging theme, develop on the test theme and deploy whenever I feel it's ready.

That said, running `yarn deploy` doesn't give any indication in shopify that the theme has been updated. The most natural thing to assume is that the theme hasn't been deployed or the 'updated at'  time in the admin would have been changed.

Is this an issue with Slate or with the way Shopify handles it when theme files are uploaded via the API? Right now it keeps us from being absolutely confident which version is pushed where.

A different thing is that when deploying with a `SLATE_THEME_ID` that doesn't exist on the shopify instance (for instance if the theme was manually replaced to make sure the time stamps update), each file returns a 404 but there's no overall indication that the theme couldn't be uploaded which would be helpful (e.g. by check the theme credentials at the beginning of the deploy/develop cycle).

/Magnus

**Comment by t-kelly** [comment]
Hey @magnuspaaske, thanks for trying out Slate.

First off, are you taking advantage of multiple `.env` files, e.g. an `.env.staging`, `.env.dev`, etc? That will let you call `yarn start --env=staging` or `yarn deploy --env=staging`

Sounds like you might not be setting the right Theme ID. Recommend reviewing the '[Connecting to your store](https://github.com/Shopify/slate/wiki/3.-Connect-to-your-store)' docs before moving further into triaging this problem...

**Comment by t-kelly** [comment]
Could you confirm that file contents change when you run `yarn deploy`? That would be an indication that it works.

**Comment by magnuspaaske** [comment]
Yes – double checked and content changes, only the time in the dashboard doesn't change. So it's still unclear which version is the latest.

The immediate fix would be to make sure the upload is handled the same way as if I directly edited a file in the Shopify dashbaord (ie, if a file is changed update the time).

Longer term it would be nice if there was a hash on the theme for tracking versions (since it's also tracked with git and it's thus possible to revert to earlier versions.

**Comment by t-kelly** [comment]
This sounds a problem with the Asset API and not Slate. I will submit a ticket to make sure this is looked at.

**Comment by magnuspaaske** [comment]
Great thanks :)

**Comment by artshostak** [comment]
Any update on this? Selective environment deployment still doesn't work for me.
