### ISSUE TITLE
Getting "DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead" on `Yarn Start`

### ISSUE THREAD

**Issue by adamrasheed** [Shopify/slate#676]
### Problem

*Succinct outline of the problem or request.*
Everytime I try to start local development by using yarn start, I get the following message: 
`DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead` and the terminal gets stuck on that message

### Replication steps

*How to replicate the problem. Screenshots or video?*
The only steps I've done is to install slate 1.0, fill in the creds in the .env file, and run `yarn start`.
Here's the screen I get:
<img width="682" alt="screenshot 2018-07-14 16 27 45" src="https://user-images.githubusercontent.com/10425543/42729133-fd964fa0-8782-11e8-8c6d-e704c01232b0.png">

**Comment by t-kelly** [comment]
Last time I checked, this was a dependency of a dependency that was triggering this warning... will take another look to see if its been updated.

**Comment by truribe** [comment]
I’ve been getting this for ages but ignored it.

**Comment by RyanAaronGreen** [comment]
I'm in the same boat as @adamrasheed - the more important part is that localhost is not working for me once running `yarn start`

**Comment by jonathanmoore** [comment]
@adamrasheed @RyanAaronGreen Slate only uses localhost as a local assets (CSS and JavaScript).  The theme's liquid files will all live on Shopify and the preview URL should be your shop's actual URL.
https://github.com/Shopify/slate/wiki/Local-development#local-development-asset-server
