### ISSUE TITLE
Just a small typo in the env file

### ISSUE THREAD

**Issue by asinofsky** [Shopify/slate#678]
### Problem

it currently reads

"# The ID of the theme you wish to upload files too "

the last "too" should be "to" I think, or I'm misunderstanding the instructions!

I don't understand git well enough to try to fix it with a pull or whatnot, this is my first time working with git! Figured it's minor but worth reporting.

**Comment by t-kelly** [comment]
@asinofsky this is the perfect opportunity for you to open up a pull request! 😉

**Comment by DMJr** [comment]
@t-kelly I'm not yet involved in this repo but just pulled it down. I switched from Pinnacle Cart to Shopify for my side business last month and it rocks so far.  I actually came here to see if I could contribute to the main product after I filed a ticket with support, but I don't think what I was looking for is open sourced.  Could I take this ticket as a first ticket to this repo? I know @asinofsky is assigned this ticket, so I thought I'd ask first.

**Comment by t-kelly** [comment]
Totally -- Thanks @DMJr!

**Comment by asinofsky** [comment]
Yeah sorry guys I literally don't get how git works so I couldn't even :(.

**Comment by DMJr** [comment]
@asinofsky If you're interested at all I can send you a quick screencast to get started and you can do this ticket : )

**Comment by asinofsky** [comment]
It's not super on my plate right now and I'm spread really thin learning a
lot of new things, including actual Shopify right now. Maybe soon 😀
