### ISSUE TITLE
Problem with add custom fonts in .scss

### ISSUE THREAD

**Issue by Qadda** [Shopify/slate#680]
### Problem

Hello! When I started working with Slate, I had a problem with recognizing the .woff format, in the "assets / fonts" folder, it found the files, but there was a type error that was not specific. As a result, I went into the configuration webpack - core.js and made a separate configuration and it solved my problem. 

I hope I helped someone :)

> {

        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 1000,
              mimetype: 'application/font-woff'
            }
          }
        ]
      },
      {
        test: /fonts\/.*\.(eot|svg|ttf)$/,
        exclude: /node_modules/,
        loader: 'file-loader',
      },

![screenshot_7](https://user-images.githubusercontent.com/7279378/42838602-e93c5994-8a09-11e8-9fad-066795e12fe5.jpg)

**Comment by t-kelly** [comment]
Assets have been simplified in #850 and the change is now available in [v1.0.0-beta.12](https://github.com/Shopify/slate/releases/tag/v1.0.0-beta.12)

Docs that have also been updated:

- https://github.com/Shopify/slate/wiki/Slate-themes
- https://github.com/Shopify/slate/wiki/Template-and-layout-bundles
- https://github.com/Shopify/slate/wiki/Local-development
