### ISSUE TITLE
Images don't upload to Shopify

### ISSUE THREAD

**Issue by CorySchulz** [Shopify/slate#687]
### Problem

When you put an image in the src/assets/images folder they do not upload to Shopify.

### Replication steps

Create new theme, run "yarn start", place image in src/assets/images folder.

### More Information

They don't show up in the dist/assets folder either, not sure if they're supposed to?

**Comment by rainerbird** [comment]
Hi Cory

Take a look at #658

**Comment by t-kelly** [comment]
Looks like this was addressed in #658
