### ISSUE TITLE
JS section not exec on other page than Home

### ISSUE THREAD

**Issue by adelh45** [Shopify/slate#688]
### Problem

I've created several section with js and css in respective folder. When i add the section on the home page the JS is loaded and executed correctly. When I add the section in the template using for example {% section 'SECTION_NAME' %}, the JS is not applied.

### Replication steps

Create a liquid section in src/section
Create a js file in src/assets/scripts/sections
Create a custom page in src/template  and put {% section 'your section file' %}
Apply the page template to a shopify page

### More Information

I also tried to the js in 
sections.register('jsFileName', {
  onLoad() {
and added a js file in src/assets/scripts/template/ for my page with this code (didnt forget to import) : 
sections.load([
    'jsFileName' 
  ]);

Nothing happens

**Comment by brantward** [comment]
Hi @adelh45,

Depending on what template you want to add a section to, you'll need to also import the section's js from the template's js file. 

See: [Template-and-layout-bundles](https://github.com/Shopify/slate/wiki/Template-and-layout-bundles).

And checkout the example from the starter theme:
[/src/assets/scripts/templates/product.js](https://github.com/Shopify/starter-theme/blob/master/src/assets/scripts/templates/product.js)
```import '../sections/product';```
