### ISSUE TITLE
Missing slate.config.js documentation

### ISSUE THREAD

**Issue by sebbean** [Shopify/slate#690]
### Problem

No documentation

https://github.com/Shopify/slate/wiki/Slate-Config

### Replication steps

Go to documentation
https://github.com/Shopify/slate/wiki/Slate-Config

### More Information

Help!

**Comment by t-kelly** [comment]
Thanks for the issue!

**Comment by t-kelly** [comment]
New docs in https://github.com/Shopify/slate/wiki/Slate-Configuration
