### ISSUE TITLE
Add documentation on how to create a development store and why its needed

### ISSUE THREAD

**Issue by clarklab** [Shopify/slate#692]
### Problem

Building a theme shouldn't require me to create a store and populate it with items.

### Replication steps

This step in the docs: https://github.com/Shopify/slate/wiki/3.-Connect-to-your-store is a pretty big hurdle for me. Is there any way to hook to an existing sample store and develop on that? Reasoning below...

### More Information

I don't have a current Shopify account or store
My client eventually will, but getting them to submit content ahead of time is like pulling teeth
It would take time to create a store and populate it with items
I would likely do that work very poorly (my fault, I'll admit haha)
The last time I made a theme for a client, I setup my own sample shop. A few weeks later, it expired. The client wasn't fast enough to review/sign-off/launch in that period.

Now that I've typed all this out, I'm thinking there's gotta be a way to connect to a populated sample store. Help me out?

**Comment by dan-gamble** [comment]
You can create unlimited development stores with a partners account, could you not create one of these and add 20 or so arbitrary products that cover all use cases? This is the route we do at our agency.

**Comment by Eleeleth** [comment]
If you're on macOS, the new Developer Tools app has a built in Data Generator for populating a development store with sample items: https://www.shopify.com/partners/blog/developer-tools

**Comment by rizqinizamil** [comment]
I use [this](https://apps.shopify.com/simple-sample-data) to generate dummy contents and orders.

**Comment by fhodzic** [comment]
Some good product data from shopify here: https://www.shopify.com.au/partners/blog/93467590-design-your-store-faster-with-product-csvs-and-images

**Comment by t-kelly** [comment]
Hey @clarklab -- I think you've hit a good topic that could use some more explaining and documentation. Renaming this and adding it to the backlog.

**Comment by clarklab** [comment]
Great! 

Here's what I ended up doing (mostly based on suggestions in this thread).

- Created a partner account
- Created a store 
- Uploaded CSV product data (from that partner blog)

It'd be great to get that into the docs. It'd be even greater if there was a demo store ready to go (perhaps the default values in the .env file?)

**Comment by clarklab** [comment]
Actually I still can't figure out the .env file. Seems like I'm supposed to run 

`slate-tools start --env=production`

to create it (which wasn't included in the main Slate docs, for some reason), but it fails with the error:

`slate-tools: command not found`

Spent about 20 mins looking through issues trying things (like running "yarn install" in the folder again), can't figure out. Stopping work (two days I've hit walls now).

Also I'm sorry if I sound like a downer, I'm just trying to communicate how it's affecting my build. Full disclosure: I'm from WordPress land so all this is totally new to me.

**Comment by jonathanmoore** [comment]
@clarklab All of the various command line scripts are set up in the `project.json` file.  Technically you would want to use the command line `yarn start --env=production` which calls `slate-tools start` behind the scenes.

**Comment by t-kelly** [comment]
@clarklab did you make a `.env.production` file before running that command?

**Comment by clarklab** [comment]
Posted above:

Actually I still can't figure out the .env file. Seems like I'm supposed to run

`slate-tools start --env=production`

to create it (which wasn't included in the main Slate docs, for some reason), but it fails with the error:

`slate-tools: command not found`

**Comment by Eleeleth** [comment]
To expand upon what @t-kelly said, that command doesn't populate the file for you, it only reads the existing .env.production file. You'll want to copy your existing .env file (assuming you created a new theme based on starter-theme) and populate it with the production theme's keys and such. Then the command will work.

As an aside, I would suggest that `slate-tools start` is _probably_ not the command you want to be running for a production environment, since it will be serving assets from localhost. My workflow is `start` for develop, and `slate-tools deploy` for staging and production.

**Comment by clarklab** [comment]
> You'll want to copy your existing .env file (assuming you created a new theme based on starter-theme) and populate it with the production theme's keys and such.

I guess that's an issue. I don't think I have an .env file? Step 3 of the docs here don't mention creating one, just updating one. There's a link to the [slate-env docs](https://github.com/Shopify/slate/blob/master/packages/slate-env/README.md), which is where I got that `slate-tools start` command. It mentions `Can create and run .env files`, so I figured that's what I needed.

I'm gathering that I'm just supposed to manually create a .env file in the root folder?

**Comment by t-kelly** [comment]
@clarklab an empty `.env` file is generated when you call `yarn create slate-theme`. If you created a new project without using that script, you'll need to create an `.env` file manually.

**Comment by recursiveElk** [comment]
Could someone give me any information around populating the .env file with environment variables from somewhere else? Currently trying to hook up automatic deployment through Teamcity but don't want to commit .env details to the repo.

**Comment by huguestennier** [comment]
👋 We just published a guide on [how to create a development store](https://github.com/Shopify/slate/wiki/Creating-a-development-store) and gave a bit more context on why it's needed and how to fill it with dummy data. Gonna close this issue for now.
