### ISSUE TITLE
How to update Slate

### ISSUE THREAD

**Issue by rizqinizamil** [Shopify/slate#693]
### Problem

I'm currently using Slate v1.0.0-alpha.1 and I want to update to latest version. How can I do that? There is no instruction how to update Slate. I think it's better to put on documentation.

**Comment by diegopelaez** [comment]
I just tried to update to beta.7 and it broke :$

**Comment by dan-gamble** [comment]
@diegopelaez do you have any more information that would help fix your issue?

**Comment by diegopelaez** [comment]
@dan-gamble yes sorry I didn't linked it before #733

**Comment by huguestennier** [comment]
Thanks for opening an issue @rizqinizamil - I just created a page on the Wiki on [how to update Slate](https://github.com/Shopify/slate/wiki/How-to-update-Slate-version).
