### ISSUE TITLE
Feature Request(?): Expose env variables (or something similar) to liquid

### ISSUE THREAD

**Issue by mxmtsk** [Shopify/slate#694]
We're trying to migrate our theme to slate because of the many features it would give us. In our custom deployment script we used until now we replaced specific strings in the liquid files with values (for example typical environment variables like `API_URL` based on if the developer was uploading to the live or staging shop.

Is there something similar in slate or can slate be extended so we can implement custom extensions like this ourself?

**Comment by Eleeleth** [comment]
Correct me if I'm wrong, but wouldn't you be able to do this with the `settings_schema.json` file and the theme customizer?

**Comment by mxmtsk** [comment]
You're absolutely right. I was taking over the project and didn't even question why they replaced stuff like this at deployment, when we could just use `settings_schema.json`. thanks!
