### ISSUE TITLE
Theme Editor Font Picker + Slate V1

### ISSUE THREAD

**Issue by nemoeric** [Shopify/slate#697]
### Problem [EDITED AFTER dan-gamble message]

The theme editor font picker schema is not working with Slate V1

On a skeleton-theme, i added to my settings_schema.json

> {
>       "name": "Typography",
>       "settings": [
>           {
>               "type":    "font_picker",
>               "label":   "Heading font",
>               "id":      "heading_font",
>               "default": "helvetica_n4"
>           },
>           {
>             "type": "color",
>             "id": "heading_color",
>             "label": "Color"
>           }
>       ]
>   }

I declared the root css properties 
`<style>
  :root {
     --heading-font-url: {{ settings.heading_font | font_url }};
     --heading-font-color: {{ settings.heading_color }};
  }
</style>`

Then in theme.scss.liquid I declared the variables and used them
`$heading_font_color: var(--heading-font-color);
$heading_font_url: var(--heading-font-url);

@font-face {
    font-family: "Header Font";
    src: url($heading_font_url) format("woff2");
}

h1,h2,h3,h4,h5,h6{
    font-family: "Header Font";
    color: $heading_font_color;
}`

The color is properly applied, but the font is not working. 
Am I misunderstanding something ?

**Comment by dan-gamble** [comment]
Your variables are different here. You've used `_` in `theme.scss.liquid` and then you've used `-` under the `h1, h2, h3, h4, h5, h6` block declaration.

**Comment by nemoeric** [comment]
Yes Sorry @dan-gamble , that was just a copy/paste error when I renamed the variables for the purpose of clarifying the issue.

The problem remains the same: color variable is working but custom font is not.

**Comment by dan-gamble** [comment]
Just thought i'd check that first, can't offer much more help at the moment sorry!

**Comment by AysunSachir** [comment]
I always got errors when trying to use Slate with Bootstrap CSS variables.
I think they are not supported. On a quick Google I found this -> https://github.com/Shopify/slate/issues/524

Try avoiding CSS variables, it should work.

**Comment by huguestennier** [comment]
Can you try outputting the full font-face instead of trying to manually build it? E.g. : 

Liquid : 
```HTML
<style>
  {{ settings.heading_font | font_face }}
  --font-heading: {{ settings.heading_font.family }}, {{ settings.heading_font.fallback_families }};
</style>
```

SCSS : 
```SCSS
h1,h2,h3,h4,h5,h6 {
  font-family: var(--font-heading);
}
```

**Comment by huguestennier** [comment]
Going to close this for now, feel free to reopen if it doesn't work!
