### ISSUE TITLE
Confusing end of file error when I try to update files locally and have them sync with Shopify

### ISSUE THREAD

**Issue by mwgraziano** [Shopify/slate#699]
### Problem

While using Slate, when I make a change to any file within the theme in hopes of having it update both locally within the browser and on Shopify, I get output similar to the following and no update occurs:

![screenshot1](https://user-images.githubusercontent.com/1749944/43921110-d54b532c-9be8-11e8-87d1-91cd29f55006.png)

### Replication steps

1. Run Slate via "npm run start:dev".
2. Make a local change in Atom, vi, or any other editor.
3. Slate attempts to sync and outputs failure.

#### My environment
- OS (including version): macOS High Sierra 10.13.6
- Versions: slate and slate-tools v0.14.0

**Comment by yangkennyk** [comment]
I all of a sudden started getting transfer failures too

"http: request canceled (Client.Timeout exceeded while awaiting headers)"

**Comment by t-kelly** [comment]
Is this still a problem?

**Comment by yangkennyk** [comment]
It's no longer a problem for me. it seemed to be due to the outage.
