### ISSUE TITLE
Confused on deploy, site doesn't load assets unless process is running

### ISSUE THREAD

**Issue by joshbedo** [Shopify/slate#701]
So i thought when you run deploy it deploys the finalized minified assets to your theme id, however the theme is all broken and doesn't load assets unless im running the process on my machine. How to i deploy everything where i don't need a background process running?

**Comment by joshbedo** [comment]
Anybody?

**Comment by dan-gamble** [comment]
This is exactly what `deploy` does. What are the full steps you're doing to achieve this? This sounds like what happens when you run `yarn start` and then someone else views the site.

**Comment by zapsilere** [comment]
https://github.com/Shopify/slate/issues/563 hi @joshbedo seems this one can answer your questions, it also took me time to understand until I found this thread.
