### ISSUE TITLE
src vs dist vs home directory? .. yarn watch issues

### ISSUE THREAD

**Issue by tr1s** [Shopify/slate#703]
### Problem

--I download slate, it comes with a src folder. I set up my local dev using theme configure and theme download... it begins to download the same files that are already in src.

How come now I have two "layout" folders in home directory and in src. What's the point of that? What's the proper process here?--

--------------------------------------------------------

So, I'm trying Slate commands now instead of Themekit commands.

I ran yarn build, and then yarn start. 

## Problem 1

Everything builds into the "dist" folder, but I thought Shopify can only read assets if it's on the home directory? Not in another folder called "dist". Hence why I can't use tools like Motifmate with this setup. Motifmate can't upload the files to the serve cause Shopify can't find the right folders.

## Problem 2

yarn start watches my files, but it only watches the theme.scss.liquid, every other file (scss, js, etc) doesn't get watched/uploaded.

## Question 1

How can I change the dist build to output all the folders (assets, layout, templates, etc) into the home directory as opposed to a "dist" folder?

## Question 2

How do I get I get yarn watch to watch all my files as opposed to just the theme.scss.liquid? For example I can't even get a console.log('hi'); to show up.. but I can change the background to blue no problem.

## Comments

How come the docs seem like they're missing a lot of information and it has contradicting opinions? I'm just confused because I hear you're not allowed to have nested folders inside the "assets" folder, but yet the main slate theme outputs a dist folder.. just doesn't make any sense. What am I missed here?

Thanks, let me know!

**Comment by huguestennier** [comment]
Did you create your project using `yarn create slate-theme my-new-theme` ? This is how your folder structure should look : 

<img width="229" alt="screen shot 2018-08-15 at 11 02 39 am" src="https://user-images.githubusercontent.com/6691035/44155235-c4cd2516-a07a-11e8-9444-241358f79b38.png">

**Comment by tr1s** [comment]
Yes, but according to Shopify's required theme setup, assets, layout, templates, etc all need to be in the home directory. Not in a "dist" folder. So how do I change it so that webpack compiles into home directory and not a 'dist' folder? There's no webpack config.

And how come yarn start only watches the main theme.scss.liquid file and nothing else in the src file?

**Comment by el-rotny** [comment]
There are 2 ways to run a production build so that you have a production version of the code / disconnected from you local machine and uploaded to your store. 

1. You run the deploy script
2. You run the zip script

You should have the following in your package.json file

```
 "scripts": {
    "start": "slate-tools start",
    "watch": "slate-tools start --skipFirstDeploy",
    "build": "slate-tools build",
    "deploy": "slate-tools build && slate-tools deploy",
    "zip": "slate-tools build && slate-tools zip",
    "lint": "slate-tools lint",
    "format": "slate-tools format"
  }
```
Keep in mind that if you are uploading your theme manually, you will want to use option 2. If you want to upload all your files automagically, use option 1.

**Comment by huguestennier** [comment]
Exactly, only the dist folder will get uploaded to Shopify servers.
