### ISSUE TITLE
Support --fix Flag for  "slate-tools lint"

### ISSUE THREAD

**Issue by lux-capacitor** [Shopify/slate#704]
### Problem
Cannot pass `--fix` flags to eslint through `./node_modules/.bin/slate-tools lint --fix` or in the starter-theme proper doing `npm run lint --fix` to enable auto-fixing of simple errors. 

### Replication steps
1. Make some JS lint errors in your code (spaces between brackets, etc)
2. run `slate-tools lint --fix` 
3. Notice it says errors are fixable with `--fix` but passing the flag is ignored. 

### More Information
Being able to fix minor alignment errors through the script instead of by hand would greatly speed development and is already a built in feature of ES Lint, it just needs mapping through the slate-tools commands.

### Sample Output:
**NOTE:** Project is a vanilla starter-theme : https://github.com/Shopify/starter-theme
```
user$ ./node_modules/.bin/slate-tools lint --fix

shopify-theme/src/assets/scripts/templates/product.js
   8:2   error  Mixed spaces and tabs                              no-mixed-spaces-and-tabs
   8:4   error  Unexpected tab character                           no-tabs
   9:2   error  Unexpected tab character                           no-tabs
   9:3   error  Expected indentation of 4 spaces but found 2 tabs  indent-legacy
  10:2   error  Unexpected tab character                           no-tabs
  10:3   error  Expected indentation of 4 spaces but found 2 tabs  indent-legacy
  10:19  error  Missing trailing comma                             comma-dangle
  11:2   error  Unexpected tab character                           no-tabs
  11:2   error  Expected indentation of 2 spaces but found 1 tab   indent-legacy

✖ 279 problems (279 errors, 0 warnings)
  190 errors, 0 warnings potentially fixable with the --fix option.
```

**Comment by huguestennier** [comment]
Hi!

You need to run `slate-tools format` to fix the errors. [More informations here](https://github.com/Shopify/slate/wiki/Slate%20Tools#format)
