### ISSUE TITLE
Vendor@ files not applying expected Babel transformations

### ISSUE THREAD

**Issue by tomdean** [Shopify/slate#705]
### Problem

The **dist/assets/vendor@*.js** files generated during build do not honor Babel plugins used when generating the non-vendor files, leading to runtime errors. Collection & template JS files are transpiled to the targets as expected (e.g. let keyword replaced with var/funcs).

*Succinct outline of the problem or request.*

Vendor files need to apply the same transforms as other sources.

### Replication steps

```
yarn add --dev babel-preset-env
```

.babelrc
```
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 3 versions", "safari >= 10"]
      }
    }]
  ]
}
```

*How to replicate the problem. Screenshots or video?*

Target Safari 10 and build with .babelrc content specified above. Check vendor@*.js files in ./dist - will not reflect expected transformations.

### More Information

slate version v1.0.0-beta.6

*Any additional information which might be helpful.*

No plugins are specified in our slate.config.js.

**Comment by chillburn** [comment]
I am having the same issue. My .bablerc file is a little different. 

```
{
  "presets": [
    ["shopify/web", {
      "browsers": [
        "last 1 version",
        ">1%"
      ]
    }]
  ],
  "plugins": ["transform-async-to-generator"]
}
```

My page breaks when it hits an es6 keyword: **class**

**Comment by t-kelly** [comment]
This is on purpose as transpiling all assets from `node_modules` significantly impacts build times and generally (from my understanding) is a bad practice. The better practice is for libraries to ship pre-transpiled -- but I understand that is not a reality everywhere.

This looks like it should be a configurable option to add exceptions to?

**Comment by tomdean** [comment]
Removing node_modules from the excluded list had no impact on what was transpiled, so not sure if it's having the effect that you think it is.

**Comment by t-kelly** [comment]
Related https://github.com/webpack/webpack/issues/2031
