### ISSUE TITLE
Template and layout bundles are not generating for page.*.liquid templates

### ISSUE THREAD

**Issue by michaelburtonray** [Shopify/slate#707]
### Problem

*Succinct outline of the problem or request.*
I am unable to generate bundles for templates files that are used for Pages.

### Replication steps

*How to replicate the problem. Screenshots or video?*
creating two files in the following file structure:

```
└── src
   ├── assets
   │   └── scripts
   │       └── templates
   │           └── page.mission.js
   └── templates
       └── page.mission.liquid
```
Should generate a JS bundle: template.page.mission.js

**Comment by t-kelly** [comment]
Good point! Thanks @michaelburtonray.

**Comment by callaginn** [comment]
This doesn't work for me either. Feel like I'm going crazy here.

Created a new page.js file that's meant to be added to be added to any pages that use the page.liquid template.
```
└── src
   ├── assets
   │   └── scripts
   │       └── templates
   │           └── page.js (new file, includes simple console.log command)
   └── templates
       └── page.liquid (default template file)
```

In my opinion, the amount of abstraction Slate v1 and Webpack has introduced has made this entire process pretty convoluted. Slate v0, on the other hand, was really straightforward. @michaelburtonray Did you ever figure out how to get out of this mess?

**Comment by callaginn** [comment]
Ok. Restarting yarn seemed to do something, just don't understand what. I'm able to see test console statement and some sort of internal link: `webpack-internal:///./assets/scripts/templates/page.js`. 

However, I don't see any physical page.js or template.page.js file in the `/dist/assets` folder or on the Shopify server. So is that `webpack-internal` link only visible via the local server that Slate boots up? If so, how would I make sure that gets added to Shopify when everything gets taken live?

And is there any reason the entrypoints aren't constantly being built? Having to restart yarn every time I add a new file is pretty cumbersome.

**Comment by dan-gamble** [comment]
When you run `yarn deploy` everything will get pushed up and work fine. On `deploy` the links get updated to the correct urls that is on the Shopify CDN vs the local development server you get with `yarn start`. If you run `yarn build` then you'll see the files appear in `dist/assets`.

When `yarn start` is run Slate serves the Javascript different to how it's normally served so it's why you see the `webpack-internal` url's.

You don't have to restart on every file change only new files in certain directories (`templates`, `layout`). Entrypoints could be rebuilt on every save but this would make the `watch` which happen son `yarn start` tons slower. Given that new file creation happens a lot less than a save i think this is the correct approach.

I don't know the inner internals of how Slate truly works but i hope this helps and again any other questions just hit me up.

**Comment by callaginn** [comment]
So does it work kinda like "Foundation for Emails" does? That is, with Foundation I can run `npm start` when developing emails (which skips certain processes) and run `npm run build` when I want to inline everything to take live.

All that being said, I'm guessing `yarn start` is quicker and should be run during development? And when I'm ready for these files to be uploaded to Shopify's server, I should either run `yarn build` or `yarn deploy`?

> _You don't have to restart on every file change only new files in certain directories (templates, layout). Entrypoints could be rebuilt on every save but this would make the watch which happen son yarn start tons slower. Given that new file creation happens a lot less than a save i think this is the correct approach._

Are you referring to the `/src/assets/scripts/templates/` and `/src/assets/scripts/layout/` directories here? This was a little confusing, since many of the directories share the same name. I guess I'll have to trust their speed justification behind not constantly watching for new endpoints.

**Comment by dan-gamble** [comment]
The way you pointed out is correct Stephen. A lot if it is outlined [here](https://github.com/Shopify/slate/wiki/Local-development) and [here](https://github.com/Shopify/slate/wiki/Template-and-layout-bundles).

And you're correct, they are the directories i was referring to.

**Comment by michaelburtonray** [comment]
@callaginn I found a list of all of the template names in the source code here:

https://github.com/Shopify/slate/blob/d066c4a6e8e85d45a734ebc2c20919f060db21f4/packages/slate-tools/tools/webpack/entrypoints.js#L7-L27

So from this I've deduced that you need to package all of the css/js for all Page entities into one package.

I think this has to do with the limitation from Liquid

```
    {%- if template.name == 'page' -%}
      <script type="text/javascript" src="https://192.168.1.102:3001/template.page.js" defer="defer"></script>
    {%- -%}
```

Like, I don't think `template.name` can refer to a specific page template name in Liquid

**Comment by t-kelly** [comment]
@diegopelaez looks like you've got something figured out, why not open a PR? 😬
