### ISSUE TITLE
Theme built with Slate based off Starter Theme does not duplicate in theme store

### ISSUE THREAD

**Issue by rainerbird** [Shopify/slate#708]
### Problem

When building a theme using Slate 1.x that is based off the starter template - the theme will not duplicate in the theme store. It just hangs on the theme page until it says not complete.

### Replication steps

Unfortunately, this is quite hard to replicate. I've been building two sites using Slate 1.x that have used Shopify Starter Theme as a base template. Recently I've tried duplicating both themes and it results in the theme editor just 'hanging'. I've had experiences in the past where a theme will duplicate and won't carry across the "settings_data.json" file - but the "duplication" itself will still complete. In this case, the duplication doesn't complete at all.

The first thing I did was create a new Slate theme fresh from Shopify Starter theme. Then publish that theme and try duplicate it. Of course, the duplication worked. So I'm now at a trial and error stage where I'm trying to find what file is causing the theme duplication to hang. 

### More Information

I haven't worked out if this is definitely a Slate issue yet. But would like to see if anyone else has ran into something similar - even if anyone currently working with a Slate 1.x theme to try duplicate it and see if it works.

If I check my themes page a day after the attempted duplication - I am able to see the "duplication failed" message and see what files did not get carried over. The files that did not get carried over are Snippets, Config and Template files. I've tried re-uploading the theme with original files from "Shopify Starter Theme". I did have luck duplicating a theme with Snippets and Config files replaced from Shopify Starter Theme. But then when trying a theme with either just snippets or just config files replaced - duplicating theme hangs again.

Would it be possible that Slate is doing anything on the build command, which ends up causing a theme to not duplicate? Covering all bases here - if this definitely is not a Slate issue I will close it and keep digging!

**Comment by jonathanmoore** [comment]
I recently ran into the same issue and spotted the same `.DS_Store.liquid` that somehow moved into the `/dist/snippets` directory during build, start and deploy.  I couldn't locate the original `.DS_Store` file that was being included in the build.  Running the following on the theme directory managed to clear it out.

```
find . -name '.DS_Store' -type f -delete
```

Should there be some type of limit on the valid filetypes that get built, or at least a set list of filetypes to ignore?
