### ISSUE TITLE
"slate-tools start" issues — No local server + files not compiling

### ISSUE THREAD

**Issue by avcohen** [Shopify/slate#709]
### Problem

Perhaps I'm missing something obvious but I cannot seem to get any of the default styles from my theme to compile locally. Furthermore the `slate-tools start` command is not launching anything at `localhost:8080` as noted in docs, [here](https://github.com/Shopify/slate/wiki/Slate%20Tools#start).

`slate-tools start` does not compile SCSS into assets (file empty).

### Replication steps

Start a new project via `yarn create slate-theme my-new-theme`
Input required values into `.env`
Make changes to `~/src/styles/theme.scss` or file imported therein.
For example, `background-color: red;` on html * body element within `~/src/assets/styles/core/layout.scss`
Run `yarn start`

Inspect contents of `~/dist/assets/`. File `layout.theme.styleliquid.scss.liquid` is _empty_.
Local server doesn't start, new window opens to hosted site with `?preview_theme_id=[#]` param.

### More Information

I am using using separate .env files (.env.development and .env.production). I was running `slate-tools start` with the `--env=development` flag but the same issue persists even on a freshly created theme.

**Comment by t-kelly** [comment]
Styles are included in the main JS bundle to enable Hot Module Reloading (instant style updates). It looks like you're following all the right steps. Are you importing your stylesheet in `assets/scripts/layout/theme.js`?

Also did you see the note on [Step 4 of the Getting Started Guide](https://github.com/Shopify/slate/wiki/4.-Start-developing)?

**Comment by t-kelly** [comment]
@dzucconi I wish Github wiki had coloured text boxes for more emphasis 😞
