### ISSUE TITLE
What is going on here??

### ISSUE THREAD

**Issue by Mindgames** [Shopify/slate#711]
### Problem
I see people having the exact same issues ranging months back without anyone stepping in and providing a solution. 

People jumping in to Shopify theme development will end up using Slate as it's referred everywhere and spend countless hours with the same issues. 

# Write in the very top of the main readme that assets url for images is broken and you will not provide a solution.  

**Or simply fix this issue.**

``` This is such a disaster, really.  You are wasting the time of the people are suppose to make life easier for```

**Comment by t-kelly** [comment]
Slate is an open-source project that is currently in Beta. Any user can help improve it by creating an issue with constructive feedback or opening a Pull Request with changes they would like to see. There is also the option to fork Slate and modify it to your needs.

Mathias Åsberg (@Mindgames), the tone of your feedback is rude, unconstructive, and violates Slate's [Code of Conduct ](https://github.com/Shopify/slate/blob/master/CODE_OF_CONDUCT.md). It adds nothing to this project and reflects poorly on your character as a developer. I understand you might be frustrated with parts of Slate, but this is not the way to communicate it.
