### ISSUE TITLE
Unable to access section setting in sections.scss file

### ISSUE THREAD

**Issue by crvella** [Shopify/slate#714]
### Problem

I am unable to reference a sections settings from the section.scss file

### Replication steps

1.  Add following to **src/sections/header.liquid**
  _{
        "type": "color",
        "id": "announcement_bg_color",
        "label": "Announcement BG Color",
        "info": "info"
      },_

2. Add following to **src/snippets/css-variables.liquid**
_:root {
   ....existing entries
   --annbar-bg-color: {{ settings.announcement_bg_color }}
}_

3.  Add following to **assets/styles/variables.scss**
_// Announcement bar
$annbar_bg_color: var(--annbar-bg-color);_

4.  Add following to **assets/styles/sections/announcement.scss**
_background-color: $annbar_bg_colour_

*Any additional information which might be helpful.*
I get an error saying

**Try opening assets/layout.theme.styleLiquid.scss.liquid in the template editor to fix the error below:
Undefined variable: "$annbar_bg_color". at 10**

**Comment by jonathanmoore** [comment]
This technically wouldn't be an issue with Slate, but rather how Shopify's sections fundamentally work.  Section settings and block information are isolated and only accessible inside the section.  This allows for quick partial reloads in the customize theme menu.

The right approach is to set colors or other values directly in the section's markup with classes, data attributes for JavaScript or `<script>` tags.  starter-theme has several good examples of this.
https://github.com/Shopify/starter-theme/blob/master/src/sections/header.liquid#L131

**Comment by t-kelly** [comment]
As @jonathanmoore mentioned, this is not a problem with Slate rather a challenge in building themes in general. Closing.
