### ISSUE TITLE
Sections Load not firing for some templates

### ISSUE THREAD

**Issue by lmartins** [Shopify/slate#717]
I've been using the approach shown on the Slate Starter theme, where some templates are wrapped in a section, which we then initialise in JavaScript using the methods from `@shopify/theme-sections`.

I was trying to follow that logic for the article template, as follows:

```js
// src/assets/scripts/templates/article.js

import { load } from '@shopify/theme-sections';
import '../sections/article';

document.addEventListener('DOMContentLoaded', () => {
  console.log('document loaded');
  load('article');
});

```

```js
// src/assets/scripts/sections/article.js

import { register } from '@shopify/theme-sections';

register('article', {
  onLoad() {
    alert('article');
  }
});

```

The article itself is a section that is showing on the theme customiser.

But no matter what I try, I can't get the `onLoad` method from the article section to run, even though the `console.log` included on the `DOMContentLoaded` callback does show on the console.

Am I missing a step here? 
Thank you.

**Comment by diegopelaez** [comment]
Having the same issue here!

**Comment by t-kelly** [comment]
@lmartins this [was an issue](https://github.com/Shopify/theme-scripts/issues/37) in the last release of [`@shopify/theme-sections`](https://github.com/Shopify/theme-scripts/tree/master/packages/theme-sections) and should no longer be a problem.

This is not a bug with Slate -- rather a bug with `@shopify/theme-scripts`. Please open future issues with this library in the appropriate repo. Thanks!
