### ISSUE TITLE
Starting a new theme without one in your theme store already

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/slate#72]
## Issue

Creating a new Slate theme requires a `config.yml` file where you have defined theme ID already.  This means that you need to duplicate/choose a theme online to get the ID.  When you run your first deploy, it takes longer than you'd like because we need to do a `replace` on every file.

## Possible solution

ThemeKit has a `theme bootstrap` command that will create a new theme in your store for you: http://shopify.github.io/themekit/#use-a-new-theme  This use the latest release of Timber by default.

Could we have a similar command for Slate that would create your theme using the lastest build?  Example:

```
slate bootstrap —password=[your-password] --store=[your-store.myshopify.com]
```

### Other info

It's likely we will sunset Timber, so the existing `theme bootstrap` command would then need to either go away or change to pull Slate instead (which would solve this).

/cc @tanema re: Timber sunset

**Comment by baberuth22** [comment]
There should be a way to upload the bare bones slate theme automatically.  As it is now, I have to run slate zip, then upload the zip, get the theme_id, and insert it into config.yml.

**Comment by aubricus** [comment]
I just went through this and, initially, ended up working around the issue in the same way as @baberuth22. After some fiddling, I realized that I can probably just grab the existing theme_id (attached by default to the Debut theme) and replace it with my new Slate generated theme. This technique also worked.

The docs, as they are written today, can come across as a bit circular. On one hand Slate claims to create a barebones theme _without the need for a base theme_ but then when it comes to getting a theme_id you must go into the admin and retrieve the id of an existing theme. 

If you're unfamiliar (as I am); this won't make sense.

Here's the errors I was getting trying to set an arbitrary theme_id, for people who may be searching issues:

```bash
11:08:52 Assets Perform Retrieve at host <myteststore.myshopify.com>
        Status: 404 Not Found
        Errors: none
11:08:53 [development]Asset Perform Update to config/settings_data.json at host myteststore.myshopify.com
        Status: 404 Not Found
        Errors: This file is not part of your theme.
```

**Comment by linuxbastard** [comment]
Current build process includes uploading a packaged Slate base theme. So you just need to upload that and get the ID. There are also slate commands that are similar to the shopify theme kit, including "slate watch", which is exactly like "theme watch" from the kit. Maybe it's time to close this enhancement request?

**Comment by NathanPJF** [comment]
Thanks for the reminder, @linuxbastard 

I updated the documentation here https://github.com/Shopify/slate/pull/205, but didn't circle back and close this issue.
