### ISSUE TITLE
Slate doesn't work on iOS 9.3.x

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/slate#723]
### Problem

First of all i understand why this isn't really a thing in Slate but unfortunately a client has requested 9.3.x

[This line](https://github.com/Shopify/slate/blob/master/packages/slate-tools/tools/webpack/hot-client.js#L14) was specifically my error. iOS 9.3.x doesn't recognise arrows so this makes it fall over and i have to use the live theme to develop on which has previously been documented as not ideal.

Is it possible that the rollup / publication process of slate could make it so the packages are ES5 based? If not i completely understand. I can manually patch it in my `node_modules` (until i install / remove something) on the off times i have to support this.

**Comment by dan-gamble** [comment]
@t-kelly i think this one can be closed by https://github.com/Shopify/slate/pull/755 now? Could just add slate-tools to the exclude right?

**Comment by t-kelly** [comment]
Yep! Didn't realize they were related. Thanks for the 👀 @dan-gamble. Let me know if you have any questions on how to add the node_modules exclusion (hopefully the comments in the config are clear?)
