### ISSUE TITLE
Preview Server Stopped Working

### ISSUE THREAD

**Issue by callaginn** [Shopify/slate#724]
### Problem

After developing my site for about an hour this morning, then the preview server went down without any warning or error messages. The site is now previewing the LIVE site, which has no styling -- since it references localhost:8080. Now gives me a bunch of certificate warnings instead:

<img width="100%" alt="screen shot 2018-09-04 at 10 04 19 am" src="https://user-images.githubusercontent.com/2430211/45039806-055e9600-b02a-11e8-9db0-4b1286290825.png">

I've tried the following:
- Removed the css I had just added. No luck there.
- Restarted slate with `yarn start`
- That didn't work, so tried `yarn build` and `yarn deploy`
- Tried `yarn watch`, which didn't work either.
- Shut down my separate local homebrew server. Still no luck.

Everything was working an hour ago.

### Replication steps

There are no replication steps. It randomly stopped after saving changes to a scss file.

### More Information

I'm using Chrome 68.0.3440.106 on Mac OS High Sierra
Slate v1 -- I also have a previous Slate v0 installation
Bash 4.4.23
Yarn 1.9.4

**Comment by t-kelly** [comment]
Hey @callaginn -- please see the note in [step 4](https://github.com/Shopify/slate/wiki/4.-Start-developing) of the Getting Started Guide

**Comment by callaginn** [comment]
I had actually done that when I first set up the site last week. I guess it forgot its settings or something. I'm clearing Chrome caches constantly; maybe that has something to do with it?
