### ISSUE TITLE
BrowserSync SSL certificate

### ISSUE THREAD

**Issue by jonathanmoore** [Shopify/slate#726]
### Problem

The new BrowserSync integration is fantastic. However, I'm struggling to figure out a way to set up an SSL certificate for the resources at 192.168.1.8.  The same steps to create a certificate for localhost are not working as expected for the new IP address.

### More Information

Browsersync does have the ability to set certificates when it's starting up, but again I'm unsure how to correctly create the certificate and config Browsersync.
https://browsersync.io/docs/options#option-https

**Comment by corypratt** [comment]
same issue here. localhost cert is no longer working for assets as they are loading w/ IP address.

**Comment by Skoulix** [comment]
same issue

**Comment by t-kelly** [comment]
Thank you for posting this! I realized this from my testing too. The fix for now will be to visit the Asset Server port at least once in your browser.

I haven't tried it yet, but you should be able to create a locally signed cert for 192.168.x.x. 

I also included a prompt in [the Browsersync PR](https://github.com/Shopify/slate/pull/712) which disables using the IP and goes with localhost, at the expense external mobile testing won't work.

**Comment by jonathanmoore** [comment]
@t-kelly Is there something I need to do in order to see the disable external IP prompt?  I'm only seeing the usual deploy prompt.
![image](https://user-images.githubusercontent.com/454095/45169794-33231680-b1b3-11e8-8da8-b5b41aac16e0.png)

For the local signed cert, I've attempted the slate instructions only using the IP as well as trying this other approach that works well for local domains.  I feel like I need to do some more research to figure out how to handle IPs.
https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/

**Comment by t-kelly** [comment]
> @t-kelly Is there something I need to do in order to see the disable external IP prompt? I'm only seeing the usual deploy prompt.

Sorry forgot a sentence in my last post. The prompt only is displayed when your local IP is publicly accessible on the internet and it would be a security risk for you to post it on a Shopify store.

I can/will add a config item to toggle it on/off.

**Comment by corypratt** [comment]
I recreated my certs per the wiki for the heck of it and visited the IP address 192.168.x.x:3001 directly, telling chrome to continue anyways. Things started working after that, although, as @jonathanmoore pointed out, chrome warns of site not being secure; no biggie for me.

On a side note, Safari didn't balk at any of it.

**Comment by callaginn** [comment]
Don't know if I can do this again, but I believe I finally solved this using mkcert and a little experimentation. FYI: I'm also running High Sierra, a homebrew server, and the latest version of Chrome.

1. Installed mkcert with homebrew: `brew install mkcert`.
2. Installed a new CA into the key store: `mkcert -install`
3. Created a new SSL certificate and key: `mkcert localhost 192.168.x.xxx ::1`. The IP address is simply your local IP.
    > _It generated a new certificate to "./localhost+1.pem" and a new key to "./localhost+1-key.pem"_
4. Opened up `node_modules/@shopify/slate-tools/slate-tools.schema.js` in my Slate v1 project. Added the applicable path to the new certificate / key pair in the `ssl.cert` and `ssl.key` lines:
```
'ssl.cert': path.resolve(os.homedir(), './localhost+1.pem'),
'ssl.key': path.resolve(os.homedir(), './localhost+1-key.pem'),
```

So now I'm getting the secure lock without full-page security warnings. Only question is: will it stick when my computer's IP address changes?
![screen shot 2018-09-28 at 12 02 53 am](https://user-images.githubusercontent.com/2430211/46188985-eadaae00-c2b1-11e8-8a8d-67ed081ff8e7.png)

**Comment by callaginn** [comment]
### Another Successful Install!
I set this up at work today with only a minor change -- which occurred due to Slate version differences between machines. Beta 7 and below seem to be using the `slate-tools.config.js` file; above instructions were for Beta 8.

And during my second install, I used the _Insert Local IP via Bash_ script that I mentioned above, instead of copying/pasting my IP address. It worked too. Now let's see how long it sticks -- and/or we can create a simple function to refresh the IP.

**Comment by callaginn** [comment]
I updated to Beta 9 last night and it removed those edits. Ended up discovering the pathnames above might be incorrect too. However, that doesn't matter; I may have stumbled across *a better way* to do this automatically and "hopefully" stick between updates.

### Automatic SSL Check
The following setup will allow you to run `slate start` and `slate watch` without manually generating new SSL certificates OR telling Chrome to ignore certificate warnings. If a valid certificate exists, it does nothing. But if it's invalid, then it will issue a new one automatically.

### Initial Setup
1. Run the following commands to install a local Certificate Authority and issue a certificate for localhost and your IP address.
```
brew install mkcert
mkcert -install
```
2. Add the following `ssl-check` script to a path in your .bash_profile.
```bash
f=~/.localhost_ssl;
ssl_crt=$f/server.crt
ssl_key=$f/server.key
b=$(tput bold)
c=$(tput sgr0)

local_ip=$(ipconfig getifaddr $(route get default | grep interface | awk '{print $2}'))
# local_ip=999.999.999 # (uncomment for testing)

domains=(
    "localhost"
    "$local_ip"
)

if [[ ! -f $ssl_crt ]]; then
    echo -e "\n🛑  ${b}Couldn't find a Slate SSL certificate:${c}"
    make_key=true
elif [[ ! $(openssl x509 -noout -text -in $ssl_crt | grep $local_ip) ]]; then
    echo -e "\n🛑  ${b}Your IP Address has changed:${c}"
    make_key=true
else
    echo -e "\n✅  ${b}Your IP address is still the same.${c}"
fi

if [[ $make_key == true ]]; then
    echo -e "Generating a new Slate SSL certificate...\n"
    count=$(( ${#domains[@]} - 1))
    mkcert ${domains[@]}

    # Create Slate's default certificate directory, if it doesn't exist
    test ! -d $f && mkdir $f

    # It appears mkcert bases its filenames off the number of domains passed after the first one.
    # This script predicts that filename, so it can copy it to Slate's default location.
    if [[ $count = 0 ]]; then
        mv ./localhost.pem $ssl_crt
        mv ./localhost-key.pem $ssl_key
    else
        mv ./localhost+$count.pem $ssl_crt
        mv ./localhost+$count-key.pem $ssl_key
    fi
fi
```

3. In the main `package.json` file in your Slate project, add `ssl-check` to the beginning of the "start" and "watch" commands. Should read something like this:
```
"start": "ssl-check && slate-tools start",
"watch": "ssl-check && slate-tools start --skipFirstDeploy",
```

**Comment by t-kelly** [comment]
Thank you @callaginn! Will give this a shot this week.

**Comment by t-kelly** [comment]
Updated the Getting Started guide with [a new step](https://github.com/Shopify/slate/wiki/4.-Create-a-self-signed-SSL-certificate). Thanks again @callaginn! Amazing help with this.

**Comment by callaginn** [comment]
@t-kelly You're welcome. Glad I could help.

**Comment by t-kelly** [comment]
> if you add ssl-check to the main package.json file (or somewhere in the build process), you won't have to worry about rerunning ssl-check when the IP address changes. 

Since this script requires an additonal dependency installation, I would prefer to keep it as an optional/manual process for now. The ideal would be to have your script live in JS and executed whenever you call `slate-tools start`

**Comment by wizardlyhel** [comment]
For whatever reason, when I follow these steps to install the local cert, it also add a redirect rule that changes **http** => **https** (notice the **s** for secure) for localhost. This can be super frustrating if you have no idea what happened. Local development from http://localhost is very common path used by developers.

To remove this rule from Chrome, follow this article: https://www.codeproject.com/Articles/1010667/SSL-Connection-Error-When-Debugging-via-Localhost

**Comment by lmartins** [comment]
I've went through the steps described in the guide, and the output of the `ssl-check` command appears to be valid:
```
➜  git:(master) ✗ ssl-check
✅  Your IP address is still the same.
```
However the localhost address refuses to open with the message `NET::ERR_CERT_AUTHORITY_INVALID` and if I open with my local IP, even though it opens because I told it to trust the IP, I still get an invalid certificate error:

https://cl.ly/129477033894

Any tips around this?

**Comment by PolarisTLX** [comment]
Also trying to debug this error: `Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID`

> 3. In the main package.json file in your Slate project, add ssl-check to the beginning of the "start" and "watch" commands. Should read something like this:
"start": "ssl-check && slate-tools start",
"watch": "ssl-check && slate-tools start --skipFirstDeploy",

When I do thi I get the following error:   
```
$ ssl-check && slate-tools start
/bin/sh: 1: ssl-check: not found
error Command failed with exit code 127.
```


yarn start also not working for me probably because of this error. It looks like it is running but any changes I make to my Slate project will not show up in my browser. Only way to make the changes show up is by running yarn deploy each time which is extremely inefficient.

Ubunto 16 (Mint)
Yarn v1.10.1
node v8.11.1
npm v5.6.0

Any help appreciated.

**Comment by callaginn** [comment]
@PolarisTLX It sounds like the `ssl-check` script isn't on your path. Just echo out the results of the $PATH variable and store it somewhere there. I should also point out that I've tested this on Mac -- but am not completely sure it works on Linux.
