### ISSUE TITLE
Previewing broken after setting up Localhost SSL Certificate

### ISSUE THREAD

**Issue by shopcreatify-quintin** [Shopify/slate#727]
### Problem

I followed the instructions here:

https://github.com/Shopify/slate/wiki/How-to-create-a-trusted-local-SSL-certificate

Once this was done, assets being served from the "external" server (10.0.0.102) started being blocked:

![screen shot 2018-09-06 at 2 56 55 pm](https://user-images.githubusercontent.com/41347963/45158813-74ccb500-b1e5-11e8-8242-a125a1984fb6.jpg)

Removing the certificate now simply blocks access to localhost and Chrome doesn't allow me to view the site because of a privacy notice. Even after setting Chrome to allow insecure localhost (per https://stackoverflow.com/questions/35565278/ssl-localhost-privacy-error) the 10.0.0.102 assets are still not reachable.

Please assist? Thanks :)

**Comment by t-kelly** [comment]
Hey @shopcreatify-quintin -- this is a side-effect of https://github.com/Shopify/slate/pull/712. Still working out the kinks.

For now, try visiting `https://10.0.0.102:3001` in your browser and telling it to trust this URL. Alternatively, if you don't need mobile device testing right now, you can revert to `beta.6` and your SSL cert should work fine!

**Comment by shopcreatify-quintin** [comment]
Thanks for the quick response, @t-kelly . You're a lifesaver.

**Comment by t-kelly** [comment]
Going to close this in preference of #726
