### ISSUE TITLE
Add JSON Linting

### ISSUE THREAD

**Issue by jonathanmoore** [Shopify/slate#732]
### Problem

When editing section schema / JSON settings or the large `settings_schema.json` file quite often I'll forget a comma, add a trailing comma or some other typo.  Slate (technically Shopify servers) will return a generic error that doesn't make it easy to track down the problem.

```
[development]: 1 / 1 [====================================================================] 100 %
13:05:41 [development]Asset Perform Update to sections/collection-list.liquid at host **********.myshopify.com
        Status: 422 Unprocessable Entity
        Errors: Invalid JSON in tag 'schema'
```

### More Information

In addition to adding liquid linting (#422), it would be helpful to add linting for JSON files or the contents of the schema blocks.  Personally, I would even like to see an opinionated package like prettier added to avoid mistakes altogether.

**Comment by t-kelly** [comment]
Does `slate-tools lint --json` not work?
