### ISSUE TITLE
Beta 7 not working

### ISSUE THREAD

**Issue by diegopelaez** [Shopify/slate#733]
I first tried to update my current project to beta 7 and it broke, then I tried to create a new theme from scratch to verify if it was just something related to my theme but it wasn't, the whole Beta7 is not working for me

/
![screen shot 2018-09-07 at 2 09 06 pm](https://user-images.githubusercontent.com/42366471/45198044-c9386900-b2a7-11e8-92cd-cd4fac89a2d4.png)

*Succinct outline of the problem or request.*

### Replication steps

Follow the documentation for Slate, create a new project with
``` yarn create slate-theme my-new-theme ```

In my case, I had to run from the new theme:

``` yarn install ``` 

Then setup your local .env file and run
``` yarn start ```

Then the browser loads which in this version redirects you to a localhost:3000 url instead of the normal shopify url as in previous versions, then I check the console and I get this:

![screen shot 2018-09-07 at 2 09 06 pm](https://user-images.githubusercontent.com/42366471/45198044-c9386900-b2a7-11e8-92cd-cd4fac89a2d4.png)

No assets is getting loaded from my local, looks like the local server is not running correctly. Did I missed something?

**Comment by jonathanmoore** [comment]
Duplicated of issue #726 

Beta 7 switched to BrowserSync to allow for easier mobile device testing.  With the change, you have to manually proceed with the "Not Secure" prompt by visiting 192.168.2.194. There are more details, as well as feedback on solutions in the open issue.

**Comment by t-kelly** [comment]
@jonathanmoore is correct in that it looks like you need to visit `https://192.168.2.194:3001` and tell your browser to trust it. Should work fine after that!

**Comment by diegopelaez** [comment]
Thanks @jonathanmoore and @t-kelly this works for me, I had to open the https://192... link in another window then accept the security warning and refresh my page and it all worked
