### ISSUE TITLE
importing js.liquid files within theme.js?

### ISSUE THREAD

**Issue by Kehza** [Shopify/slate#734]
Has anyone figured this out? Whenever I used a liquid variant of the file everything comes back undefined, even with simple tests such as: 

test.js.liquid
export const test = 1; 

thene.js
import test from '../test.js.liquid'
console.log(test);

Result is undefined. 

But if I rename "test.js.liquid" to 'test.js' it works fine. 

If i try using the old school method of just referencing the the path in the theme.liquid header, then I run into dependency issues with JQuery. If there's a way to make JQuery global but within ES6 that would also be an option.. 

Any advice is appreciated!

**Comment by dan-gamble** [comment]
For starters if you wanted to import `test` it would be `import { test } from '../test.js.liquid` as it's not a default export

Is there a reason you're wanting to import a `.js.liquid` as opposed to just a `.js` file?

It's quite a common pattern to have any liquid variables you want in JS to be passed by data attributes like `data-variable-i-want="{{ liquid_variable }}"` and then access them in JS that way

**Comment by Kehza** [comment]
Apologies I've been using e.g. { test } just missed it out in my example. In this scenario I'd like access to the collection object, I know that I can use work-around such as data attributes, or JSON objects but ultimately it would be a lot easier to have the liquid functionality too.

**Comment by dan-gamble** [comment]
You're right in the best way would be something like:

```liquid
<script type="application/json" data-collection-json>
  {{ collection | json }}
</script>
```

I'd strongly advise going this route as it would make your code a lot easier to maintain and reason with.

I'm speaking for myself here but i think one of the goals of Slate is to help produce better and cleaner code for Shopify and preventing a mix of liquid and JS / Sass by stopping the `theme.js.liquid` and `theme.scss.liquid` is only a good thing.

I'll be more than happy to help you try and fix your issue if you want to outline in a bit more detail.

**Comment by Kehza** [comment]
Thanks @dan-gamble - this solution appears to have worked.

**Comment by t-kelly** [comment]
@dan-gamble is right in that the more you can reduce the spread of liquid, the easier your life will be. His proposed solution is what I would recommend as well!
