### ISSUE TITLE
Different behaviour per website using Slate

### ISSUE THREAD

**Issue by brandammo** [Shopify/slate#741]
I have two separate clients i am working on themes for. I have set both up in the same way, but both are behaving slightly differently.

As you can see from the screen shots below. I am seeing different information in the terminal for each site when starting slate up.

Everything works, apart from the browser-sync which has no effect (no refresh) on the site displayed in the first screen shot.

I'd really appreciate some help understanding why they are different?

Not working as expected:
![screenshot 2018-09-11 13 46 17](https://user-images.githubusercontent.com/2786007/45361790-031cae80-b5cb-11e8-8943-8b670c6d199b.png)

This works perfectly:
<img width="559" alt="screenshot 2018-09-11 13 49 09" src="https://user-images.githubusercontent.com/2786007/45361791-031cae80-b5cb-11e8-822f-c8e158b3da37.png">

**Comment by dan-gamble** [comment]
This is due to you using Slate version `v1.0.0-beta.7` on your first site and a version less than that on your 2nd.

`v1.0.0-beta.7` introduced a new Browserync mode and you might have to revisit your asset url again to verify the ssl cert

**Comment by brandammo** [comment]
Thanks for your help so far...

Unfortunately this had no effect. I also get a blank Browsersync control panel if i visit via the local url provided in the terminal. Not sure if this is expected behaviour?

When the browser opens the preview of the site it opens via the localhost url (https://localhost:3000/?preview_theme_id=35900981317). Is this correct also?

**Comment by dan-gamble** [comment]
If you check your `package.json` of each product you should see the version of `@shopify/slate-tools` is `v1.0.0-beta.7`. You can downgrade this to `v1.0.0-beta.6` in the interim to get it working again.
