### ISSUE TITLE
color swatches in Venture theme problem

### ISSUE THREAD

**Issue by blackos-dorara** [Shopify/slate#747]
I've tried to include swatches in the Venture theme according to [this manual](https://help.shopify.com/en/themes/customization/products/features/add-color-swatches) and was wondering if anyone was able to do that? At the beginning of the tutorial it says that it might not work for the Venture and the Boundless theme, but since there are a lot of smart guys here in the forum, I thought maybe someone knows better.  

Actually, I'm able to follow this tutorial until Locate your selectCallback function as I can't seem to find it. If someone could give me a hint that'd be great

**Comment by t-kelly** [comment]
This issue is [out of scope](https://github.com/Shopify/slate/blob/master/CONTRIBUTING.md#scope) for this repo. This is not a theme development forum.
