### ISSUE TITLE
Liquid in JS in slate?

### ISSUE THREAD

**Issue by adrianocr** [Shopify/slate#758]
### Problem

Before with shopify themes you could have a filename.js.liquid file and inside liquid tags for things like getting an image url was perfectly fine. But now with the whole new slate concept and webpack, it seems that's not possible? So if I need to add an image url to an element via something like `$('.target').append("<img src='" + {{ 'imagename.jpg | asset_img_url: 'master' }} + " ' >")` how is it done?

**Comment by qw-in** [comment]
I'm not sure what the reccomended approach is but two viable options are:


1. Have a single `*.js.liquid` file in `assest/static` imported at the top of `theme.liquid`. In this file retrieve the liquid variables and bind them to  `window`.
1. Add liquid variables as HTML data and access it with javascript
```
  <!--collection.liquid-->
  <div id="src" data-src="{{ liquid }}" >
```
```
// collection.js
const src = $('#src').attr('data-src');
```

**Comment by dan-gamble** [comment]
2nd is definitely the recommended approach. You should separate your liquid and JS completely.

**Comment by t-kelly** [comment]
I have no interest in supporting `.js.liquid` files as they don't play well with any other JS tooling nor are you writing in valid JS syntax which breaks syntax highlighting.

@qw-in @adrianocr  what we typically do is use the JSON liquid filter in an inline script tag:

```
<script type="type="application/json">
  {{ product | json }}
</script>
```

Or assign values to a global object in your `<head>`:
```
<script>
window.Shopify.theme.liquidVars = {
  product: {{ product | json }}
}
</script>
```
(It's been a while so this might not work directly with a copy and paste but you should get the idea of whats going on! 😅)
