### ISSUE TITLE
External Link Not Visible Outside of Network

### ISSUE THREAD

**Issue by callaginn** [Shopify/slate#759]
### Problem
The "external link" provided by Slate Tools does NOT work externally. That is, it ONLY works within my local network.

<img width="100%" alt="screen shot 2018-09-17 at 12 50 37 pm" src="https://user-images.githubusercontent.com/2430211/45640496-736a7a80-ba78-11e8-8b40-aedb4fdfff4f.png">

### Replication steps
- Start Slate using `yarn start`
- Viewing the site with the external link (https://10.0.1.2:3000) works. However, viewing that link outside of the network either shows a blank page or "site can't be reached" error page. This means clients can't view the progress of our site during development.

### More Information
- macOS High Sierra 10.13.4
- Using Slate v1.0.0-beta.7
- Chrome 68.0.3440.106 (Official Build) (64-bit)

I should also mention that both the internal and external BrowserSync control panel doesn't work correctly, no matter what computer it's viewed at inside our network. Plugin loads, but no content is visible:
<img width="100%" alt="screen shot 2018-09-17 at 1 02 27 pm" src="https://user-images.githubusercontent.com/2430211/45641076-0a840200-ba7a-11e8-95e3-ca6dd5fc4418.png">

Gives me a bunch of console errors instead:
<img width="100%" alt="screen shot 2018-09-17 at 1 06 48 pm" src="https://user-images.githubusercontent.com/2430211/45641268-9bf37400-ba7a-11e8-8c18-323173583ab3.png">

### Solution?
All that being said, is there a way to view sites that are being actively developed with Slate outside of our network?

**Comment by JPrisk** [comment]
The most common solution to this problem is to have two themes setup on your Shopify site. One for production and one for development. You can publish and deploy your code to the production theme and continue working on the development theme using preview. Having this setup alows you to provide a client with the mystore.myshopify.com URL to review

**Comment by callaginn** [comment]
Ok, that kinda makes sense. So would a workflow like this work?

## Setup
- Keep my current development theme id in `.env`.
- Duplicate my current theme as "production" and add the new theme id to `.env.production`.
- Add an `--env=production` flag to the package.json "scripts.deploy" section:
```
"scripts": {
    "start": "slate-tools start",
    "watch": "slate-tools start --skipFirstDeploy",
    "build": "slate-tools build",
    "deploy": "slate-tools build && slate-tools deploy --env=production",
    "zip": "slate-tools build && slate-tools zip",
    "lint": "slate-tools lint",
    "format": "slate-tools format"
}
```

### Local Development
Since Slate defaults to `.env`, only my "development" theme would change when I run `yarn start`, `yarn watch`, etc? And since I'm developing locally, I don't see any reason to "deploy" to my dev theme. This would be accessible via Slate's localhost:3000 link.

### Production / Proofing
Due to my changes above, running `yarn deploy` would rebuild my site and push it to the production theme? Since this would be accessible via the public mystore.myshopify.com link, I could share daily snapshots with clients.

**Comment by dan-gamble** [comment]
That's pretty much the exact same workflow i use @callaginn. This way you can work on a site without affecting the live theme at all.

**Comment by t-kelly** [comment]
@callaginn if you realllly want, you can use a service like https://forwardhq.com/. Though I might need to ship https://github.com/Shopify/slate/issues/757 before thats possible again.. Haven't tested it.
