### ISSUE TITLE
Browsersync not working

### ISSUE THREAD

**Issue by lukasentebbe** [Shopify/slate#761]
### Problem

After setting up the latest Slate Version and also setting up a SSL for Localhost local dev process is working without any console errors. However the Browsersync is not working at all.

https://localhost:3002 --> Cannot reach site
http://xxx.xxx.x.xxx:3002 --> Panel is showing up but not working

Any hints ?
Also: Is there any browsersync config file?

**Comment by dan-gamble** [comment]
Do you have something else running on `3000`? Normally the port is `3000`. Not sur eif that would help

**Comment by lukasentebbe** [comment]
No nothing running on this port.

**Comment by dan-gamble** [comment]
Are you sure you don't have 2 instances of this running? The fact it's running on port `3000` seems to be an indicator that something is awry, just not sure what.

**Comment by lukasentebbe** [comment]
Sorry for the misunderstanding:
The Site is running on 3000 and working without Browsersync.
Browsersync Control Panel under 3002 is showing up but not working.

**Comment by t-kelly** [comment]
This is a problem with the browser defaulting to `https://` for localhost after you've gone there at least once. Try opening a new incognito window and going to `http://localhost:3002` (note the panel is on http not https).

`http://xxx.xxx.x.xxx:3002` should be working... hmmm

**Comment by lukasentebbe** [comment]
Thanks for the comment. Yes i noticed. Browsersync Panel is now reachable on both  localhost and IP Adress. Still the Panel it self is not showing any info. Also Browsersync it self is not working on `3000` while developing.

**Comment by t-kelly** [comment]
Have you visited `https://xxx.xxx.xxx.xxx:3000` or `https://xxx.xxx.xxx.xxx:3001` and told the browser to trust the URL? 

Going to need more details (errors, logs) @lukasentebbe.

**Comment by tonyd256** [comment]
@t-kelly I'm having the same issues so maybe I can help by providing more info.

Here is a screen shot
<img width="1680" alt="screen shot 2018-10-15 at 11 56 24 am" src="https://user-images.githubusercontent.com/1169797/46972484-78204f80-d073-11e8-8240-d3bfcffceced.png">

Here is the request that is failing to load
<img width="912" alt="screen shot 2018-10-15 at 12 12 30 pm" src="https://user-images.githubusercontent.com/1169797/46972588-a736c100-d073-11e8-8e45-13f941d59a98.png">

These are the only errors I'm seeing

**Comment by t-kelly** [comment]
@tonyd256 I added a new page to the getting started guide, [Creating a self-signed SSL cert](https://github.com/Shopify/slate/wiki/4.-Create-a-self-signed-SSL-certificate). Can you give that a try?

Also, try checking @huguestennier branch of his PR https://github.com/Shopify/slate/pull/820

**Comment by tonyd256** [comment]
@t-kelly yup looks like beta11 fixed it for me. Thanks!
