### ISSUE TITLE
Browsersync not working - browsersync socket doesn't look to be secure.

### ISSUE THREAD

**Issue by adamrasheed** [Shopify/slate#763]
### Problem

When I run `yarn start` or `yarn watch`, I get a new tab that automatically opens to show the preview, but it won't update any style changes or javascript changes, nor refresh the page when I make changes to any `.liquid`.

However, I see the upload screen happen in the terminal when I change `liquid` files, and 

I also get the following errors in the console (that keeps repeating):
`https://192.168.100.81:3000/browser-sync/socket.io/?EIO=3&transport=polling&t=MNrS5OM net::ERR_CERT_COMMON_NAME_INVALID`. I've tried this in safari as well, and while I don't get the same console log errors, I still have the same problems.

I've also clicked on the `https://localhost:3001/`which the terminal tells me is the location where 'Assets are being served from:'. The screen just shows a 'Cannot GET /' and the console shows a 404  message. Maybe that's the problem? Because when I run `yarn deploy` all the changes show up just fine to the shopify theme.

Note: I've already added localhost as "always trusted" as instructed in the wiki.

### Replication steps

- spin up a slate project

### More Information

env:
⇒  npm: 6.4.1
⇒  yarn: 1.9.4
⇒  node: v8.12.0

Please help!

**Comment by t-kelly** [comment]
Hey @adamrasheed -- I've added a [new note at the top of the SSL Certificate Guide](https://github.com/Shopify/slate/wiki/How-to-create-a-trusted-local-SSL-certificate) since releasing Browsersync. 

For now, you'll need to visit `https://192.168.100.81:3000` and confirm to the browser to trust the URL. Things should work fine after that!

**Comment by dan-gamble** [comment]
@t-kelly when you say "For now", does this mean something is in the pipeline for this to not be the case? Is it part of that issue you mentioned with BrowserSync up the chain?

**Comment by t-kelly** [comment]
> does this mean something is in the pipeline for this to not be the case?

It is something that can definitely be improved (ideally you can make a self-signed cert that works like before) but I haven't had the chance to investigate so nothing solid in the pipeline.

**Comment by dan-gamble** [comment]
Fair enough, thanks for the insight Tom 🤙

**Comment by adamrasheed** [comment]
@t-kelly I actually already did that :/ (Adding 'always trust' to the localhost cert) When I do to go `https://192.168.100.81:3001` and click on trust it takes me the a blank page that says 'Cannot GET/' and the console is showing a 404 error. Anything else I should be doing?
