### ISSUE TITLE
Yarn Start - ReferenceError: alias is not defined

### ISSUE THREAD

**Issue by thedesignersdeveloper** [Shopify/slate#764]
### Problem
Hey there, 
I'm having an issue attempting to connect my them to the online store. When i run 'yarn start' from terminal on a mac I get this.

/Users/brendanfoster/albertandnikola/slate.config.js:9
    dev: {resolve: {alias}},
                    ^
ReferenceError: alias is not defined
    at Object.<anonymous> (/Users/brendanfoster/albertandnikola/slate.config.js:9:21)

### Replication steps

See Screenshot.
<img width="768" alt="screen shot 2018-09-20 at 2 13 51 pm" src="https://user-images.githubusercontent.com/40186658/45799313-99458880-bcdf-11e8-9142-d5398a3b7baa.png">

### More Information

I have my .env file setup with the connection and the private app set to read-write.

**Comment by huguestennier** [comment]
Can you copy the content of `slate.config.js` here?

**Comment by thedesignersdeveloper** [comment]
You are one great human being. 

Just copied the updated slate.config.js files content from the repo. Deleted my old code and pasted the new code in. Working perfectly now.

Thanks so much and have an amazing day.
