### ISSUE TITLE
Localhost asks for domain purchase

### ISSUE THREAD

**Issue by dilby** [Shopify/slate#767]
### Problem

*Succinct outline of the problem or request.*

### Replication steps

*How to replicate the problem. Screenshots or video?*

### More Information

*Any additional information which might be helpful.*

**Comment by dan-gamble** [comment]
@dilby i think you need to provide slightly more information

**Comment by dilby** [comment]
Hi all -

I've followed the steps to setting up Slate in [Shopify's slate webiner video](https://www.youtube.com/watch?v=36Rfv_TeQRY&t=1377s) but when I use the 'slate watch' command, the browser goes to 'https://localhost:3000/?preview_theme_id=32614809661'
and gives me the following notice:

```
Only one step left!
To finish setting up your new web address, go to your domain settings, click "Connect existing domain", and enter: localhost
```

From what I can see in the docs the port is normally 8080 but I never set anything up differently, and am unsure how to stop shopify giving me this notice. Thanks!

**Comment by dilby** [comment]
Sorry I didn't mean to post when I did!

**Comment by dan-gamble** [comment]
No worries @dilby just wanted to bring it to your attention just incase you hadn't realised :)

Have you tried it with `yarn start`? The `:3000` is normal.

Are you able to provide a screenshot with any sensitive information blurred out?

**Comment by dilby** [comment]
Thanks for swift reply. I get a command not found on yarn start, am I missing something?

<img width="945" alt="image 2018-09-21 at 1 43 51 pm" src="https://user-images.githubusercontent.com/6115730/45881885-64e7d000-bda4-11e8-94e9-9f6e9065a6d3.png">

**Comment by dan-gamble** [comment]
I've just checked the date on that video, that might be using the older version of Slate.

I'd recommend going to the Wiki, specifically [this page](https://github.com/Shopify/slate/wiki/Getting-Started) and trying the setup again. This will be using the current version of Slate which might alleviate your issue.

**Comment by dilby** [comment]
Thanks dan, good advice. Might be worth updating the description there then. I'll give it a go and let you know!

**Comment by dilby** [comment]
Do you know recommended method to uninstall?

**Comment by dan-gamble** [comment]
Hey @dilby. There shouldn't necessarily be a method of uninstalling, you should be able to just get up and go with the current Slate installation instructions. I've not used the old version of Slate though so i may be slightly wrong on that.

**Comment by t-kelly** [comment]
@dilby no harm in leaving v0 on your machine, there is no conflict with v1.

Otherwise you can run `npm uninstall @shopify/slate -g` and that should remove v0.

**Comment by t-kelly** [comment]
@dilby make sure you're adding the space:
```
yarn create slate-theme my-theme
```
Shouldn't need to change anything -- it should run and create a folder called `my-theme` with your theme contents.
