### ISSUE TITLE
Missing required files,  but really not

### ISSUE THREAD

**Issue by jeroesguerra** [Shopify/slate#770]
When launching Yarn Start, I receive this error in my local server

<img width="1034" alt="screen shot 2018-09-22 at 6 06 38 pm" src="https://user-images.githubusercontent.com/29985602/45923134-6bed0c00-be92-11e8-880d-6494c6cb690d.png">

However, after checking if I am missing any files, I found them all.

<img width="358" alt="screen shot 2018-09-22 at 6 06 50 pm" src="https://user-images.githubusercontent.com/29985602/45923139-78716480-be92-11e8-9675-c64e775f66a7.png">
<img width="593" alt="screen shot 2018-09-22 at 6 06 57 pm" src="https://user-images.githubusercontent.com/29985602/45923140-78716480-be92-11e8-8140-68915713cea7.png">
<img width="438" alt="screen shot 2018-09-22 at 6 07 07 pm" src="https://user-images.githubusercontent.com/29985602/45923141-78716480-be92-11e8-96f9-6e96bc963e6d.png">

Not entirely sure what I should do next

**Comment by t-kelly** [comment]
As stated in the README, Slate v1 has not yet been tested on Windows so there are bound to be bugs. Will leave this open until we have the chance to tackle Windows compatibility.

**Comment by jeroesguerra** [comment]
However, I’m using a MacBook Pro.

**Comment by t-kelly** [comment]
😅 

Check your Theme ID -- I've seen this when you upload to a theme ID that doesn't exist.
