### ISSUE TITLE
SSL certificate doesn't work with new Browsersync setup

### ISSUE THREAD

**Issue by t-kelly** [Shopify/slate#777]
### Problem

We've regressed back to needing to visit `https://xxx.xxx.xxx.xxx:3000` and telling the browser to trust the URL every few days. This isn't as nice as [creating a self-signed certificate](https://github.com/Shopify/slate/wiki/How-to-create-a-trusted-local-SSL-certificate) once and never needing to worry about it again.

Let's try and get this working again!

**Comment by ianseverance** [comment]
I can't even get that to work (telling the browser to trust the URL). Very frustrating experience as a first time user of Slate. I followed the directions for getting started but https still doesn't work. What do I do?

**Comment by josephchan91** [comment]
Ran into the same issue. Running 'yarn deploy' as mentioned [here](https://github.com/Shopify/slate/issues/726) works.

**Comment by t-kelly** [comment]
Related https://github.com/Shopify/slate/issues/726 -- closing this issue to keep discussion in one place.
