### ISSUE TITLE
The `forget password click event` of login page would lose if you update slate-tools to 1.0.0-beta.9

### ISSUE THREAD

**Issue by hitoweb** [Shopify/slate#787]
### Problem

After updating `@shopify/slate-tools` to `1.0.0-beta.9`, the `forget password` link on the login page cannot work. By checking the code and adding some console outputs, I found that the file `src/assets/scripts/templates/customers/login.js` is not loaded automatically. So the click definition does not work.

```
$(selectors.recoverPasswordForm).on('click', onShowHidePasswordForm);
``` 

### Replication steps

Update the `@shopify/slate-tools` to `1.0.0-beta.9` in your project based on `starter-theme`.

### More Information

It will be ok if you recover `@shopify/slate-tools` to `1.0.0-beta.8`.

**Comment by t-kelly** [comment]
Hey @hitoweb -- could you open this in the [Starter Theme repo](https://github.com/Shopify/starter-theme) since this is a theme specific problem not a problem with Slate. Thanks!
