### ISSUE TITLE
SCSS not compiling

### ISSUE THREAD

**Issue by liamtucker** [Shopify/slate#788]
### Problem

I'm no longer able to compile scss assets to preview in either local or remote (It was before). Running 'yarn start' powers up the express server but no scss is being rendered. I have tried starting with a blank slate theme.

There's not enough documentation for me to debug anything. I also don't understand why theres a theme.scss and theme.scss.liquid under src/assets/styles

Neither of these files are getting processed as far as I can see.

### Replication steps

- Create new theme using 'yarn create slate-theme my-theme'
- Connect .env file to store
- run yarn start
- Change scss in any of the files under src/assets/styles
- Preview on local or remote servers (no changes rendered)

**Comment by huguestennier** [comment]
Have you made sure you visited the local assets server once as described here ? https://github.com/Shopify/slate/wiki/4.-Start-developing

You can also create a local SSL certificate so you don't have to visit the URL everytime as described here : https://github.com/Shopify/slate/wiki/How-to-create-a-trusted-local-SSL-certificate

**Comment by liamtucker** [comment]
Hi @huguestennier 

I had done both of those things but doing again has resolved it on the local server. However I still have to do this every time even after following the steps described here: https://github.com/Shopify/slate/wiki/How-to-create-a-trusted-local-SSL-certificate

Also, when I run 'yarn build' the styles are still not compiled/visible on the remote store? 

I may just be coming at this wrong, but I'm struggling to understand how any of it works with the current documentation

**Comment by huguestennier** [comment]
> Also, when I run 'yarn build' the styles are still not compiled/visible on the remote store?

`yarn build` is not enough, you need to run `yarn deploy` to deploy all your assets on Shopify.

> I may just be coming at this wrong, but I'm struggling to understand how any of it works with the current documentation

We're definitely adding documentation soon make this step clearer.

**Comment by liamtucker** [comment]
Thanks @huguestennier yep that worked.

For me in general the entire slate process is still very complicated. I think with better documentation around file structures and processing/compiling that will help

**Comment by huguestennier** [comment]
Gonna close this issue, but rest assured we're always trying to improve our docs 😄
