### ISSUE TITLE
Webpack Load Order Breaks JS Dependencies

### ISSUE THREAD

**Issue by callaginn** [Shopify/slate#789]
### Problem
The way Webpack loads modules baffles me. I believe it's a combination of the order it all loads in, as well as the usage of the "defer" and "<link preload" attributes.

In fact, everything loaded via webpack seems to create load order issues. The ONLY thing that seems reliable is to remove ALL javascript from the "scripts" folder and resort to using either regular CDN <script> links or liquid includes.

### Replication Steps
1. Add Bootstrap to your project using `yarn add bootstrap`.
2. Import Bootstrap into theme.js as individual imports. This will be added to the `<head>` of the site, of course, using the default `{% include 'script-tags', layout: 'theme' %}` code.
    ```
    import 'bootstrap/js/dist/util.js';
    import 'bootstrap/js/dist/alert.js';
    import 'bootstrap/js/dist/button.js';
    import 'bootstrap/js/dist/carousel.js';
    import 'bootstrap/js/dist/collapse.js';
    import 'bootstrap/js/dist/dropdown.js';
    import 'bootstrap/js/dist/modal.js';
    import 'bootstrap/js/dist/tooltip.js';
    import 'bootstrap/js/dist/popover.js';
    import 'bootstrap/js/dist/scrollspy.js';
    import 'bootstrap/js/dist/tab.js';
    ```
2. Add the following code to the very BOTTOM of theme.liquid to trigger modals when certain URL parameters are detected.
    ```
    <script>
        // Link directly to modals
        function getUrlParameter(sParam) {
            var sPageURL = decodeURIComponent(window.location.search.substring(1)),
               sURLVariables = sPageURL.split('&'),
                sParameterName,
                i;

            for (i = 0; i < sURLVariables.length; i++) {
                sParameterName = sURLVariables[i].split('=');
    
                if (sParameterName[0] === sParam) {
                    return sParameterName[1] === undefined ? true : sParameterName[1];
                }
            }
        }
    
        $(function() {
            var modal_class = getUrlParameter('modal');
    
            if (modal_class !== undefined) {
                $('#modal-' + modal_class).modal('show');
        	}
        });
    </script>
    ```
3. Visiting "https://localhost:3000/pages/calendar?modal=success" should show a "success" modal. However, it triggers an "uncaught error exception" instead:
    <img width="642" alt="screen shot 2018-10-01 at 12 58 02 pm" src="https://user-images.githubusercontent.com/2430211/46306364-b26cf580-c579-11e8-8109-8e944f7fe22a.png">

### Solution?
We typically don't load scripts with "defer", "async", or "preload" attributes on our sites, since we've found that creates issues like this. That being said, I realize there are performance benefits to doing things this way. I'm pretty comfortable with javascript and bash, but am not familiar with how webpack, ES6 modules, or JS promises work.

Can someone please explain a viable way of dealing with javascript load order issues in Slate, without resorting to external links?

**Comment by huguestennier** [comment]
Bootstrap requires jQuery - so first question, did you also add jQuery to your project?

**Comment by jonathanmoore** [comment]
Unfortunately, the approach you're taking is not going to work.  Since step 3 mentions that you're including script tags that reference jQuery and other dependencies included via webpack, your script tags on the page are not going to have scope to any of the packages.

All of the JS to read the URL params and trigger a popup will need to be added to the theme.js file or better yet one of the template specific JS files.

**Comment by huguestennier** [comment]
Exactly like @jonathanmoore said. You should have something like this : 

`theme.js` (or even better, `specific-sections.js`)

```JS
import $ from 'jquery';
import 'bootstrap/dist/js/bootstrap.bundle.min.js';

// Link directly to modals
    function getUrlParameter(sParam) {
        var sPageURL = decodeURIComponent(window.location.search.substring(1)),
           sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] === sParam) {
                return sParameterName[1] === undefined ? true : sParameterName[1];
            }
        }
    }

    $(function() {
        var modal_class = getUrlParameter('modal');

        if (modal_class !== undefined) {
            $('#modal-' + modal_class).modal('show');
    	}
    });

```

Everything should work fine.

**Comment by callaginn** [comment]
@huguestennier Yes, I tried loading jQuery a couple of different ways -- but every method seems to have drawbacks.

a. At first I was using `import 'jquery'` within theme.js, but that gave me all sorts of "Uncaught Exception" errors. Bootstrap worked, but no external scripts fired.
<img width="846" alt="screen shot 2018-10-02 at 9 22 15 am" src="https://user-images.githubusercontent.com/2430211/46354679-c02b8500-c624-11e8-8525-b05cbcb88ef5.png">

b. Adding the following code to theme.js initially didn't help...
```
import $ from 'jquery';
window.jQuery = $;
window.$ = $;
```

...until I added the regular <script> import to the top of theme.liquid. That fixed a few plugins, but still broke SlickSlider (which was being imported via a data-module).
<img width="588" alt="screen shot 2018-10-02 at 9 39 57 am" src="https://user-images.githubusercontent.com/2430211/46355836-3204ce00-c627-11e8-8f13-6e8c8b1f8e19.png">

I'm not a scientist, but that seems to tell me that there's a load order issue. I think my init function is loading before the actual plugin -- since all the webpack plugins load with the defer attribute.

**Comment by callaginn** [comment]
@jonathanmoore:

# Webpack Clarification
> Unfortunately, the approach you're taking is not going to work. Since step 3 mentions that you're including script tags that reference jQuery and other dependencies included via webpack, your script tags on the page are not going to have scope to any of the packages.

1. Is this similar to how variables set within a JS function can't be read outside that function?

> All of the JS to read the URL params and trigger a popup will need to be added to the theme.js file or better yet one of the template specific JS files.

2. So if I have three pages with slideshows that require different init code, there would need to be three webpack modules? I'm not used to dealing with scope issues; we typically just import a JS script once (without async) and initialize it differently on different pages. Or would the best way to handle that is to add conditional statements for that init code to ONE file in sections.js?

3. A lot of the plugins I'm using require jquery and/or bootstrap. So if I'm importing several modules with overlapping imports -- could that result in duplicate JS code?

# Current Setup / New Issues
Since you seem to indicate webpack modules don't have the same scope as <script> tags within templates, I moved my plugins, their dependencies, and init code to individual script files. Btw, I added all these scripts to my project using yarn beforehand.

**So here's my current setup:**

### theme.js (new double-click issue)
*New Issue:* Moving the <script> tags into webpack JS files, breaks Bootstrap nav dropdowns. That is, you have to click twice on them before they start working. Curiously, BS modals do not have this issue.
```
// CSS Styles
import '../../styles/hcbc.scss';
import '../../styles/fullcalendar-theme.scss';

// JQuery
import $ from 'jquery';

// Bootstrap v4
import 'bootstrap/js/dist/util.js';
import 'bootstrap/js/dist/alert.js';
import 'bootstrap/js/dist/button.js';
import 'bootstrap/js/dist/carousel.js';
import 'bootstrap/js/dist/collapse.js';
import 'bootstrap/js/dist/dropdown.js';
import 'bootstrap/js/dist/modal.js';
import 'bootstrap/js/dist/tooltip.js';
import 'bootstrap/js/dist/popover.js';
import 'bootstrap/js/dist/scrollspy.js';
import 'bootstrap/js/dist/tab.js';

// Javascript Plugins (work)
import 'lazysizes/plugins/object-fit/ls.object-fit';
import 'lazysizes/plugins/parent-fit/ls.parent-fit';
import 'lazysizes/plugins/rias/ls.rias';
import 'lazysizes/plugins/bgset/ls.bgset';
import 'lazysizes';
import 'lazysizes/plugins/respimg/ls.respimg';

// See https://github.com/Shopify/slate/issues/720#issuecomment-417390252
Array.from(document.querySelectorAll('[data-module]')).forEach(el => {
    const name = el.getAttribute('data-module')
    const Module = require(`../modules/${name}`).default
    new Module(el)
});
```
### Modal Direct Linking (works)
The following code was added to `scripts/modules/modals.js` and added to each page that requires it via a data-module="modals" element:
```
export default class TestModule {
    constructor (el) {
        this.el = el
    }
}

import $ from 'jquery';
import 'bootstrap';

// Link directly to modals
function getUrlParameter(sParam) {
    var sPageURL = decodeURIComponent(window.location.search.substring(1)),
        sURLVariables = sPageURL.split('&'),
        sParameterName,
        i;

    for (i = 0; i < sURLVariables.length; i++) {
        sParameterName = sURLVariables[i].split('=');

        if (sParameterName[0] === sParam) {
            return sParameterName[1] === undefined ? true : sParameterName[1];
        }
    }
}

$(function() {
    var modal_class = getUrlParameter('modal');

    if (modal_class !== undefined) {
        console.log("Show Modal: " + '#modal-' + modal_class)
		$('#modal-' + modal_class).modal('show');
	}
});
```

### Slick Carousel (works)
The following code was added to `scripts/modules/slider.js` and added to each page that requires it via a data-module="slider" element:
```
export default class TestModule {
    constructor (el) {
        this.el = el
    }
}

import $ from 'jquery';
import 'slick-carousel';

$(function() {
    var $slider = $('.slider');

    $slider.slick({
        fade: true,
        dots: true,
        speed: 500,
        infinite: true,
        autoplay: true,
        autoplaySpeed: 4000,
        pauseOnHover: false,
        mobileFirst: true
    });
});
```
### FullCalendar Custom View (Works)
The following code was added to `scripts/modules/calendar.js` and added to each page that requires it via a data-module="calendar" element:

```
export default class TestModule {
    constructor (el) {
        this.el = el
    }
}

import $ from 'jquery';
import 'moment'
import 'fullcalendar'
import 'fullcalendar/dist/gcal'

var $calendar = $('#calendar-wrap');
var eventLimit = 7;

// Custom FullCalendar Views
var FC = $.fullCalendar; // a reference to FullCalendar's root namespace
var View = FC.View;      // the class that all views must inherit from
var CustomView;          // our subclass

// Create a Custom View Subclass
CustomView = View.extend({
    render: function() {
        var events=$calendar.fullCalendar('clientEvents');

        var events_asc = function(date1, date2) {
            var eventDate1 = date1.start._i;
            var eventDate2 = date2.start._i;
            return (eventDate1 > eventDate2) ? 1 : (eventDate1 < eventDate2) ? -1 : 0;
        };

        events.sort(events_asc);
        console.log(events);

        var counter = 0;
        events.forEach(function(item) {
            var currentDate = moment().format("YYYY-MM-DDTHH:mm:ssZ");
            var eventDate = '<small>' + moment(item.start._i).format("MMM") + '</small>' + moment(item.start._i).format("DD");
            var eventStart = moment(item.start._i).format("h:mma");
            var eventEnd = moment(item.end._i).format("h:mma");
            var eventRange = eventStart + '&thinsp;&ndash;&thinsp;' + eventEnd;
            var eventTitle = '<h5 class="mb-1 event-title">' + item.title + '</h5>';

            // Only insert future dates...
            if (item.start._i >= currentDate && counter < eventLimit) {
                counter++;
                $('.fc-view').append('<div class="event mt-3 text-crop"><span class="date">' + eventDate + '</span>' + eventTitle + eventRange + '</div>');
            }
        });
    }
});

FC.views.custom = CustomView; // register our class with the view system

$(function() {
    $calendar.fullCalendar({
        googleCalendarApiKey: 'XXX',
        events: 'XXX@import.calendar.google.com'
    });

    // For some reason, I have to delay changing to the new view by half a second
    setTimeout(function() {
        $calendar.fullCalendar('changeView', 'custom');
        $calendar.removeClass('d-none');
    }, 500);
});
```

**Comment by callaginn** [comment]
@huguestennier: I believe I'm doing that now (see above). However, that caused a new "double-click to fire" issue with Bootstrap dropdowns and make me concerned about loading the same script multiple times.

Any idea what could be causing that double-click issue? And do people usually import ALL their scripts into theme.js and split them apart with conditional statements OR just put the core stuff there and import page specific code with section / data-modules?

**Comment by huguestennier** [comment]
You're doing everything fine - can't really answer about the double-click to fire especially if no other scripts have this problem.

>  And do people usually import ALL their scripts into theme.js and split them apart with conditional statements OR just put the core stuff there and import page specific code with section / data-modules?

You should always include code that goes in your section in your `whatever-section.js` instead of `theme.js`. 

Closing this as it's more a Bootstrap issue now

**Comment by callaginn** [comment]
Still seems more like a webpack load issue to me. I've built about 60-75 sites on various versions of Bootstrap and haven't dealt with issues like this in a long time. I believe a lot of my confusion stems from not being familiar with how webpack bundles section-specific modules and loads them asynchronously.

**I ended up tracking my last two issues down to the following:**
1. Certain npm plugins seem to need to be loaded using some sort of object/namespace. For example, moment.js had to be loaded via `import moment from 'moment'`, instead of `import 'moment'`. This ended up fixing my calendars.
2. I was importing Bootstrap in webpack using two different methods, which was causing the double-load issue. That is: in `theme.js`, I was using individual imports for each Bootstrap plugin...
```
import 'bootstrap/js/dist/util.js';
import 'bootstrap/js/dist/alert.js';
import 'bootstrap/js/dist/button.js';
import 'bootstrap/js/dist/carousel.js';
import 'bootstrap/js/dist/collapse.js';
import 'bootstrap/js/dist/dropdown.js';
import 'bootstrap/js/dist/modal.js';
import 'bootstrap/js/dist/tooltip.js';
import 'bootstrap/js/dist/popover.js';
import 'bootstrap/js/dist/scrollspy.js';
import 'bootstrap/js/dist/tab.js';
```

...but in `assets/scripts/modules/modals.js`, I was using a single Bootstrap import:
```
import 'bootstrap';
```

My theory is that webpack couldn't tell these imports were duplicates, so imported Bootstrap twice. As soon as I changed modals.js to the individual imports -- my dropdowns started working on the first click.

**Thanks for all ya'lls help today!** Don't know how long it would have taken me to figure this out without the guidance. I was actually in the process of stripping out all the webpack code earlier today, because of all the issues it was causing. It seems like some of the explanations explained in this issue would be pretty useful for all the non-hardcore designers/developers like myself.

**Comment by huguestennier** [comment]
> Still seems more like a webpack load issue to me

Oh yes, being a webpack or bootstrap issue - I just meant it wasn't Slate specific.

> My theory is that webpack couldn't tell these imports were duplicates, so imported Bootstrap twice.

Exactly, since they were different files.

I'm glad everything worked out in the end 😄

**Comment by t-kelly** [comment]
Related https://github.com/Shopify/slate/issues/575
