### ISSUE TITLE
require is not defined when running yarn start

### ISSUE THREAD

**Issue by KylekJeon** [Shopify/slate#790]
### Problem
I'm trying to update my shopify theme to use slate instead of theme kit (I've been informed that theme kit is no longer supported). I created a new slate project as recommended, and ported over the files from my old theme to the new slate project theme. When I run yarn start, I get an error that I can't seem to resolve. 

![screen shot 2018-10-01 at 3 23 10 pm](https://user-images.githubusercontent.com/16788566/46312447-164fe800-c593-11e8-8443-612345d55887.png)

My slate.config.js file for reference.

`/* eslint-disable */

// Configuration file for all things Slate.
// For more information, visit https://github.com/Shopify/slate/wiki/Slate-Configuration
var webpack = require('webpack');
const path = require('path');

module.exports = {
  'cssVarLoader.liquidPath': ['src/snippets/css-variables.liquid'],
  'webpack.extend': {
    resolve: {
      alias: {
        jquery: path.resolve('./node_modules/jquery'),
        $: path.resolve('./node_modules/jquery'),
        'lodash-es': path.resolve('./node_modules/lodash-es'),
      },
    },
    module: {
      rules: [
        {
          test: /\.css$/,
          use: [
            "css-loader"
          ]
        },
        {
          test: /\.scss$/,
          use: [
            "sass-loader"
          ]
        },
        {
          test: /\.js$/,
          use: 'imports-loader?$=jquery,jQuery=jquery',
        },
      ]
    }
  },
};
`

From poking around stackoverflow in other places regarding debugging webpack, it looks like it's an issue of node not supporting require on the browser-side, but other than that I haven't really come across any relevant information that might be helpful. 

Looking for any tips or anything to try to resolve this issue.

**Comment by t-kelly** [comment]
> I've been informed that theme kit is no longer supported
Not sure where you heard that -- it is still being maintained but is a lower-level solution than Slate -- i.e. mainly handles interacting with Shopify's Asset and Theme APIs.

As for your error -- it looks like there is something in your `theme.teaser.liquid` file that isn't playing well with `extract-loader`. Can you paste the contents of it?
