### ISSUE TITLE
Duplicating theme and running Yarn watch or start doesn't load styles

### ISSUE THREAD

**Issue by 937aaron** [Shopify/slate#794]
### Problem

If I duplicate the live theme to a store to develop locally I can preview the duplicated theme and it shows up normal. When I run Yarn start or watch and it pulls up the theme in the browser no custom styles load and I get a load of "Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID" errors in the console. 
Yarn throws no errors in the terminal.

### More Information

<img width="1200" alt="screen shot 2018-10-02 at 2 29 48 pm" src="https://user-images.githubusercontent.com/18430872/46369131-f7635b80-c64f-11e8-9de0-d7a55366d44f.png">

**Comment by huguestennier** [comment]
Did you create a different `.env` file for you new store ? https://github.com/Shopify/slate/wiki/3.-Connect-to-your-store#creating-an-alternative-env-file

It looks like you're previewing the wrong Theme ID

**Comment by 937aaron** [comment]
Actually after a bit more research those errors were resolved by following the instructions [here ](https://github.com/Shopify/slate/wiki/How-to-create-a-trusted-local-SSL-certificate): 

The CSS loading issue was resolved by changing this line 

`{% include 'style-tags'}`

to 

`{% include 'style-tags', layout: 'theme' %}`

**Comment by t-kelly** [comment]
`Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID` is an SSL error. See https://github.com/Shopify/slate/issues/726 and https://github.com/Shopify/slate/issues/763
