### ISSUE TITLE
Recommended stable version

### ISSUE THREAD

**Issue by halburgiss** [Shopify/slate#795]
### Problem
All the installation instructions I find, result in 0.14 being installed, yet there seems to be newer versions. Are these 1.* versions stable and recommend over .14?  If so, the 'upgrade slate' in the wiki, does not upgrade slate itself. I am new to this too ;-)

### Replication steps
$ sudo npm install -g @shopify/slate

### More Information
I have started work on a custom theme with .14. If 1.2 turns out to be the preferred version, can I just copy the src folder and re-work the config files? How to install, 'npm i @shopify/slate@1.2' doesn't work.

Thanks.

**Comment by ironmarketing** [comment]
If I'm not mistaken, it's referring to themekit 0.14, not slate.
Stick with using the version your project is already built in, you won't be able to easily swap over to the latest version of slate.

**Comment by halburgiss** [comment]
Thanks, will do. Seems like the slate version to me though.
$ slate --version
0.14.0

**Comment by ironmarketing** [comment]
Ahh, I usually get a message saying to upgrade themekit to 0.14. I'm on the older versions of slate too, and honestly it works just fine for me.
It still fundamentally does the same thing as the latest version of slate, just not as effeciently (eg, no webpack hotspot module to easily see css/js changes).

**Comment by halburgiss** [comment]
Thanks. Is all development now in 1.*, or will there be a 0.15?

**Comment by ironmarketing** [comment]
All 1.* now mate. 
Still in beta though, Mr T. Kelly and others are working hard to get a stable release out :)

**Comment by t-kelly** [comment]
@halburgiss v0 exists on the v0 branch and the link to the docs is in the README of that branch.

v1 exists on the master branch and the docs for it, including how to get started, are in the Wiki. 

Hope that helps!
