### ISSUE TITLE
Theme Preview bar undefined height

### ISSUE THREAD

**Issue by jonathan5572** [Shopify/slate#796]
The Theme Preview bar is giving a height of undefinedpx, causing it to have an unnecessarily tall transparent background.

<img width="426" alt="Preview Bar" src="https://user-images.githubusercontent.com/17129278/46492179-ac695580-c7c1-11e8-9d87-cc0fdfe0d2ef.png">

Not a technical issue, but it does bug me seeing a thin line running through the page! Multiple browsers, same thing.

Is this a slate issue or a Shopify issue?

```
element.style {
    position: fixed;
    bottom: 0;
    left: 0;
    z-index: 2147483647;
    width: 100%;
    height: undefinedpx; ⬅ the offender right here
    border: none;
    box-shadow: 0 -1px 3px rgba(0, 0, 0, 0.2);
    overflow: hidden;
    transform: translateY(0);
    transition: transform 300ms;
}
```

**Comment by huguestennier** [comment]
This usually happens when you have a JavaScript error on your site. Can you check your console?

**Comment by huguestennier** [comment]
Related issue [https://github.com/Shopify/slate/issues/637](url)
