### ISSUE TITLE
Question - Converting template literals

### ISSUE THREAD

**Issue by george-dotdev** [Shopify/slate#798]
### Problem

I would like to convert es6 template literals to strings for backwards browser compatibility. I am trying to use Babel to achieve this with this package.

https://babeljs.io/docs/en/babel-plugin-transform-es2015-template-literals

I have installed the package with yarn and added it to the .babelrc file. However It doesn't seem to be working. Is there something else that needs to be done to make this work with Slate.

Here's some of the relevant stuff that is in my `package.json`

```
"devDependencies": {
    "@shopify/slate-tools": "^1.0.0-beta.6",
    "babel-plugin-transform-es2015-template-literals": "^6.22.0",
    "babel-preset-shopify": "^16.2.0",
    "eslint-plugin-shopify": "^19.0.0",
    "stylelint-config-prettier": "^3.3.0",
    "stylelint-config-shopify": "^5.1.2"
  },
  "dependencies": {
    "@shopify/theme-a11y": "^1.0.1",
    "@shopify/theme-cart": "^1.0.0-alpha.7",
    "@shopify/theme-currency": "^1.0.0-alpha.7",
    "@shopify/theme-images": "^1.0.0-alpha.7",
    "@shopify/theme-rte": "^1.0.0-alpha.7",
    "@shopify/theme-sections": "^1.0.0",
    "@shopify/theme-variants": "^1.0.0-alpha.8",
}
```
Using node v8.11.2

**Comment by george-dotdev** [comment]
Don't worry figured it out.

**Comment by t-kelly** [comment]
@george-dotdev mind writing what you did to fix it to help anyone else who stumbles across this issue?

**Comment by taylorwilliams** [comment]
How did you figure it out, @george-dotdev?
