### ISSUE TITLE
script_tag doesn't work locally with asset_url

### ISSUE THREAD

**Issue by andreirt** [Shopify/slate#801]
### Problem

This line of code works correctly in production mode (after a yarn deploy command), but not in development mode (yarn start)

{{ '../assets/static/js.cookie.js' | asset_url | script_tag }}

In development mode, it just outputs the asset url, without any <script> tag. In production mode, it works correctly.

### Replication steps

I don't know if this happens in other situations.

### More Information

If needed, I can share my theme with you.

**Comment by t-kelly** [comment]
Related https://github.com/Shopify/slate/issues/558. Closing this to keep discussion centralized there.
