### ISSUE TITLE
Slate analytics prompting email even if already exists Continuous Integration.

### ISSUE THREAD

**Issue by diegopego86** [Shopify/slate#804]
I'm using Team City for contiues integration. Runing yarn deploy --env=qa --skipPrompts for example, slate analytics still prompts:

```
To continue, please enter your email address:
```

I noticed a few issues here:

1- In slate-theme we are running 2 tasks on deploy, but yarn:
slate-tools build && slate-tools deploy
As in this link https://stackoverflow.com/questions/50835221/pass-command-line-argument-to-child-script-in-yarn it seems that the arguments passed in yarn are only added to the last part of the script, so what is happening in my case is :

```
slate-tools build && slate-tools deploy --env=qa --skipPrompts
```

So the environment and skipPrompts arguments are only passed to deploy and not to the build command.

2- On slate-analytics/index.js line 24:

```
let email = getUserEmail();
```
This value is never read from the env file, first because of the issue 1, but even fixing that error won't help. For some reason the env is not loaded correctly and the function always return undefined.

3 - SLATE_USER_EMAIL, it seems that we can use this environment variable but there is no information about it.

### Replication steps

1) First you need to remove your ~/.slaterc file as this contains the email you've set up when you first created your project

```
rm -r ~/.slaterc
```

2) Add SLATE_USER_EMAIL=  into you .env.{environment} file assigning a valid email to it

.env=qa
```
SLATE_USER_EMAIL=mytest@email.com
```

3) Run 
```
yarn deploy --env=dev-qa --skipPrompts
```

You'll now should be prompted for an email:

![screen shot 2018-10-08 at 12 05 14 pm](https://user-images.githubusercontent.com/1388364/46589166-6e866d00-caf2-11e8-8c14-d3865580d126.png)

This shouldn't happen as the email has already been set in .env=qa

I'm creating some pull request with the updates I made to try to fix this issue.

**Comment by marcnewport** [comment]
+1 for buddy

**Comment by t-kelly** [comment]
Good catch! 💯
