### ISSUE TITLE
Best practices for using Slate after initial theme build and go-live?

### ISSUE THREAD

**Issue by andreikorchagin** [Shopify/slate#813]
### Problem

If I have a non-live theme in Shopify, the "preview" mode acts as a sort of staging environment. However, when I launch, what is the best practice for being able to work on a theme developed with Slate without every change reflecting in production?

Without Slate, I would otherwise duplicate the themes, download their files locally (using Theme Kit), develop and push, then "publish" that new theme to go live. This isn't elegant at all and forces me to have a lot of different folders of theme files and to have duplicated themes all over the place. This also makes version control much more difficult to use. However, this means that I can still create non-live themes, test them in "preview" mode, then push to production once I am satisfied. 

When first developing a Slate theme on a Shopify site, we can develop that as a non-live theme. Since I know that Slate is only one-way for now (in that you can't download files from the remote Shopify server, only upload them), how can someone continue work on a theme, without modifying a production website, but still using Slate? 

### Replication steps

Develop theme using Slate. Push live.

### More Information

*Any additional information which might be helpful.*

**Comment by huguestennier** [comment]
Here's a great blog article written by @chrisberthe on [How to Improve your Theme Development Workflow](https://www.shopify.ca/partners/blog/development-workflow). Explaining in details how we're using Slate at Shopify.

**Comment by andreikorchagin** [comment]
> Hey @andreikorchagin 😄 Here's a great blog article written by @chrisberthe on [How to Improve your Theme Development Workflow](https://www.shopify.ca/partners/blog/development-workflow). Explaining in details how we're using Slate at Shopify.

This article really had it all. Incredibly helpful and succinctly answered so many lingering questions. Thank you @huguestennier!

**Comment by huguestennier** [comment]
Glad it helped!
