### ISSUE TITLE
Lazy loading picture error

### ISSUE THREAD

**Issue by Noostop** [Shopify/slate#828]
### Problem
Product loading image error for collection page and product page

### Replication steps
![image](https://user-images.githubusercontent.com/41714012/46940003-48387280-d09a-11e8-9582-ce54146657bb.png)

**Comment by dan-gamble** [comment]
This would be an issue [this repo](https://github.com/Shopify/starter-theme) and not Slate.

**Comment by t-kelly** [comment]
I agree with @dan-gamble. Also please provide more details on how to reproduce the bug in your new issue in Starter Theme repo.
