### ISSUE TITLE
dev environment points to live

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/slate#83]
*From conversation in https://github.com/Shopify/slate-tools/issues/39*

We are having the `development` environment point to the live theme by default.  The is where a `production` environment should point.  We should encourage pushing to a safe dev environment by default.

**Comment by jmcmullen** [comment]
+1

**Comment by NathanPJF** [comment]
@jmcmullen If you're finding your theme_id isn't being respected then I believe the issue you're experiencing is related to this one: https://github.com/Shopify/slate-cli/issues/115

**Comment by NathanPJF** [comment]
Fixed in https://github.com/Shopify/slate/pull/84
