### ISSUE TITLE
No css being generated on create and start of new project

### ISSUE THREAD

**Issue by pault70** [Shopify/slate#830]
I have followed the steps in the docs including setting up an SSL cert for localhost. I have had the same problem on both Mac and PC. When I run yarn start, the main css file is completely blank: https://cdn.shopify.com/s/files/1/0022/0014/1860/t/5/assets/layout.theme.styleLiquid.scss.css?11825614703423977481
I do see an error during yarn start about not using @import to import .css files into an .scss file.

**Comment by huguestennier** [comment]
On `yarn start`, [assets are served locally](https://github.com/Shopify/slate/wiki/Local-development#local-development-asset-server). This is the intended behaviour for faster development. 

You need to run `yarn deploy` for your assets to be deployed on Shopify's servers.

**Comment by pault70** [comment]
Thanks for the reply. I did read this and therefore am confused why remote links are generated in the html when I run yarn start. There are no other css files in the HTML and therefore the resulting page is styleless.

**Comment by huguestennier** [comment]
> There are no other css files in the HTML and therefore the resulting page is styleless

Starter theme is [intentionally lacking styles](https://github.com/Shopify/starter-theme#intentional-lack-of-styles). In development, most of the styles will get injected into the page because of [Hot Module Replacement](https://webpack.js.org/concepts/hot-module-replacement/).

**Comment by t-kelly** [comment]
> There are no other css files in the HTML and therefore the resulting page is styleless

There is no generated stylesheet because the styles are contained within the JS bundle to enable Hot Module Reloading.

Please check your browser console for errors and post them here.
