### ISSUE TITLE
Import JS into theme and have it build

### ISSUE THREAD

**Issue by demomohawk** [Shopify/slate#843]
Is there a way to convert a theme over to slate?

I am trying to get brooklyn/narrative theme over to slate but can't seem to convert.

I mainly run into issues when trying to move over the scripts and styles over. Is there proper documentation on how to do so?

For example I am trying to convert the following into the new templating style.
```
  <!--[if (gt IE 9)|!(IE)]><!--><script src="{{ 'theme.min.js' | asset_url }}" defer="defer"></script><!--<![endif]-->
  <!--[if lte IE 9]><script src="{{ 'theme.min.js' | asset_url }}"></script><![endif]-->

```
I removed it completely from the theme.liquid and instead I am doing 
`   import './theme.min.js';`
within the index.js file within templates folder. but i receive error

> "Uncaught TypeError: Cannot read property 'loaded' of null"

**Comment by huguestennier** [comment]
There's an issue open on migrating to Slate v1, you can continue the discussion there : https://github.com/Shopify/slate/issues/542

> I am trying to get brooklyn/narrative theme over to slate but can't seem to convert.

Brooklyn and Narrative are not open sourced and there are no plans to convert them to Slate v1 at the moment. Also, as you only get the dist folder, you won't easily be able to convert the theme to Slate.
