### ISSUE TITLE
yarn start issues - SyntaxError: Invalid shorthand property initializer 

### ISSUE THREAD

**Issue by classroomdropout** [Shopify/slate#851]
I followed all steps properly for amending the .env file but I get an error when running the command 'yarn start' in Terminal in order to complete the setup and get working with Slate.

Here is the output on from Terminal once I run the command 'yarn start':

[My computer]$ yarn start
yarn run v1.10.1
$ slate-tools start
[myuser]/my-new-theme/node_modules/@shopify/slate-env/slate-env.schema.js:30
  SLATE_STORE=[my=store].myshopify.com,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid shorthand property initializer
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([myuser]/my-new-theme/node_modules/@shopify/slate-env/index.js:5:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Here is the code in my .env file:
  // The environment variable key which contains the myshopify.com URL to your
  // Shopify store
  'env.keys.store': 'SLATE_STORE',
  SLATE_STORE=[my-store].myshopify.com,

  // The environment variable key which contains the API password generated from
  // a Private App
  'env.keys.password': 'SLATE_PASSWORD',
  SLATE_PASSWORD=[password],

  // The environment variable key which contains the ID of the theme you wish to
  // upload files to
  'env.keys.themeId': 'SLATE_THEME_ID',
  SLATE_THEME_ID=5758910504,

  // The environment variable key which contains a list of file patterns to
  // ignore, with each list item separated by ':'
  'env.keys.ignoreFiles': 'SLATE_IGNORE_FILES',
  SLATE_IGNORE_FILES=config/settings_data.json,

Has anyone else had this problem when looking to start developing with Slate. 

Let me know where I've gone wrong. I have tried removing the 'env.keys' lines. I have tried removing the commas from the end of the added code. I continue to get some sort of syntax error.

Am I missing something here?

**Comment by huguestennier** [comment]
Where did all the `env.keys.xx` come from? Your `.env` should look like this : 
```
SLATE_STORE=your-store.myshopify.com
SLATE_PASSWORD=xxxx
SLATE_THEME_ID= 5758910504
SLATE_IGNORE_FILES=
```

No commas either. Can you try with above and see how it looks?

**Comment by classroomdropout** [comment]
the env.keys.xx were in the file when i opened it as default settings. I have removed these and and commas and still get the following error:

[my computer]$ yarn start
yarn run v1.10.1
$ slate-tools start
[myuser]my-new-theme/node_modules/@shopify/slate-env/slate-env.schema.js:35
  SLATE_PASSWORD=[mypass]
  ^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/cameron/my-new-theme/node_modules/@shopify/slate-env/index.js:5:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I feel like this is a simple syntax error as I am getting a red underline in my file where it says SLATE_PASSWORD, SLATE_THEME_ID, etc. I am not familiar with the JS syntax but am I missing something here?

**Comment by huguestennier** [comment]
Are you on macOS or Windows?

**Comment by classroomdropout** [comment]
macOS and node v8.12.0

**Comment by classroomdropout** [comment]
Any update here? @huguestennier @t-kelly

**Comment by t-kelly** [comment]
Cannot reproduce this bug on our end. Please make sure you're file follow [the following example](https://github.com/Shopify/slate/tree/master/packages/slate-env)
