### ISSUE TITLE
Template and layout bundling not working per the documentation

### ISSUE THREAD

**Issue by adrianocr** [Shopify/slate#854]
### Problem

Per the documentation, if you have  a page.liquid file in /src/templates/ and a page.js file in /src/scripts/templates/, slate should identify the combination and create a bundle. 
~Well, that isn't working.~ Edit: it actually is working with page.js but not with the page templates that start with `page.` 

Example: I have a page.lookbook-1.liquid file in /src/templates/ and a page.lookbook-1.js file in /src/scripts/templates/ and a bundle does not get created. Is there some kind of naming convention like underscores instead of periods or dashes or omitting `page.` or something? 

### Replication steps

I don't know if I should be testing in any particular way but I tried a simple console.log("[filename here]") in the templates referenced above and it does not work. But on the other hand, if I place console.log("index.js") in the /src/scripts/templates/index.js file and go to the homepage, it works. If I go to any other page than the homepage, I don't see "index.js" in the console. 

### More Information

Per the above, the code-splitting and bundling is working, just not with anything except the default templates that come with the starter theme (index.js, product.js, etc). 

*Any additional information which might be helpful.*

Latest version of Slate, macOS mojave, npm 8.11.2, yarn latest.

**Comment by adrianocr** [comment]
Figured it out. Templates need to be created with an underscore rather than `-`. Which seems kind of weird to me that Slate would allow page templates with `-`s rather than `_` when it _requires_ `_`s to work correctly.

**Comment by t-kelly** [comment]
Sounds like this an be closed?
