### ISSUE TITLE
Styling password.liquid (again)

### ISSUE THREAD

**Issue by fabianwohlfart** [Shopify/slate#858]
#### src/layout/password.liquid:
`{% include 'style-tags', layout: 'password' %}`
(nor)
`{% include 'style-tags' %}`

#### src/scripts/layout/password.js:
```
import '../../styles/theme.scss';
import '../../styles/theme.scss.liquid';
```

why is this not loading the css?

Edit: 
A simple console.log from password.js does not echo anything. but what did i do wrong, its the structure you suggested, right?

**Comment by fabianwohlfart** [comment]
#### src/layout/password.liquid:
`{% include 'script-tags', layout: 'password' %}`

i must admit, that this seems obvious now, but its not documented well enough, as i thought its done automatically.

**Comment by huguestennier** [comment]
Related issue : https://github.com/Shopify/slate/issues/799
