### ISSUE TITLE
Calling assets from inside React components

### ISSUE THREAD

**Issue by lmartins** [Shopify/slate#859]
### Problem
Is there a way we can call static assets, like images for example, from inside React components?
I'm working on a store where we have a custom product builder experience built on React. On that UI we would still like to use a few static assets from the theme, but I'm not finding a way to load it.

Is declaring those images as global variables and pass them to React the only way to do it?

**Comment by t-kelly** [comment]
@lmartins you're going into unexplored territory with React + Liquid so I'm afraid there is not much I can say to help. But if passing it through a global works then I would start there?

Also, please keep in mind the [Slate repo scope](https://github.com/Shopify/slate/blob/master/CONTRIBUTING.md#scope). This question is not really related to Slate.

**Comment by isaac-martin** [comment]
@lmartins I did something just like this this week. Happy to help you out a bit if you need it.

**Comment by isaac-martin** [comment]
You can email at isaac@smkkstudios.com

**Comment by lmartins** [comment]
@t-kelly thank you for looking into this.

@isaac-martin I'll reach out via email, thank you for be willing to share your experience with this.
