### ISSUE TITLE
Inline SVGs with beta 12

### ISSUE THREAD

**Issue by lmartins** [Shopify/slate#862]
### Problem
How can one inline SVGs coming from the assets folder with the latest update?
Before you could just include them with `{% include 'icon-filename' %}` but that stopped worked as mentioned https://github.com/Shopify/slate/pull/850

I can display the files as image tags using the `asset_img_url` but I need to have the actual SVG tags to be able to access its internal elements.

Is this still possible with the new version?

**Comment by t-kelly** [comment]
Hey @lmartins -- yes it is still possible. The latest version just removed some magic around what we were doing before, and uses a more manual approach.

If you want to inline an SVG, you just need to create a copy of it in the `snippets` folder, and rename the extension from `.svg` to `.liquid`. This is exactly what the Slate was doing before, but ultimately I chose to remove it for now because the assets folder had too much going on.

Take a look at [Starter Theme for an example](https://github.com/Shopify/starter-theme/tree/master/src/snippets).

**Comment by dan-gamble** [comment]
Hey @t-kelly, sorry for digging up a closed thread.

Would we be able to add something to `slate.config.js` to re-instate the old behaviour? We use a `PostCSS` pipeline which in turn uses [postcss-inline-svg](https://github.com/TrySound/postcss-inline-svg) which we used to reference the `assets/svg` folder. I think if we had to use `.liquid` this wouldn't work.

Could i just look back at what you removed then just pop that in to my `slate.config.js`?

**Comment by lmartins** [comment]
Hey @t-kelly thank you for looking into this.
Kinda bummed, as this breaks my workflow around SVG processing (due to the file extension change), but I understand the reasons. 
As @dan-gamble suggests, if this could be opt-in, that would be great.

**Comment by t-kelly** [comment]
You should be able to [add something like we had in the preview config](https://github.com/Shopify/slate/blob/22b9c0fc03ad81d9ed2b4afcfaca8a31ee55f120/packages/slate-tools/tools/webpack/config/parts/core.js#L135-L141):
```
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  'webpack.extend' = (config) => {
    return {
      plugins: [
        new CopyWebpackPlugin({
          from: config.get('paths.theme.src.svgs'),
          ignore: ['.DS_Store'],
          to: `${config.get('paths.theme.dist.snippets')}/[name].liquid`,
        }),
      ],
    };
  },
};
```

**Comment by lmartins** [comment]
Oh I'm going to try this. As much as I love Slate and the latest updates, this really felt like a downgrade from prior releases.

**Comment by t-kelly** [comment]
@lmartins we will definitely revisit this in the future and hopefully find something better!
