### ISSUE TITLE
Incorrect environment displayed in themekit's logs when using non-dev .env files

### ISSUE THREAD

**Issue by HauntedSmores** [Shopify/slate#863]
### Problem

Themekit shows it's using `development` environment regardless of `.env.***` file.

While the new Slate warnings are great and remind you which theme you're on, it does not inform you of the correct environment. The reason for this is that when Slate constructs the `config.yml` file in the dist folder, it simply puts whatever was in your `.env` file as the `development` entry.

This gave me great pause when I was deploying using `.env.staging` and seeing:

```
[development]: 50 / 100 [--------------->-------------] 50%
```

### Replication steps

Simply run `npm run deploy -- --env=anything` and it will show the above console log (`[development]`)

### More Information

Build process should take `****` from `.env.****` and use that as the key name in the constructed `config.yml` - if using just `.env`, then leave env name as `development`.

**Comment by t-kelly** [comment]
Fixed in #866
