### ISSUE TITLE
Does the CDN link ever change?

### ISSUE THREAD

**Issue by isaac-martin** [Shopify/slate#873]
This is more of a question then a bug. But I am building a react app inside a store where I can not use the liquid `assett_url` filter. Instead I have assigned a global variable that contains the start of the CDN url. I am then rendering SVGs using props. See below for an example. 

`window.assetUrl = '//cdn.shopify.com/s/files/1/0093/8852/3579/t/1/assets';`
`<SVG src={`${window.assetUrl}/tuck_${value}.svg`}`

https://cdn.shopify.com/s/files/1/0093/8852/3579/t/2/assets/tuck_untucked.svg
https://cdn.shopify.com/s/files/1/0093/8852/3579/t/1/assets/tuck_untucked.svg

As you can see here though there are two versions of the icon on different CDN urls. 

If there is no guarantee that the url doesn't change I will just need to spin up my own CDN for hosting the icons on that I am using through React.

**Comment by jonathanmoore** [comment]
This would probably be a better question for the Shopify Forums, but I would say that it is best practice to assume that the URLs could change at any time.  Here is a breakdown of the URL parts, as it is now, although it could change at any point.

The `/0093/8853/3579` part is linked to the store ID.  Your Shopify ID is probably `938853579`.

The `/t/2` part is a theme incrementer.  As you duplicate themes, upload a new theme, and install new themes the number will increase.  One of our development shops is at `/t/94`.

Finally, you're missing the important query part at the very end to help with caching and file changes.  `?0000000000000000`.  

I'd recommend taking a different approach with the theme assets.  In this case or other similar ones, your best option would be to create a JavaScript object or variables that contain all sorts of theme asset URLs, language strings or other values accessible only through liquid.

**Comment by isaac-martin** [comment]
Thanks @jonathanmoore for the thorough explanation.
