### ISSUE TITLE
Refused to apply style from Shopify CDN

### ISSUE THREAD

**Issue by james-prado** [Shopify/slate#880]
### Problem

Maybe related to #864 

From a fresh project on [v1.0.0-beta.13](https://www.npmjs.com/package/create-slate-theme/v/1.0.0-beta.13) css fails to load from Shopify CDN

Error Msg:
```
Refused to apply style from 'https://cdn.shopify.com/s/files/1/0015/2987/2461/t/1/assets/layout.theme.styleLiquid.scss.css?5743935083682793812' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

### Replication steps

1. Create new project from [v1.0.0-beta.13](https://www.npmjs.com/package/create-slate-theme/v/1.0.0-beta.13)
2. Add ssl cert
3. `npm start`

### Platform

Ubuntu 18.04 & MacOS Mojave

**Comment by james-prado** [comment]
It looks like webpack is supposed to extract the text into `[name].styleLiquid.scss.liquid` but I only see `/styles/theme.scss.liquid` getting deployed to shopify when I run `npm start`.

**Comment by t-kelly** [comment]
Thanks for opening a new issue on this @james-prado. I've had a chance to investigate and it looks to be related to #864. Though I had fixed it but doesn't look like it!

Opening a PR now. Going to close this issue and reopen #864.
