### ISSUE TITLE
Why are images being lost & replaced by the placeholder when Slate is deployed?

### ISSUE THREAD

**Issue by Aly-76** [Shopify/slate#884]
### Problem

When Slate is deployed content images that were uploaded via Shopify are lost. The images are still in Shopify but after deployment the theme defaults back to the SVG placeholder and the image is lost.

### Replication steps

Upload images via Shopify > Render correctly > Deploy Slate to Shopify > Images are removed from the page and replaced with the default placeholder

### More Information

Is this normal for slate or a bug?

**Comment by Aly-76** [comment]
The config.yaml states on line 21 and 28 that in order to ignore the settings_data.json the line of code needs uncommenting. Introducing this ignore_files setting here has no effect and images are still lost. Therefore, the only other option is updating the .env file as in your link. However, where is this in Slate/Shopify? If found do you just need to add the following line SLATE_IGNORE_FILES=config/settings_data.json

**Comment by huguestennier** [comment]
If you have a `config.yml` file it means that you are using Slate v0 and you follow [these docs](https://shopify.github.io/slate/). In that case, a `.env` file won't have any effect.

If you want to use Slate v1 with a `.env` file, you need to follow the steps here : https://github.com/Shopify/slate/wiki

**Comment by Aly-76** [comment]
Ah .. great news is I have updated to Slatev1 and I nolonger have a problem with loosing content when I deploy to Shopify as I have correctly set up the .env file based on your recommendation. However, I now have no compiled CSS styles, only a theme.scss.liquid file which have been stripped so it is empty. // removed by extract-text-webpack-plugin  is there a way to prevent this happening?

**Comment by huguestennier** [comment]
on `yarn start`, the CSS and JavaScript assets are loaded locally. You will only see CSS files in your dist folder when you run `yarn build`.

Since you seem new to Slate, I suggest you read through the wiki - it will answer most of the question you will have coming up :)

**Comment by t-kelly** [comment]
@Aly-76 the `theme.scss.liquid` is an artifact that will be removed when #883 is merged and released!

**Comment by Aly-76** [comment]
@huguestennier Thank you for your guidance and patience. I appriciate you help. I own you a beer or a coffee. 

@t-kelly Thanks for the update. I will certainly look out for that.
