### ISSUE TITLE
layout.theme.styleLiquid.scss.liquid is empty

### ISSUE THREAD

**Issue by james-prado** [Shopify/slate#890]
### Problem

`dist/assets/layout.theme.styleLiquid.scss.liquid` is empty

```
/**
 * Insert your styles with Liquid below.
 *
 * Import additional stylesheets into this sheet using CSS imports:
 * @import url('./global/form.scss');
 */

```

### Replication steps

- create fresh theme from [v.1.0.0-beta.14](https://www.npmjs.com/package/create-slate-theme): `npx create-slate-theme demo-theme`
- bump `@shopify/slate-tools` version to `1.0.0-beta.14` (because it still installs with `...beta.12`)
- `npm start`

**Comment by huguestennier** [comment]
[src/styles/theme.scss.liquid](https://github.com/Shopify/starter-theme/blob/master/src/styles/theme.scss.liquid) is indeed empty by default. What is your question ?

**Comment by james-prado** [comment]
Ohh, I thought it was supposed to have my styles in it. I still can't get styles working on a fresh install, where are my css styles supposed to be coming from then?

**Comment by huguestennier** [comment]
There's multiple ways to do it but usually anything that doesn't require liquid variable in it, we will create normal `.scss` files. You can see the [files structure](https://github.com/Shopify/starter-theme/tree/master/src/styles) here

**Comment by t-kelly** [comment]
Or read the doc on [styles with Liquid](https://github.com/Shopify/slate/wiki/Styles-with-Liquid)

**Comment by james-prado** [comment]
@t-kelly @huguestennier Thx! I'll have a read through the styles with liquid docs. Also I didn't realize the starter-theme was intentionally lacking styles, I thought it was supposed to be the same as the debut theme
