### ISSUE TITLE
Is there a way not to load theme.scss.liquid

### ISSUE THREAD

**Issue by marioloncarek** [Shopify/slate#904]
### Problem

I am not using theme.scss.liquid and I dont need it in my process, but the file is always loading in the theme.liquid head within `{% include 'style-tags', layout: 'theme' %}` . Which means that i have render blocking resource that is empty file. I cant find style-tags.liquid or any place to remove that file from loading. Is there a way to do it? thanks

**Comment by t-kelly** [comment]
You should be able to just delete the file and it won't be included in the build?

**Comment by marioloncarek** [comment]
if i just delete the file whole build/start will crash

```
Failed to compile.
undefined
./assets/styles/theme.scss.liquid
Module build failed (from ../node_modules/extract-text-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/concat-style-loader/index.js):
Error: ENOENT: no such file or directory,
```

**Comment by t-kelly** [comment]
Hm -- well then thats a bug! Thanks @marioloncarek, will take a look 😄

**Comment by t-kelly** [comment]
Nevermind not a bug. Make sure you remove any reference to the `theme.scss.liquid` file. In Starter Theme it is imported in the `scripts/layout/theme.js` file.
