### ISSUE TITLE
Slate not loading css on 'Yarn Start' anymore.

### ISSUE THREAD

**Issue by thedesignersdeveloper** [Shopify/slate#907]
### Problem

Yarn Start no longer compiles CSS into layout.theme.styleLiquid.scss.css.

The website was previously working fine, then upon a new days startup of 'Yarn Start', it no longer uploads css files.

I have had this exact issue before and had to install a new slate project to solve the issue. *Do not want to do this again.

### More Information

- Updated Slate to v1.12.3 which did not solve the issue.
- When viewing source layout.theme.styleLiquid.scss.css is now empty after running 'Yarn Start'.
- When running 'Yarn Deploy' the website loads correctly and the CSS files upload with the layout.theme.styleLiquid.scss.css showing all the necessary CSS.
- The issue could be with the SSL certificate now showing ERR_CERT_AUTHORITY_INVALID in Chrome Version 70.0.3538.110.
- Have searched the internet for days on how to fix this SSL issue on mac for Shopify however, no clear fix found.

### Other
Any help would be much appreciated as I feel like this is a very time costly issue that will continue to happen (having happened once before) and I would love to solve this for good.

**Comment by thedesignersdeveloper** [comment]
It's working now thanks very much!

A few notes:

- Yes, I did try reading the wiki however when i clicked on that link in the past issues I viewed I was taken to the slate docs with no information on this subject. The link you provided above takes me to the correct place.
- After following these steps I then had to (on a mac):
- In Keychain add my Certificate to the 'System' and in both the 'Login' & 'System' section change the settings to 'Always Trust'.
- Then view the website from the (External) source as the (Local) still no longer works.

For other people what I mean is after running 'Yarn Start' i used the second link labelled external to view my website:

   Your theme can be previewed at:

      https://localhost:3000/?preview_theme_id=00000000 (Local)
      https://000.000.0.000:3000/?preview_theme_id=0000000 (External)

Further Notes:
- It still only works in Chrome. Firefox & Safari do not work (I don't care about this, just need one and chrome is my primary).

Really appreciate the link to the article, saved my arse.

**Comment by km-likhon** [comment]
I need A help, im tried with the ssl, can any one help me how to create a self signed SSL certificate ? on windows. 

https://github.com/Shopify/slate/wiki/4.-Create-a-self-signed-SSL-certificate
 this link work fine on macOs but i want it on windows.

thanks everyone.

**Comment by t-kelly** [comment]
@km-likhon there are a few open threads if you [filter issues by the `windows` tag](https://github.com/Shopify/slate/issues?q=is%3Aopen+is%3Aissue+label%3Awindows). 

We're not using Windows here at Shopify and not quite ready to officially support it so it will have to be something you and other Slate users figure out.
