### ISSUE TITLE
Using <use xlink:href>

### ISSUE THREAD

**Issue by binarytrance** [Shopify/slate#908]
### Problem

So I have been trying to use `<use xlink:href="">` to include icons instead of using icon fonts to leverage browser cache. (more info here: [css-tricks](https://css-tricks.com/svg-use-with-external-reference-take-2/))

I generally define images in slate like this: `<img src="{{'shopify-plus-logo--darkbg.svg' | asset_url}}"/>`. 

I tried doing something similar with `<use>` like so: `<use xlink:href={{ "icons-sprite.svg#icon-arrow" | assert_url }}></use>` but it doesn't seem to work.

Any suggestions as to how do i make it work?

**Comment by t-kelly** [comment]
The Slate Github repo exists for the theme development community to discuss and solve problems directly related to Slate. It **is not the place** to discuss general theme development problems, nor the place to seek help for non-Slate related problems.

Shopify Theme development is a big topic and it's completely normal that you will encounter problems which might require you to reach out for help. In fact, we provide several knowledge and support platforms for theme development:

* [The Shopify Help Center](https://help.shopify.com/themes)
* [The Partners Blog](https://www.shopify.ca/partners/blog/topics/shopify-theme-development)
* [Shopify Forum](https://ecommerce.shopify.com/forums)
* [Shopify Experts](https://experts.shopify.com/)
* [Shopify Support](https://help.shopify.com/questions)
