### ISSUE TITLE
Are you serious?

### ISSUE THREAD

**Issue by nuc** [Shopify/slate#911]
![image](https://user-images.githubusercontent.com/697014/49830759-6537ac00-fd92-11e8-9d63-ded73d8a0fbb.png)

**Comment by nuc** [comment]
Well, I didn't meant that. I meant that there's no way to opt-out from tracking, since the email is required to proceed.

**Comment by t-kelly** [comment]
Nope, there is not for alpha/beta so we can make Slate better when it's in its most fragile state. Tracking will be optional when we make a stable release.
