### ISSUE TITLE
Shopify Design Mode (Deprecated?) 

### ISSUE THREAD

**Issue by panoply** [Shopify/slate#919]
It seems that the `window.Shopify.designMode` boolean is deprecated – I've tested this with several stores and multiple browsers with an `undefined` result every time.

Event listeners are only initialized if this boolean is present, see here:
https://github.com/Shopify/theme-scripts/blob/master/packages/theme-sections/theme-sections.js#L226

**Comment by huguestennier** [comment]
Duplicated issue https://github.com/Shopify/theme-scripts/issues/67

Please open an issue only once and in the right repo. Closing this
