### ISSUE TITLE
Updating 0.14 to 1

### ISSUE THREAD

**Issue by ClearMarble** [Shopify/slate#935]
Apologies if this is answered somewhere obvious but I'm having trouble finding it...

We started building a theme on Slate 0.13 before v1 beta was released and we were already kind of in too deep and trying to hit a deadline to go through the process of upgrading.

We've been up an running for a while now though and I'd like to get things up to date...is there any info available on how I can upgrade a theme from v0 to v1? Or are the changes so significant that we'd kind of need to rebuild the whole thing at this point?

**Comment by t-kelly** [comment]
Hey @ClearMarble -- v0 to v1 is a major version bump so there are a lot of breaking changes between the two versions. I would recommend that if the workflow you have for your current theme works well for you, then keep it. 

If you're looking to refactor your theme or create a new theme using modern web technologies then Slate v1 is for you. We haven't really documented the migration process from v0 to v1, but there is a related issue (https://github.com/Shopify/slate/issues/542) that might help.

Going to close this in favour of https://github.com/Shopify/slate/issues/542
