### ISSUE TITLE
Unable to use Sass functions with liquid variables

### ISSUE THREAD

**Issue by james-prado** [Shopify/slate#937]
### Problem

Using css variables with sass functions doesn't work, even with [CSS var loader](https://github.com/Shopify/slate/wiki/Slate-CSSVar-Loader).

`theme.scss`
```
body {
  background-color: darken($color-body, 10%);
}
```

Error:
```
background-color: darken($color-body, 10%);
                 ^
      Argument `$color` of `darken($color, $amount)` must be a color
```

I understand normally this would be a limitation of css custom properties, but since slate uses [CSS var loader](https://github.com/Shopify/slate/wiki/Slate-CSSVar-Loader), this should be possible right?  

### Replication steps

From a fresh slate repo, add the following to `theme.scss`

```
body {
  background-color: darken($color-body, 10%);
}
```

**Comment by jonathanmoore** [comment]
This is related to an open issue with Slate and how liquid variables and SCSS work together.  There is a lot of good information on how it can work together now, and ultimately there will be improvements to Slate in general down the road.
[#504 CSS Custom Variable - Liquid variable or control flow tags](https://github.com/Shopify/slate/issues/541)

Another closed issue that discusses SCSS functions specifically:
[#503 CSS Custom Variable - SCSS operations and functions](https://github.com/Shopify/slate/issues/503)
