### ISSUE TITLE
Easiest way to import/copy styling from theme to Slate Starter Theme

### ISSUE THREAD

**Issue by ralcar** [Shopify/slate#939]
Just getting started with Shopify/Slate, and I am up and running on the slate v1 using the unstyled Starter Theme. I know this is the starting point and that i can build upon that, but as many others I wish the starting point was with the default styling from Debut (or other), and this is where the "Community Starter Themes" comes in as I understand it. 

So far I have not found any other starter themes than "Starter Theme" or "Skeleton Theme", or the vue/react Starter Themes that @liron-navon did. Google didnt return anything usefull either, so i suppose there are none yet?

If not, how would you go about reapplying the Debut styling from its assets/theme.scss.liquid styling, is that the correct way to go about it or is there any other way I can get to a more styled version of the Starter Theme without having to reinvent the wheel?

Love everything else so far by the way.

**Comment by t-kelly** [comment]
> So far I have not found any other starter themes than "Starter Theme" or "Skeleton Theme", or the vue/react Starter Themes that @liron-navon did.

These are all that I'm aware of. We are relying on the community to share their own starting points, and so far not many people have.

> If not, how would you go about reapplying the Debut styling from its assets/theme.scss.liquid styling, is that the correct way to go about it

Yes but that is still means a lot of HTML and classes you need to apply across the theme.

> is there any other way I can get to a more styled version of the Starter Theme without having to reinvent the wheel?

Partner up with other developers and create a starter theme that mirrors Debut?
