### ISSUE TITLE
Graceful warning / reporting for `ECONNRESET` during yarn deploy

### ISSUE THREAD

**Issue by justinmetros** [Shopify/slate#941]
### Problem

Error `ECONNRESET` doesn't give very helpful feedback on what happened for production deployment.

Expected behavior is not having to guess if everything uploaded ok

### Replication steps

yarn deploy ( slate-tools build && slate-tools deploy --env=production )

Happens 1/25 times maybe?

### More Information

Error is:  `UnhandledPromiseRejectionWarning: Error: read ECONNRESET`

```
↑  Uploading to Shopify...

[production]: 52 / 217 [==============>-----------------------------------------------------]  23 %
(node:18204) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:139:27)
(node:18204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[production]: 217 / 217 [====================================================================] 100 %
```

**Comment by dan-gamble** [comment]
This is the same as https://github.com/Shopify/slate/issues/938

**Comment by t-kelly** [comment]
Closing in preference to #938.
