### ISSUE TITLE
Feature Request  - option for lint on deploy and let deploy fail if lint has errors

### ISSUE THREAD

**Issue by justinmetros** [Shopify/slate#944]
### Problem

No problem, just an idea. 

### Replication steps

N/A

### More Information

I know this can be done in a ton of other ways. Modifying slate.config.js and adding some new tools. 

But it would be cool if you could eject from a deploy if lint had any errors as a default feature ( or a warning - you have lint errors deploy y/N ).

**Comment by justinmetros** [comment]
I just finished making our codebase compliant with Shopify's eslint and stylint plugins. 

A few personal preference overrides but for the most part I really like them.

Would be awesome if no one on our team could deploy if they jam in some css or js and lint fails.

**Comment by t-kelly** [comment]
The beauty of NPM scripts is they can be whatever you want. You should be able to achieve this by replacing the `deploy` script with something like `slate-tools lint && slate-tools deploy`

**Comment by justinmetros** [comment]
Thanks @t-kelly - yeah this is how i was doing it. I didn't quite get to how to skip the slate-tools deploy if slate-tools lint failed. Even when slate-lint throws errors, it continues to next script. 

You sparked the idea though to use slate-tools lint just on the liquid and add my own js/(s)css lint that pulls the ripcord on an error.

Appreciate the feedback, thank you! Not sure if I'm doing this the 'slate way' but got it working for now :)
