### ISSUE TITLE
Event-stream not found 404

### ISSUE THREAD

**Issue by Oscarteg** [Shopify/slate#946]
### Problem
`yarn create slate-theme my-new-theme` gives a 404 error on the event-stream package.
```
~ ❯ yarn create slate-theme .
yarn create v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/Example/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
~ ❯
```

### Replication steps
`yarn create slate-theme my-new-theme`

### More Information
Maybe the version should be updated on the theme? I'm not sure where the package comes from.

**Comment by t-kelly** [comment]
[Just encountered and fixed this in Theme Scripts.](https://github.com/Shopify/theme-scripts/commit/bc3038012244bc4042929648aa28162493490ef8) Will follow through here as well. Thanks for the bug report @Oscarteg!

**Comment by t-kelly** [comment]
Hmm so in Theme Scripts we were referencing a particular version of `event-stream`, which I was able to fix by updating the `yarn.lock` file. I don't see any reference to `event-stream` in any other `yarn.lock` files.

**Comment by cmincarelli** [comment]
So, for anyone still running into this (as I just did), check your yarn-log and back track the dependency chain. I found out that the global install of nodemon.1.18.4 was the culprit in my case; it has nothing to do with this package.

nodemon@^1.18.4:
pstree.remy@^1.1.0:
ps-tree@^1.1.0:
event-stream@~3.3.0:
flatmap-stream "^0.1.0"
