### ISSUE TITLE
Should not close the issues that didn't fix and Lock the conversation that currently active

### ISSUE THREAD

**Issue by Uysim** [Shopify/slate#952]
I just go through this repo. I see a lot of issues have been closed and conversation has been  locked by bot while it is not address or fixed yet. 
Like currently I am facing the problem with jQuery is undefined I saw a lot of issues that have been closed with any fixing. Also the conversation is locked to prevent me from commenting event if it is inactive in the short time.

**Comment by george-dotdev** [comment]
If you are trying to use jQuery globally you may want to just do this:
```
import $ from 'jquery';

window.$ = $;
window.jQuery = $;
```

**Comment by t-kelly** [comment]
Hey @Uysim -- we lock closed issues that have not been commented on in 30 days automatically to prevent users from pulling up old issues with potentially unrelated problems.

If you have a problem similar to one that is closed and locked, feel free to create a new issue and link to the one that is locked. That is a lot easier for us to manage!

**Comment by Uysim** [comment]
@george-dotdev that work like charm

**Comment by Uysim** [comment]
@t-kelly  I understand. This is just my opinion
