### ISSUE TITLE
Assets workflow

### ISSUE THREAD

**Issue by goldsteinr** [Shopify/slate#956]
### Problem

We're having a problem working with the assets folder. The folder is full of images, and every time we run `yarn start` and the files are uploaded. How is the common workflow for that case? Add the assets to the .gitignore? Delete the folder's content every time the files are uploaded?

### More Information

Is there a limit image size to upload? We're getting a TIMEOUT very often too.

**Comment by t-kelly** [comment]
@goldsteinr if the images aren't changing often, you can ignore them in `.env` or create a seperate .env file (`.env.no-images`) so they don't upload every single time:
```
SLATE_IGNORE_FILES=assets/*.jpg:assets/*.png
```

**Comment by goldsteinr** [comment]
ok, thanks for the response
