### ISSUE TITLE
Generated script-tags for customer templates not checking Windows Slashes

### ISSUE THREAD

**Issue by YourWishes** [Shopify/slate#966]
### Problem

See #806 - Resolved issue does not work for Windows under `slate-tools/tools/webpack/script-tags.html`, since;
`<% if (htmlWebpackPlugin.options.liquidTemplates[chunk].includes('customers/')) { %>`
will be `false` on windows due to directory slashes being `\` rather than `/`

### Replication steps

1. Pull Slate starter theme on a Windows based PC
2. Execute `yarn build`
3. Inspect `dist/snippets/script-tags.liquid` to see that the template if statement will be as: `{%- if template == 'login' -%}`

### More Information

Easily fixed by replacing `/` with `\\` on Windows, ideally needs to facilitate both environments.

**Comment by t-kelly** [comment]
A PR would be welcome!

**Comment by t-kelly** [comment]
🤦‍♂️ Of course I didn't see it. Thanks!
