### ISSUE TITLE
Section schema not updating on live site

### ISSUE THREAD

**Issue by crimsondeal** [Shopify/slate#980]
### Problem

I am changing section schema settings and output, yet it only updates on the live theme some of the time. I cannot seem to find a rhyme or reason for when it updates and when it doesn't.

### Replication steps

Make a section schema, npm start, then it may or may  not be there. If there, try changing schema or adding settings/blocks/etc. Even try recompiling the app and reuploading each time, and the changes still don't take (even with clearing the browser cache).

### More Information

First time using Slate so please forgive me if this isn't how it should be working!

**Comment by crimsondeal** [comment]
Silly error on my part with an invalid setting for one of the schema settings. Is there any way for Slate to validate code and give an error message, to give the same errors as within the Admin panel > Edit Code for that file?

**Comment by t-kelly** [comment]
No this would be really hard at Slates level. This is a problem with the Assets API.
