### ISSUE TITLE
Passing Sensitive Data From Liquid To Js

### ISSUE THREAD

**Issue by jesster2k10** [Shopify/slate#987]
### Problem

How exactly would you pass senstive data (e.g. Instagram Access Token) from the settings_schema (Liquid) to Slate's JS without exposing it to the DOM?

I know it's possible to use data attributes on the HTML object or global variables but this exposes the access token. 

### Replication steps

N/A

### More Information

N/A

**Comment by dan-gamble** [comment]
Access tokens that are already in the settings_schema or was embedded in the Javascript by doing `{{ settings.access_token }}` have always been exposed. Just in the Javascript instead of the DOM.

There's no real way for you to hide access tokens truly if you're going to be storing them in settings. (As far as i know)

**Comment by justinmetros** [comment]
Dan is correct and it's important to know that liquid renders to HTML so anything in liquid is HTML. And anything you have in HTML is inherently insecure.

For things like an instagram access token - thousands of sites use that and you should be fine. It doesn't compromise your account with Instagram. 

If you need to have private credentials available ( to access a private app or other sensitive info ) - you can build a private Shopify App for that and retrieve your information from that ( the details of that are beyond the scope of this issue, I believe ).

**Comment by jesster2k10** [comment]
Ok, great thanks for the response. I've already implemented it into my site. There's no reason for concern since it was already exposed before.

Thanks for the comemnt!
