### ISSUE TITLE
Slate is completely broken

### ISSUE THREAD

**Issue by masterShake** [Shopify/slate#989]
I don't even now where to begin with the problems I am experiencing with my FRESH install of slate, see image:

<img width="653" alt="screen shot 2019-02-22 at 4 41 33 pm" src="https://user-images.githubusercontent.com/5078014/53275458-d19f2780-36c0-11e9-8dca-506bdf7d43f8.png">

The Stylesheet for the theme is loading but it is completely blank. The icons are not loading even though HTTPS is enabled just fine. There is no functional javascript since the "preview" buttons at the bottom don't work. And half the translations were missing (although I figured out how to add those).

I need to develop, I got deadlines and I really can't work with this. I'm following the documentation exactly and this is what I get. I must be doing something wrong because there's no way that shopify developers would ship a development kit with this many problems.

**Comment by shelldandy** [comment]
You gotta put your big boy pants read the readme and figure it out pal you got this!

**Comment by masterShake** [comment]
> You gotta put your big boy pants read the readme and figure it out pal you got this!

Thank you for the valuable input, this is extremely helpful and exactly the kind of support I have come to expect from Shopify developers.

**Comment by ConduciveMammal** [comment]
@masterShake that's exactly what Slate's supposed to look like. The entire point of Slate is to provide a blank **slate** for you to work from.
