### ISSUE TITLE
Sass doesn't compile &--

### ISSUE THREAD

**Issue by peke314** [Shopify/slate#997]
### Problem

When using & -- 
I get an error in console 
`Refused to apply style from 'https://cdn.shopify.com/s/files/1/1125/3830/t/22/assets/layout.theme.styleLiquid.scss.css?16127461793031031666' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

And in the 'layout.theme.styleLiquid.scss.css' file it is written
`Failed to compile SCSS file`

### Replication steps

```
.pfeil{
    &--close {
      right:0;
    }
}
```

might this be a yarn problem? 
Any thoughts? 
Thanks!

**Comment by dan-gamble** [comment]
I think this comes from Shopify's Sass version being 3.2 where as `&--` is only supported in 3.4 and above.

For what it's worth `&--` is bad practice so i'd try to avoid it if you can. It makes finding the source code much much harder.

**Comment by peke314** [comment]
@dan-gamble 
Thx for the reply! 

I'm recoding a theme with slate, so I'm using code from previous programmer, did not know this was bad practice, thank you for that! 

Removed it from my code anyways as it didn't bring that much value 
Closing this now

**Comment by dan-gamble** [comment]
Happy to help @peke314
