### ISSUE TITLE
Sass not compiling when using Chinese Characters

### ISSUE THREAD

**Issue by peke314** [Shopify/slate#998]
### Problem

Sass not compiling when using Chinese Characters

### Replication steps
With latin characters text is works
```
.product-single__add-to-cart .btn {
    &.is-added {
      &::after {
        content: "hello";
      }
    }
  }
```

With Chinese Characters it doesn't compile the scss file. 
```
.product-single__add-to-cart .btn {
    &.is-added {
      &::after {
        content: "添加至愿望单";
      }
    }
  }
```

Any ideas? 
Thank you!
Victor

**Comment by justinmetros** [comment]
This is not an issue with Slate but rather Sass. This [thread](https://github.com/sass/sass/issues/659) should hopefully help.

**Comment by peke314** [comment]
@justinmetros
Thx for pointing that out, I experimented with that with no luck.

I used _content: "添加至愿望单";_ with Timber, and I tried it on other projects and sass compiles it fine. 
When using it in Slate, I get no error in the terminal when compiling it, 
but I get a "net::ERR_ABORTED 422" error on my console
and the layout.theme.styleLiquid.scss.css file only contains "Failed to compile SCSS file"

**Comment by peke314** [comment]
I made it work by putting the chinese characters in the _theme.scss_ and not the _theme.scss.liquid_
